// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         opted_out: true
 *     }
 */
export interface OptOutCuratedFeedsRequest {
    account_id: string;
    opted_out: boolean;
}
