// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export interface ListOperationsResponse extends CloudflareApi.ApiShieldApiResponseCollection {
    result: CloudflareApi.ApiShieldPerOperationSetting[];
}
