// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         app_id: "app_id",
 *         policy_id: "policy_id",
 *         body: {
 *             decision: "allow",
 *             include: [{
 *                     everyone: {
 *                         "key": "value"
 *                     }
 *                 }],
 *             name: "Allow SSH users with a FIDO2 key",
 *             mfa_config: {
 *                 allowed_authenticators: ["ssh_fido2_key"]
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         app_id: "app_id",
 *         policy_id: "policy_id",
 *         body: {
 *             decision: "allow",
 *             include: [{
 *                     everyone: {
 *                         "key": "value"
 *                     }
 *                 }],
 *             name: "Allow SSH users with a PIV key or FIDO2 key",
 *             mfa_config: {
 *                 allowed_authenticators: ["piv_key", "ssh_fido2_key"]
 *             }
 *         }
 *     }
 *
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         app_id: "app_id",
 *         policy_id: "policy_id",
 *         body: {
 *             decision: "allow",
 *             include: [{
 *                     everyone: {
 *                         "key": "value"
 *                     }
 *                 }],
 *             name: "Allow SSH users with a PIV key",
 *             mfa_config: {
 *                 allowed_authenticators: ["piv_key"]
 *             }
 *         }
 *     }
 */
export interface UpdatePoliciesRequest {
    account_or_zone: string;
    /** Identifier. */
    account_or_zone_id: string;
    /** The application ID. */
    app_id: string;
    /** The policy ID. */
    policy_id: string;
    body: CloudflareApi.AccessAppPolicyWriteRequest;
}
