// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         rule_id: "rule_id",
 *         body: {
 *             action: {
 *                 action: "Block"
 *             },
 *             conditions: [{
 *                     operator: "InList",
 *                     selector: "Recipients",
 *                     value: ["value"]
 *                 }],
 *             enabled: true,
 *             name: "name"
 *         }
 *     }
 */
export interface UpdateRulesRequest {
    account_id: string;
    rule_id: string;
    body: CloudflareApi.DlpCreateEmailRule;
}
