// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         body: {
 *             config: {},
 *             name: "Widget Corps IDP",
 *             type: "onetimepin"
 *         }
 *     }
 */
export interface CreateIdentityProvidersRequest {
    account_or_zone: string;
    /** Identifier. */
    account_or_zone_id: string;
    body: CloudflareApi.AccessIdentityProviders;
}
