// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface CreateAddressMapsRequest {
    /** Identifier of a Cloudflare account. */
    account_id: string;
    description?: CloudflareApi.AddressingDescription2 | null;
    enabled?: CloudflareApi.AddressingEnabled | null;
    ips?: CloudflareApi.AddressingIpAddress[];
    memberships?: CloudflareApi.AddressingMembershipRequests;
}
