// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         list_id: "list_id"
 *     }
 */
export interface GetListsRequest {
    /** Specify the Cloudflare account identifier. */
    account_id: string;
    /** Identify the API resource with a UUID. */
    list_id: string;
}
