// This file was auto-generated by Fern from our API Definition.

import * as fs from "fs";
import * as core from "../../../../../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         account_id: "account_id"
 *     }
 */
export interface UploadListsRequest {
    /** Specify the Cloudflare account identifier. */
    account_id: string;
    /** The CSV file containing list items. Must be `text/csv` or `text/plain` and cannot exceed 2 MB. */
    file: core.file.Uploadable;
}
