// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         list_id: "list_id"
 *     }
 */
export interface GetListsRequest {
    /** The Account ID for this resource. */
    account_id: string;
    /** The unique ID of the list. */
    list_id: string;
}
