// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         ruleset_id: "ruleset_id"
 *     }
 */
export interface ListRulesRequest {
    /** Identifier. */
    account_id: string;
    /** The Web Analytics ruleset identifier. */
    ruleset_id: string;
}
