// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         ruleset_id: "ruleset_id"
 *     }
 */
export interface RumModifyRulesRequest {
    /** Identifier. */
    account_id: string;
    /** The Web Analytics ruleset identifier. */
    ruleset_id: string;
    /** A list of rule identifiers to delete. */
    delete_rules?: CloudflareApi.RumRuleIdentifier[];
    /** A list of rules to create or update. */
    rules?: CloudflareApi.RumModifyRulesRequestRulesItem[];
}
