// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         document_fingerprint_id: "document_fingerprint_id"
 *     }
 */
export interface DeleteDocumentFingerprintsRequest {
    account_id: string;
    document_fingerprint_id: string;
}
