// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import { CustomClient } from "../resources/custom/client/Client.js";
import { ManagedClient } from "../resources/managed/client/Client.js";

export declare namespace DomainsClient {
    export type Options = BaseClientOptions;
}

export class DomainsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DomainsClient.Options>;
    protected _custom: CustomClient | undefined;
    protected _managed: ManagedClient | undefined;

    constructor(options: DomainsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get custom(): CustomClient {
        return (this._custom ??= new CustomClient(this._options));
    }

    public get managed(): ManagedClient {
        return (this._managed ??= new ManagedClient(this._options));
    }
}
