// This file was auto-generated by Fern from our API Definition.

/** Field to order zones by. */
export const ListZonesRequestOrder = {
    Name: "name",
    Status: "status",
    AccountId: "account.id",
    AccountName: "account.name",
    PlanId: "plan.id",
} as const;
export type ListZonesRequestOrder = (typeof ListZonesRequestOrder)[keyof typeof ListZonesRequestOrder];
