// This file was auto-generated by Fern from our API Definition.

export const TimeseriesGroupsWebCrawlersRequestResponseStatusCategoryItem = {
    Informational: "INFORMATIONAL",
    Success: "SUCCESS",
    Redirection: "REDIRECTION",
    ClientError: "CLIENT_ERROR",
    ServerError: "SERVER_ERROR",
} as const;
export type TimeseriesGroupsWebCrawlersRequestResponseStatusCategoryItem =
    (typeof TimeseriesGroupsWebCrawlersRequestResponseStatusCategoryItem)[keyof typeof TimeseriesGroupsWebCrawlersRequestResponseStatusCategoryItem];
