// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface UpdateIpsecTunnelsResponse {
    modified?: boolean | undefined;
    modified_ipsec_tunnel?: CloudflareApi.MagicIpsecTunnel | undefined;
}
