// This file was auto-generated by Fern from our API Definition.

export interface LocationsOutagesResponse {
    annotations: LocationsOutagesResponse.Annotations.Item[];
}

export namespace LocationsOutagesResponse {
    export type Annotations = Annotations.Item[];

    export namespace Annotations {
        export interface Item {
            clientCountryAlpha2: string;
            clientCountryName: string;
            /** A numeric string. */
            value: string;
        }
    }
}
