// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account-123",
 *         repo_connection_uuid: "repo_connection_uuid"
 *     }
 */
export interface DeleteConnectionsRequest {
    account_id: CloudflareApi.BuildsAccountId;
    repo_connection_uuid: CloudflareApi.BuildsRepoConnectionUuid;
}
