// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "46148281d8a93d002ef242d8b0d5f9f6"
 *     }
 */
export interface ListExportsRequest {
    /** Cloudflare account ID for the user making the request. */
    account_id: string;
    /** A page number within the paginated result set. */
    page?: number;
    /** Number of results to return per page. */
    per_page?: number;
    /** Filter on export job's status */
    status?: CloudflareApi.PostureApiStatusEnum;
}
