// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         since: "2014-01-01T05:20:00Z",
 *         until: "2014-01-01T05:20:00Z"
 *     }
 */
export interface GetReportRequest {
    since?: CloudflareApi.SpectrumAnalyticsSince;
    until?: CloudflareApi.SpectrumAnalyticsUntil;
    /** Include CDN traffic in the bandwidth aggregation. */
    cdn_traffic?: boolean;
}
