// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import { ContentFindingsClient } from "../resources/contentFindings/client/Client.js";
import { FindingsClient } from "../resources/findings/client/Client.js";

export declare namespace DataSecurityClient {
    export type Options = BaseClientOptions;
}

export class DataSecurityClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DataSecurityClient.Options>;
    protected _contentFindings: ContentFindingsClient | undefined;
    protected _findings: FindingsClient | undefined;

    constructor(options: DataSecurityClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get contentFindings(): ContentFindingsClient {
        return (this._contentFindings ??= new ContentFindingsClient(this._options));
    }

    public get findings(): FindingsClient {
        return (this._findings ??= new FindingsClient(this._options));
    }
}
