// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         index_name: "index_name",
 *         body: "@/path/to/vectors.ndjson"
 *     }
 */
export interface UpsertVectorizeRequest {
    /** Identifier */
    account_id: string;
    index_name: string;
    /** Behavior for ndjson parse failures. */
    "unparsable-behavior"?: CloudflareApi.UpsertVectorizeRequestUnparsableBehavior;
    /** ndjson file containing vectors to upsert. */
    body: string;
}
