// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         origin_ip: "192.0.2.1",
 *         body: {
 *             origin_ip: "192.0.2.1",
 *             region: "us-east-1",
 *             vendor: "aws"
 *         }
 *     }
 */
export interface UpdateOriginCloudRegionsRequest {
    /** Identifier. */
    zone_id: string;
    /** Origin IP address to create or replace. */
    origin_ip: string;
    body: CloudflareApi.CacheSettingsOriginCloudRegionV2Request;
}
