// This file was auto-generated by Fern from our API Definition.

/** Defines the search requirements. When set to `all`, all the search requirements must match. When set to `any`, only one of the search requirements has to match. */
export const ListAccessRulesRequestMatch = {
    Any: "any",
    All: "all",
} as const;
export type ListAccessRulesRequestMatch =
    (typeof ListAccessRulesRequestMatch)[keyof typeof ListAccessRulesRequestMatch];
