// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         description: "endpoints",
 *         modified_on: "2014-01-01T05:20:00Z",
 *         ip: "1.2.3.4",
 *         priority: 5,
 *         uri_search: "/some/path",
 *         ip_range_search: "1.2.3.0/16",
 *         created_on: "2014-01-01T05:20:00Z",
 *         description_search: "endpoints",
 *         ip_search: "1.2.3.4"
 *     }
 */
export interface ListLockdownsRequest {
    /** Defines an identifier. */
    zone_id: string;
    /** Page number of paginated results. */
    page?: number;
    description?: CloudflareApi.FirewallSchemasDescriptionSearch;
    modified_on?: CloudflareApi.FirewallModifiedOn;
    ip?: CloudflareApi.FirewallIpSearch;
    priority?: CloudflareApi.FirewallSchemasPriority;
    uri_search?: CloudflareApi.FirewallUriSearch;
    ip_range_search?: CloudflareApi.FirewallIpRangeSearch;
    /** The maximum number of results per page. You can only set the value to `1` or to a multiple of 5 such as `5`, `10`, `15`, or `20`. */
    per_page?: number;
    /** The timestamp of when the rule was created. */
    created_on?: string;
    /** A string to search for in the description of existing rules. */
    description_search?: string;
    /** A single IP address to search for in existing rules. */
    ip_search?: string;
}
