// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         ruleset_id: "ruleset_id"
 *     }
 */
export interface ListVersionsRequest {
    account_or_zone: string;
    /** The unique ID of the account. */
    account_or_zone_id: string;
    /** The unique ID of the ruleset. */
    ruleset_id: string;
}
