// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListInvitesResponse {
    result: CloudflareApi.IamUserInvite[];
    result_info?: CloudflareApi.IamResultInfo | undefined;
}
