// This file was auto-generated by Fern from our API Definition.

export interface ListProfilesAgentMemoryResponse {
    result: ListProfilesAgentMemoryResponse.Result.Item[];
    result_info?: ListProfilesAgentMemoryResponse.ResultInfo | undefined;
}

export namespace ListProfilesAgentMemoryResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export interface Item {
            /** Time the profile was first recorded in the namespace index. */
            createdAt: string;
            /** Profile name. */
            name: string;
        }
    }

    export interface ResultInfo {
        /** Number of results returned in this page. */
        count?: number | undefined;
        /** Opaque cursor for the next page; omitted on the last page. */
        cursor?: string | undefined;
        /** Page size used for this query. */
        per_page?: number | undefined;
    }
}
