// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id"
 *     }
 */
export interface GetVerificationRequest {
    /** Identifier. */
    zone_id: string;
    /** Immediately retry SSL Verification. */
    retry?: true;
}
