// This file was auto-generated by Fern from our API Definition.

export const ListFindingsRequestType = {
    Content: "Content",
    Posture: "Posture",
} as const;
export type ListFindingsRequestType = (typeof ListFindingsRequestType)[keyof typeof ListFindingsRequestType];
