// This file was auto-generated by Fern from our API Definition.

export const ListFindingsRequestProduct = {
    Cloud: "Cloud",
    Saas: "Saas",
} as const;
export type ListFindingsRequestProduct = (typeof ListFindingsRequestProduct)[keyof typeof ListFindingsRequestProduct];
