// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         key_rotation_interval_days: 30
 *     }
 */
export interface UpdateSigningKeysRequest {
    /** Identifier. */
    account_id: string;
    key_rotation_interval_days: CloudflareApi.AccessKeyRotationIntervalDays;
}
