// This file was auto-generated by Fern from our API Definition.

export const DeleteSippyRequestCfR2Jurisdiction = {
    VDefault: "default",
    Eu: "eu",
    Us: "us",
    Fedramp: "fedramp",
    FedrampHigh: "fedramp-high",
} as const;
export type DeleteSippyRequestCfR2Jurisdiction =
    (typeof DeleteSippyRequestCfR2Jurisdiction)[keyof typeof DeleteSippyRequestCfR2Jurisdiction];
