// This file was auto-generated by Fern from our API Definition.

export const IndustryTopRequestProtocolItem = {
    Udp: "UDP",
    Tcp: "TCP",
    Icmp: "ICMP",
    Gre: "GRE",
} as const;
export type IndustryTopRequestProtocolItem =
    (typeof IndustryTopRequestProtocolItem)[keyof typeof IndustryTopRequestProtocolItem];
