// This file was auto-generated by Fern from our API Definition.

export interface ListPipelinesResponse {
    result: ListPipelinesResponse.Result.Item[];
    result_info?: ListPipelinesResponse.ResultInfo | undefined;
}

export namespace ListPipelinesResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export interface Item {
            created_at: string;
            /** Indicates a unique identifier for this pipeline. */
            id: string;
            modified_at: string;
            /** Indicates the name of the Pipeline. */
            name: string;
            /** Specifies SQL for the Pipeline processing flow. */
            sql: string;
            /** Indicates the current status of the Pipeline. */
            status: string;
        }
    }

    export interface ResultInfo {
        /** Indicates the number of items on current page. */
        count: number;
        /** Indicates the current page number. */
        page: number;
        /** Indicates the number of items per page. */
        per_page: number;
        /** Indicates the total number of items. */
        total_count: number;
    }
}
