// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface ListSessionsResponse {
    data?: ListSessionsResponse.Data | undefined;
    paging?: ListSessionsResponse.Paging | undefined;
    success?: boolean | undefined;
}

export namespace ListSessionsResponse {
    export interface Data {
        sessions?: CloudflareApi.RealtimekitActiveSession[] | undefined;
    }

    export interface Paging {
        end_offset?: number | undefined;
        start_offset?: number | undefined;
        total_count?: number | undefined;
    }
}
