// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         site_id: "site_id"
 *     }
 */
export interface GetSitesRequest {
    /** Identifier */
    account_id: string;
    /** Identifier */
    site_id: string;
    /** If true, the health check target in the response body will be presented using the new object format. Defaults to false. */
    "x-magic-new-hc-target"?: boolean;
}
