// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListHealthChecksResponse {
    result: CloudflareApi.SmartshieldHealthchecks[];
    result_info?: CloudflareApi.SmartshieldResultInfo | undefined;
}
