// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         operation_id: "operation_id"
 *     }
 */
export interface GetBulkOperationsRequest {
    /** The Account ID for this resource. */
    account_id: string;
    /** The unique operation ID of the asynchronous action. */
    operation_id: string;
}
