// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         article_ids: ["article_ids"],
 *         read: true
 *     }
 */
export interface BulkMarkReadArticlesRequest {
    account_id: string;
    article_ids: string[];
    read: boolean;
}
