// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface GetReserveResponse extends CloudflareApi.CacheSettingsCacheReserve {
    value: CloudflareApi.CacheSettingsCacheReserveValue;
}
