// This file was auto-generated by Fern from our API Definition.

export const SummaryV2HttpRequestHttpVersionItem = {
    HttPv1: "HTTPv1",
    HttPv2: "HTTPv2",
    HttPv3: "HTTPv3",
} as const;
export type SummaryV2HttpRequestHttpVersionItem =
    (typeof SummaryV2HttpRequestHttpVersionItem)[keyof typeof SummaryV2HttpRequestHttpVersionItem];
