// This file was auto-generated by Fern from our API Definition.

export const SummaryV2HttpRequestDeviceTypeItem = {
    Desktop: "DESKTOP",
    Mobile: "MOBILE",
    Other: "OTHER",
} as const;
export type SummaryV2HttpRequestDeviceTypeItem =
    (typeof SummaryV2HttpRequestDeviceTypeItem)[keyof typeof SummaryV2HttpRequestDeviceTypeItem];
