// This file was auto-generated by Fern from our API Definition.

export const TimeseriesHttpRequestApiTrafficItem = {
    Api: "API",
    NonApi: "NON_API",
} as const;
export type TimeseriesHttpRequestApiTrafficItem =
    (typeof TimeseriesHttpRequestApiTrafficItem)[keyof typeof TimeseriesHttpRequestApiTrafficItem];
