// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const TimeseriesHttpRequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type TimeseriesHttpRequestFormat =
    (typeof TimeseriesHttpRequestFormat)[keyof typeof TimeseriesHttpRequestFormat];
