// This file was auto-generated by Fern from our API Definition.

export const GetHttpProtocolRequestBrowserFamilyItem = {
    Chrome: "CHROME",
    Edge: "EDGE",
    Firefox: "FIREFOX",
    Safari: "SAFARI",
} as const;
export type GetHttpProtocolRequestBrowserFamilyItem =
    (typeof GetHttpProtocolRequestBrowserFamilyItem)[keyof typeof GetHttpProtocolRequestBrowserFamilyItem];
