// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id"
 *     }
 */
export interface GetRobotsRequest {
    /** Identifier of the zone. */
    zone_id: string;
    /** Optional subdomain to fetch robots.txt for. If omitted, fetches robots.txt for the zone apex domain. */
    subdomain?: string;
}
