// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface IamCreateAccount {
    /** Optional key that identifies an Account-creation request. Free Account creation can require exactly one valid key, so API clients should send a key with every Account-creation request. Reuse the same key when retrying the same request. */
    "Idempotency-Key"?: string;
    /** Account name */
    name: string;
    /** Set to `true` and omit `unit` to create a standalone Free Account. If provided, this field must be `true`. */
    standalone?: true;
    type?: CloudflareApi.IamAccountType;
    unit?: CloudflareApi.IamCreateAccountUnit;
}
