// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "example.com"
 *     }
 */
export interface ListAccountsRequest {
    /** Name of the account. */
    name?: string;
    /** Page number of paginated results. */
    page?: number;
    /** Maximum number of results per page. */
    per_page?: number;
    /** Direction to order results. */
    direction?: CloudflareApi.ListAccountsRequestDirection;
}
