// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         namespace: "namespace",
 *         name: "name",
 *         ref: "ref",
 *         path: "path"
 *     }
 */
export interface GetRawRequest {
    /** Cloudflare account ID. */
    account_id: string;
    /** Artifacts namespace name. */
    namespace: string;
    /** Repository name. */
    name: string;
    /** Git ref, branch, tag, or 40-character commit hash. */
    ref: string;
    /** File path. May contain slashes. */
    path: string;
}
