// This file was auto-generated by Fern from our API Definition.

export const ListParticipantsRequestSortBy = {
    JoinedAt: "joinedAt",
    Duration: "duration",
} as const;
export type ListParticipantsRequestSortBy =
    (typeof ListParticipantsRequestSortBy)[keyof typeof ListParticipantsRequestSortBy];
