// This file was auto-generated by Fern from our API Definition.

export interface ChunksItemsResponse {
    result: ChunksItemsResponse.Result.Item[];
    result_info?: ChunksItemsResponse.ResultInfo | undefined;
}

export namespace ChunksItemsResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export interface Item {
            end_byte?: number | undefined;
            id: string;
            item: Item.Item;
            start_byte?: number | undefined;
            text: string;
        }

        export namespace Item {
            export interface Item {
                key: string;
                metadata?: Record<string, unknown> | undefined;
                timestamp?: number | undefined;
            }
        }
    }

    export interface ResultInfo {
        count: number;
        limit: number;
        offset: number;
        total: number;
    }
}
