// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export interface GetLastSeenIdentityResponse extends CloudflareApi.AccessIdentity {
    /** Active passkey enrollments for the user. */
    passkeys?: GetLastSeenIdentityResponse.Passkeys.Item[] | undefined;
}

export namespace GetLastSeenIdentityResponse {
    export type Passkeys = Passkeys.Item[];

    export namespace Passkeys {
        export interface Item {
            created_at?: string | undefined;
            /** Authenticator ID used to delete the passkey. */
            id?: string | undefined;
            last_used_at?: string | undefined;
            name?: string | undefined;
        }
    }
}
