// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         asn_id: "asn_id",
 *         date: "2014-01-01T05:20:00Z"
 *     }
 */
export interface DayReportAsnRequest {
    /** Identifier. */
    account_id: string;
    asn_id: string;
    date?: CloudflareApi.DosTimestamp;
}
