// This file was auto-generated by Fern from our API Definition.

/** Direction to order widgets. */
export const CreateWidgetsRequestDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type CreateWidgetsRequestDirection =
    (typeof CreateWidgetsRequestDirection)[keyof typeof CreateWidgetsRequestDirection];
