// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const SummaryV2Layer3RequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type SummaryV2Layer3RequestFormat =
    (typeof SummaryV2Layer3RequestFormat)[keyof typeof SummaryV2Layer3RequestFormat];
