// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { IssuesClient } from "../resources/issues/client/Client.js";
import { IssueTypesClient } from "../resources/issueTypes/client/Client.js";

export declare namespace AttackSurfaceReportClient {
    export type Options = BaseClientOptions;
}

export class AttackSurfaceReportClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AttackSurfaceReportClient.Options>;
    protected _issueTypes: IssueTypesClient | undefined;
    protected _issues: IssuesClient | undefined;

    constructor(options: AttackSurfaceReportClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get issueTypes(): IssueTypesClient {
        return (this._issueTypes ??= new IssueTypesClient(this._options));
    }

    public get issues(): IssuesClient {
        return (this._issues ??= new IssuesClient(this._options));
    }
}
