// This file was auto-generated by Fern from our API Definition.

export interface UserAgentTimeseriesGroupsResponse {
    /** Metadata for the results. */
    meta: UserAgentTimeseriesGroupsResponse.Meta;
    serie_0: UserAgentTimeseriesGroupsResponse.Serie0;
}

export namespace UserAgentTimeseriesGroupsResponse {
    /**
     * Metadata for the results.
     */
    export interface Meta {
        /** Aggregation interval of the results (e.g., in 15 minutes or 1 hour intervals). Refer to [Aggregation intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/). */
        aggInterval: Meta.AggInterval;
        confidenceInfo: Meta.ConfidenceInfo;
        dateRange: Meta.DateRange.Item[];
        /** Timestamp of the last dataset update. */
        lastUpdated: string;
        /** Normalization method applied to the results. Refer to [Normalization methods](https://developers.cloudflare.com/radar/concepts/normalization/). */
        normalization: Meta.Normalization;
        /** Measurement units for the results. */
        units: Meta.Units.Item[];
    }

    export namespace Meta {
        /** Aggregation interval of the results (e.g., in 15 minutes or 1 hour intervals). Refer to [Aggregation intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/). */
        export const AggInterval = {
            FifteenMinutes: "FIFTEEN_MINUTES",
            OneHour: "ONE_HOUR",
            OneDay: "ONE_DAY",
            OneWeek: "ONE_WEEK",
            OneMonth: "ONE_MONTH",
        } as const;
        export type AggInterval = (typeof AggInterval)[keyof typeof AggInterval];

        export interface ConfidenceInfo {
            annotations: ConfidenceInfo.Annotations.Item[];
            /** Provides an indication of how much confidence Cloudflare has in the data. */
            level: number;
        }

        export namespace ConfidenceInfo {
            export type Annotations = Annotations.Item[];

            export namespace Annotations {
                /**
                 * Annotation associated with the result (e.g. outage or other type of event).
                 */
                export interface Item {
                    /** Data source for annotations. */
                    dataSource: Item.DataSource;
                    description: string;
                    endDate: string;
                    /** Event type for annotations. */
                    eventType: Item.EventType;
                    /** Whether event is a single point in time or a time range. */
                    isInstantaneous: boolean;
                    linkedUrl: string;
                    startDate: string;
                    tags?: string[] | undefined;
                }

                export namespace Item {
                    /** Data source for annotations. */
                    export const DataSource = {
                        All: "ALL",
                        AiBots: "AI_BOTS",
                        AiGateway: "AI_GATEWAY",
                        Bgp: "BGP",
                        Bots: "BOTS",
                        ConnectionAnomaly: "CONNECTION_ANOMALY",
                        Ct: "CT",
                        Dns: "DNS",
                        DnsMagnitude: "DNS_MAGNITUDE",
                        DnsAs112: "DNS_AS112",
                        Dos: "DOS",
                        EmailRouting: "EMAIL_ROUTING",
                        EmailSecurity: "EMAIL_SECURITY",
                        Fw: "FW",
                        FwPg: "FW_PG",
                        Http: "HTTP",
                        HttpControl: "HTTP_CONTROL",
                        HttpCrawlerReferer: "HTTP_CRAWLER_REFERER",
                        HttpOrigins: "HTTP_ORIGINS",
                        Iqi: "IQI",
                        LeakedCredentials: "LEAKED_CREDENTIALS",
                        Net: "NET",
                        RobotsTxt: "ROBOTS_TXT",
                        Speed: "SPEED",
                        WorkersAi: "WORKERS_AI",
                    } as const;
                    export type DataSource = (typeof DataSource)[keyof typeof DataSource];
                    /** Event type for annotations. */
                    export const EventType = {
                        General: "GENERAL",
                        Outage: "OUTAGE",
                        PartialProjection: "PARTIAL_PROJECTION",
                        Pipeline: "PIPELINE",
                        TrafficAnomaly: "TRAFFIC_ANOMALY",
                    } as const;
                    export type EventType = (typeof EventType)[keyof typeof EventType];
                }
            }
        }

        export type DateRange = DateRange.Item[];

        export namespace DateRange {
            export interface Item {
                /** Adjusted end of date range. */
                endTime: string;
                /** Adjusted start of date range. */
                startTime: string;
            }
        }

        /** Normalization method applied to the results. Refer to [Normalization methods](https://developers.cloudflare.com/radar/concepts/normalization/). */
        export const Normalization = {
            Percentage: "PERCENTAGE",
            Min0Max: "MIN0_MAX",
            MinMax: "MIN_MAX",
            RawValues: "RAW_VALUES",
            PercentageChange: "PERCENTAGE_CHANGE",
            RollingAverage: "ROLLING_AVERAGE",
            OverlappedPercentage: "OVERLAPPED_PERCENTAGE",
            Ratio: "RATIO",
        } as const;
        export type Normalization = (typeof Normalization)[keyof typeof Normalization];
        export type Units = Units.Item[];

        export namespace Units {
            export interface Item {
                name: string;
                value: string;
            }
        }
    }

    export interface Serie0 {
        timestamps: string[];
    }
}
