// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         migration_id: "migration_id"
 *     }
 */
export interface LogsImportRequest {
    /** Account identifier tag. */
    account_id: string;
    /** Sourcing kit resource identifier. */
    migration_id: string;
    /** Number of items to skip before returning results. */
    offset?: number;
    /** Maximum number of items to return. */
    limit?: number;
}
