// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         issue_id: "issue_id"
 *     }
 */
export interface DismissSecurityInsightsRequest {
    account_or_zone: string;
    /** Identifier. */
    account_or_zone_id: string;
    issue_id: string;
    dismiss?: boolean;
}
