// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         bucket_name: "bucket_name"
 *     }
 */
export interface EnableR2DataCatalogRequest {
    /** Identifies the account. */
    account_id: string;
    /** Specifies the R2 bucket name to enable as catalog. */
    bucket_name: string;
}
