// This file was auto-generated by Fern from our API Definition.

export const GetBrowserFamilyRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type GetBrowserFamilyRequestIpVersionItem =
    (typeof GetBrowserFamilyRequestIpVersionItem)[keyof typeof GetBrowserFamilyRequestIpVersionItem];
