// This file was auto-generated by Fern from our API Definition.

export const CacheHitTimeseriesGroupsRequestProtocolItem = {
    Udp: "UDP",
    Tcp: "TCP",
    Https: "HTTPS",
    Tls: "TLS",
} as const;
export type CacheHitTimeseriesGroupsRequestProtocolItem =
    (typeof CacheHitTimeseriesGroupsRequestProtocolItem)[keyof typeof CacheHitTimeseriesGroupsRequestProtocolItem];
