// This file was auto-generated by Fern from our API Definition.

export const DnssecTimeseriesGroupsRequestResponseCodeItem = {
    Noerror: "NOERROR",
    Formerr: "FORMERR",
    Servfail: "SERVFAIL",
    Nxdomain: "NXDOMAIN",
    Notimp: "NOTIMP",
    Refused: "REFUSED",
    Yxdomain: "YXDOMAIN",
    Yxrrset: "YXRRSET",
    Nxrrset: "NXRRSET",
    Notauth: "NOTAUTH",
    Notzone: "NOTZONE",
    Badsig: "BADSIG",
    Badkey: "BADKEY",
    Badtime: "BADTIME",
    Badmode: "BADMODE",
    Badname: "BADNAME",
    Badalg: "BADALG",
    Badtrunc: "BADTRUNC",
    Badcookie: "BADCOOKIE",
} as const;
export type DnssecTimeseriesGroupsRequestResponseCodeItem =
    (typeof DnssecTimeseriesGroupsRequestResponseCodeItem)[keyof typeof DnssecTimeseriesGroupsRequestResponseCodeItem];
