// This file was auto-generated by Fern from our API Definition.

export const IpVersionTimeseriesGroupsRequestProtocolItem = {
    Udp: "UDP",
    Tcp: "TCP",
    Https: "HTTPS",
    Tls: "TLS",
} as const;
export type IpVersionTimeseriesGroupsRequestProtocolItem =
    (typeof IpVersionTimeseriesGroupsRequestProtocolItem)[keyof typeof IpVersionTimeseriesGroupsRequestProtocolItem];
