// This file was auto-generated by Fern from our API Definition.

/** Column to sort by. Options: 'matchedAt', 'domain', 'similarityScore', or 'registrar' */
export const GetLogoMatchesRequestOrderBy = {
    MatchedAt: "matchedAt",
    Domain: "domain",
    SimilarityScore: "similarityScore",
    Registrar: "registrar",
} as const;
export type GetLogoMatchesRequestOrderBy =
    (typeof GetLogoMatchesRequestOrderBy)[keyof typeof GetLogoMatchesRequestOrderBy];
