// This file was auto-generated by Fern from our API Definition.

/** The ranking type. */
export const TopRankingRequestRankingType = {
    Popular: "POPULAR",
    TrendingRise: "TRENDING_RISE",
    TrendingSteady: "TRENDING_STEADY",
} as const;
export type TopRankingRequestRankingType =
    (typeof TopRankingRequestRankingType)[keyof typeof TopRankingRequestRankingType];
