// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../environments.js";
import { UpdatesClient } from "../resources/updates/client/Client.js";

export declare namespace ScimClient {
    export type Options = BaseClientOptions;
}

export class ScimClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ScimClient.Options>;
    protected _updates: UpdatesClient | undefined;

    constructor(options: ScimClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get updates(): UpdatesClient {
        return (this._updates ??= new UpdatesClient(this._options));
    }
}
