// This file was auto-generated by Fern from our API Definition.

export const ListAuditRequestActionResultItem = {
    Success: "success",
    Failure: "failure",
} as const;
export type ListAuditRequestActionResultItem =
    (typeof ListAuditRequestActionResultItem)[keyof typeof ListAuditRequestActionResultItem];
