// This file was auto-generated by Fern from our API Definition.

export const ListAuditRequestActorTypeNotItem = {
    Account: "account",
    CloudflareAdmin: "cloudflare_admin",
    DelegatedService: "delegated_service",
    System: "system",
    User: "user",
} as const;
export type ListAuditRequestActorTypeNotItem =
    (typeof ListAuditRequestActorTypeNotItem)[keyof typeof ListAuditRequestActorTypeNotItem];
