// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { RulesClient } from "../resources/rules/client/Client.js";

export declare namespace CloudConnectorClient {
    export type Options = BaseClientOptions;
}

export class CloudConnectorClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CloudConnectorClient.Options>;
    protected _rules: RulesClient | undefined;

    constructor(options: CloudConnectorClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get rules(): RulesClient {
        return (this._rules ??= new RulesClient(this._options));
    }
}
