// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         app_id: "app_id",
 *         meeting_id: "meeting_id"
 *     }
 */
export interface KickActiveRequest {
    /** The account identifier tag. */
    account_id: string;
    /** The app identifier tag. */
    app_id: string;
    /** ID of the meeting */
    meeting_id: string;
    custom_participant_ids?: string[];
    participant_ids?: string[];
}
