// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         app_id: "app_id",
 *         meeting_id: "meeting_id"
 *     }
 */
export interface MuteAllActiveRequest {
    /** The account identifier tag. */
    account_id: string;
    /** The app identifier tag. */
    app_id: string;
    /** ID of the meeting */
    meeting_id: string;
    /** if false, participants won't be able to unmute themselves after they are muted */
    allow_unmute?: boolean;
}
