// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 5,
 *         name: ["main_series"]
 *     }
 */
export interface DomainCategoriesTopRequest {
    /** Limits the number of objects returned in the response. */
    limit?: number;
    /** Array of names used to label the series in the response. */
    name?: string | string[];
    /** Filters results by user agent category. */
    userAgentCategory?: "AI";
    /** Filters results by the specified array of dates. */
    date?: string | string[];
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.robotsTxt.DomainCategoriesTopRequestFormat;
}
