// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { BucketsClient } from "../resources/buckets/client/Client.js";
import { ObjectsClient } from "../resources/objects/client/Client.js";
import { SuperSlurperClient } from "../resources/superSlurper/client/Client.js";
import { TemporaryCredentialsClient } from "../resources/temporaryCredentials/client/Client.js";

export declare namespace R2Client {
    export type Options = BaseClientOptions;
}

export class R2Client {
    protected readonly _options: NormalizedClientOptionsWithAuth<R2Client.Options>;
    protected _buckets: BucketsClient | undefined;
    protected _objects: ObjectsClient | undefined;
    protected _temporaryCredentials: TemporaryCredentialsClient | undefined;
    protected _superSlurper: SuperSlurperClient | undefined;

    constructor(options: R2Client.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get buckets(): BucketsClient {
        return (this._buckets ??= new BucketsClient(this._options));
    }

    public get objects(): ObjectsClient {
        return (this._objects ??= new ObjectsClient(this._options));
    }

    public get temporaryCredentials(): TemporaryCredentialsClient {
        return (this._temporaryCredentials ??= new TemporaryCredentialsClient(this._options));
    }

    public get superSlurper(): SuperSlurperClient {
        return (this._superSlurper ??= new SuperSlurperClient(this._options));
    }
}
