// This file was auto-generated by Fern from our API Definition.

export const TimeseriesLayer7RequestMitigationProductItem = {
    Ddos: "DDOS",
    Waf: "WAF",
    BotManagement: "BOT_MANAGEMENT",
    AccessRules: "ACCESS_RULES",
    IpReputation: "IP_REPUTATION",
    ApiShield: "API_SHIELD",
    DataLossPrevention: "DATA_LOSS_PREVENTION",
} as const;
export type TimeseriesLayer7RequestMitigationProductItem =
    (typeof TimeseriesLayer7RequestMitigationProductItem)[keyof typeof TimeseriesLayer7RequestMitigationProductItem];
