// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         category_uuid: "category_uuid"
 *     }
 */
export interface DeleteLegacyRequest {
    /** Account ID. */
    account_id: string;
    /** Tag Category UUID. */
    category_uuid: string;
}
