// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface UpdateDynamicRoutingResponse {
    route: UpdateDynamicRoutingResponse.Route;
    success: boolean;
}

export namespace UpdateDynamicRoutingResponse {
    export interface Route {
        account_tag: string;
        created_at: string;
        deployment: Route.Deployment;
        elements: CloudflareApi.aiGateway.UpdateDynamicRoutingResponseRouteElementsItem[];
        gateway_id: string;
        id: string;
        modified_at: string;
        name: string;
        version: Route.Version;
    }

    export namespace Route {
        export interface Deployment {
            created_at: string;
            deployment_id: string;
            version_id: string;
        }

        export interface Version {
            active: Version.Active;
            created_at: string;
            data: string;
            is_valid?: boolean | undefined;
            version_id: string;
        }

        export namespace Version {
            export const Active = {
                VTrue: "true",
                VFalse: "false",
            } as const;
            export type Active = (typeof Active)[keyof typeof Active];
        }
    }
}
