// This file was auto-generated by Fern from our API Definition.

export const ListColosRequestSortBy = {
    FleetStatusUsage: "fleet-status-usage",
    ApplicationTestsUsage: "application-tests-usage",
} as const;
export type ListColosRequestSortBy = (typeof ListColosRequestSortBy)[keyof typeof ListColosRequestSortBy];
