// This file was auto-generated by Fern from our API Definition.

export const BrowserFamilyTopRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type BrowserFamilyTopRequestIpVersionItem =
    (typeof BrowserFamilyTopRequestIpVersionItem)[keyof typeof BrowserFamilyTopRequestIpVersionItem];
