// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         stream_id: "stream_id"
 *     }
 */
export interface CloudflareK2UpdateK2StreamRequest {
    /** Specifies the public ID of the account. */
    account_id: string;
    /** Specifies the public ID of the K2 stream. */
    stream_id: string;
    http?: CloudflareApi.CloudflareK2K2StreamHttpInput;
    /** Sets the record retention period from 1 hour (3600 seconds) to 30 days (2592000 seconds), inclusive. */
    retention_seconds?: number;
    worker_binding?: CloudflareApi.CloudflareK2K2StreamWorkerBindingInput;
}
