// This file was auto-generated by Fern from our API Definition.

export interface GetLoaDocumentsRequest {
    /** Identifier of a Cloudflare account. */
    account_id: string;
    /** Identifier for the uploaded LOA document. */
    loa_document_id: string;
}
