// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const CategoriesInternetServicesRequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type CategoriesInternetServicesRequestFormat =
    (typeof CategoriesInternetServicesRequestFormat)[keyof typeof CategoriesInternetServicesRequestFormat];
