// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         integration: "integration"
 *     }
 */
export interface CreateDatabaseSignatureHyperdriveRequest {
    /** The Cloudflare account ID. */
    account_id: string;
    /** The database integration to authorize against. This value is case-insensitive. */
    integration: string;
}
