// This file was auto-generated by Fern from our API Definition.

export type RunModelAiRequestBody =
    | {
          text: string;
      }
    | {
          guidance?: number | undefined;
          height?: number | undefined;
          image?: number[] | undefined;
          image_b64?: string | undefined;
          mask?: number[] | undefined;
          negative_prompt?: string | undefined;
          num_steps?: number | undefined;
          prompt: string;
          seed?: number | undefined;
          strength?: number | undefined;
          width?: number | undefined;
      }
    | {
          lang?: string | undefined;
          prompt: string;
      }
    | {
          text: string | string[];
      }
    | string
    | {
          audio: number[];
          source_lang?: string | undefined;
          target_lang?: string | undefined;
      }
    | string
    | {
          image: number[];
      }
    | string
    | {
          image?: number[] | undefined;
      }
    | {
          frequency_penalty?: number | undefined;
          lora?: string | undefined;
          max_tokens?: number | undefined;
          presence_penalty?: number | undefined;
          prompt: string;
          raw?: boolean | undefined;
          repetition_penalty?: number | undefined;
          response_format?:
              | {
                    json_schema?: unknown | undefined;
                    type?: ("json_object" | "json_schema") | undefined;
                }
              | undefined;
          seed?: number | undefined;
          stream?: boolean | undefined;
          temperature?: number | undefined;
          top_k?: number | undefined;
          top_p?: number | undefined;
      }
    | {
          frequency_penalty?: number | undefined;
          functions?:
              | {
                    code: string;
                    name: string;
                }[]
              | undefined;
          max_tokens?: number | undefined;
          messages: {
              content:
                  | string
                  | {
                        text?: string | undefined;
                        type?: string | undefined;
                    }[];
              role: string;
          }[];
          presence_penalty?: number | undefined;
          raw?: boolean | undefined;
          repetition_penalty?: number | undefined;
          response_format?:
              | {
                    json_schema?: unknown | undefined;
                    type?: ("json_object" | "json_schema") | undefined;
                }
              | undefined;
          seed?: number | undefined;
          stream?: boolean | undefined;
          temperature?: number | undefined;
          tools?:
              | (
                    | {
                          description: string;
                          name: string;
                          parameters: {
                              properties: Record<
                                  string,
                                  {
                                      description: string;
                                      type: string;
                                  }
                              >;
                              required?: string[] | undefined;
                              type: string;
                          };
                      }
                    | {
                          function: {
                              description: string;
                              name: string;
                              parameters: {
                                  properties: Record<
                                      string,
                                      {
                                          description: string;
                                          type: string;
                                      }
                                  >;
                                  required?: string[] | undefined;
                                  type: string;
                              };
                          };
                          type: string;
                      }
                )[]
              | undefined;
          top_k?: number | undefined;
          top_p?: number | undefined;
      }
    | {
          source_lang?: string | undefined;
          target_lang: string;
          text: string;
      }
    | {
          input_text: string;
          max_length?: number | undefined;
      }
    | string
    | {
          frequency_penalty?: number | undefined;
          image: number[] | string;
          max_tokens?: number | undefined;
          presence_penalty?: number | undefined;
          prompt?: string | undefined;
          raw?: boolean | undefined;
          repetition_penalty?: number | undefined;
          seed?: number | undefined;
          temperature?: number | undefined;
          top_k?: number | undefined;
          top_p?: number | undefined;
      }
    | {
          frequency_penalty?: number | undefined;
          ignore_eos?: boolean | undefined;
          image: string;
          max_tokens?: number | undefined;
          presence_penalty?: number | undefined;
          prompt: string;
          repetition_penalty?: number | undefined;
          seed?: number | undefined;
          temperature?: number | undefined;
          top_k?: number | undefined;
          top_p?: number | undefined;
      }
    | {
          frequency_penalty?: number | undefined;
          ignore_eos?: boolean | undefined;
          image: string;
          max_tokens?: number | undefined;
          messages: {
              content:
                  | string
                  | {
                        image_url?:
                            | {
                                  url: string;
                              }
                            | undefined;
                        text?: string | undefined;
                        type: string;
                    }[];
              role: string;
          }[];
          presence_penalty?: number | undefined;
          repetition_penalty?: number | undefined;
          seed?: number | undefined;
          temperature?: number | undefined;
          top_k?: number | undefined;
          top_p?: number | undefined;
      }
    | {
          image?: string | undefined;
          text?: string[] | undefined;
      };
