// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         dispatch_namespace: "dispatch_namespace"
 *     }
 */
export interface GetDispatchNamespacesRequest {
    /** Identifier. */
    account_id: string;
    /** Name of the Workers for Platforms dispatch namespace. */
    dispatch_namespace: string;
}
