// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         namespace_name: "support-agent",
 *         profile_name: "my-profile",
 *         session_id: "chat-session-44"
 *     }
 */
export interface DeleteSessionAgentMemoryRequest {
    /** Cloudflare Account ID. */
    account_id: string;
    /** Namespace name. */
    namespace_name: string;
    /** Profile name. */
    profile_name: string;
    /** Session identifier. */
    session_id: string;
}
