// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../index.js";

export interface QueryD1Response {
    result: CloudflareApi.D1QueryResultResponse[];
    result_info?: Record<string, unknown> | undefined;
}
