// This file was auto-generated by Fern from our API Definition.

export const ListTestsRequestKind = {
    Http: "http",
    Traceroute: "traceroute",
} as const;
export type ListTestsRequestKind = (typeof ListTestsRequestKind)[keyof typeof ListTestsRequestKind];
