// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         body: {
 *             host: "shop.example.com",
 *             name: "production_webinar",
 *             new_users_per_minute: 1,
 *             total_active_users: 1
 *         }
 *     }
 */
export interface CreateWaitingRoomsRequest {
    /** Identifier. */
    zone_id: string;
    body: CloudflareApi.WaitingroomQueryWaitingroom;
}
