// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { AsnClient } from "../resources/asn/client/Client.js";

export declare namespace ConfigsClient {
    export type Options = BaseClientOptions;
}

export class ConfigsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConfigsClient.Options>;
    protected _asn: AsnClient | undefined;

    constructor(options: ConfigsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get asn(): AsnClient {
        return (this._asn ??= new AsnClient(this._options));
    }
}
