// This file was auto-generated by Fern from our API Definition.

export const GetAsesRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type GetAsesRequestIpVersionItem =
    (typeof GetAsesRequestIpVersionItem)[keyof typeof GetAsesRequestIpVersionItem];
