// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export type GetVersionsResponseElementsItem =
    | CloudflareApi.aiGateway.dynamicRouting.GetVersionsResponseElementsItem.Start
    | CloudflareApi.aiGateway.dynamicRouting.GetVersionsResponseElementsItem.Conditional
    | CloudflareApi.aiGateway.dynamicRouting.GetVersionsResponseElementsItem.Percentage
    | CloudflareApi.aiGateway.dynamicRouting.GetVersionsResponseElementsItem.Rate
    | CloudflareApi.aiGateway.dynamicRouting.GetVersionsResponseElementsItem.Model
    | CloudflareApi.aiGateway.dynamicRouting.GetVersionsResponseElementsItem.End;

export namespace GetVersionsResponseElementsItem {
    export interface Start {
        type: "start";
        id: string;
        outputs: GetVersionsResponseElementsItemStart.Outputs;
    }

    export namespace GetVersionsResponseElementsItemStart {
        export interface Outputs {
            next: Outputs.Next;
        }

        export namespace Outputs {
            export interface Next {
                elementId: string;
            }
        }
    }

    export interface Conditional {
        type: "conditional";
        id: string;
        outputs: GetVersionsResponseElementsItemConditional.Outputs;
        properties: GetVersionsResponseElementsItemConditional.Properties;
    }

    export namespace GetVersionsResponseElementsItemConditional {
        export interface Outputs {
            false: Outputs.False;
            true: Outputs.True;
        }

        export namespace Outputs {
            export interface False {
                elementId: string;
            }

            export interface True {
                elementId: string;
            }
        }

        export interface Properties {
            conditions?: Record<string, unknown> | undefined;
        }
    }

    export interface Percentage {
        type: "percentage";
        id: string;
        outputs: Record<string, GetVersionsResponseElementsItemPercentage.Outputs.Value>;
    }

    export namespace GetVersionsResponseElementsItemPercentage {
        export namespace Outputs {
            export interface Value {
                elementId: string;
            }
        }
    }

    export interface Rate {
        type: "rate";
        id: string;
        outputs: GetVersionsResponseElementsItemRate.Outputs;
        properties: GetVersionsResponseElementsItemRate.Properties;
    }

    export namespace GetVersionsResponseElementsItemRate {
        export interface Outputs {
            fallback: Outputs.Fallback;
            success: Outputs.Success;
        }

        export namespace Outputs {
            export interface Fallback {
                elementId: string;
            }

            export interface Success {
                elementId: string;
            }
        }

        export interface Properties {
            key: string;
            limit: number;
            limitType: Properties.LimitType;
            window: number;
        }

        export namespace Properties {
            export const LimitType = {
                Count: "count",
                Cost: "cost",
            } as const;
            export type LimitType = (typeof LimitType)[keyof typeof LimitType];
        }
    }

    export interface Model {
        type: "model";
        id: string;
        outputs: GetVersionsResponseElementsItemModel.Outputs;
        properties: GetVersionsResponseElementsItemModel.Properties;
    }

    export namespace GetVersionsResponseElementsItemModel {
        export interface Outputs {
            fallback: Outputs.Fallback;
            success: Outputs.Success;
        }

        export namespace Outputs {
            export interface Fallback {
                elementId: string;
            }

            export interface Success {
                elementId: string;
            }
        }

        export interface Properties {
            model: string;
            provider: string;
            retries: number;
            timeout: number;
        }
    }

    export interface End {
        type: "end";
        id: string;
        outputs: Record<string, GetVersionsResponseElementsItemEnd.Outputs.Value>;
    }

    export namespace GetVersionsResponseElementsItemEnd {
        export namespace Outputs {
            export interface Value {
                elementId: string;
            }
        }
    }
}
