// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         membership_id: "membership_id",
 *         status: "accepted"
 *     }
 */
export interface UpdateMembershipsRequest {
    /** Membership identifier tag. */
    membership_id: string;
    /** Whether to accept or reject this account invitation. */
    status: UpdateMembershipsRequest.Status;
}

export namespace UpdateMembershipsRequest {
    /** Whether to accept or reject this account invitation. */
    export const Status = {
        Accepted: "accepted",
        Rejected: "rejected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
