// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "c3dc5f0b34a14ff8e1b3ec04895e1b22",
 *         name: "my-namespace",
 *         ai_search_options: {
 *             instance_ids: ["my-ai-search"]
 *         }
 *     }
 */
export interface MultiSearchAiSearchRequest {
    account_id: string;
    /** Namespace name */
    name: string;
    ai_search_options: MultiSearchAiSearchRequest.AiSearchOptions;
    /** OpenAI-compatible message array. For multimodal queries, set the last user message's `content` to an array of typed parts: `[{type:'text', text:'…'}, {type:'image_url', image_url:{url:'…'}}]`. Image inputs require the RAG's embedding_model to declare 'image' in supported_modalities. */
    messages?: MultiSearchAiSearchRequest.Messages.Item[];
    /** A simple text query string. Alternative to 'messages' — provide either this or 'messages', not both. */
    query?: string;
}

export namespace MultiSearchAiSearchRequest {
    export interface AiSearchOptions {
        cache?: AiSearchOptions.Cache | undefined;
        /** Metadata added to AI Gateway logs for requests triggered by this operation. Accepts up to 2 string, number, or boolean entries. Keys 'ai-search', 'task', 'origin', and keys beginning with 'cf.' are reserved. */
        custom_metadata?: Record<string, AiSearchOptions.CustomMetadata.Value> | undefined;
        instance_ids: string[];
        query_rewrite?: AiSearchOptions.QueryRewrite | undefined;
        reranking?: AiSearchOptions.Reranking | undefined;
        retrieval?: AiSearchOptions.Retrieval | undefined;
    }

    export namespace AiSearchOptions {
        export interface Cache {
            cache_threshold?: Cache.CacheThreshold | undefined;
            enabled?: boolean | undefined;
        }

        export namespace Cache {
            export const CacheThreshold = {
                SuperStrictMatch: "super_strict_match",
                CloseEnough: "close_enough",
                FlexibleFriend: "flexible_friend",
                AnythingGoes: "anything_goes",
            } as const;
            export type CacheThreshold = (typeof CacheThreshold)[keyof typeof CacheThreshold];
        }

        export namespace CustomMetadata {
            export type Value = string | number | boolean;
        }

        export interface QueryRewrite {
            enabled?: boolean | undefined;
            /** A Workers AI model ID or an AI Gateway model ID compatible with the OpenAI Chat Completions API. An empty string uses the configured or default model. */
            model?: string | undefined;
            rewrite_prompt?: string | undefined;
        }

        export interface Reranking {
            enabled?: boolean | undefined;
            match_threshold?: number | undefined;
            model?: string | undefined;
        }

        export interface Retrieval {
            /** Metadata fields to boost search results by. Overrides the instance-level boost_by config. Direction defaults to 'asc' for numeric/datetime fields, 'exists' for text/boolean fields. Fields must match 'timestamp' or a defined custom_metadata field. */
            boost_by?: Retrieval.BoostBy.Item[] | undefined;
            context_expansion?: number | undefined;
            filters?: Record<string, unknown> | undefined;
            fusion_method?: Retrieval.FusionMethod | undefined;
            /** Controls which documents are candidates for BM25 scoring. 'and' restricts candidates to documents containing all query terms; 'or' includes any document containing at least one term, ranked by BM25 relevance. When omitted, falls back to the instance-level retrieval_options.keyword_match_mode, then to 'and'. */
            keyword_match_mode?: Retrieval.KeywordMatchMode | undefined;
            match_threshold?: number | undefined;
            max_num_results?: number | undefined;
            retrieval_type?: Retrieval.RetrievalType | undefined;
            return_on_failure?: boolean | undefined;
        }

        export namespace Retrieval {
            export type BoostBy = BoostBy.Item[];

            export namespace BoostBy {
                export interface Item {
                    /** Boost direction. 'desc' = higher values rank higher (e.g. newer timestamps). 'asc' = lower values rank higher. 'exists' = boost chunks that have the field. 'not_exists' = boost chunks that lack the field. Optional — defaults to 'asc' for numeric/datetime fields, 'exists' for text/boolean fields. */
                    direction?: Item.Direction | undefined;
                    /** Metadata field name to boost by. Use 'timestamp' for document freshness, or any custom_metadata field. Numeric and datetime fields support all four directions (asc, desc, exists, not_exists); text/boolean fields only support exists/not_exists. */
                    field: string;
                }

                export namespace Item {
                    /** Boost direction. 'desc' = higher values rank higher (e.g. newer timestamps). 'asc' = lower values rank higher. 'exists' = boost chunks that have the field. 'not_exists' = boost chunks that lack the field. Optional — defaults to 'asc' for numeric/datetime fields, 'exists' for text/boolean fields. */
                    export const Direction = {
                        Asc: "asc",
                        Desc: "desc",
                        Exists: "exists",
                        NotExists: "not_exists",
                    } as const;
                    export type Direction = (typeof Direction)[keyof typeof Direction];
                }
            }

            export const FusionMethod = {
                Max: "max",
                Rrf: "rrf",
            } as const;
            export type FusionMethod = (typeof FusionMethod)[keyof typeof FusionMethod];
            /** Controls which documents are candidates for BM25 scoring. 'and' restricts candidates to documents containing all query terms; 'or' includes any document containing at least one term, ranked by BM25 relevance. When omitted, falls back to the instance-level retrieval_options.keyword_match_mode, then to 'and'. */
            export const KeywordMatchMode = {
                And: "and",
                Or: "or",
            } as const;
            export type KeywordMatchMode = (typeof KeywordMatchMode)[keyof typeof KeywordMatchMode];
            export const RetrievalType = {
                Vector: "vector",
                Keyword: "keyword",
                Hybrid: "hybrid",
            } as const;
            export type RetrievalType = (typeof RetrievalType)[keyof typeof RetrievalType];
        }
    }

    export type Messages = Messages.Item[];

    export namespace Messages {
        export interface Item {
            content?: unknown | undefined;
            role: Item.Role;
            /** Accepts any additional properties */
            [key: string]: any;
        }

        export namespace Item {
            export const Role = {
                System: "system",
                Developer: "developer",
                User: "user",
                Assistant: "assistant",
                Tool: "tool",
            } as const;
            export type Role = (typeof Role)[keyof typeof Role];
        }
    }
}
