// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         namespace: "my-namespace",
 *         "instance-id": "my-ai-search"
 *     }
 */
export interface PurgeCacheAiSearchRequest {
    account_id: string;
    /** Namespace name */
    namespace: string;
    /** AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores. */
    "instance-id": string;
}
