// This file was auto-generated by Fern from our API Definition.

export interface GetTokensResponse {
    cf_api_id: string;
    created_at?: string | undefined;
    created_by?: (string | null) | undefined;
    enabled?: boolean | undefined;
    id: string;
    legacy?: boolean | undefined;
    modified_at?: string | undefined;
    modified_by?: (string | null) | undefined;
    name: string;
}
