// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface ListIpProfilesResponse {
    result: CloudflareApi.TeamsDevicesIpProfile[];
    result_info?: CloudflareApi.TeamsDevicesPaginationInfo | undefined;
}
