// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353",
 *         content: "content",
 *         name: "name"
 *     }
 */
export interface ValidateRulesRequest {
    /** Cloudflare account ID. */
    account_id: string;
    content: string;
    excludeRuleId?: string;
    name: string;
    namespaces?: string[];
    path?: string;
}
