// This file was auto-generated by Fern from our API Definition.

export const QueueMaintenanceConfigsRequestConfigurationType = {
    Compaction: "compaction",
    SnapshotExpiration: "snapshot_expiration",
} as const;
export type QueueMaintenanceConfigsRequestConfigurationType =
    (typeof QueueMaintenanceConfigsRequestConfigurationType)[keyof typeof QueueMaintenanceConfigsRequestConfigurationType];
