// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         worker_id: "worker_id"
 *     }
 */
export interface GetLatestRequest {
    /** Identifier. */
    account_id: string;
    /** Identifier for the Worker, which can be ID or name. */
    worker_id: string;
    /** Whether to include the `modules` property of the version in the response, which contains code and sourcemap content and may add several megabytes to the response size. */
    include?: "modules";
}
