// This file was auto-generated by Fern from our API Definition.

export const DeleteBucketsRequestCfR2Jurisdiction = {
    VDefault: "default",
    Eu: "eu",
    Us: "us",
    Fedramp: "fedramp",
    FedrampHigh: "fedramp-high",
} as const;
export type DeleteBucketsRequestCfR2Jurisdiction =
    (typeof DeleteBucketsRequestCfR2Jurisdiction)[keyof typeof DeleteBucketsRequestCfR2Jurisdiction];
