// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { RoutingClient } from "../resources/routing/client/Client.js";
import { SecurityClient } from "../resources/security/client/Client.js";

export declare namespace EmailClient {
    export type Options = BaseClientOptions;
}

export class EmailClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EmailClient.Options>;
    protected _routing: RoutingClient | undefined;
    protected _security: SecurityClient | undefined;

    constructor(options: EmailClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get routing(): RoutingClient {
        return (this._routing ??= new RoutingClient(this._options));
    }

    public get security(): SecurityClient {
        return (this._security ??= new SecurityClient(this._options));
    }
}
