// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListLiveInputsResponse {
    liveInputs?: CloudflareApi.StreamLiveInputObjectWithoutUrl[] | undefined;
    /** The total number of remaining live inputs based on cursor position. */
    range?: number | undefined;
    /** The total number of live inputs that match the provided filters. */
    total?: number | undefined;
}
