// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         tld: "com"
 *     }
 */
export interface GetTldsRequest {
    /** Top-level domain. */
    tld: string;
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.GetTldsRequestFormat;
}
