// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../environments.js";
import { LiveClient } from "../resources/live/client/Client.js";
import { OverTimeClient } from "../resources/overTime/client/Client.js";

export declare namespace AggregatesClient {
    export type Options = BaseClientOptions;
}

export class AggregatesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AggregatesClient.Options>;
    protected _live: LiveClient | undefined;
    protected _overTime: OverTimeClient | undefined;

    constructor(options: AggregatesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get live(): LiveClient {
        return (this._live ??= new LiveClient(this._options));
    }

    public get overTime(): OverTimeClient {
        return (this._overTime ??= new OverTimeClient(this._options));
    }
}
