// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { ExpressionTemplateClient } from "../resources/expressionTemplate/client/Client.js";
import { SchemaValidationClient } from "../resources/schemaValidation/client/Client.js";
import { SessionIdentifiersClient } from "../resources/sessionIdentifiers/client/Client.js";
import { TokenValidationClient } from "../resources/tokenValidation/client/Client.js";
import { VulnerabilityScannerClient } from "../resources/vulnerabilityScanner/client/Client.js";

export declare namespace ApiSecurityClient {
    export type Options = BaseClientOptions;
}

export class ApiSecurityClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ApiSecurityClient.Options>;
    protected _sessionIdentifiers: SessionIdentifiersClient | undefined;
    protected _expressionTemplate: ExpressionTemplateClient | undefined;
    protected _schemaValidation: SchemaValidationClient | undefined;
    protected _tokenValidation: TokenValidationClient | undefined;
    protected _vulnerabilityScanner: VulnerabilityScannerClient | undefined;

    constructor(options: ApiSecurityClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get sessionIdentifiers(): SessionIdentifiersClient {
        return (this._sessionIdentifiers ??= new SessionIdentifiersClient(this._options));
    }

    public get expressionTemplate(): ExpressionTemplateClient {
        return (this._expressionTemplate ??= new ExpressionTemplateClient(this._options));
    }

    public get schemaValidation(): SchemaValidationClient {
        return (this._schemaValidation ??= new SchemaValidationClient(this._options));
    }

    public get tokenValidation(): TokenValidationClient {
        return (this._tokenValidation ??= new TokenValidationClient(this._options));
    }

    public get vulnerabilityScanner(): VulnerabilityScannerClient {
        return (this._vulnerabilityScanner ??= new VulnerabilityScannerClient(this._options));
    }
}
