// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         app_id: "app_id",
 *         livestream_id: "livestream_id"
 *     }
 */
export interface GetLivestreamsRequest {
    /** The account identifier tag. */
    account_id: string;
    /** The app identifier tag. */
    app_id: string;
    livestream_id: string;
    /** The page number from which you want your page search results to be displayed. */
    page_no?: number;
    /** Number of results per page. */
    per_page?: number;
}
