// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         rule_id: "rule_id"
 *     }
 */
export interface GetAccessRulesRequest {
    /** Unique identifier for a rule. */
    rule_id: string;
}
