// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         dimension: "AS",
 *         name: ["main_series"],
 *         dateRange: ["7d"],
 *         limitPerGroup: 10,
 *         tld: ["com"]
 *     }
 */
export interface SummaryV2DnsRequest {
    /** Specifies the attribute by which to group the results. Grouping by `TLD_DNS_MAGNITUDE` does not support sub-daily aggregation intervals; `15m` and `1h` are raised to `1d`. */
    dimension: CloudflareApi.radar.SummaryV2DnsRequestDimension;
    /** Array of names used to label the series in the response. */
    name?: string | string[];
    /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
    dateRange?: string | string[];
    /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateStart?: string | string[];
    /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateEnd?: string | string[];
    /** Filters results by Autonomous System. Specify one or more Autonomous System Numbers (ASNs) as a comma-separated list. Prefix with `-` to exclude ASNs from results. For example, `-174, 3356` excludes results from AS174, but includes results from AS3356. */
    asn?: string | string[];
    /** Filters results by location. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude locations from results. For example, `-US,PT` excludes results from the US, but includes results from PT. */
    location?: string | string[];
    /** Filters results by continent. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude continents from results. For example, `-EU,NA` excludes results from EU, but includes results from NA. */
    continent?: string | string[];
    /** Filters results based on cache status. */
    cacheHit?: boolean | boolean[];
    /** Specifies whether the response includes empty DNS responses (NODATA). */
    nodata?: boolean | boolean[];
    /** Filters results by DNS transport protocol. */
    protocol?:
        | CloudflareApi.radar.SummaryV2DnsRequestProtocolItem
        | CloudflareApi.radar.SummaryV2DnsRequestProtocolItem[];
    /** Filters results by DNS query type. */
    queryType?:
        | (CloudflareApi.radar.SummaryV2DnsRequestQueryTypeItem | null)
        | (CloudflareApi.radar.SummaryV2DnsRequestQueryTypeItem | null)[];
    /** Filters results by DNS response code. */
    responseCode?:
        | CloudflareApi.radar.SummaryV2DnsRequestResponseCodeItem
        | CloudflareApi.radar.SummaryV2DnsRequestResponseCodeItem[];
    /** Filters results by DNS response TTL. */
    responseTtl?:
        | CloudflareApi.radar.SummaryV2DnsRequestResponseTtlItem
        | CloudflareApi.radar.SummaryV2DnsRequestResponseTtlItem[];
    /** Filters results based on DNSSEC (DNS Security Extensions) support. */
    dnssec?: CloudflareApi.radar.SummaryV2DnsRequestDnssecItem | CloudflareApi.radar.SummaryV2DnsRequestDnssecItem[];
    /** Filters results based on DNSSEC (DNS Security Extensions) client awareness. */
    dnssecAware?:
        | CloudflareApi.radar.SummaryV2DnsRequestDnssecAwareItem
        | CloudflareApi.radar.SummaryV2DnsRequestDnssecAwareItem[];
    /** Filters results based on DNSSEC-validated answers by end-to-end security status. */
    dnssecE2e?: boolean | boolean[];
    /** Filters results by IP version (Ipv4 vs. IPv6). */
    ipVersion?:
        | CloudflareApi.radar.SummaryV2DnsRequestIpVersionItem
        | CloudflareApi.radar.SummaryV2DnsRequestIpVersionItem[];
    /** Limits the number of objects per group to the top items within the specified time range. When item count exceeds the limit, extra items appear grouped under an "other" category. Only supported on high-cardinality dimensions; otherwise the request is rejected. Minimum value is 2. */
    limitPerGroup?: number;
    /** Filters results based on whether the queries have a matching answer. */
    matchingAnswer?: boolean | boolean[];
    /** Filters results by top-level domain. Incompatible with the `ipVersion`, `protocol`, `dnssecE2e`, `dnssecAware`, `responseTtl`, and `cacheHit` filters/dimensions; this restriction does not apply to country-code TLDs (2-letter, e.g. `uk`). */
    tld?: string | string[];
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.SummaryV2DnsRequestFormat;
}
