// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface DeleteSchemasResponse extends CloudflareApi.ApiShieldApiResponseCommon {
    /** Schema deletion returns no result body. */
    result: Record<string, unknown> | null;
}
