// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListResourcesResponse {
    result: CloudflareApi.ResourceSharingShareResourceObject[];
    result_info?: CloudflareApi.ResourceSharingResultInfo | undefined;
}
