// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "46148281d8a93d002ef242d8b0d5f9f6",
 *         finding_instance_ids: ["3f7b8c9d-6e5a-4f3b-9c2d-1e0a8b7c6d5e", "ab7b8c9d-6e5a-4f3b-9c2d-1e0a8b7c6d7g"],
 *         remediation_type_id: "5a7d9e2f-1b3c-4d5e-8f6a-7b8c9d0e1f2a"
 *     }
 */
export interface PostureApiRemediationJobsCreateRequest {
    /** Cloudflare account ID for the user making the request. */
    account_id: string;
    /** UUIDs identifying Finding Instances. */
    finding_instance_ids: string[];
    /** A UUID identifying this Remediation Type. */
    remediation_type_id: string;
}
