// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account-123",
 *         body: {
 *             scheduling_policy: "default",
 *             configuration: {
 *                 image: "image"
 *             },
 *             instances: 1,
 *             max_instances: 1,
 *             name: "name"
 *         }
 *     }
 */
export interface CreateApplicationsRequest {
    /** Account identifier. */
    account_id: string;
    body: CloudflareApi.CcContainersCreateApplicationRequest;
}
