// This file was auto-generated by Fern from our API Definition.

export interface AaaAuditLogsActor {
    /** The email of the user that performed the action. */
    email?: string | undefined;
    /** The ID of the actor that performed the action. If a user performed the action, this will be their User ID. */
    id?: string | undefined;
    /** The IP address of the request that performed the action. */
    ip?: string | undefined;
    /** The type of actor, whether a User, Cloudflare Admin, or an Automated System. */
    type?: AaaAuditLogsActor.Type | undefined;
}

export namespace AaaAuditLogsActor {
    /** The type of actor, whether a User, Cloudflare Admin, or an Automated System. */
    export const Type = {
        User: "user",
        Admin: "admin",
        Cloudflare: "Cloudflare",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
