// This file was auto-generated by Fern from our API Definition.

/**
 * Timestamp of the last time an attempt to dispatch a notification to this webhook failed.
 */
export type AaaLastFailure = string;
