// This file was auto-generated by Fern from our API Definition.

/**
 * Please provide a more detailed description of the infringement between 1 and 5000 characters
 */
export type AbuseReportsBadJustError = string;
