// This file was auto-generated by Fern from our API Definition.

/**
 * You have entered URLs that contain more than 1 unique hostname. A single report may only include 1 unique hostname (i.e, www.example.com). To report URLs related to another hostname (i.e. other.example.com) you'll need to file a separate report.
 */
export type AbuseReportsUrlNotvalidError = string;
