// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AbuseReportsSubmittedAbuseReportDetail {
    /** Time the report was submitted. */
    cdate: string;
    /** Submitter-safe reason for a denied report. Null when unavailable. */
    denial_reason: string | null;
    /** Domain identified in the report. */
    domain: string;
    /** Public report code. */
    id: string;
    status: CloudflareApi.AbuseReportsSubmittedAbuseReportStatus;
    submitter?: CloudflareApi.AbuseReportsSubmitterDetails | undefined;
    type: CloudflareApi.AbuseReportsReportType;
    /** Authorized agent name supplied with the report. */
    agent_name?: string | undefined;
    /** Additional comments supplied with the report. */
    comments?: string | undefined;
    /** The string "on" when a court proceeding applies to the report; otherwise omitted. */
    court?: string | undefined;
    /** Destination IP addresses supplied with a network abuse report. */
    destination_ips?: string[] | undefined;
    /** Whether the submitter provided the Digital Services Act attestation. */
    dsa_attestation: boolean;
    /** Submitter preference for notifying the hosting provider. */
    host_notification?: string | undefined;
    /** Evidence supplied with the report. */
    justification?: string | undefined;
    /** Submitter preference for notifying NCMEC. */
    ncmec_notification?: string | undefined;
    /** Representation supplied for an NCSEI report. */
    ncsei_subject_representation?: boolean | undefined;
    /** Original work or targeted brand supplied with the report. */
    original_work?: string | undefined;
    /** Submitter preference for notifying the content owner. */
    owner_notification?: string | undefined;
    /** Ports and protocols supplied with a network abuse report. */
    ports_protocols?: string[] | undefined;
    reg_who_request?: CloudflareApi.AbuseReportsRegistrarWhoIsFields | undefined;
    /** Country associated with the reported activity. */
    reported_country?: string | undefined;
    /** User agent associated with the reported activity. */
    reported_user_agent?: string | undefined;
    /** Source IP addresses supplied with a network abuse report. */
    source_ips?: string[] | undefined;
    /** Additional abuse classifications supplied with the report. */
    subtypes?: string[] | undefined;
    /** Title supplied with the report. */
    title?: string | undefined;
    /** The string "on" when a UDRP proceeding applies to the report; otherwise omitted. */
    udrp?: string | undefined;
    /** URLs supplied with the report. */
    urls: string[];
    /** The string "on" when a URS proceeding applies to the report; otherwise omitted. */
    urs?: string | undefined;
}
