// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AbuseReportsBaseReportFields {
    act: CloudflareApi.AbuseReportsSubmissionReportType;
    /** Any additional comments about the infringement not exceeding 2000 characters */
    comments?: string | undefined;
    /** Text not exceeding 100 characters. This field may be released by Cloudflare to third parties such as the Lumen Database (https://lumendatabase.org/). */
    company?: string | undefined;
    /** A valid email of the abuse reporter. This field may be released by Cloudflare to third parties such as the Lumen Database (https://lumendatabase.org/). */
    email: string;
    /** Should match the value provided in `email` */
    email2: string;
    /** Text not exceeding 255 characters. This field may be released by Cloudflare to third parties such as the Lumen Database (https://lumendatabase.org/). */
    name: string;
    /** Text containing 2 characters */
    reported_country?: string | undefined;
    /** Text not exceeding 255 characters */
    reported_user_agent?: string | undefined;
    /** Text not exceeding 20 characters. This field may be released by Cloudflare to third parties such as the Lumen Database (https://lumendatabase.org/). */
    tele?: string | undefined;
    /** Text not exceeding 255 characters */
    title?: string | undefined;
    /** A list of valid URLs separated by ‘\n’ (new line character). The list of the URLs should not exceed 250 URLs. All URLs should have the same hostname. Each URL should be unique. This field may be released by Cloudflare to third parties such as the Lumen Database (https://lumendatabase.org/). */
    urls: string;
}
