// This file was auto-generated by Fern from our API Definition.

/** The status of a mitigation */
export const AbuseReportsMitigationStatus = {
    Pending: "pending",
    Active: "active",
    InReview: "in_review",
    Cancelled: "cancelled",
    Removed: "removed",
} as const;
export type AbuseReportsMitigationStatus =
    (typeof AbuseReportsMitigationStatus)[keyof typeof AbuseReportsMitigationStatus];
