// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Configuration for provisioning to this application via SCIM. This is currently in closed beta.
 */
export interface AccessScimConfig {
    authentication?: CloudflareApi.AccessScimConfigAuthentication | undefined;
    /** If false, propagates DELETE requests to the target application for SCIM resources. If true, sets 'active' to false on the SCIM resource. Note: Some targets do not support DELETE operations. */
    deactivate_on_delete?: boolean | undefined;
    /** Whether SCIM provisioning is turned on for this application. */
    enabled?: boolean | undefined;
    /** The UID of the IdP to use as the source for SCIM resources to provision to this application. */
    idp_uid: string;
    /** A list of mappings to apply to SCIM resources before provisioning them in this application. These can transform or filter the resources to be provisioned. */
    mappings?: CloudflareApi.AccessScimConfigMapping[] | undefined;
    /** The base URI for the application's SCIM-compatible API. */
    remote_uri: string;
}
