// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessCustomPageWithoutHtml {
    app_count?: CloudflareApi.AccessAppCount2 | undefined;
    contract_version?: CloudflareApi.AccessContractVersion | undefined;
    created_at?: CloudflareApi.AccessCreatedAt | undefined;
    name: CloudflareApi.AccessName11;
    type: CloudflareApi.AccessType2;
    uid?: CloudflareApi.AccessUuid | undefined;
    updated_at?: CloudflareApi.AccessUpdatedAt | undefined;
    /** Advisory validation findings returned when creating or updating a template. Omitted when empty. */
    warnings?: CloudflareApi.AccessTemplateViolation[] | undefined;
}
