// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessIdResponse5Result {
    id?: CloudflareApi.AccessId3 | undefined;
}
