// This file was auto-generated by Fern from our API Definition.

/**
 * The Client ID for the service token. Access will check for this value in the `CF-Access-Client-ID` request header.
 */
export type AccessClientId = string;
