// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessJitRequestEvent {
    actor_email?: string | undefined;
    actor_idp?: string | undefined;
    actor_uuid?: string | undefined;
    decision_outcome?: string | undefined;
    ray_id?: string | undefined;
    session_duration_seconds?: number | undefined;
    success?: boolean | undefined;
    timestamp?: CloudflareApi.AccessTimestamp | undefined;
    type?: CloudflareApi.AccessJitRequestEventType | undefined;
}
