// This file was auto-generated by Fern from our API Definition.

export interface AccessOidcSaasApp2HybridAndImplicitOptions {
    /** If an Access Token should be returned from the OIDC Authorization endpoint */
    return_access_token_from_authorization_endpoint?: boolean | undefined;
    /** If an ID Token should be returned from the OIDC Authorization endpoint */
    return_id_token_from_authorization_endpoint?: boolean | undefined;
}
