// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessDevicePostureRuleDevicePosture {
    /** The ID of the account that owns the device posture integration. */
    account_id?: CloudflareApi.AccessIdentifier | undefined;
    /** The ID of a device posture integration. */
    integration_uid: string;
}
