// This file was auto-generated by Fern from our API Definition.

/**
 * Requires the user to request access from an administrator at the start of each session.
 */
export type AccessApprovalRequired2 = boolean;
