// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessPolicyCheckResponseResult {
    app_state?: CloudflareApi.AccessPolicyCheckResponseResultAppState | undefined;
    user_identity?: CloudflareApi.AccessPolicyCheckResponseResultUserIdentity | undefined;
}
