// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * The result of validating a template's content.
 */
export interface AccessValidationResult {
    /** Blocking findings; a non-empty list means the template cannot be published. */
    errors: CloudflareApi.AccessTemplateViolation[];
    page_type: CloudflareApi.AccessType2;
    /** The contract version the template was validated against. */
    version: number;
    /** Advisory findings that do not block publishing. */
    warnings: CloudflareApi.AccessTemplateViolation[];
}
