// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Clipboard formats allowed when copying from local machine to remote RDP session.
 */
export type AccessAllowedClipboardLocalToRemoteFormats = CloudflareApi.AccessRdpClipboardFormat[];
