// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Create Allow or Block policies which evaluate the user based on custom criteria.
 */
export interface AccessExternalEvaluationRule {
    external_evaluation: CloudflareApi.AccessExternalEvaluationRuleExternalEvaluation;
}
