// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Matches an Okta group.
 * Requires an Okta identity provider.
 */
export interface AccessOktaGroupRule {
    okta: CloudflareApi.AccessOktaGroupRuleOkta;
}
