// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessNameResponseResult {
    name?: CloudflareApi.AccessName13 | undefined;
}
