// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessSshProps2 {
    allow_iframe?: CloudflareApi.AccessAllowIframe | undefined;
    allowed_idps?: CloudflareApi.AccessAllowedIdps | undefined;
    app_launcher_visible?: CloudflareApi.AccessAppLauncherVisible | undefined;
    auto_redirect_to_identity?: CloudflareApi.AccessAutoRedirectToIdentity2 | undefined;
    cors_headers?: CloudflareApi.AccessCorsHeaders | undefined;
    custom_deny_message?: CloudflareApi.AccessCustomDenyMessage | undefined;
    custom_deny_url?: CloudflareApi.AccessCustomDenyUrl2 | undefined;
    domain: CloudflareApi.AccessDomain3;
    eager_redirect_cookie_setting?: CloudflareApi.AccessEagerRedirectCookieSetting | undefined;
    enable_binding_cookie?: CloudflareApi.AccessEnableBindingCookie | undefined;
    http_only_cookie_attribute?: CloudflareApi.AccessHttpOnlyCookieAttribute | undefined;
    logo_url?: CloudflareApi.AccessLogoUrl | undefined;
    name?: CloudflareApi.AccessName8 | undefined;
    options_preflight_bypass?: CloudflareApi.AccessOptionsPreflightBypass2 | undefined;
    same_site_cookie_attribute?: CloudflareApi.AccessSameSiteCookieAttribute | undefined;
    service_auth_401_redirect?: CloudflareApi.AccessServiceAuth401Redirect | undefined;
    session_duration?: CloudflareApi.AccessSessionDuration4 | undefined;
    skip_interstitial?: CloudflareApi.AccessSkipInterstitial | undefined;
    /** The application type. */
    type: string;
    use_clientless_isolation_app_launcher_url?: CloudflareApi.AccessUseClientlessIsolationAppLauncherUrl | undefined;
}
