// This file was auto-generated by Fern from our API Definition.

export interface AccessCustomPages {
    /** The uid of the custom page to use when a user is denied access after failing a non-identity rule. */
    forbidden?: string | undefined;
    /** The uid of the custom page to use when a user is denied access. */
    identity_denied?: string | undefined;
}
