// This file was auto-generated by Fern from our API Definition.

/**
 * The Authenticator Attestation GUID (AAGUID) uniquely identifying a FIDO2 authenticator model
 */
export type AccessAaguid = string;
