// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Administrators who can approve a temporary authentication request.
 */
export type AccessApprovalGroups = CloudflareApi.AccessApprovalGroup[];
