// This file was auto-generated by Fern from our API Definition.

/**
 * Contract version of the page's Liquid template. Present (>= 1) marks a sanitized template; absent or 0 marks a legacy page served verbatim.
 */
export type AccessContractVersion = number;
