// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessCertificates3 {
    associated_hostnames?: CloudflareApi.AccessAssociatedHostnames2 | undefined;
    created_at?: CloudflareApi.AccessTimestamp | undefined;
    expires_on?: CloudflareApi.AccessTimestamp | undefined;
    fingerprint?: CloudflareApi.AccessFingerprint | undefined;
    /** The ID of the application that will use this certificate. */
    id?: string | undefined;
    name?: CloudflareApi.AccessName18 | undefined;
    updated_at?: CloudflareApi.AccessTimestamp | undefined;
}
