// This file was auto-generated by Fern from our API Definition.

/**
 * Contains a map of target attribute keys to target attribute values.
 */
export type AccessTargetAttributes = Record<string, string[]>;
