// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AccessGroups3 {
    created_at?: CloudflareApi.AccessTimestamp | undefined;
    exclude?: CloudflareApi.AccessExclude | undefined;
    id?: CloudflareApi.AccessUuid | undefined;
    include?: CloudflareApi.AccessInclude | undefined;
    name?: CloudflareApi.AccessName16 | undefined;
    require?: CloudflareApi.AccessRequire | undefined;
    updated_at?: CloudflareApi.AccessTimestamp | undefined;
}
