// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Matches an Azure Authentication Context.
 * Requires an Azure identity provider.
 */
export interface AccessAuthContextRule {
    auth_context: CloudflareApi.AccessAuthContextRuleAuthContext;
}
