// This file was auto-generated by Fern from our API Definition.

/**
 * When set to true, users can authenticate via WARP for any application in your organization. Application settings will take precedence over this value.
 */
export type AccessAllowAuthenticateViaWarp = boolean;
