// This file was auto-generated by Fern from our API Definition.

/**
 * Last time the advertisement status was changed. This field is only not 'null' if on demand is enabled.
 */
export type AddressingAdvertisedModifiedAtNullable = string | null;
