// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AddressingIpamBgpPrefixes {
    asn?: (CloudflareApi.AddressingAsn2 | null) | undefined;
    asn_prepend_count?: CloudflareApi.AddressingAsnPrependCount | undefined;
    auto_advertise_withdraw?: CloudflareApi.AddressingAutoAdvertiseWithdraw | undefined;
    bgp_signal_opts?: CloudflareApi.AddressingBgpSignalOpts | undefined;
    cidr?: CloudflareApi.AddressingCidr | undefined;
    created_at?: CloudflareApi.AddressingTimestamp | undefined;
    id?: CloudflareApi.AddressingBgpPrefixIdentifier | undefined;
    modified_at?: CloudflareApi.AddressingTimestamp | undefined;
    on_demand?: CloudflareApi.AddressingBgpOnDemand | undefined;
}
