// This file was auto-generated by Fern from our API Definition.

/** The type of the membership. */
export const AddressingKind = {
    Zone: "zone",
    Account: "account",
} as const;
export type AddressingKind = (typeof AddressingKind)[keyof typeof AddressingKind];
