// This file was auto-generated by Fern from our API Definition.

/**
 * Content signal directives from robots.txt.
 */
export interface AiAuditContentSignal {
    /** Whether AI input usage is permitted. */
    "ai-input"?: AiAuditContentSignal.AiInput | undefined;
    /** Whether AI training is permitted. */
    "ai-train"?: AiAuditContentSignal.AiTrain | undefined;
    /** Whether search indexing is permitted. */
    search?: AiAuditContentSignal.Search | undefined;
}

export namespace AiAuditContentSignal {
    /** Whether AI input usage is permitted. */
    export const AiInput = {
        Yes: "yes",
        No: "no",
    } as const;
    export type AiInput = (typeof AiInput)[keyof typeof AiInput];
    /** Whether AI training is permitted. */
    export const AiTrain = {
        Yes: "yes",
        No: "no",
    } as const;
    export type AiTrain = (typeof AiTrain)[keyof typeof AiTrain];
    /** Whether search indexing is permitted. */
    export const Search = {
        Yes: "yes",
        No: "no",
    } as const;
    export type Search = (typeof Search)[keyof typeof Search];
}
