// This file was auto-generated by Fern from our API Definition.

export interface AigBillingGetTopupConfigResult {
    amount: number | null;
    disabledReason?: (string | null) | undefined;
    error?: (string | null) | undefined;
    lastFailedAt?: (number | null) | undefined;
    threshold: number | null;
}
