// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface AlexandriaGetCategoriesResponse {
    errors: CloudflareApi.AlexandriaMessages;
    messages: CloudflareApi.AlexandriaMessages;
    /** Indicates whether the API call was successful. */
    success: true;
    result?: CloudflareApi.AlexandriaCategories | undefined;
}
