// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsSqlApiErrorResponse {
    /** Machine-readable error code. */
    code: number;
    /** Additional errors that caused this error. */
    error_chain?: Record<string, unknown>[] | undefined;
    /** Human-readable error message. */
    message: string;
}
