// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsSqlDatasetAvailability {
    /** Whether the dataset is enabled for the whole account or for a single zone. */
    scope: AnalyticsSqlDatasetAvailability.Scope;
    /** Zone tag. Present only when `scope` is `zone`. */
    zone?: string | undefined;
}

export namespace AnalyticsSqlDatasetAvailability {
    /** Whether the dataset is enabled for the whole account or for a single zone. */
    export const Scope = {
        Account: "account",
        Zone: "zone",
    } as const;
    export type Scope = (typeof Scope)[keyof typeof Scope];
}
