// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsSqlLogExplorerQueryResponse {
    /** Log Explorer query rows keyed by selected column names. */
    data: Record<string, unknown>[];
    /** Number of rows in data. */
    rows: number;
}
