// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsEngineJsonFormatResponseMetaItem {
    /** Column name. */
    name: string;
    /** Column data type. */
    type: string;
}
