// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ApiShieldOperationFeatureThresholdsThresholds {
    auth_id_tokens?: CloudflareApi.ApiShieldAuthIdTokens | undefined;
    data_points?: CloudflareApi.ApiShieldDataPoints | undefined;
    last_updated?: CloudflareApi.ApiShieldTimestamp | undefined;
    p50?: CloudflareApi.ApiShieldP50 | undefined;
    p90?: CloudflareApi.ApiShieldP90 | undefined;
    p99?: CloudflareApi.ApiShieldP99 | undefined;
    period_seconds?: CloudflareApi.ApiShieldPeriodSeconds | undefined;
    requests?: CloudflareApi.ApiShieldRequests | undefined;
    suggested_threshold?: CloudflareApi.ApiShieldSuggestedThreshold | undefined;
}
