// This file was auto-generated by Fern from our API Definition.

/** Action to take on requests that match operations included in `selector` and fail `expression`. */
export const ApiShieldAction = {
    Log: "log",
    Block: "block",
} as const;
export type ApiShieldAction = (typeof ApiShieldAction)[keyof typeof ApiShieldAction];
