// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Schema active on endpoint.
 */
export interface ApiShieldOperationFeatureSchemaInfoSchemaInfoActiveSchema {
    created_at?: CloudflareApi.ApiShieldTimestamp | undefined;
    id?: CloudflareApi.ApiShieldUuid2 | undefined;
    /** Schema file name. */
    name?: string | undefined;
}
