// This file was auto-generated by Fern from our API Definition.

/**
 * Rule expression. Requests that fail to match this expression will be subject to `action`.
 *
 * For details on expressions, see the [Cloudflare Docs](https://developers.cloudflare.com/api-shield/security/jwt-validation/).
 */
export type ApiShieldExpression = string;
