// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ApiShieldTrafficStatsTrafficStats {
    last_updated: CloudflareApi.ApiShieldTimestamp2;
    /** The period in seconds these statistics were computed over */
    period_seconds?: number | undefined;
    /** The average number of requests seen during this period */
    requests?: number | undefined;
}
