// This file was auto-generated by Fern from our API Definition.

/**
 * Mark state of operation in API Discovery
 *   * `review` - Mark operation as for review
 *   * `ignored` - Mark operation as ignored
 */
export const ApiShieldApiDiscoveryStatePatch = {
    Review: "review",
    Ignored: "ignored",
} as const;
export type ApiShieldApiDiscoveryStatePatch =
    (typeof ApiShieldApiDiscoveryStatePatch)[keyof typeof ApiShieldApiDiscoveryStatePatch];
