// This file was auto-generated by Fern from our API Definition.

/**
 * JSON representation of a symmetric verification key in API responses (secret material is redacted).
 */
export interface ApiShieldCredentialsJwtKeyOctResponse {
    /** Key ID */
    kid: string;
    /** Algorithm */
    alg: ApiShieldCredentialsJwtKeyOctResponse.Alg;
    /** Key Type */
    kty: "oct";
}

export namespace ApiShieldCredentialsJwtKeyOctResponse {
    /** Algorithm */
    export const Alg = {
        Hs256: "HS256",
        Hs384: "HS384",
        Hs512: "HS512",
    } as const;
    export type Alg = (typeof Alg)[keyof typeof Alg];
}
