// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * API Routing settings on endpoint.
 */
export interface ApiShieldOperationFeatureApiRoutingApiRouting {
    last_updated?: CloudflareApi.ApiShieldTimestamp | undefined;
    /** Target route. */
    route?: string | undefined;
}
