// This file was auto-generated by Fern from our API Definition.

export interface BadGatewayErrorBody {
    errors: BadGatewayErrorBody.Errors.Item[];
    messages: BadGatewayErrorBody.Messages.Item[];
    result: Record<string, unknown> | null;
    success: false;
}

export namespace BadGatewayErrorBody {
    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            code: number;
            documentation_url?: string | undefined;
            message: string;
            source?: Item.Source | undefined;
        }

        export namespace Item {
            export interface Source {
                pointer?: string | undefined;
            }
        }
    }

    export type Messages = Messages.Item[];

    export namespace Messages {
        export interface Item {
            code: number;
            documentation_url?: string | undefined;
            message: string;
            source?: Item.Source | undefined;
        }

        export namespace Item {
            export interface Source {
                pointer?: string | undefined;
            }
        }
    }
}
