// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface BillSubsApiUnpaidInvoicesResponseSingle {
    errors: CloudflareApi.BillSubsApiMessages;
    messages: CloudflareApi.BillSubsApiMessages;
    result: CloudflareApi.BillSubsApiUnpaidInvoicesResponseSingleResult;
    /** Whether the API call was successful */
    success: true;
}
