// This file was auto-generated by Fern from our API Definition.

export interface BillSubsApiPaymentMethod {
    /** Billing address line 1. */
    address?: string | undefined;
    /** Billing address line 2. */
    address2?: string | undefined;
    /** Bank account type. */
    bank_account_type?: string | undefined;
    /** Bank code. */
    bank_code?: string | undefined;
    /** Bank country. */
    bank_country?: string | undefined;
    /** Bank name for bank-based payment methods. */
    bank_name?: string | undefined;
    /** Bank routing number. */
    bank_routing_number?: string | undefined;
    /** Cash App cash tag. */
    cashapp_cash_tag?: string | undefined;
    /** Billing city. */
    city?: string | undefined;
    /** Billing country. */
    country?: string | undefined;
    /** Whether this is the default payment method. */
    default?: boolean | undefined;
    /** Device data for fraud prevention. */
    device_data?: string | undefined;
    /** Card expiration date. */
    expiration_date?: string | undefined;
    /** Billing first name. */
    first_name?: string | undefined;
    /** Payment method identifier. */
    id?: string | undefined;
    /** Last four digits of the card number. */
    last_four?: string | undefined;
    /** Billing last name. */
    last_name?: string | undefined;
    /** A nickname for the payment method. */
    nick_name?: string | undefined;
    /** Email associated with the payment account. */
    payment_account_email?: string | undefined;
    /** Payment email address. */
    payment_email?: string | undefined;
    /** The payment gateway used. */
    payment_gateway?: string | undefined;
    /** Payment nonce for tokenized payments. */
    payment_nonce?: string | undefined;
    /** Billing state. */
    state?: string | undefined;
    /** The payment method type. */
    type?: BillSubsApiPaymentMethod.Type | undefined;
    /** Billing zip code. */
    zipcode?: string | undefined;
}

export namespace BillSubsApiPaymentMethod {
    /** The payment method type. */
    export const Type = {
        CreditCard: "CREDIT_CARD",
        Paypal: "PAYPAL",
        Cashapp: "CASHAPP",
        SepaDebit: "SEPA_DEBIT",
        Link: "LINK",
        AchDirectDebit: "ACH_DIRECT_DEBIT",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
