// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Successful response containing account-visible billable metrics.
 */
export interface BillableUsageApiV2AccountBillableMetricsResponse {
    errors: CloudflareApi.BillableUsageApiMessage[] | null;
    messages: CloudflareApi.BillableUsageApiMessage[] | null;
    result: CloudflareApi.BillableUsageApiV2AccountBillableMetric[];
    success: true;
}
