// This file was auto-generated by Fern from our API Definition.

/**
 * The rate plan applied to the subscription.
 */
export interface BillSubsApiRatePlan {
    /** The currency applied to the rate plan subscription. */
    currency?: string | undefined;
    /** Whether this rate plan is managed externally from Cloudflare. */
    externally_managed?: boolean | undefined;
    /** The ID of the rate plan. */
    id?: string | undefined;
    /** Whether a rate plan is enterprise-based (or newly adopted term contract). */
    is_contract?: boolean | undefined;
    /** The full name of the rate plan. */
    public_name?: string | undefined;
    /** The scope that this rate plan applies to. */
    scope?: string | undefined;
    /** The list of sets this rate plan applies to. Returns array of strings. */
    sets?: string[] | undefined;
}
