// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Represents a successful response containing subscription info.
 */
export interface BillableUsageApiUsageInfoResponse {
    /** Contains error details if the request failed. */
    errors: CloudflareApi.BillableUsageApiMessage[] | null;
    /** Contains any informational messages from the API. */
    messages: CloudflareApi.BillableUsageApiMessage[] | null;
    result: CloudflareApi.BillableUsageApiUsageInfoResponseResult;
    /** Indicates whether the API call was successful. */
    success: true;
}
