// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface BotManagementBotFightModeConfig extends CloudflareApi.BotManagementBaseConfig {
    fight_mode?: CloudflareApi.BotManagementFightMode | undefined;
    /** A read-only field that shows which unauthorized settings are currently active on the zone. These settings typically result from upgrades or downgrades. */
    stale_zone_configuration?: BotManagementBotFightModeConfig.StaleZoneConfiguration | undefined;
}

export namespace BotManagementBotFightModeConfig {
    /**
     * A read-only field that shows which unauthorized settings are currently active on the zone. These settings typically result from upgrades or downgrades.
     */
    export interface StaleZoneConfiguration {
        optimize_wordpress?: CloudflareApi.BotManagementOptimizeWordpressTurnedOn | undefined;
        sbfm_definitely_automated?: CloudflareApi.BotManagementSbfmDefinitelyAutomatedTurnedOn | undefined;
        sbfm_likely_automated?: CloudflareApi.BotManagementSbfmLikelyAutomatedTurnedOn | undefined;
        sbfm_static_resource_protection?: CloudflareApi.BotManagementSbfmStaticResourceProtectionTurnedOn | undefined;
        sbfm_verified_bots?: CloudflareApi.BotManagementSbfmVerifiedBotsTurnedOn | undefined;
        suppress_session_score?: CloudflareApi.BotManagementSuppressSessionScoreTurnedOff | undefined;
    }
}
