// This file was auto-generated by Fern from our API Definition.

/** Enable rule to block AI Scrapers and Crawlers. */
export const BotManagementAiBotsProtection = {
    Block: "block",
    Disabled: "disabled",
    OnlyOnAdPages: "only_on_ad_pages",
} as const;
export type BotManagementAiBotsProtection =
    (typeof BotManagementAiBotsProtection)[keyof typeof BotManagementAiBotsProtection];
