// This file was auto-generated by Fern from our API Definition.

/** Type of feedback report. */
export const BotManagementFeedbackType = {
    FalsePositive: "false_positive",
    FalseNegative: "false_negative",
} as const;
export type BotManagementFeedbackType = (typeof BotManagementFeedbackType)[keyof typeof BotManagementFeedbackType];
