// This file was auto-generated by Fern from our API Definition.

/**
 * Use lightweight, invisible JavaScript detections to improve Bot Management. [Learn more about JavaScript Detections](https://developers.cloudflare.com/bots/reference/javascript-detections/).
 */
export type BotManagementEnableJs = boolean;
