// This file was auto-generated by Fern from our API Definition.

export interface BrexBrowserExtensionConfigInput {
    /** Minimum required browser extension version. */
    min_extension_version?: string | undefined;
    /** Access team name. The service derives `team_domain` as `<team_name>.cloudflareaccess.com`. */
    team_name: string;
}
