// This file was auto-generated by Fern from our API Definition.

/**
 * Provider-specific identifier of the account or namespace that owns the repository.
 */
export type BuildsProviderAccountId = string;
