// This file was auto-generated by Fern from our API Definition.

/**
 * Whether pushes to the git branch build this Preview. Deploy hooks, manual builds, and retries run regardless of this setting.
 */
export type BuildsPreviewAutoBuild = boolean;
