// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type BuildsCreateWorkerGitRepositoryInput =
    | CloudflareApi.BuildsCreateWorkerGitRepositoryInput.Github
    | CloudflareApi.BuildsCreateWorkerGitRepositoryInput.Gitlab
    | CloudflareApi.BuildsCreateWorkerGitRepositoryInput.GitlabInternal
    | CloudflareApi.BuildsCreateWorkerGitRepositoryInput.Origin;

export namespace BuildsCreateWorkerGitRepositoryInput {
    export interface Github extends CloudflareApi.BuildsCreateWorkerGitRepositoryFunfettiInput {
        provider_type: "github";
    }

    export interface Gitlab extends CloudflareApi.BuildsCreateWorkerGitRepositoryFunfettiInput {
        provider_type: "gitlab";
    }

    export interface GitlabInternal extends CloudflareApi.BuildsCreateWorkerGitRepositoryGrantInput {
        provider_type: "gitlab_internal";
    }

    export interface Origin extends CloudflareApi.BuildsCreateWorkerGitRepositoryGrantInput {
        provider_type: "origin";
    }
}
