// This file was auto-generated by Fern from our API Definition.

/**
 * Pagination metadata for list responses.
 */
export interface CacheSettingsOriginCloudRegionV2ResultInfo {
    /** Number of items returned in this response. */
    count: number;
    /** Current page number. */
    page: number;
    /** Number of items per page. */
    per_page: number;
    /** Total number of mappings configured for the zone. */
    total_count: number;
    /** Total number of pages. */
    total_pages: number;
}
