// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for creating or replacing an origin cloud region mapping.
 */
export interface CacheSettingsOriginCloudRegionV2Request {
    /** Origin IP address (IPv4 or IPv6). For the single PUT endpoint (`PUT /origin/cloud_regions/{origin_ip}`), this field must match the path parameter or the request will be rejected with a 400 error. For the batch PUT endpoint, this field identifies which mapping to upsert. */
    origin_ip: string;
    /** Cloud vendor region identifier. Must be a valid region for the specified vendor as returned by the supported_regions endpoint. */
    region: string;
    /** Cloud vendor hosting the origin. Must be one of the supported vendors. */
    vendor: CacheSettingsOriginCloudRegionV2Request.Vendor;
}

export namespace CacheSettingsOriginCloudRegionV2Request {
    /** Cloud vendor hosting the origin. Must be one of the supported vendors. */
    export const Vendor = {
        Aws: "aws",
        Azure: "azure",
        Gcp: "gcp",
        Oci: "oci",
    } as const;
    export type Vendor = (typeof Vendor)[keyof typeof Vendor];
}
