// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CacheAutoOriginTlsKexResult {
    /** Whether Auto-Origin TLS KEX selection is enabled for the zone. */
    enabled?: CloudflareApi.CacheAutoOriginTlsKexValue | undefined;
    id?: string | undefined;
    /** Last time this setting was modified. */
    modified_on?: string | undefined;
}
