// This file was auto-generated by Fern from our API Definition.

/**
 * Result for a single item in a batch operation.
 */
export interface CacheSettingsOriginCloudRegionBatchItemResult {
    /** Error message explaining why the item failed. Present only on failed items. */
    error?: string | undefined;
    /** The origin IP address for this item. */
    "origin-ip": string;
    /** Cloud vendor region identifier. Present on succeeded items for patch operations. */
    region?: string | undefined;
    /** Cloud vendor identifier. Present on succeeded items for patch operations. */
    vendor?: string | undefined;
}
