// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CachePurgeApiResponseSingleId {
    errors: CloudflareApi.CachePurgeMessages;
    messages: CloudflareApi.CachePurgeMessages;
    result?: (CloudflareApi.CachePurgeApiResponseSingleIdResult | null) | undefined;
    /** Indicates the API call's success or failure. */
    success: boolean;
}
