// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CacheSettingsOriginPostQuantumEncryptionResponseValue {
    result?: CacheSettingsOriginPostQuantumEncryptionResponseValue.Result | undefined;
}

export namespace CacheSettingsOriginPostQuantumEncryptionResponseValue {
    export interface Result extends CloudflareApi.CacheSettingsOriginPostQuantumEncryption {
        value: CloudflareApi.CacheSettingsOriginPostQuantumEncryptionValue;
    }
}
