// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * The location of the instance's current container placement.
 */
export interface CcContainerInstanceLocation {
    name: CloudflareApi.CcLocationId;
    region: CloudflareApi.CcRegion;
}
