// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Create a Containers application.
 * Set `scheduling_policy` to `default` for a
 * scheduler-backed application with deployment configuration, instance counts,
 * constraints, versions, and rollouts. Set it to `durable_object` for a
 * Durable Object-managed application where each Durable Object creates and manages
 * the lifecycle of its container instance. For `durable_object` requests, supply
 * `name`, `scheduling_policy`, and `durable_objects`, with optional `configuration`
 * and top-level `observability` settings.
 */
export type CcContainersCreateApplicationRequest =
    | CloudflareApi.CcContainersCreateApplicationRequest.Default
    | CloudflareApi.CcContainersCreateApplicationRequest.DurableObject;

export namespace CcContainersCreateApplicationRequest {
    export interface Default extends CloudflareApi.CcContainersCreateScheduledApplicationRequest {
        scheduling_policy: "default";
    }

    export interface DurableObject extends CloudflareApi.CcContainersCreateDurableObjectApplicationRequest {
        scheduling_policy: "durable_object";
    }
}
