// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Steps defining the rollout process.
 */
export interface CcRolloutStepRequest {
    /** Description of the rollout step. */
    description: string;
    step_size: CloudflareApi.CcRolloutStepRequestStepSize;
}
