// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ClientSideSecurityConnection {
    added_at: string;
    domain_reported_malicious?: boolean | undefined;
    first_page_url?: string | undefined;
    first_seen_at: string;
    host: string;
    id?: CloudflareApi.ClientSideSecurityId | undefined;
    last_seen_at: string;
    malicious_domain_categories?: string[] | undefined;
    malicious_url_categories?: string[] | undefined;
    page_urls?: string[] | undefined;
    url: string;
    url_contains_cdn_cgi_path: boolean;
    url_reported_malicious?: boolean | undefined;
}
