// This file was auto-generated by Fern from our API Definition.

/**
 * When true, CSP reports will be sent to https://csp-reporting.cloudflare.com/cdn-cgi/script_monitor/report
 */
export type ClientSideSecurityUseCloudflareReportingEndpoint = boolean;
