// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CloudflareK2K2StreamResponse {
    result: CloudflareApi.CloudflareK2K2Stream;
    success: CloudflareApi.CloudflareK2WorkersK2CommonSuccess;
}
