// This file was auto-generated by Fern from our API Definition.

/**
 * Proposed update or deletion awaiting approval. The other rule fields describe the currently applied version.
 */
export interface CloudforceOnePendingRuleChange {
    approval_id: number;
    requested_at: number;
    requested_by: string;
    type: CloudforceOnePendingRuleChange.Type;
}

export namespace CloudforceOnePendingRuleChange {
    export const Type = {
        Update: "update",
        Delete: "delete",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
