// This file was auto-generated by Fern from our API Definition.

/** Cloud Provider type */
export const CloudConnectorProvider = {
    AwsS3: "aws_s3",
    CloudflareR2: "cloudflare_r2",
    GcpStorage: "gcp_storage",
    AzureStorage: "azure_storage",
    OciStorage: "oci_storage",
} as const;
export type CloudConnectorProvider = (typeof CloudConnectorProvider)[keyof typeof CloudConnectorProvider];
