// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Contains structured proposed rule changes, or null for unresolved persisted data.
 */
export type CloudforceOneApprovalProposedChanges =
    | CloudflareApi.CloudforceOneApprovalProposedChanges.Create
    | CloudflareApi.CloudforceOneApprovalProposedChanges.Update
    | CloudflareApi.CloudforceOneApprovalProposedChanges.Delete;

export namespace CloudforceOneApprovalProposedChanges {
    export interface Create {
        type: "create";
        content?: string | undefined;
        created_at: number;
        created_by: string;
        description: string;
        enabled: boolean;
        id: string;
        is_public: boolean;
        name: string;
        namespaces: string[];
        path: string;
        structured_source?: (string | null) | undefined;
        sync_message?: string | undefined;
        sync_source?: string | undefined;
    }

    export interface Update {
        type: "update";
        content?: string | undefined;
        description?: string | undefined;
        enabled?: boolean | undefined;
        is_public?: boolean | undefined;
        name?: string | undefined;
        namespaces?: string[] | undefined;
        path?: string | undefined;
        structured_source?: (string | null) | undefined;
        sync_message?: string | undefined;
        sync_source?: string | undefined;
    }

    export interface Delete {
        type: "delete";
        id: string;
        name: string;
        sync_message?: string | undefined;
        sync_source?: string | undefined;
    }
}
