// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CloudforceOneCompilerWarningLabelsItem {
    code_origin: string | null;
    column: number;
    level: string;
    line: number;
    span: CloudflareApi.CloudforceOneCompilerWarningLabelsItemSpan;
    text: string;
}
