// This file was auto-generated by Fern from our API Definition.

export interface CloudflareK2K2ConsumedRecord {
    /** The record payload, encoded as standard base64. */
    content: string;
    /** Lists the metadata the producer attached to the record. Omitted when the record carries none. */
    headers?: Record<string, string> | undefined;
    /** Shows when K2 received the record, in epoch milliseconds. */
    timestamp_ms: number;
}
