// This file was auto-generated by Fern from our API Definition.

export interface CloudforceOneTreeNode {
    children: Record<string, unknown>[];
    count: number;
    name: string;
    path: string;
}
