// This file was auto-generated by Fern from our API Definition.

export type CloudforceOneEventsArticleTagDiagnosticJsonValue =
    | Record<string, Record<string, unknown>>
    | Record<string, unknown>[]
    | string
    | null
    | number
    | boolean;
