// This file was auto-generated by Fern from our API Definition.

export interface CloudforceOnePortScanApiMessagesItem {
    code: number;
    documentation_url?: string | undefined;
    message: string;
    source?: CloudforceOnePortScanApiMessagesItem.Source | undefined;
}

export namespace CloudforceOnePortScanApiMessagesItem {
    export interface Source {
        pointer?: string | undefined;
    }
}
