// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CloudforceOnePortScanApiApiResponseCommonFailure {
    errors: Record<string, unknown>;
    messages: CloudflareApi.CloudforceOnePortScanApiMessages;
    success: boolean;
}
