// This file was auto-generated by Fern from our API Definition.

export const CloudflarePipelinesDecimalEncoding = {
    Number: "number",
    String: "string",
    Bytes: "bytes",
} as const;
export type CloudflarePipelinesDecimalEncoding =
    (typeof CloudflarePipelinesDecimalEncoding)[keyof typeof CloudflarePipelinesDecimalEncoding];
