// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CloudConnectorRule {
    description?: string | undefined;
    enabled?: boolean | undefined;
    expression?: string | undefined;
    id?: string | undefined;
    parameters?: CloudflareApi.CloudConnectorRuleParameters | undefined;
    provider?: CloudflareApi.CloudConnectorProvider | undefined;
}
