// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CloudforceOneRequestsRequestItem {
    completed?: CloudflareApi.CloudforceOneRequestsTime | undefined;
    content: CloudflareApi.CloudforceOneRequestsRequestContent;
    created: CloudflareApi.CloudforceOneRequestsTime;
    id: CloudflareApi.CloudforceOneRequestsUuid;
    /** Tokens for the request messages. */
    message_tokens?: number | undefined;
    priority: CloudflareApi.CloudforceOneRequestsTime;
    readable_id?: CloudflareApi.CloudforceOneRequestsRequestReadableId | undefined;
    request: CloudflareApi.CloudforceOneRequestsRequestType;
    status?: CloudflareApi.CloudforceOneRequestsRequestStatus | undefined;
    summary: CloudflareApi.CloudforceOneRequestsRequestSummary;
    tlp: CloudflareApi.CloudforceOneRequestsTlp;
    /** Tokens for the request. */
    tokens?: number | undefined;
    updated: CloudflareApi.CloudforceOneRequestsTime;
}
