// This file was auto-generated by Fern from our API Definition.

/**
 * Rolling policy for file sinks (when & why to close a file and open a new one).
 */
export interface CloudflarePipelinesR2DataCatalogTablePublicRollingPolicy {
    /** Files will be rolled after reaching this number of bytes */
    file_size_bytes?: number | undefined;
    /** Number of seconds of inactivity to wait before rolling over to a new file */
    inactivity_seconds?: number | undefined;
    /** Number of seconds to wait before rolling over to a new file */
    interval_seconds?: number | undefined;
}
