// This file was auto-generated by Fern from our API Definition.

export type CloudflareK2K2StreamWorkerBindingInput =
    | {
          enabled: false;
      }
    | {
          enabled: true;
      };
