// This file was auto-generated by Fern from our API Definition.

export interface CloudforceOneEmailRuleValidationResponse {
    compiled_yara?: string | undefined;
    error?: string | undefined;
    valid: boolean;
}
