// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * CSAM Scanner configuration for a zone.
 */
export interface CsamConfigServiceCsamScannerSetting {
    /**
     * Whether the feature state can be changed. When false, the zone
     * or account may be locked by Trust & Safety.
     */
    editable?: boolean | undefined;
    /** The feature identifier. */
    id?: "csam_scanner" | undefined;
    /**
     * When the setting was last modified. Currently always null as the
     * server does not populate this field.
     */
    modified_on?: (string | null) | undefined;
    value?: CloudflareApi.CsamConfigServiceCsamScannerValue | undefined;
}
