// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface CustomIndicatorFeedsUploadStatusResponse {
    errors: CloudflareApi.CustomIndicatorFeedsMessages2;
    messages: CloudflareApi.CustomIndicatorFeedsMessages2;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.CustomIndicatorFeedsUploadStatus | undefined;
}
