// This file was auto-generated by Fern from our API Definition.

export interface CustomIndicatorFeedsPermissionsRequest {
    /** The Cloudflare account tag of the account to change permissions on */
    account_tag?: string | undefined;
    /** The ID of the feed to add/remove permissions on */
    feed_id?: number | undefined;
}
