// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for D1 read replication.
 */
export interface D1ReadReplicationDetailsForRequest {
    /** The read replication mode for the database. Use 'auto' to create replicas and allow D1 automatically place them around the world, or 'disabled' to not use any database replicas (it can take a few hours for all replicas to be deleted). */
    mode: D1ReadReplicationDetailsForRequest.Mode;
}

export namespace D1ReadReplicationDetailsForRequest {
    /** The read replication mode for the database. Use 'auto' to create replicas and allow D1 automatically place them around the world, or 'disabled' to not use any database replicas (it can take a few hours for all replicas to be deleted). */
    export const Mode = {
        Auto: "auto",
        Disabled: "disabled",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
