// This file was auto-generated by Fern from our API Definition.

/** Region location hint of the database instance that handled the query. */
export const D1ServedByRegion = {
    Wnam: "WNAM",
    Enam: "ENAM",
    Weur: "WEUR",
    Eeur: "EEUR",
    Apac: "APAC",
    Oc: "OC",
} as const;
export type D1ServedByRegion = (typeof D1ServedByRegion)[keyof typeof D1ServedByRegion];
