// This file was auto-generated by Fern from our API Definition.

/**
 * A bookmark representing a specific state of the database at a specific point in time.
 */
export type D1TimeTravelBookmark = string;
