// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DigitalExperienceMonitoringFleetStatusLiveResponse {
    errors: CloudflareApi.DigitalExperienceMonitoringMessages;
    messages: CloudflareApi.DigitalExperienceMonitoringMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.DigitalExperienceMonitoringFleetStatusLiveResponseResult | undefined;
}
