// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DigitalExperienceMonitoringTimeslotRttStats {
    /** Timestamp of the time slot. */
    timestamp: string;
    /** Round-trip time statistics for the time slot. */
    value: CloudflareApi.DigitalExperienceMonitoringRttStats;
}
