// This file was auto-generated by Fern from our API Definition.

/**
 * Determines whether or not the test is active.
 */
export type DigitalExperienceMonitoringDeviceDexTestSchemasEnabled = boolean;
