// This file was auto-generated by Fern from our API Definition.

export interface DigitalExperienceMonitoringDeviceStateTopNetworksSummary {
    /** Number of observations. */
    count: number;
    /** Network name. */
    name: string;
}
