// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DigitalExperienceMonitoringTestsResponse {
    overviewMetrics: CloudflareApi.DigitalExperienceMonitoringTestsResponseOverviewMetrics;
    /** array of test results objects. */
    tests: CloudflareApi.DigitalExperienceMonitoringTestsResponseTestsItem[];
}
