// This file was auto-generated by Fern from our API Definition.

export interface DigitalExperienceMonitoringTimeslotInt {
    /** Timestamp of the time slot. */
    timestamp: string;
    /** Integer metric value for the time slot. */
    value: number;
}
