// This file was auto-generated by Fern from our API Definition.

export interface DigitalExperienceMonitoringCpuPctByApp {
    /** CPU usage percentage, on a scale of 0 to 100. */
    cpu_pct?: (number | null) | undefined;
    /** Application name. */
    name?: (string | null) | undefined;
}
