// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type DigitalExperienceMonitoringWarpEventsResponseItem =
    | CloudflareApi.DigitalExperienceMonitoringWarpToggleChangeEvent
    | CloudflareApi.DigitalExperienceMonitoringWarpConfigChangeEvent;
