// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DigitalExperienceMonitoringWarpConfigChangeEvent {
    /** The device ID. */
    device_id?: CloudflareApi.DigitalExperienceMonitoringUuid | undefined;
    /** Deprecated: use registration_id. The device registration ID. */
    device_registration?: CloudflareApi.DigitalExperienceMonitoringUuid | undefined;
    /** The details for the WARP configuration that was switched from. */
    from?: CloudflareApi.DigitalExperienceMonitoringWarpConfigDetails | undefined;
    /** The hostname of the machine the event is from. */
    hostname?: string | undefined;
    /** The device registration ID. */
    registration_id?: CloudflareApi.DigitalExperienceMonitoringUuid | undefined;
    /** The serial number of the machine the event is from. */
    serial_number?: string | undefined;
    /** The event time. */
    timestamp?: CloudflareApi.DigitalExperienceMonitoringTimestampDatetime | undefined;
    /** The details for the WARP configuration that was switched to. */
    to?: CloudflareApi.DigitalExperienceMonitoringWarpConfigDetails | undefined;
    /** Email tied to the device. */
    user_email?: string | undefined;
}
