// This file was auto-generated by Fern from our API Definition.

export interface DigitalExperienceMonitoringSchemasIpInfoLocation {
    city?: (string | null) | undefined;
    country_iso?: (string | null) | undefined;
    state_iso?: (string | null) | undefined;
    zip?: (string | null) | undefined;
}
