// This file was auto-generated by Fern from our API Definition.

/**
 * The configuration object which contains the details for the WARP client to conduct the test.
 */
export interface DigitalExperienceMonitoringDeviceDexTestSchemasData {
    /** The desired endpoint to test. */
    host: string;
    /** The type of test. */
    kind: DigitalExperienceMonitoringDeviceDexTestSchemasData.Kind;
    /** The HTTP request method type. */
    method?: "GET" | undefined;
}

export namespace DigitalExperienceMonitoringDeviceDexTestSchemasData {
    /** The type of test. */
    export const Kind = {
        Http: "http",
        Traceroute: "traceroute",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
