// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DlpApiResponseCollection {
    errors: CloudflareApi.DlpMessages;
    messages: CloudflareApi.DlpMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.DlpApiResponseCollectionResultInfo | undefined;
}
