// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DlpBehavior {
    description: string;
    enabled: boolean;
    name: string;
    risk_level: CloudflareApi.DlpRiskLevel;
}
