// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DlpDataTagCategory {
    created_at: string;
    description?: (string | null) | undefined;
    id: string;
    name: string;
    tags: CloudflareApi.DlpDataTag[];
    template_id?: (string | null) | undefined;
    updated_at: string;
}
