// This file was auto-generated by Fern from our API Definition.

export interface DlpEntryConfidence {
    /** Indicates whether this entry has AI remote service validation. */
    ai_context_available: boolean;
    /** Indicates whether this entry has any form of validation that is not an AI remote service. */
    available: boolean;
}
