// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DlpIntegrationProfile {
    created_at: string;
    /** The description of the profile. */
    description?: (string | null) | undefined;
    entries: CloudflareApi.DlpEntry[];
    id: string;
    integration_id?: string | undefined;
    name: string;
    shared_entries: CloudflareApi.DlpEntry[];
    updated_at: string;
}
