// This file was auto-generated by Fern from our API Definition.

export interface DnsAnalyticsDataItem {
    /** Array of dimension values, representing the combination of dimension values corresponding to this row. */
    dimensions: string[];
}
