// This file was auto-generated by Fern from our API Definition.

/**
 * Components of a CERT record.
 */
export interface DnsRecordsCertRecordData {
    /** Algorithm. */
    algorithm?: number | undefined;
    /** Certificate. */
    certificate?: string | undefined;
    /** Key Tag. */
    key_tag?: number | undefined;
    /** Type. */
    type?: number | undefined;
}
