// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DnsRecordsOpenpgpkeyRecord {
    comment?: CloudflareApi.DnsRecordsComment | undefined;
    name?: CloudflareApi.DnsRecordsName | undefined;
    proxied?: CloudflareApi.DnsRecordsProxied | undefined;
    settings?: CloudflareApi.DnsRecordsSettings | undefined;
    tags?: CloudflareApi.DnsRecordsTags | undefined;
    ttl?: CloudflareApi.DnsRecordsTtl | undefined;
    /** A single Base64-encoded OpenPGP Transferable Public Key (RFC 4880 Section 11.1) */
    content?: string | undefined;
}
