// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type DnsRecordsDnsRecordWithData =
    | CloudflareApi.DnsRecordsDnsRecordWithData.Caa
    | CloudflareApi.DnsRecordsDnsRecordWithData.Cert
    | CloudflareApi.DnsRecordsDnsRecordWithData.Dnskey
    | CloudflareApi.DnsRecordsDnsRecordWithData.Ds
    | CloudflareApi.DnsRecordsDnsRecordWithData.Https
    | CloudflareApi.DnsRecordsDnsRecordWithData.Loc
    | CloudflareApi.DnsRecordsDnsRecordWithData.Naptr
    | CloudflareApi.DnsRecordsDnsRecordWithData.Smimea
    | CloudflareApi.DnsRecordsDnsRecordWithData.Srv
    | CloudflareApi.DnsRecordsDnsRecordWithData.Sshfp
    | CloudflareApi.DnsRecordsDnsRecordWithData.Svcb
    | CloudflareApi.DnsRecordsDnsRecordWithData.Tlsa
    | CloudflareApi.DnsRecordsDnsRecordWithData.Uri;

export namespace DnsRecordsDnsRecordWithData {
    export interface Caa extends CloudflareApi.DnsRecordsCaaRecord {
        type: "CAA";
    }

    export interface Cert extends CloudflareApi.DnsRecordsCertRecord {
        type: "CERT";
    }

    export interface Dnskey extends CloudflareApi.DnsRecordsDnskeyRecord {
        type: "DNSKEY";
    }

    export interface Ds extends CloudflareApi.DnsRecordsDsRecord {
        type: "DS";
    }

    export interface Https extends CloudflareApi.DnsRecordsHttpsRecord {
        type: "HTTPS";
    }

    export interface Loc extends CloudflareApi.DnsRecordsLocRecord {
        type: "LOC";
    }

    export interface Naptr extends CloudflareApi.DnsRecordsNaptrRecord {
        type: "NAPTR";
    }

    export interface Smimea extends CloudflareApi.DnsRecordsSmimeaRecord {
        type: "SMIMEA";
    }

    export interface Srv extends CloudflareApi.DnsRecordsSrvRecord {
        type: "SRV";
    }

    export interface Sshfp extends CloudflareApi.DnsRecordsSshfpRecord {
        type: "SSHFP";
    }

    export interface Svcb extends CloudflareApi.DnsRecordsSvcbRecord {
        type: "SVCB";
    }

    export interface Tlsa extends CloudflareApi.DnsRecordsTlsaRecord {
        type: "TLSA";
    }

    export interface Uri extends CloudflareApi.DnsRecordsUriRecord {
        type: "URI";
    }

    export type Request =
        | CloudflareApi.DnsRecordsDnsRecordWithData.Caa
        | CloudflareApi.DnsRecordsDnsRecordWithData.Cert
        | CloudflareApi.DnsRecordsDnsRecordWithData.Dnskey
        | CloudflareApi.DnsRecordsDnsRecordWithData.Ds
        | CloudflareApi.DnsRecordsDnsRecordWithData.Https
        | CloudflareApi.DnsRecordsDnsRecordWithData.Loc
        | CloudflareApi.DnsRecordsDnsRecordWithData.Naptr
        | CloudflareApi.DnsRecordsDnsRecordWithData.Smimea
        | CloudflareApi.DnsRecordsDnsRecordWithData.Srv
        | CloudflareApi.DnsRecordsDnsRecordWithData.Sshfp
        | CloudflareApi.DnsRecordsDnsRecordWithData.Svcb
        | CloudflareApi.DnsRecordsDnsRecordWithData.Tlsa
        | CloudflareApi.DnsRecordsDnsRecordWithData.Uri;
}
