// This file was auto-generated by Fern from our API Definition.

/**
 * Components of a SVCB record.
 */
export interface DnsRecordsSvcbRecordData {
    /** Priority. */
    priority?: number | undefined;
    /** Target. */
    target?: string | undefined;
    /** Value. */
    value?: string | undefined;
}
