// This file was auto-generated by Fern from our API Definition.

export interface DnsRecordsDnsResponseImportScanResult {
    /** Number of DNS records added. */
    recs_added?: number | undefined;
    /** Total number of DNS records parsed. */
    total_records_parsed?: number | undefined;
}
