// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DnsSettingsNameserverSetCreateMember {
    ip_count?: CloudflareApi.DnsSettingsNameserverSetIpCount | undefined;
    name: CloudflareApi.DnsSettingsNameserverName;
}
