// This file was auto-generated by Fern from our API Definition.

/**
 * Settings determining the nameservers through which the zone should be available.
 */
export interface DnsSettingsDnsSettingsZoneResponseNameservers {
    /** Configured nameserver set to be used for this zone */
    ns_set?: number | undefined;
    /** Nameserver type */
    type: DnsSettingsDnsSettingsZoneResponseNameservers.Type;
}

export namespace DnsSettingsDnsSettingsZoneResponseNameservers {
    /** Nameserver type */
    export const Type = {
        CloudflareStandard: "cloudflare.standard",
        CloudflareAdvanced: "cloudflare.advanced",
        CustomAccount: "custom.account",
        CustomTenant: "custom.tenant",
        CustomZone: "custom.zone",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
