// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface DnssecDnssecZskResponseCollection {
    errors: CloudflareApi.DnssecMessages;
    messages: CloudflareApi.DnssecMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.DnssecDnssecZsk[] | undefined;
}
