// This file was auto-generated by Fern from our API Definition.

/**
 * Message processing properties.
 */
export interface EmailSecurityMessageDetailsProperties {
    /** Pattern that allowlisted this message. */
    allowlisted_pattern?: (string | null) | undefined;
    /** Type of allowlist pattern. */
    allowlisted_pattern_type?: (EmailSecurityMessageDetailsProperties.AllowlistedPatternType | null) | undefined;
    /** Whether message was blocklisted. */
    blocklisted_message?: (boolean | null) | undefined;
    /** Pattern that blocklisted this message. */
    blocklisted_pattern?: (string | null) | undefined;
    /** Legacy field for allowlist pattern type. */
    whitelisted_pattern_type?: (EmailSecurityMessageDetailsProperties.WhitelistedPatternType | null) | undefined;
}

export namespace EmailSecurityMessageDetailsProperties {
    /** Type of allowlist pattern. */
    export const AllowlistedPatternType = {
        QuarantineRelease: "quarantine_release",
        AcceptableSender: "acceptable_sender",
        AllowedSender: "allowed_sender",
        AllowedRecipient: "allowed_recipient",
        DomainSimilarity: "domain_similarity",
        DomainRecency: "domain_recency",
        ManagedAcceptableSender: "managed_acceptable_sender",
        OutboundNdr: "outbound_ndr",
    } as const;
    export type AllowlistedPatternType = (typeof AllowlistedPatternType)[keyof typeof AllowlistedPatternType];
    /** Legacy field for allowlist pattern type. */
    export const WhitelistedPatternType = {
        QuarantineRelease: "quarantine_release",
        AcceptableSender: "acceptable_sender",
        AllowedSender: "allowed_sender",
        AllowedRecipient: "allowed_recipient",
        DomainSimilarity: "domain_similarity",
        DomainRecency: "domain_recency",
        ManagedAcceptableSender: "managed_acceptable_sender",
        OutboundNdr: "outbound_ndr",
    } as const;
    export type WhitelistedPatternType = (typeof WhitelistedPatternType)[keyof typeof WhitelistedPatternType];
}
