// This file was auto-generated by Fern from our API Definition.

export const EmailSecurityRegion = {
    Global: "GLOBAL",
    Au: "AU",
    De: "DE",
    In: "IN",
    Us: "US",
} as const;
export type EmailSecurityRegion = (typeof EmailSecurityRegion)[keyof typeof EmailSecurityRegion];
