// This file was auto-generated by Fern from our API Definition.

/** DMARC configuration status. The API omits this field when DMARC is correctly configured. If the zone lacks a DMARC TXT record of its own, the API resolves _dmarc.{zone} recursively and evaluates whatever that lookup returns. A CNAME at _dmarc.{zone} that points to a valid DMARC record is therefore healthy; the cname-on-dmarc-record value means the CNAME resolves to no DMARC record at all. */
export const EmailAuthDmarcStatus = {
    MissingDmarcReport: "missing-dmarc-report",
    MultipleDmarcReports: "multiple-dmarc-reports",
    MissingDmarcRua: "missing-dmarc-rua",
    CnameOnDmarcRecord: "cname-on-dmarc-record",
    UnauthorizedReportingDomain: "unauthorized-reporting-domain",
} as const;
export type EmailAuthDmarcStatus = (typeof EmailAuthDmarcStatus)[keyof typeof EmailAuthDmarcStatus];
