// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface EmailSecurityReclassificationSubmission {
    alert_id: string;
    escalated_submission_id?: string | undefined;
    expected_disposition: CloudflareApi.EmailSecuritySubmissionDisposition;
}
