// This file was auto-generated by Fern from our API Definition.

export interface EmailSecurityMoveResponseItem {
    /** When the move operation completed (UTC). */
    completed_at?: (string | null) | undefined;
    /** Deprecated, use `completed_at` instead. End of life: November 1, 2026. */
    completed_timestamp?: string | undefined;
    /** Destination folder for the message. */
    destination?: (string | null) | undefined;
    /** Number of items moved. End of life: November 1, 2026. */
    item_count?: number | undefined;
    /** Message identifier. */
    message_id?: (string | null) | undefined;
    /** Type of operation performed. */
    operation?: (string | null) | undefined;
    /** Recipient email address. */
    recipient?: (string | null) | undefined;
    /** Operation status. */
    status?: (string | null) | undefined;
    /** Whether the operation succeeded. */
    success: boolean;
}
