// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface EmailSecurityDomain {
    allowed_delivery_modes?: CloudflareApi.EmailSecurityDeliveryMode[] | undefined;
    authorization?: (CloudflareApi.EmailSecurityDomainAuthorization | null) | undefined;
    created_at?: CloudflareApi.EmailSecurityTimestamp | undefined;
    dmarc_status?: (CloudflareApi.EmailSecurityDmarcStatus | null) | undefined;
    domain?: string | undefined;
    drop_dispositions?: CloudflareApi.EmailSecurityDispositionLabel[] | undefined;
    emails_processed?: (CloudflareApi.EmailSecurityEmailsProcessed | null) | undefined;
    folder?: (CloudflareApi.EmailSecurityScannableFolder | null) | undefined;
    id?: CloudflareApi.EmailSecurityDomainId | undefined;
    inbox_provider?: (EmailSecurityDomain.InboxProvider | null) | undefined;
    integration_id?: (string | null) | undefined;
    ip_restrictions?: string[] | undefined;
    /** Deprecated, use `modified_at` instead. End of life: November 1, 2026. */
    last_modified?: CloudflareApi.EmailSecurityTimestamp | undefined;
    lookback_hops?: number | undefined;
    modified_at?: CloudflareApi.EmailSecurityTimestamp | undefined;
    o365_tenant_id?: (string | null) | undefined;
    regions?: CloudflareApi.EmailSecurityRegion[] | undefined;
    require_tls_inbound?: (boolean | null) | undefined;
    require_tls_outbound?: (boolean | null) | undefined;
    spf_status?: (CloudflareApi.EmailSecuritySpfStatus | null) | undefined;
    status?: (CloudflareApi.EmailSecurityDomainStatus | null) | undefined;
    transport?: string | undefined;
}

export namespace EmailSecurityDomain {
    export const InboxProvider = {
        Microsoft: "Microsoft",
        Google: "Google",
    } as const;
    export type InboxProvider = (typeof InboxProvider)[keyof typeof InboxProvider];
}
