// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface EmailSecurityActionEntry {
    /** Timestamp when the action completed. */
    completed_at?: (string | null) | undefined;
    operation: EmailSecurityActionEntry.Operation;
    properties?: (CloudflareApi.EmailSecurityActionEntryProperties | null) | undefined;
    /** Timestamp when the action was initiated. */
    started_at?: (string | null) | undefined;
    status?: (string | null) | undefined;
    success?: (boolean | null) | undefined;
}

export namespace EmailSecurityActionEntry {
    export const Operation = {
        Preview: "PREVIEW",
        QuarantineRelease: "QUARANTINE_RELEASE",
        Submission: "SUBMISSION",
        Move: "MOVE",
    } as const;
    export type Operation = (typeof Operation)[keyof typeof Operation];
}
