// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface EmailUpdateRuleProperties {
    actions: CloudflareApi.EmailRuleActions;
    enabled?: CloudflareApi.EmailRuleEnabled | undefined;
    matchers: CloudflareApi.EmailRuleMatchers;
    name?: CloudflareApi.EmailRuleName | undefined;
    owner_worker_tag?: CloudflareApi.EmailRuleOwnerWorkerTag | undefined;
    priority?: CloudflareApi.EmailRulePriority | undefined;
    source?: CloudflareApi.EmailRuleSource | undefined;
}
