// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * List actions for the catch-all routing rule.
 */
export type EmailRuleCatchallActions = CloudflareApi.EmailRuleCatchallAction[];
