// This file was auto-generated by Fern from our API Definition.

export interface EmailSecurityCursorResultInfo {
    /** Number of items in current page. */
    count: number;
    /** Cursor for next page. */
    next?: (string | null) | undefined;
    /** Deprecated: Always returns 0. End of life: November 1, 2026. */
    page?: number | undefined;
    /** Number of items per page. */
    per_page: number;
    /** Cursor for previous page. */
    previous?: (string | null) | undefined;
    /** Deprecated: Always returns 0. End of life: November 1, 2026. */
    total_count: number;
}
