// This file was auto-generated by Fern from our API Definition.

export const EmailSecurityMailboxDestination = {
    Inbox: "Inbox",
    JunkEmail: "JunkEmail",
    DeletedItems: "DeletedItems",
    RecoverableItemsDeletions: "RecoverableItemsDeletions",
    RecoverableItemsPurges: "RecoverableItemsPurges",
} as const;
export type EmailSecurityMailboxDestination =
    (typeof EmailSecurityMailboxDestination)[keyof typeof EmailSecurityMailboxDestination];
