// This file was auto-generated by Fern from our API Definition.

/**
 * Describes a product feature associated with an entitlement.
 */
export interface EntitlementsFeature {
    /** The logical grouping (set) this feature belongs to. */
    feature_set: string;
    /** Numeric identifier of the feature. */
    id: number;
    /** Unique string key for the feature. */
    key: string;
    /** Human-readable name of the feature. */
    name: string;
}
