// This file was auto-generated by Fern from our API Definition.

/**
 * The configuration object for the current rule.
 */
export interface FirewallSchemasConfiguration {
    /** The configuration target for this rule. You must set the target to `ua` for User Agent Blocking rules. */
    target?: string | undefined;
    /** The exact user agent string to match. This value will be compared to the received `User-Agent` HTTP header value. */
    value?: string | undefined;
}
