// This file was auto-generated by Fern from our API Definition.

export interface FirewallIpConfiguration {
    /** The IP address to match. This address will be compared to the IP address of incoming requests. */
    value?: string | undefined;
}
