// This file was auto-generated by Fern from our API Definition.

/** The operator used when matching: `eq` means "equal" and `ne` means "not equal". */
export const FirewallHeaderOp = {
    Eq: "eq",
    Ne: "ne",
} as const;
export type FirewallHeaderOp = (typeof FirewallHeaderOp)[keyof typeof FirewallHeaderOp];
