// This file was auto-generated by Fern from our API Definition.

/** The action to apply to a matched request. */
export const FirewallComponentsSchemasMode = {
    Block: "block",
    Challenge: "challenge",
    JsChallenge: "js_challenge",
    ManagedChallenge: "managed_challenge",
} as const;
export type FirewallComponentsSchemasMode =
    (typeof FirewallComponentsSchemasMode)[keyof typeof FirewallComponentsSchemasMode];
