// This file was auto-generated by Fern from our API Definition.

/**
 * The content type of the body. Must be one of the following: `text/plain`, `text/xml`, or `application/json`.
 */
export type FirewallContentType = string;
