// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface FirewallFirewalluablockResponseCollection {
    result?: (CloudflareApi.FirewallFirewalluablock[] | null) | undefined;
    errors: CloudflareApi.FirewallMessages;
    messages: CloudflareApi.FirewallMessages;
    /** Defines whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.FirewallResultInfo | undefined;
}
