// This file was auto-generated by Fern from our API Definition.

/**
 * The filter expression. For more information, refer to [Expressions](https://developers.cloudflare.com/ruleset-engine/rules-language/expressions/).
 */
export type FirewallExpression = string;
