// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface FraudApiResponseCommon {
    errors: CloudflareApi.FraudMessages;
    messages: CloudflareApi.FraudMessages;
    /** Whether the API call was successful. */
    success: true;
}
