// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface GetAccountOrZoneAccountOrZoneIdEntitlementsResponse {
    /** List of entitlements for the requested object. */
    result: CloudflareApi.EntitlementsEntitlement[];
    result_info?: Record<string, unknown> | undefined;
}
