// This file was auto-generated by Fern from our API Definition.

/**
 * The name of the Hyperdrive configuration. Used to identify the configuration in the Cloudflare dashboard and API.
 */
export type HyperdriveHyperdriveName = string;
