// This file was auto-generated by Fern from our API Definition.

/**
 * DNS verification code. Add this entire string to the DNS TXT record of the email domain to validate ownership.
 */
export type IamDnsVerificationCode = string;
