// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A set of permission groups that are specified to the policy.
 */
export type IamMemberPermissionGroups = CloudflareApi.IamMemberPermissionGroup[];
