// This file was auto-generated by Fern from our API Definition.

export const IamOauthClientGrantTypesItem = {
    AuthorizationCode: "authorization_code",
    RefreshToken: "refresh_token",
} as const;
export type IamOauthClientGrantTypesItem =
    (typeof IamOauthClientGrantTypesItem)[keyof typeof IamOauthClientGrantTypesItem];
