// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A list of resource groups that the policy applies to.
 */
export type IamResourceGroups = CloudflareApi.IamResourceGroup[];
