// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * SCIM ListResponse envelope for User resources (RFC 7644 Section 3.4.2).
 */
export interface IamScimUserListResponse {
    Resources: CloudflareApi.IamScimUser[];
    /** The number of resources returned in this page. */
    itemsPerPage?: number | undefined;
    schemas: string[];
    /** The 1-based index of the first result in this set. */
    startIndex?: number | undefined;
    /** The total number of results matching the query. */
    totalResults: number;
}
