// This file was auto-generated by Fern from our API Definition.

/**
 * An attribute definition within a SCIM schema (RFC 7643 Section 7).
 */
export interface IamScimSchemaAttr {
    /** A collection of canonical values for the attribute. */
    canonicalValues?: string[] | undefined;
    /** Indicates if the string attribute is case-sensitive. */
    caseExact: boolean;
    /** A human-readable description of the attribute. */
    description: string;
    /** Indicates if the attribute is multi-valued. */
    multiValued: boolean;
    /** Indicates the circumstances under which the value of the attribute can be defined or redefined. */
    mutability: IamScimSchemaAttr.Mutability;
    /** The attribute's name. */
    name: string;
    /** A multi-valued attribute that indicates the SCIM resource types that may be referenced. */
    referenceTypes?: string[] | undefined;
    /** Indicates if the attribute is required. */
    required: boolean;
    /** Indicates when an attribute and associated values are returned in response to a GET request or in response to a PUT, POST, or PATCH request. */
    returned: IamScimSchemaAttr.Returned;
    /** Defines a set of sub-attributes when the attribute type is `complex`. */
    subAttributes?: Record<string, unknown>[] | undefined;
    /** The attribute's data type. */
    type: IamScimSchemaAttr.Type;
    /** Indicates how the service provider enforces uniqueness of attribute values. */
    uniqueness: IamScimSchemaAttr.Uniqueness;
}

export namespace IamScimSchemaAttr {
    /** Indicates the circumstances under which the value of the attribute can be defined or redefined. */
    export const Mutability = {
        ReadOnly: "readOnly",
        ReadWrite: "readWrite",
        Immutable: "immutable",
        WriteOnly: "writeOnly",
    } as const;
    export type Mutability = (typeof Mutability)[keyof typeof Mutability];
    /** Indicates when an attribute and associated values are returned in response to a GET request or in response to a PUT, POST, or PATCH request. */
    export const Returned = {
        Always: "always",
        Never: "never",
        VDefault: "default",
        Request: "request",
    } as const;
    export type Returned = (typeof Returned)[keyof typeof Returned];
    /** The attribute's data type. */
    export const Type = {
        String: "string",
        Boolean: "boolean",
        Decimal: "decimal",
        Integer: "integer",
        DateTime: "dateTime",
        Reference: "reference",
        Complex: "complex",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Indicates how the service provider enforces uniqueness of attribute values. */
    export const Uniqueness = {
        None: "none",
        Server: "server",
        Global: "global",
    } as const;
    export type Uniqueness = (typeof Uniqueness)[keyof typeof Uniqueness];
}
