// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface IamTokenWithValue {
    condition?: CloudflareApi.IamCondition | undefined;
    expires_on?: CloudflareApi.IamExpiresOn | undefined;
    id?: CloudflareApi.IamTokenIdentifier | undefined;
    issued_on?: CloudflareApi.IamIssuedOn | undefined;
    last_used_on?: CloudflareApi.IamLastUsedOn | undefined;
    modified_on?: CloudflareApi.IamModifiedOn | undefined;
    name?: CloudflareApi.IamName | undefined;
    not_before?: CloudflareApi.IamNotBefore | undefined;
    policies?: CloudflareApi.IamTokenPolicies | undefined;
    status?: CloudflareApi.IamTokenStatus | undefined;
    value?: CloudflareApi.IamValue | undefined;
}
