// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Detailed member information for a User Group member.
 */
export interface IamUserGroupMemberDetailed {
    /** When the member was added to the user group. */
    created_at?: string | undefined;
    email?: CloudflareApi.IamEmail | undefined;
    /** Account member identifier. */
    id?: string | undefined;
    /** The member's status in the account. */
    status?: IamUserGroupMemberDetailed.Status | undefined;
    user?: CloudflareApi.IamUserGroupMemberDetailedUser | undefined;
}

export namespace IamUserGroupMemberDetailed {
    /** The member's status in the account. */
    export const Status = {
        Accepted: "accepted",
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
