// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ImagesImageVariantPublicRequestHero {
    id: CloudflareApi.ImagesImageVariantIdentifier;
    neverRequireSignedURLs?: CloudflareApi.ImagesImageVariantNeverRequireSignedUrLs | undefined;
    options: CloudflareApi.ImagesImageVariantOptions;
}
