// This file was auto-generated by Fern from our API Definition.

/** The fit property describes how the width and height dimensions should be interpreted. */
export const ImagesImageVariantFit = {
    ScaleDown: "scale-down",
    Contain: "contain",
    Cover: "cover",
    Crop: "crop",
    Pad: "pad",
} as const;
export type ImagesImageVariantFit = (typeof ImagesImageVariantFit)[keyof typeof ImagesImageVariantFit];
