// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ImagesImagesStatsResponse {
    errors: CloudflareApi.ImagesMessages;
    messages: CloudflareApi.ImagesMessages;
    result: CloudflareApi.ImagesImagesStats;
    /** Whether the API call was successful */
    success: true;
}
