// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface IntelResolvesToRef {
    id?: CloudflareApi.IntelStixIdentifier | undefined;
    /** IP address or domain name. */
    value?: string | undefined;
}
