// This file was auto-generated by Fern from our API Definition.

export interface IntelSinkholesMessagesItem {
    code: number;
    documentation_url?: string | undefined;
    message: string;
    source?: IntelSinkholesMessagesItem.Source | undefined;
}

export namespace IntelSinkholesMessagesItem {
    export interface Source {
        pointer?: string | undefined;
    }
}
