// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface IntelWhois {
    created_date?: string | undefined;
    domain?: CloudflareApi.IntelDomainName | undefined;
    nameservers?: string[] | undefined;
    registrant?: string | undefined;
    registrant_country?: string | undefined;
    registrant_email?: string | undefined;
    registrant_org?: string | undefined;
    registrar?: string | undefined;
    updated_date?: string | undefined;
}
