// This file was auto-generated by Fern from our API Definition.

/**
 * STIX 2.1 identifier: https://docs.oasis-open.org/cti/stix/v2.1/cs02/stix-v2.1-cs02.html#_64yvzeku5a5c.
 */
export type IntelStixIdentifier = string;
