// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface KaminoEnvironmentsResponse {
    errors: CloudflareApi.KaminoMessage[];
    messages: CloudflareApi.KaminoMessage[];
    result: CloudflareApi.KaminoEnvironmentsResult;
    success: boolean;
}
