// This file was auto-generated by Fern from our API Definition.

export interface LexLogField {
    /** Whether the API includes this field in log ingest. */
    enabled: boolean;
    /** Field name in lowercase. */
    name: string;
}
