// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ListsItemBase {
    comment?: CloudflareApi.ListsItemComment | undefined;
    created_on?: CloudflareApi.ListsCreatedOn | undefined;
    id?: CloudflareApi.ListsItemId | undefined;
    modified_on?: CloudflareApi.ListsModifiedOn | undefined;
}
