// This file was auto-generated by Fern from our API Definition.

/**
 * Time to live (TTL) of the DNS entry for the IP address returned by this load balancer. This only applies to gray-clouded (unproxied) load balancers.
 */
export type LoadBalancingTtl = number;
