// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface LoadBalancingMonitorEditable {
    allow_insecure?: CloudflareApi.LoadBalancingAllowInsecure | undefined;
    consecutive_down?: CloudflareApi.LoadBalancingConsecutiveDown | undefined;
    consecutive_up?: CloudflareApi.LoadBalancingConsecutiveUp | undefined;
    description?: CloudflareApi.LoadBalancingDescription | undefined;
    expected_body?: CloudflareApi.LoadBalancingExpectedBody | undefined;
    expected_codes?: CloudflareApi.LoadBalancingExpectedCodes | undefined;
    follow_redirects?: CloudflareApi.LoadBalancingFollowRedirects | undefined;
    header?: CloudflareApi.LoadBalancingHeader | undefined;
    interval?: CloudflareApi.LoadBalancingInterval | undefined;
    method?: CloudflareApi.LoadBalancingMethod | undefined;
    path?: CloudflareApi.LoadBalancingPath | undefined;
    port?: (CloudflareApi.LoadBalancingPort | null) | undefined;
    probe_zone?: CloudflareApi.LoadBalancingProbeZone | undefined;
    retries?: CloudflareApi.LoadBalancingRetries | undefined;
    timeout?: CloudflareApi.LoadBalancingTimeout | undefined;
    type?: CloudflareApi.LoadBalancingType | undefined;
}
