// This file was auto-generated by Fern from our API Definition.

/**
 * Whether to enable (the default) or disable this pool. Disabled pools will not receive traffic and are excluded from health checks. Disabling a pool will cause any load balancers using it to failover to the next pool (if any).
 */
export type LoadBalancingEnabled = boolean;
