// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Resulting health data from a preview operation.
 */
export type LoadBalancingPreviewResult = Record<string, LoadBalancingPreviewResult.Value>;

export namespace LoadBalancingPreviewResult {
    export interface Value {
        healthy?: boolean | undefined;
        origins?: Record<string, CloudflareApi.LoadBalancingOriginHealthData>[] | undefined;
    }
}
