// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface LoadBalancingSearch {
    /** A list of resources matching the search query. */
    resources?: CloudflareApi.LoadBalancingResourceReference[] | undefined;
}
