// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface LogpushInstantLogsJob {
    destination_conf?: CloudflareApi.LogpushDestinationConf2 | undefined;
    fields?: CloudflareApi.LogpushFields | undefined;
    filter?: CloudflareApi.LogpushFilter2 | undefined;
    sample?: CloudflareApi.LogpushSample | undefined;
    session_id?: CloudflareApi.LogpushSessionId | undefined;
}
