// This file was auto-generated by Fern from our API Definition.

/**
 * The filters to select the events to include and/or remove from your logs. For more information, refer to [Filters](https://developers.cloudflare.com/logs/reference/filters/).
 */
export type LogpushFilter = string | null;
