// This file was auto-generated by Fern from our API Definition.

/** The kind parameter (optional) is used to differentiate between Logpush and Edge Log Delivery jobs (when supported by the dataset). */
export const LogpushKind = {
    Empty: "",
    Edge: "edge",
} as const;
export type LogpushKind = (typeof LogpushKind)[keyof typeof LogpushKind];
