// This file was auto-generated by Fern from our API Definition.

/**
 * When true, excludes DDoS attack traffic from logs. This option is supported for the `http_requests`, `firewall_events`, and `network_analytics_logs` datasets.
 */
export type LogpushFilterAttackTraffic = boolean;
