// This file was auto-generated by Fern from our API Definition.

export interface MagicCustomRemoteIdentities {
    /**
     * A custom IKE ID of type FQDN that may be used to identity the IPsec tunnel. The
     * generated IKE IDs can still be used even if this custom value is specified.
     *
     * Must be of the form `<custom label>.<account ID>.custom.ipsec.cloudflare.com`.
     *
     * This custom ID does not need to be unique. Two IPsec tunnels may have the same custom
     * fqdn_id. However, if another IPsec tunnel has the same value then the two tunnels
     * cannot have the same cloudflare_endpoint.
     */
    fqdn_id?: string | undefined;
}
