// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MagicRoutedSubnet {
    nat?: CloudflareApi.MagicNat | undefined;
    next_hop: CloudflareApi.MagicIpAddress;
    prefix: CloudflareApi.MagicCidr;
}
