// This file was auto-generated by Fern from our API Definition.

/**
 * True if automatic stateful return routing should be enabled for a tunnel, false otherwise. Requires the `coupler_integration` account flag to be enabled; requests setting this to `true` without that flag will be rejected.
 */
export type MagicAutomaticReturnRouting = boolean;
