// This file was auto-generated by Fern from our API Definition.

/**
 * The name of the data center used for the packet capture. This can be a specific colo (ord02) or a multi-colo name (ORD). This field only applies to `full` packet captures.
 */
export type MagicVisibilityPcapsPcapsColoName = string;
