// This file was auto-generated by Fern from our API Definition.

/**
 * IPv4 CIDRs to associate with traffic decisions. (IPv6 CIDRs are currently unsupported)
 */
export type MagicAppSourceSubnets = string[];
