// This file was auto-generated by Fern from our API Definition.

/**
 * IPv4 CIDR of the router sourcing flow data. Only /32 addresses are currently supported.
 */
export type MagicVisibilityMnmMnmConfigRouterIp = string;
