// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MagicWanUpdateRequest {
    name?: string | undefined;
    physport?: CloudflareApi.MagicPort | undefined;
    priority?: number | undefined;
    static_addressing?: CloudflareApi.MagicWanStaticAddressing | undefined;
    vlan_tag?: CloudflareApi.MagicVlanTag | undefined;
}
