// This file was auto-generated by Fern from our API Definition.

/**
 * Field appears if there is an additional annotation printed when the probe returns. Field also appears when running a GRE+ICMP traceroute to denote which traceroute a node comes from.
 */
export type MagicTransitLabels = string[];
