// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MagicMagicBgpSettingsResponse {
    errors: CloudflareApi.MagicMessages;
    messages: CloudflareApi.MagicMessages;
    result: CloudflareApi.MagicBgpSettings;
    /** Whether the API call was successful */
    success: true;
}
