// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MagicBgpSettings {
    /** Route advertisements from Cloudflare to ramps in this account will use this ASN. */
    cloudflare_asn: number;
    modified_on?: string | undefined;
    redistribute: CloudflareApi.MagicBgpRedistributeSources;
}
