// This file was auto-generated by Fern from our API Definition.

export interface McnAzureSetup {
    azure_consent_url: string;
    integration_identity_tag: string;
    item_type: string;
    tag_cli_command: string;
}
