// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface McnError {
    code: number;
    documentation_url?: string | undefined;
    message: string;
    meta?: CloudflareApi.McnErrorMeta | undefined;
    source?: CloudflareApi.McnErrorSource | undefined;
}
