// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface McnProvider {
    aws_arn?: string | undefined;
    azure_subscription_id?: string | undefined;
    azure_tenant_id?: string | undefined;
    cloud_type: CloudflareApi.McnCloudType;
    description?: string | undefined;
    friendly_name: string;
    gcp_project_id?: string | undefined;
    gcp_service_account_email?: string | undefined;
    id: CloudflareApi.McnProviderId;
    last_updated: string;
    lifecycle_state: CloudflareApi.McnProviderLifecycleState;
    state: CloudflareApi.McnProviderDiscoveryStatus;
    state_v2: CloudflareApi.McnProviderDiscoveryStatus;
    status?: CloudflareApi.McnProviderStatus | undefined;
}
