// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface McnReadAccountProvidersResponse {
    messages: CloudflareApi.McnError[];
    success: boolean;
    errors: CloudflareApi.McnError[];
    result: CloudflareApi.McnProvider[];
}
