// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface McnReadAccountResourcesResponse {
    messages: CloudflareApi.McnError[];
    result_info?: CloudflareApi.McnResultInfo | undefined;
    success: boolean;
    errors: CloudflareApi.McnError[];
    result: CloudflareApi.McnResourceDetails[];
}
