// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MconnConnectorInterruptsListResponse {
    messages: CloudflareApi.MconnCodedMessage[];
    success: boolean;
    errors: CloudflareApi.MconnCodedMessage[];
    result: CloudflareApi.MconnConnectorInterruptsResult[];
}
