// This file was auto-generated by Fern from our API Definition.

/**
 * Snapshot Thermal
 */
export interface MconnTelemetrySnapshotThermal {
    /** Critical failure temperature of the component (degrees Celsius) */
    critical_celcius?: number | undefined;
    /** Current temperature of the component (degrees Celsius) */
    current_celcius?: number | undefined;
    /** Sensor identifier for the component */
    label: string;
    /** Maximum temperature of the component (degrees Celsius) */
    max_celcius?: number | undefined;
}
