// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MconnTelemetryCustomerEventsGetSuccess {
    errors?: CloudflareApi.MconnTelemetryCodedMessage[] | undefined;
    messages?: CloudflareApi.MconnTelemetryCodedMessage[] | undefined;
    success: boolean;
    result: CloudflareApi.MconnTelemetryRecordedEvent;
}
