// This file was auto-generated by Fern from our API Definition.

export interface MonetizationMonetizationEligibilityResult {
    /** Public, human-readable reasons for a rejected decision, when available. */
    reasons?: string[] | undefined;
    /** Current monetization eligibility decision. */
    status: MonetizationMonetizationEligibilityResult.Status;
}

export namespace MonetizationMonetizationEligibilityResult {
    /** Current monetization eligibility decision. */
    export const Status = {
        Pending: "pending",
        Approved: "approved",
        Rejected: "rejected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
