// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MonetizationMonetizationRuleCollectionResponse {
    errors: CloudflareApi.MonetizationResponseInfo[];
    messages: CloudflareApi.MonetizationResponseInfo[];
    success: true;
    result: CloudflareApi.MonetizationMonetizationRuleCollection;
}
