// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MqEventSubscription {
    /** When the subscription was created */
    created_at: string;
    destination: CloudflareApi.MqEventDestination;
    /** Whether the subscription is active */
    enabled: boolean;
    /** List of event types this subscription handles */
    events: string[];
    /** Unique identifier for the subscription */
    id: string;
    /** When the subscription was last modified */
    modified_at: string;
    /** Name of the subscription */
    name: string;
    source: CloudflareApi.MqEventSource;
}
