// This file was auto-generated by Fern from our API Definition.

export interface MqQueueSettings {
    /** Number of seconds to delay delivery of all messages to consumers. */
    delivery_delay?: number | undefined;
    /** Indicates if message delivery to consumers is currently paused. */
    delivery_paused?: boolean | undefined;
    /** Number of seconds after which an unconsumed message will be delayed. */
    message_retention_period?: number | undefined;
}
