// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface MqQueue {
    consumers?: CloudflareApi.MqConsumerResponse[] | undefined;
    consumers_total_count?: number | undefined;
    created_on?: string | undefined;
    jurisdiction?: CloudflareApi.MqJurisdiction | undefined;
    modified_on?: string | undefined;
    producers?: CloudflareApi.MqProducer[] | undefined;
    producers_total_count?: number | undefined;
    queue_id?: string | undefined;
    queue_name?: CloudflareApi.MqQueueName | undefined;
    settings?: CloudflareApi.MqQueueSettings | undefined;
}
