// This file was auto-generated by Fern from our API Definition.

/**
 * An opaque reference to a peeked message. You must hold on to this value and use it to purge the message.
 */
export type MqRef = string;
