// This file was auto-generated by Fern from our API Definition.

export interface PagesPagesAssetsUpsertHashesRequest {
    /** List of file content hashes to register in the asset store. */
    hashes: string[];
}
