// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PagesApiResponseCollection {
    errors: CloudflareApi.PagesMessages;
    messages: CloudflareApi.PagesMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.PagesApiResponseCollectionResultInfo | undefined;
}
