// This file was auto-generated by Fern from our API Definition.

export interface PagesMessagesItem {
    code: number;
    documentation_url?: string | undefined;
    message: string;
    source?: PagesMessagesItem.Source | undefined;
}

export namespace PagesMessagesItem {
    export interface Source {
        pointer?: string | undefined;
    }
}
