// This file was auto-generated by Fern from our API Definition.

/**
 * A plaintext environment variable.
 */
export interface PagesPlainTextEnvVar {
    type: "plain_text";
    /** Environment variable value. */
    value: string;
}
