// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PagesDomain {
    certificate_authority?: PagesDomain.CertificateAuthority | undefined;
    created_on?: string | undefined;
    domain_id?: string | undefined;
    id?: string | undefined;
    name: CloudflareApi.PagesDomainName;
    status?: PagesDomain.Status | undefined;
    validation_data?: CloudflareApi.PagesDomainValidationData | undefined;
    verification_data?: CloudflareApi.PagesDomainVerificationData | undefined;
    zone_tag?: string | undefined;
}

export namespace PagesDomain {
    export const CertificateAuthority = {
        Google: "google",
        LetsEncrypt: "lets_encrypt",
    } as const;
    export type CertificateAuthority = (typeof CertificateAuthority)[keyof typeof CertificateAuthority];
    export const Status = {
        Initializing: "initializing",
        Pending: "pending",
        Active: "active",
        Deactivated: "deactivated",
        Blocked: "blocked",
        Error: "error",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
