// This file was auto-generated by Fern from our API Definition.

export interface PagesSourceConfig {
    /**
     * Whether to enable automatic deployments when pushing to the source repository.
     * When disabled, no deployments (production or preview) will be triggered automatically.
     */
    deployments_enabled: boolean;
    /** The owner of the repository. */
    owner: string;
    /** The owner ID of the repository. */
    owner_id: string;
    /** A list of paths that should be excluded from triggering a preview deployment. Wildcard syntax (`*`) is supported. */
    path_excludes: string[];
    /** A list of paths that should be watched to trigger a preview deployment. Wildcard syntax (`*`) is supported. */
    path_includes: string[];
    /** Whether to enable PR comments. */
    pr_comments_enabled: boolean;
    /** A list of branches that should not trigger a preview deployment. Wildcard syntax (`*`) is supported. Must be used with `preview_deployment_setting` set to `custom`. */
    preview_branch_excludes: string[];
    /** A list of branches that should trigger a preview deployment. Wildcard syntax (`*`) is supported. Must be used with `preview_deployment_setting` set to `custom`. */
    preview_branch_includes: string[];
    /** Controls whether commits to preview branches trigger a preview deployment. */
    preview_deployment_setting: PagesSourceConfig.PreviewDeploymentSetting;
    /** The production branch of the repository. */
    production_branch: string;
    /** Whether to trigger a production deployment on commits to the production branch. */
    production_deployments_enabled: boolean;
    /** The ID of the repository. */
    repo_id: string;
    /** The name of the repository. */
    repo_name: string;
}

export namespace PagesSourceConfig {
    /** Controls whether commits to preview branches trigger a preview deployment. */
    export const PreviewDeploymentSetting = {
        All: "all",
        None: "none",
        Custom: "custom",
    } as const;
    export type PreviewDeploymentSetting = (typeof PreviewDeploymentSetting)[keyof typeof PreviewDeploymentSetting];
}
