// This file was auto-generated by Fern from our API Definition.

/**
 * Name of the Pages project. Must begin with a lowercase letter or digit and contain only lowercase letters, digits, and hyphens.
 */
export type PagesProjectName = string;
