// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PayPerCrawlPpuUsageStatsResponse {
    result: CloudflareApi.PayPerCrawlPpuUsageStats;
    result_info?: CloudflareApi.PayPerCrawlResultInfo | undefined;
    success: boolean;
}
