// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PayPerCrawlGetTermsSignatureResponse {
    errors?: CloudflareApi.PayPerCrawlMsg[] | undefined;
    messages?: CloudflareApi.PayPerCrawlMsg[] | undefined;
    result?: (string | null) | undefined;
    result_info?: CloudflareApi.PayPerCrawlResultInfo | undefined;
    success?: boolean | undefined;
}
