// This file was auto-generated by Fern from our API Definition.

export interface PayPerCrawlPpuUsageStatsDataPoint {
    /** Stable identifier for the buyer represented by this data point. */
    operator_id: string;
    operator_name: string;
    /** Inclusive start of the UTC hour or day represented by this data point. */
    period_start: string;
    /** Full gross value of this data point in USD microcents before the publisher revenue share. */
    total_price_usd_microcents: number;
    usage_count: number;
}
