// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PayPerCrawlCreateStripeConfigResponse {
    errors?: CloudflareApi.PayPerCrawlMsg[] | undefined;
    messages?: CloudflareApi.PayPerCrawlMsg[] | undefined;
    result?: CloudflareApi.PayPerCrawlStripeConnectResp | undefined;
    result_info?: CloudflareApi.PayPerCrawlResultInfo | undefined;
    success?: boolean | undefined;
}
