// This file was auto-generated by Fern from our API Definition.

/**
 * The finding instance that caused the policy to fire.
 */
export interface PostureApiPolicyLogTriggerResponse {
    /** When the finding was first detected, in ISO 8601 / RFC3339 format. */
    date_detected: string;
    /** Free-form JSON object containing finding-type-specific context fields (e.g. file owner, sharing scope). Schema varies per finding type; consumers should treat unknown keys defensively. Null when the upstream row had no fields_of_interest. */
    fields_of_interest: Record<string, unknown> | null;
    /** Display name of the finding type that triggered the policy. */
    finding_type_name: string;
    /** Name of the specific resource (file, drive item, etc.) the finding was raised against. */
    instance_asset: string;
    /** Display name of the CASB integration that produced the finding. */
    integration_name: string;
    /** Path to the integration in the dashboard. */
    integration_url: string;
}
