// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * The actions configured for this policy.
 */
export interface PostureApiPolicyActionsResponse {
    /** List of remediation types that will be executed. */
    remediation_types: CloudflareApi.PostureApiPolicyRemediationTypeResponse[];
    /** List of webhook configurations that will be triggered. */
    webhook_configs: CloudflareApi.PostureApiPolicyWebhookConfigResponse[];
}
