// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Paginated list of remediation jobs.
 */
export interface PostureApiPaginatedRemediationJobList {
    /** Array of error messages. */
    errors: Record<string, unknown>[];
    /** Array of informational messages. */
    messages: Record<string, unknown>[];
    /** Array of remediation job objects. */
    result: CloudflareApi.PostureApiRemediationJob[];
    result_info: CloudflareApi.PostureApiPaginatedRemediationJobListResultInfo;
    /** Whether the API call was successful. */
    success: boolean;
}
