// This file was auto-generated by Fern from our API Definition.

/** The product category. */
export const PostureApiProductEnum = {
    SaaS: "SaaS",
    Cloud: "Cloud",
} as const;
export type PostureApiProductEnum = (typeof PostureApiProductEnum)[keyof typeof PostureApiProductEnum];
