// This file was auto-generated by Fern from our API Definition.

/**
 * Remediation guide information for a finding.
 */
export interface PostureApiFindingRemediation {
    /** Relevant Compliance Frameworks. */
    frameworks?: string[] | undefined;
    /** Remediation guide text. */
    guide: string;
    /** Remediation Id. */
    id?: string | undefined;
    /** Description of the potential impact. */
    impact: string;
    /** I18N Locale. */
    locale?: string | undefined;
    /** Description of the threat. */
    threat: string;
}
