// This file was auto-generated by Fern from our API Definition.

/**
 * Information about a Zero Trust product integration.
 */
export interface PostureApiZeroTrustProduct {
    /** Brief description of the Zero Trust Product. */
    description?: string | undefined;
    /** The verbose name of the Zero Trust Product. */
    display_name?: string | undefined;
    /** Flag to enable/disable access to the listed integration from the corresponding Cloudflare product. */
    enabled?: boolean | undefined;
    /** The internal identifier of the Zero Trust Product. */
    id?: string | undefined;
}
