// This file was auto-generated by Fern from our API Definition.

/** Status of a webhook job. */
export const PostureApiWebhookJobStatusEnum = {
    Pending: "pending",
    Processing: "processing",
    Completed: "completed",
    Failed: "failed",
} as const;
export type PostureApiWebhookJobStatusEnum =
    (typeof PostureApiWebhookJobStatusEnum)[keyof typeof PostureApiWebhookJobStatusEnum];
