// This file was auto-generated by Fern from our API Definition.

/**
 * A remediation job dispatched during a policy invocation.
 */
export interface PostureApiPolicyLogRemediationResponse {
    /** Identifier of the remediation job, suitable for cross-referencing with the remediations API. */
    id: string;
    /** Display name of the remediation type that ran. */
    type: string;
    /** Path to the remediation job in the dashboard. */
    url: string;
}
