// This file was auto-generated by Fern from our API Definition.

/**
 * A webhook configuration associated with the policy.
 */
export interface PostureApiPolicyWebhookConfigResponse {
    /** Display name/label of the webhook configuration. */
    display_name?: string | undefined;
    /** Unique identifier for the webhook configuration. */
    webhook_config_id: string;
}
