// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * The ordered list of enforcement rules for the zone.
 */
export type PrecursorEnforcementRules = CloudflareApi.PrecursorEnforcementRule[];
