// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PrecursorPrecursorConfigResponseBody {
    errors: CloudflareApi.PrecursorMessages;
    messages: CloudflareApi.PrecursorMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.PrecursorPrecursorConfig | undefined;
}
