// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface PublicIpApiResponseCommon {
    errors: CloudflareApi.PublicIpMessages;
    messages: CloudflareApi.PublicIpMessages;
    /** Whether the API call was successful. */
    success: true;
}
