// This file was auto-generated by Fern from our API Definition.

export interface R2AddCustomDomainResponse {
    /** An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format. */
    ciphers?: string[] | undefined;
    /** Domain name of the affected custom domain. */
    domain: string;
    /** Whether this bucket is publicly accessible at the specified custom domain. */
    enabled: boolean;
    /** Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0. */
    minTLS?: R2AddCustomDomainResponse.MinTls | undefined;
    /** Zone ID of the custom domain. */
    zoneId: string;
}

export namespace R2AddCustomDomainResponse {
    /** Minimum TLS Version the custom domain will accept for incoming connections. If not set, defaults to 1.0. */
    export const MinTls = {
        V10: "1.0",
        V11: "1.1",
        V12: "1.2",
        V13: "1.3",
    } as const;
    export type MinTls = (typeof MinTls)[keyof typeof MinTls];
}
