// This file was auto-generated by Fern from our API Definition.

/** Location of the bucket. */
export const R2BucketLocation = {
    Apac: "apac",
    Eeur: "eeur",
    Enam: "enam",
    Weur: "weur",
    Wnam: "wnam",
    Oc: "oc",
} as const;
export type R2BucketLocation = (typeof R2BucketLocation)[keyof typeof R2BucketLocation];
