// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A single R2 bucket.
 */
export interface R2Bucket {
    /** Creation timestamp. */
    creation_date?: string | undefined;
    jurisdiction?: CloudflareApi.R2Jurisdiction | undefined;
    location?: CloudflareApi.R2BucketLocation | undefined;
    name?: CloudflareApi.R2BucketName | undefined;
    storage_class?: CloudflareApi.R2StorageClass | undefined;
}
