// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface R2CorsRule {
    allowed: CloudflareApi.R2CorsRuleAllowed;
    /** Specifies the headers that can be exposed back, and accessed by, the JavaScript making the cross-origin request. If you need to access headers beyond the safelisted response headers, such as Content-Encoding or cf-cache-status, you must specify it here. */
    exposeHeaders?: string[] | undefined;
    /** Identifier for this rule. */
    id?: string | undefined;
    /** Specifies the amount of time (in seconds) browsers are allowed to cache CORS preflight responses. Browsers may limit this to 2 hours or less, even if the maximum value (86400) is specified. */
    maxAgeSeconds?: number | undefined;
}
