// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Updates snapshot expiration configuration (all fields optional).
 */
export interface R2DataCatalogSnapshotExpirationUpdateParams {
    /** Updates the maximum age for snapshots optionally. */
    max_snapshot_age?: string | undefined;
    /** Updates the minimum number of snapshots to retain optionally. */
    min_snapshots_to_keep?: number | undefined;
    /** Updates the state optionally. */
    state?: CloudflareApi.R2DataCatalogCatalogMaintenanceState | undefined;
}
