// This file was auto-generated by Fern from our API Definition.

/** Shows the credential configuration status. */
export const R2DataCatalogCredentialStatus = {
    Present: "present",
    Absent: "absent",
} as const;
export type R2DataCatalogCredentialStatus =
    (typeof R2DataCatalogCredentialStatus)[keyof typeof R2DataCatalogCredentialStatus];
