// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface R2EnableSippyGcs {
    destination?: CloudflareApi.R2EnableSippyGcsDestination | undefined;
    source?: CloudflareApi.R2EnableSippyGcsSource | undefined;
}
