// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type R2LifecycleRuleDeleteObjectsTransitionCondition =
    | CloudflareApi.R2LifecycleRuleDeleteObjectsTransitionCondition.Age
    | CloudflareApi.R2LifecycleRuleDeleteObjectsTransitionCondition.Date;

export namespace R2LifecycleRuleDeleteObjectsTransitionCondition {
    export interface Age extends CloudflareApi.R2LifecycleAgeCondition {
        type: "Age";
    }

    export interface Date extends CloudflareApi.R2LifecycleDateCondition {
        type: "globalThis.Date";
    }
}
