// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface R2V4ResponseList {
    errors: CloudflareApi.R2Errors;
    messages: CloudflareApi.R2Messages;
    result: Record<string, unknown>;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.R2ResultInfo | undefined;
}
