// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface RealtimekitUpdatePresetUi {
    design_tokens?: CloudflareApi.RealtimekitUpdatePresetUiDesignTokens | undefined;
}
