// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Media permissions
 */
export interface RealtimekitUpdatePresetPermissionsMedia {
    audio?: CloudflareApi.RealtimekitUpdatePresetPermissionsMediaAudio | undefined;
    screenshare?: CloudflareApi.RealtimekitUpdatePresetPermissionsMediaScreenshare | undefined;
    video?: CloudflareApi.RealtimekitUpdatePresetPermissionsMediaVideo | undefined;
}
