// This file was auto-generated by Fern from our API Definition.

export interface RealtimekitTranscript {
    sessionId: string;
    /** URL where the transcript can be downloaded */
    transcript_download_url: string;
    /** Time when the download URL will expire */
    transcript_download_url_expiry: string;
}
