// This file was auto-generated by Fern from our API Definition.

export interface RealtimekitWebhook {
    /** Timestamp when this webhook was created */
    created_at: string;
    /** Set to true if the webhook is active */
    enabled: boolean;
    /** Events this webhook will send updates for */
    events: RealtimekitWebhook.Events.Item[];
    /** ID of the webhook */
    id?: string | undefined;
    /** Name of the webhook */
    name: string;
    /** Timestamp when this webhook was updated */
    updated_at: string;
    /** URL the webhook will send events to */
    url: string;
}

export namespace RealtimekitWebhook {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            MeetingStarted: "meeting.started",
            MeetingEnded: "meeting.ended",
            MeetingParticipantJoined: "meeting.participantJoined",
            MeetingParticipantLeft: "meeting.participantLeft",
            MeetingChatSynced: "meeting.chatSynced",
            RecordingStatusUpdate: "recording.statusUpdate",
            LivestreamingStatusUpdate: "livestreaming.statusUpdate",
            MeetingTranscript: "meeting.transcript",
            MeetingSummary: "meeting.summary",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
