// This file was auto-generated by Fern from our API Definition.

/**
 * Video permissions
 */
export interface RealtimekitPresetPermissionsMediaVideo {
    /** Can produce video */
    can_produce: RealtimekitPresetPermissionsMediaVideo.CanProduce;
}

export namespace RealtimekitPresetPermissionsMediaVideo {
    /** Can produce video */
    export const CanProduce = {
        Allowed: "ALLOWED",
        NotAllowed: "NOT_ALLOWED",
        CanRequest: "CAN_REQUEST",
    } as const;
    export type CanProduce = (typeof CanProduce)[keyof typeof CanProduce];
}
