// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface RealtimekitErrorResponse {
    error: CloudflareApi.RealtimekitErrorResponseError;
    /** Whether the operation succeeded or not */
    success: boolean;
}
