// This file was auto-generated by Fern from our API Definition.

export interface RealtimekitTrackConfigLayer {
    /** A file name prefix to apply for files generated from this layer */
    file_name_prefix?: string | undefined;
    /** Media kind to record. Track recording currently supports audio only. */
    media_kind?: "audio" | undefined;
}
