// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Status of an async registration workflow.
 */
export interface RegistrarApiSandboxWorkflowStatus {
    /** Indicates whether the workflow reached a terminal state. A `succeeded` or `failed` state returns `true`; `pending`, `in_progress`, `action_required`, and `blocked` return `false`. */
    completed: boolean;
    /**
     * Provides workflow-specific data.
     *
     * For domain-centric workflows, `context.domain_name` identifies the
     * workflow subject.
     */
    context?: Record<string, unknown> | undefined;
    created_at: string;
    error?: (CloudflareApi.RegistrarApiSandboxWorkflowError | null) | undefined;
    links: CloudflareApi.RegistrarApiSandboxWorkflowLinks;
    /**
     * Describes the workflow lifecycle state.
     * - `pending`: The workflow awaits processing.
     * - `in_progress`: Processing started. Continue polling `links.self`.
     *   An internal deadline limits the duration of this state.
     * - `action_required`: The workflow pauses for user action. See
     *   `context.action` for details. Stop automated polling until the user
     *   completes the required action.
     * - `blocked`: A third party, such as the domain extension's registry or
     *   a losing registrar, prevents progress. Continue polling because the
     *   block may resolve when the third party responds.
     * - `succeeded`: Terminal state. The operation completed successfully.
     *   `completed` equals `true`. For registrations,
     *   `context.registration` contains the resulting registration resource.
     * - `failed`: Terminal state. The operation failed. `completed` equals
     *   `true`. See `error.code` and `error.message` for the reason. Require
     *   user review before retrying.
     */
    state: RegistrarApiSandboxWorkflowStatus.State;
    updated_at: string;
}

export namespace RegistrarApiSandboxWorkflowStatus {
    /**
     * Describes the workflow lifecycle state.
     * - `pending`: The workflow awaits processing.
     * - `in_progress`: Processing started. Continue polling `links.self`.
     *   An internal deadline limits the duration of this state.
     * - `action_required`: The workflow pauses for user action. See
     *   `context.action` for details. Stop automated polling until the user
     *   completes the required action.
     * - `blocked`: A third party, such as the domain extension's registry or
     *   a losing registrar, prevents progress. Continue polling because the
     *   block may resolve when the third party responds.
     * - `succeeded`: Terminal state. The operation completed successfully.
     *   `completed` equals `true`. For registrations,
     *   `context.registration` contains the resulting registration resource.
     * - `failed`: Terminal state. The operation failed. `completed` equals
     *   `true`. See `error.code` and `error.message` for the reason. Require
     *   user review before retrying.
     */
    export const State = {
        Pending: "pending",
        InProgress: "in_progress",
        ActionRequired: "action_required",
        Blocked: "blocked",
        Succeeded: "succeeded",
        Failed: "failed",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
