// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface RegistrarApiDomainUpdateProperties {
    auto_renew?: CloudflareApi.RegistrarApiAutoRenew | undefined;
    locked?: CloudflareApi.RegistrarApiLocked | undefined;
    privacy?: CloudflareApi.RegistrarApiPrivacy | undefined;
}
