// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface RegistrarApiApiResponseCommonFailure {
    errors: CloudflareApi.RegistrarApiMessages;
    messages: CloudflareApi.RegistrarApiMessages;
    result: Record<string, unknown> | null;
    /** Whether the API call was successful. */
    success: false;
}
