// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Extension entry with metadata and JSON Schema documents for registration and transfer operations.
 */
export interface RegistrarApiSandboxExtensionItem {
    metadata: CloudflareApi.RegistrarApiSandboxExtensionItemMetadata;
    /** JSON Schema describing the expected input structure for registration operations on this extension. */
    registration_schema: Record<string, unknown>;
    /** JSON Schema describing the expected input structure for transfer operations on this extension. */
    transfer_schema: Record<string, unknown>;
}
