// This file was auto-generated by Fern from our API Definition.

/**
 * Statuses for domain transfers into Cloudflare Registrar.
 */
export interface RegistrarApiSandboxTransferIn {
    /** Status of the registrant authorization step. */
    accept_foa?: RegistrarApiSandboxTransferIn.AcceptFoa | undefined;
    /** Status of the registry transfer-approval step. */
    approve_transfer?: RegistrarApiSandboxTransferIn.ApproveTransfer | undefined;
    /** Indicates if cancellation is still possible. */
    can_cancel_transfer?: boolean | undefined;
    /** Status of the privacy-guard disabling step at the foreign registrar. */
    disable_privacy?: RegistrarApiSandboxTransferIn.DisablePrivacy | undefined;
    /** Status of the auth-code entry and verification step. */
    enter_auth_code?: RegistrarApiSandboxTransferIn.EnterAuthCode | undefined;
    /** Status of the domain-unlock step at the foreign registrar. */
    unlock_domain?: RegistrarApiSandboxTransferIn.UnlockDomain | undefined;
}

export namespace RegistrarApiSandboxTransferIn {
    /** Status of the registrant authorization step. */
    export const AcceptFoa = {
        Needed: "needed",
        Ok: "ok",
    } as const;
    export type AcceptFoa = (typeof AcceptFoa)[keyof typeof AcceptFoa];
    /** Status of the registry transfer-approval step. */
    export const ApproveTransfer = {
        Needed: "needed",
        Ok: "ok",
        Pending: "pending",
        Trying: "trying",
        Rejected: "rejected",
        Unknown: "unknown",
    } as const;
    export type ApproveTransfer = (typeof ApproveTransfer)[keyof typeof ApproveTransfer];
    /** Status of the privacy-guard disabling step at the foreign registrar. */
    export const DisablePrivacy = {
        Needed: "needed",
        Ok: "ok",
        Unknown: "unknown",
    } as const;
    export type DisablePrivacy = (typeof DisablePrivacy)[keyof typeof DisablePrivacy];
    /** Status of the auth-code entry and verification step. */
    export const EnterAuthCode = {
        Needed: "needed",
        Ok: "ok",
        Pending: "pending",
        Trying: "trying",
        Rejected: "rejected",
    } as const;
    export type EnterAuthCode = (typeof EnterAuthCode)[keyof typeof EnterAuthCode];
    /** Status of the domain-unlock step at the foreign registrar. */
    export const UnlockDomain = {
        Needed: "needed",
        Ok: "ok",
        Pending: "pending",
        Trying: "trying",
        Unknown: "unknown",
    } as const;
    export type UnlockDomain = (typeof UnlockDomain)[keyof typeof UnlockDomain];
}
