// This file was auto-generated by Fern from our API Definition.

/** Optional reason enum providing additional context about the report status (e.g., cancellation reason, error details) */
export const ReportsGetReportResponseReason = {
    Unspecified: "unspecified",
    InvalidEntitlements: "invalid_entitlements",
    PolicyDisabled: "policy_disabled",
} as const;
export type ReportsGetReportResponseReason =
    (typeof ReportsGetReportResponseReason)[keyof typeof ReportsGetReportResponseReason];
