// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ReportsApplicationSecurityReportV1Data {
    /** Cloudflare account ID this report was generated for */
    account_id: string;
    /** Human-readable name of the account */
    account_name: string;
    industry: CloudflareApi.ReportsApplicationSecurityReportV1DataIndustry;
    /** Percentile ranking of this account's security posture within their industry (0-100). Null when industry is unknown/unsupported or benchmarks are unavailable. */
    industry_percentile: number | null;
    time_range: CloudflareApi.ReportsApplicationSecurityReportV1DataTimeRange;
    /** Countries that generated the most mitigated (blocked/challenged) requests */
    top_countries_by_mitigated_requests: CloudflareApi.ReportsApplicationSecurityReportV1DataTopCountriesByMitigatedRequestsItem[];
    /** Countries that generated the most legitimate (served) requests */
    top_countries_by_served_requests: CloudflareApi.ReportsApplicationSecurityReportV1DataTopCountriesByServedRequestsItem[];
    /** Hostnames with the highest number of mitigated (blocked/challenged) requests */
    top_hostnames_by_mitigated_requests: CloudflareApi.ReportsApplicationSecurityReportV1DataTopHostnamesByMitigatedRequestsItem[];
    /** Firewall rules that blocked or challenged the most requests */
    top_rules_by_mitigated_requests: CloudflareApi.ReportsApplicationSecurityReportV1DataTopRulesByMitigatedRequestsItem[];
    total_requests: CloudflareApi.ReportsApplicationSecurityReportV1DataTotalRequests;
    total_requests_mitigated: CloudflareApi.ReportsApplicationSecurityReportV1DataTotalRequestsMitigated;
    total_requests_served: CloudflareApi.ReportsApplicationSecurityReportV1DataTotalRequestsServed;
    /** Total number of zones (domains) in this account */
    total_zones: number;
    /** Number of zones that were included in this security analysis */
    total_zones_analyzed: number;
}
