// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for alerting_webhook resources
 */
export interface ResourceTaggingTaggedResourceObjectAlertingWebhook
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccountLevelBase {}
