// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Request body schema for deleting tags from account-level resources.
 */
export interface ResourceTaggingDeleteTagsRequestAccountLevelBase {
    resource_id: CloudflareApi.ResourceTaggingResourceId;
}
