// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for vectorize_index resources
 */
export interface ResourceTaggingTaggedResourceObjectVectorizeIndex
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccountLevelBase {}
