// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for infrastructure_target resources
 */
export interface ResourceTaggingTaggedResourceObjectInfrastructureTarget
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccountLevelBase {}
