// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ResourceSharingShareRecipientResourceObject {
    error: CloudflareApi.ResourceSharingRecipientResourceError;
    resource_id: CloudflareApi.ResourceSharingResourceResourceId;
    resource_version: CloudflareApi.ResourceSharingResourceVersion;
    terminal: CloudflareApi.ResourceSharingRecipientResourceErrorTerminal;
}
