// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ResourceTaggingTagValuesResponseCollection {
    errors: CloudflareApi.ResourceTaggingMessages;
    messages: CloudflareApi.ResourceTaggingMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: string[] | undefined;
    result_info?: CloudflareApi.ResourceTaggingCursorResultInfo | undefined;
}
