// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ResourceTaggingTagKeysResponseCollection {
    errors: CloudflareApi.ResourceTaggingMessages;
    messages: CloudflareApi.ResourceTaggingMessages;
    /** Whether the API call was successful. */
    success: true;
    /** Contains an array of distinct tag keys. */
    result?: string[] | undefined;
    result_info?: CloudflareApi.ResourceTaggingCursorResultInfo | undefined;
}
