// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for load_balancer_monitor resources
 */
export interface ResourceTaggingTaggedResourceObjectLoadBalancerMonitor
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccountLevelBase {}
