// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for access_application_policy resources
 */
export interface ResourceTaggingTaggedResourceObjectAccessApplicationPolicy
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectAccessApplicationPolicyBase {}
