// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Response for dns_record resources
 */
export interface ResourceTaggingTaggedResourceObjectDnsRecord
    extends CloudflareApi.ResourceTaggingTaggedResourceObjectZoneLevelBase {}
