// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for shared dictionary compression. When set, Cloudflare injects Use-As-Dictionary headers on matching cacheable responses.
 */
export interface RulesetsSetCacheSettingsSharedDictionary {
    /** URL pattern for the Use-As-Dictionary match field. This pattern specifies which URLs can use this response as a dictionary. */
    match_pattern: string;
}
