// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export type RulesetsRequestRule =
    | CloudflareApi.RulesetsRequestRule.Block
    | CloudflareApi.RulesetsRequestRule.Challenge
    | CloudflareApi.RulesetsRequestRule.CompressResponse
    | CloudflareApi.RulesetsRequestRule.DdosDynamic
    | CloudflareApi.RulesetsRequestRule.Execute
    | CloudflareApi.RulesetsRequestRule.ForceConnectionClose
    | CloudflareApi.RulesetsRequestRule.JsChallenge
    | CloudflareApi.RulesetsRequestRule.Log
    | CloudflareApi.RulesetsRequestRule.LogCustomField
    | CloudflareApi.RulesetsRequestRule.ManagedChallenge
    | CloudflareApi.RulesetsRequestRule.Redirect
    | CloudflareApi.RulesetsRequestRule.Rewrite
    | CloudflareApi.RulesetsRequestRule.Route
    | CloudflareApi.RulesetsRequestRule.Score
    | CloudflareApi.RulesetsRequestRule.ServeError
    | CloudflareApi.RulesetsRequestRule.SetCacheControl
    | CloudflareApi.RulesetsRequestRule.SetCacheSettings
    | CloudflareApi.RulesetsRequestRule.SetCacheTags
    | CloudflareApi.RulesetsRequestRule.SetConfig
    | CloudflareApi.RulesetsRequestRule.Skip
    | CloudflareApi.RulesetsRequestRule.TransformResponseHtml;

export namespace RulesetsRequestRule {
    export interface Block extends CloudflareApi.RulesetsBlockRule {
        action: "block";
    }

    export interface Challenge extends CloudflareApi.RulesetsChallengeRule {
        action: "challenge";
    }

    export interface CompressResponse extends CloudflareApi.RulesetsCompressResponseRule {
        action: "compress_response";
    }

    export interface DdosDynamic extends CloudflareApi.RulesetsDDoSDynamicRule {
        action: "ddos_dynamic";
    }

    export interface Execute extends CloudflareApi.RulesetsExecuteRule {
        action: "execute";
    }

    export interface ForceConnectionClose extends CloudflareApi.RulesetsForceConnectionCloseRule {
        action: "force_connection_close";
    }

    export interface JsChallenge extends CloudflareApi.RulesetsJsChallengeRule {
        action: "js_challenge";
    }

    export interface Log extends CloudflareApi.RulesetsLogRule {
        action: "log";
    }

    export interface LogCustomField extends CloudflareApi.RulesetsLogCustomFieldRule {
        action: "log_custom_field";
    }

    export interface ManagedChallenge extends CloudflareApi.RulesetsManagedChallengeRule {
        action: "managed_challenge";
    }

    export interface Redirect extends CloudflareApi.RulesetsRedirectRule {
        action: "redirect";
    }

    export interface Rewrite extends CloudflareApi.RulesetsRewriteRule {
        action: "rewrite";
    }

    export interface Route extends CloudflareApi.RulesetsRouteRule {
        action: "route";
    }

    export interface Score extends CloudflareApi.RulesetsScoreRule {
        action: "score";
    }

    export interface ServeError extends CloudflareApi.RulesetsServeErrorRule {
        action: "serve_error";
    }

    export interface SetCacheControl extends CloudflareApi.RulesetsSetCacheControlRule {
        action: "set_cache_control";
    }

    export interface SetCacheSettings extends CloudflareApi.RulesetsSetCacheSettingsRule {
        action: "set_cache_settings";
    }

    export interface SetCacheTags extends CloudflareApi.RulesetsSetCacheTagsRule {
        action: "set_cache_tags";
    }

    export interface SetConfig extends CloudflareApi.RulesetsSetConfigRule {
        action: "set_config";
    }

    export interface Skip extends CloudflareApi.RulesetsSkipRule {
        action: "skip";
    }

    export interface TransformResponseHtml extends CloudflareApi.RulesetsTransformResponseHtmlRule {
        action: "transform_response_html";
    }

    export type Request =
        | CloudflareApi.RulesetsRequestRule.Block
        | CloudflareApi.RulesetsRequestRule.Challenge
        | CloudflareApi.RulesetsRequestRule.CompressResponse
        | CloudflareApi.RulesetsRequestRule.DdosDynamic
        | CloudflareApi.RulesetsRequestRule.Execute
        | CloudflareApi.RulesetsRequestRule.ForceConnectionClose
        | CloudflareApi.RulesetsRequestRule.JsChallenge
        | CloudflareApi.RulesetsRequestRule.Log
        | CloudflareApi.RulesetsRequestRule.LogCustomField
        | CloudflareApi.RulesetsRequestRule.ManagedChallenge
        | CloudflareApi.RulesetsRequestRule.Redirect
        | CloudflareApi.RulesetsRequestRule.Rewrite
        | CloudflareApi.RulesetsRequestRule.Route
        | CloudflareApi.RulesetsRequestRule.Score
        | CloudflareApi.RulesetsRequestRule.ServeError
        | CloudflareApi.RulesetsRequestRule.SetCacheControl
        | CloudflareApi.RulesetsRequestRule.SetCacheSettings
        | CloudflareApi.RulesetsRequestRule.SetCacheTags
        | CloudflareApi.RulesetsRequestRule.SetConfig
        | CloudflareApi.RulesetsRequestRule.Skip
        | CloudflareApi.RulesetsRequestRule.TransformResponseHtml;
}
