// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Controls how cached responses vary based on request headers. `default` is required by the API and applies to any Vary response header that does not have a per-header override.
 */
export interface RulesetsSetCacheSettingsVary {
    default?: CloudflareApi.RulesetsSetCacheSettingsVaryDefault | undefined;
    /** A mapping of lowercase request header names to their vary configuration. */
    headers?: Record<string, CloudflareApi.RulesetsSetCacheSettingsVaryHeader> | undefined;
}
