// This file was auto-generated by Fern from our API Definition.

export interface RulesetsSetCacheSettingsStatusCodeTtlItem {
    /** A single status code to apply the TTL to. */
    status_code?: number | undefined;
    /** A range of status codes to apply the TTL to. */
    status_code_range?: RulesetsSetCacheSettingsStatusCodeTtlItem.StatusCodeRange | undefined;
    /** The time to cache the response for (in seconds). A value of 0 is equivalent to setting the cache control header with the value "no-cache". A value of -1 is equivalent to setting the cache control header with the value of "no-store". */
    value: number;
}

export namespace RulesetsSetCacheSettingsStatusCodeTtlItem {
    /**
     * A range of status codes to apply the TTL to.
     */
    export interface StatusCodeRange {
        /** The lower bound of the range. */
        from?: number | undefined;
        /** The upper bound of the range. */
        to?: number | undefined;
    }
}
