// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Which query string parameters to include in or exclude from the cache key.
 */
export interface RulesetsSetCacheSettingsCustomCacheKeyQueryString {
    exclude?: CloudflareApi.RulesetsSetCacheSettingsCustomCacheKeyQueryStringExclude | undefined;
    include?: CloudflareApi.RulesetsSetCacheSettingsCustomCacheKeyQueryStringInclude | undefined;
}
