// This file was auto-generated by Fern from our API Definition.

/**
 * A list of additional ports that caching should be enabled on.
 */
export type RulesetsSetCacheSettingsAdditionalCacheablePorts = number[];
