// This file was auto-generated by Fern from our API Definition.

/**
 * Whether to strip ETag headers from the origin response before caching.
 */
export type RulesetsSetCacheSettingsStripETags = boolean;
