// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A cache-control directive configuration.
 */
export type RulesetsSetCacheControlDirective =
    /**
     * Set the directive. */
    | {
          cloudflare_only?: CloudflareApi.RulesetsSetCacheControlCloudflareOnly | undefined;
          operation: "set";
      }
    /**
     * Remove the directive. */
    | {
          cloudflare_only?: CloudflareApi.RulesetsSetCacheControlCloudflareOnly | undefined;
          operation: "remove";
      };
