// This file was auto-generated by Fern from our API Definition.

/**
 * The source of this message.
 */
export interface RulesetsMessageSource {
    /** A JSON pointer to the field that is the source of the message. */
    pointer: string;
}
