// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface RumSiteTagListResponse {
    errors: CloudflareApi.RumMessages;
    messages: CloudflareApi.RumMessages;
    /** Whether the API call was successful. */
    success: boolean;
    /** List of Web Analytics site tag identifiers. */
    result?: CloudflareApi.RumSiteTag[] | undefined;
}
