// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface SecondaryDnsTsig {
    algo: CloudflareApi.SecondaryDnsAlgo;
    id?: CloudflareApi.SecondaryDnsIdentifier2 | undefined;
    name: CloudflareApi.SecondaryDnsName2;
    secret: CloudflareApi.SecondaryDnsSecret;
}
