// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface SecretsStoreStoreObject {
    account_id?: CloudflareApi.SecretsStoreAccountIdentifier | undefined;
    created?: CloudflareApi.SecretsStoreCreated | undefined;
    id?: CloudflareApi.SecretsStoreStoreIdentifier | undefined;
    modified?: CloudflareApi.SecretsStoreModified | undefined;
    name: CloudflareApi.SecretsStoreStoreName;
}
