// This file was auto-generated by Fern from our API Definition.

export const SecurityCenterIssueType = {
    ComplianceViolation: "compliance_violation",
    EmailSecurity: "email_security",
    ExposedInfrastructure: "exposed_infrastructure",
    InsecureConfiguration: "insecure_configuration",
    WeakAuthentication: "weak_authentication",
    ConfigurationSuggestion: "configuration_suggestion",
} as const;
export type SecurityCenterIssueType = (typeof SecurityCenterIssueType)[keyof typeof SecurityCenterIssueType];
