// This file was auto-generated by Fern from our API Definition.

/** The current state of the Cache Reserve Clear operation. */
export const SmartshieldCacheReserveClearState = {
    InProgress: "In-progress",
    Completed: "Completed",
} as const;
export type SmartshieldCacheReserveClearState =
    (typeof SmartshieldCacheReserveClearState)[keyof typeof SmartshieldCacheReserveClearState];
