// This file was auto-generated by Fern from our API Definition.

export interface SmartshieldSmartShieldSettingsSmartRouting {
    /** Whether the setting is editable. */
    editable?: boolean | undefined;
    /** The id of the Smart Routing setting. */
    id?: string | undefined;
    /** Specifies the enablement value of Argo Smart Routing. */
    value?: SmartshieldSmartShieldSettingsSmartRouting.Value | undefined;
}

export namespace SmartshieldSmartShieldSettingsSmartRouting {
    /** Specifies the enablement value of Argo Smart Routing. */
    export const Value = {
        On: "on",
        Off: "off",
    } as const;
    export type Value = (typeof Value)[keyof typeof Value];
}
