// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface SmartshieldSingleSmartShieldPatchResponse {
    errors: CloudflareApi.SmartshieldMessages;
    messages: CloudflareApi.SmartshieldMessages;
    result: CloudflareApi.SmartshieldSmartShieldSettingsPatchResponse;
    /** Whether the API call was successful. */
    success: true;
}
