// This file was auto-generated by Fern from our API Definition.

export interface SmartshieldBase {
    /** Identifier of the zone setting. */
    id: string;
    /** Last time this setting was modified. */
    modified_on?: (string | null) | undefined;
}
