// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Define a snippet.
 */
export interface SnippetsSnippet {
    /** Indicates when the snippet was created. */
    created_on: string;
    /** Indicates when the snippet was last modified. */
    modified_on?: string | undefined;
    snippet_name: CloudflareApi.SnippetsSnippetName;
}
