// This file was auto-generated by Fern from our API Definition.

/** The type of TLS termination associated with the application. */
export const SpectrumConfigTls = {
    Off: "off",
    Flexible: "flexible",
    Full: "full",
    Strict: "strict",
} as const;
export type SpectrumConfigTls = (typeof SpectrumConfigTls)[keyof typeof SpectrumConfigTls];
