// This file was auto-generated by Fern from our API Definition.

/**
 * Optional UUID of a virtual network for routing origin traffic through tunnel virtual networks.
 */
export type SpectrumConfigVirtualNetworkId = string;
