// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface SpectrumAnalyticsZonesReportResponse {
    errors: CloudflareApi.SpectrumAnalyticsMessages;
    messages: CloudflareApi.SpectrumAnalyticsMessages;
    /** Whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.SpectrumAnalyticsZonesReportResponseResultInfo | undefined;
    query: CloudflareApi.SpectrumAnalyticsZonesReportResponseQuery;
    result: CloudflareApi.SpectrumAnalyticsZoneReport[];
}
