// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface SpectrumAnalyticsQuery {
    dimensions?: CloudflareApi.SpectrumAnalyticsDimensions | undefined;
    filters?: CloudflareApi.SpectrumAnalyticsFilters | undefined;
    /** Limit number of returned metrics. */
    limit?: number | undefined;
    metrics?: CloudflareApi.SpectrumAnalyticsMetrics | undefined;
    since?: CloudflareApi.SpectrumAnalyticsSince | undefined;
    sort?: CloudflareApi.SpectrumAnalyticsSort | undefined;
    until?: CloudflareApi.SpectrumAnalyticsUntil | undefined;
}
