// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface SpectrumConfigBaseAppConfig {
    created_on?: CloudflareApi.SpectrumConfigCreated | undefined;
    id?: CloudflareApi.SpectrumConfigAppIdentifier | undefined;
    modified_on?: CloudflareApi.SpectrumConfigModified | undefined;
}
