// This file was auto-generated by Fern from our API Definition.

/**
 * Controls Binary AST behavior:
 * - "off": Feature disabled.
 * - "on": Binary AST enabled.
 * - "latest": Binary AST enabled using the latest version.
 */
export const SpeedBinaryAstValue = {
    Off: "off",
    On: "on",
    Latest: "latest",
} as const;
export type SpeedBinaryAstValue = (typeof SpeedBinaryAstValue)[keyof typeof SpeedBinaryAstValue];
