// This file was auto-generated by Fern from our API Definition.

/** Whether the feature is enabled or disabled. */
export const SpeedCloudflareFontsValue = {
    On: "on",
    Off: "off",
} as const;
export type SpeedCloudflareFontsValue = (typeof SpeedCloudflareFontsValue)[keyof typeof SpeedCloudflareFontsValue];
