// This file was auto-generated by Fern from our API Definition.

/** Specifies the processing status for all quality levels for a video. */
export const StreamMediaState = {
    Pendingupload: "pendingupload",
    Downloading: "downloading",
    Queued: "queued",
    Inprogress: "inprogress",
    Ready: "ready",
    Error: "error",
    LiveInprogress: "live-inprogress",
} as const;
export type StreamMediaState = (typeof StreamMediaState)[keyof typeof StreamMediaState];
