// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface StreamCaptions {
    generated?: CloudflareApi.StreamGeneratedCaption | undefined;
    label?: CloudflareApi.StreamLabel | undefined;
    language?: CloudflareApi.StreamLanguage | undefined;
    status?: CloudflareApi.StreamCaptionStatus | undefined;
}
