// This file was auto-generated by Fern from our API Definition.

/**
 * Provisions a URL to let your end users upload videos directly to Cloudflare Stream without exposing your API token to clients.
 */
export type StreamDirectUser = boolean;
