// This file was auto-generated by Fern from our API Definition.

/**
 * Includes the total number of videos associated with the submitted query parameters.
 */
export type StreamIncludeCounts = boolean;
