// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Details for playback from an live input using SRT.
 */
export interface StreamPlaybackSrt {
    passphrase?: CloudflareApi.StreamPlaybackSrtStreamPassphrase | undefined;
    streamId?: CloudflareApi.StreamPlaybackSrtStreamId | undefined;
    url?: CloudflareApi.StreamPlaybackSrtUrl | undefined;
}
