// This file was auto-generated by Fern from our API Definition.

/**
 * The source URL for a downloaded image. If the watermark profile was created via direct upload, this field is null.
 */
export type StreamDownloadedFrom = string;
