// This file was auto-generated by Fern from our API Definition.

/**
 * Indicates the number of days after which the live inputs recordings will be deleted. When a stream completes and the recording is ready, the value is used to calculate a scheduled deletion date for that recording. Omit the field to indicate no change, or include with a `null` value to remove an existing scheduled deletion.
 */
export type StreamLiveInputRecordingDeletion = number;
