// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface StreamWatermarks {
    created?: CloudflareApi.StreamWatermarkCreated | undefined;
    downloadedFrom?: CloudflareApi.StreamDownloadedFrom | undefined;
    height?: CloudflareApi.StreamHeight | undefined;
    name?: CloudflareApi.StreamName | undefined;
    opacity?: CloudflareApi.StreamOpacity | undefined;
    padding?: CloudflareApi.StreamPadding | undefined;
    position?: CloudflareApi.StreamPosition | undefined;
    scale?: CloudflareApi.StreamScale | undefined;
    size?: CloudflareApi.StreamWatermarkSize | undefined;
    uid?: CloudflareApi.StreamWatermarkIdentifier | undefined;
    width?: CloudflareApi.StreamWidth | undefined;
}
