// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface StreamVideoResponseSingle {
    errors: CloudflareApi.StreamMessages;
    messages: CloudflareApi.StreamMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.StreamVideos | undefined;
}
