// This file was auto-generated by Fern from our API Definition.

/**
 * Determines whether uninstalling the WARP client requires an override code. (Windows only).
 */
export type TeamsDevicesUninstallProtection = boolean;
