// This file was auto-generated by Fern from our API Definition.

export interface TeamsDevicesPaginationInfo {
    /** Number of records in the response. */
    count: number;
    /** The page size number of the response. */
    page: number;
    /** The limit for the number of records in the response. */
    per_page: number;
    /** Total number of records available. */
    total_count: number;
    /** Total number of pages available. */
    total_pages?: number | undefined;
}
