// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * List of routes included in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request.
 */
export type TeamsDevicesIncludeRequest = CloudflareApi.TeamsDevicesSplitTunnelInclude[];
