// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TeamsDevicesDeviceSettingsPolicy {
    allow_mode_switch?: CloudflareApi.TeamsDevicesAllowModeSwitch | undefined;
    allow_updates?: CloudflareApi.TeamsDevicesAllowUpdates | undefined;
    allowed_to_leave?: CloudflareApi.TeamsDevicesAllowedToLeave | undefined;
    auto_connect?: CloudflareApi.TeamsDevicesAutoConnect | undefined;
    browser_extension_config?: (CloudflareApi.TeamsDevicesBrowserExtensionConfig | null) | undefined;
    captive_portal?: CloudflareApi.TeamsDevicesCaptivePortal | undefined;
    default?: CloudflareApi.TeamsDevicesDefault | undefined;
    description?: CloudflareApi.TeamsDevicesSchemasDescription | undefined;
    disable_auto_fallback?: CloudflareApi.TeamsDevicesDisableAutoFallback | undefined;
    dns_search_suffixes?: CloudflareApi.TeamsDevicesDnsSearchSuffixes | undefined;
    /** Whether the policy will be applied to matching devices. */
    enabled?: boolean | undefined;
    exclude?: CloudflareApi.TeamsDevicesExclude | undefined;
    exclude_office_ips?: CloudflareApi.TeamsDevicesExcludeOfficeIps | undefined;
    fallback_domains?: CloudflareApi.TeamsDevicesFallbackDomains | undefined;
    gateway_unique_id?: CloudflareApi.TeamsDevicesGatewayUniqueId | undefined;
    global_acceleration?: (CloudflareApi.TeamsDevicesGlobalAcceleration | null) | undefined;
    include?: CloudflareApi.TeamsDevicesInclude | undefined;
    lan_allow_minutes?: CloudflareApi.TeamsDevicesLanAllowMinutes | undefined;
    lan_allow_subnet_size?: CloudflareApi.TeamsDevicesLanAllowSubnetSize | undefined;
    match?: CloudflareApi.TeamsDevicesSchemasMatch | undefined;
    /** The name of the device settings profile. */
    name?: string | undefined;
    policy_id?: CloudflareApi.TeamsDevicesSchemasUuid | undefined;
    precedence?: CloudflareApi.TeamsDevicesPrecedence | undefined;
    profile_type?: CloudflareApi.TeamsDevicesProfileType | undefined;
    register_interface_ip_with_dns?: CloudflareApi.TeamsDevicesRegisterInterfaceIpWithDns | undefined;
    sccm_vpn_boundary_support?: CloudflareApi.TeamsDevicesSccmVpnBoundarySupport | undefined;
    service_mode_v2?: CloudflareApi.TeamsDevicesServiceModeV2 | undefined;
    support_url?: CloudflareApi.TeamsDevicesSupportUrl | undefined;
    switch_locked?: CloudflareApi.TeamsDevicesSwitchLocked | undefined;
    target_tests?: CloudflareApi.TeamsDevicesTargetDexTest[] | undefined;
    tunnel_protocol?: CloudflareApi.TeamsDevicesTunnelProtocol | undefined;
    uninstall_protection?: CloudflareApi.TeamsDevicesUninstallProtection | undefined;
    virtual_networks?: (CloudflareApi.TeamsDevicesVirtualNetworks | null) | undefined;
}
