// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TeamsDevicesV4ErrorResponse {
    errors: CloudflareApi.TeamsDevicesV4ResponseMessage[];
    messages: CloudflareApi.TeamsDevicesV4ResponseMessage[];
    result: Record<string, unknown> | null;
    success: false;
}
