// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TeamsDevicesApiResponseSingle {
    errors: CloudflareApi.TeamsDevicesMessages;
    messages: CloudflareApi.TeamsDevicesMessages;
    result: TeamsDevicesApiResponseSingle.Result | null;
    /** Whether the API call was successful. */
    success: true;
}

export namespace TeamsDevicesApiResponseSingle {
    export type Result = Record<string, unknown> | string;
}
