// This file was auto-generated by Fern from our API Definition.

export interface TeamsDevicesClientCertificateInputRequest {
    /** UUID of Cloudflare managed certificate. */
    certificate_id: string;
    /** Common Name that is protected by the certificate. */
    cn: string;
}
