// This file was auto-generated by Fern from our API Definition.

/**
 * Global Acceleration settings for China. When configured, WARP clients connect to the Global Accelerator addresses instead of the default ones. Please contact your account representative to enable this feature on your account. See https://developers.cloudflare.com/china-network/concepts/global-acceleration/.
 */
export interface TeamsDevicesGlobalAcceleration {
    /** IP:port entries for the API endpoints. */
    api_endpoints: string[];
    /** Automatically switch Global Acceleration regions based on device location. Defaults to false when not provided. */
    autoswitch?: boolean | undefined;
    /** Global acceleration settings are used only when "enabled". */
    enabled: boolean;
    /** IP:port entries for the MASQUE tunnel endpoints. Either wireguard_endpoints or masque_endpoints must be provided. */
    masque_endpoints: string[];
    /** IP:port entries for the WireGuard tunnel endpoints. Either wireguard_endpoints or masque_endpoints must be provided. */
    wireguard_endpoints: string[];
}
