// This file was auto-generated by Fern from our API Definition.

/**
 * Whether to allow the user to turn off the WARP switch and disconnect the client.
 */
export type TeamsDevicesSwitchLocked = boolean;
