// This file was auto-generated by Fern from our API Definition.

/** The type of the certificate, indicating how it was created and who manages it. */
export const TlsCertificatesAndHostnamesType3 = {
    Custom: "custom",
    GatewayManaged: "gateway_managed",
    AccessManaged: "access_managed",
} as const;
export type TlsCertificatesAndHostnamesType3 =
    (typeof TlsCertificatesAndHostnamesType3)[keyof typeof TlsCertificatesAndHostnamesType3];
