// This file was auto-generated by Fern from our API Definition.

/**
 * The private key for the certificate. This field is only needed for specific use cases such as using a custom certificate with Zero Trust's block page.
 */
export type TlsCertificatesAndHostnamesPrivateKey4 = string;
