// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Configuration for using Keyless SSL through a Cloudflare Tunnel.
 */
export interface TlsCertificatesAndHostnamesKeylessTunnel {
    private_ip: CloudflareApi.TlsCertificatesAndHostnamesKeylessPrivateIp;
    vnet_id: CloudflareApi.TlsCertificatesAndHostnamesKeylessVnetId;
}
