// This file was auto-generated by Fern from our API Definition.

/**
 * These are errors that were encountered while trying to activate a fallback origin.
 */
export type TlsCertificatesAndHostnamesErrors = string[];
