// This file was auto-generated by Fern from our API Definition.

/** Status of the zone's custom SSL. */
export const TlsCertificatesAndHostnamesStatus7 = {
    Initializing: "initializing",
    PendingDeployment: "pending_deployment",
    Active: "active",
    PendingDeletion: "pending_deletion",
    Deleted: "deleted",
    Expired: "expired",
} as const;
export type TlsCertificatesAndHostnamesStatus7 =
    (typeof TlsCertificatesAndHostnamesStatus7)[keyof typeof TlsCertificatesAndHostnamesStatus7];
