// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TlsCertificatesAndHostnamesCustomTrustStoreResponseIdOnly {
    errors: CloudflareApi.TlsCertificatesAndHostnamesMessages;
    messages: CloudflareApi.TlsCertificatesAndHostnamesMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.TlsCertificatesAndHostnamesCustomTrustStoreResponseIdOnlyResult | undefined;
}
