// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TlsCertificatesAndHostnamesZoneAuthenticatedOriginPull {
    certificate?: CloudflareApi.TlsCertificatesAndHostnamesCertificate5 | undefined;
    enabled?: CloudflareApi.TlsCertificatesAndHostnamesEnabled4 | undefined;
    id?: CloudflareApi.TlsCertificatesAndHostnamesZoneAopCertificateIdentifier | undefined;
    private_key?: CloudflareApi.TlsCertificatesAndHostnamesPrivateKey2 | undefined;
    expires_on?: CloudflareApi.TlsCertificatesAndHostnamesExpiresOn4 | undefined;
    issuer?: CloudflareApi.TlsCertificatesAndHostnamesIssuer | undefined;
    signature?: CloudflareApi.TlsCertificatesAndHostnamesSignature | undefined;
    status?: CloudflareApi.TlsCertificatesAndHostnamesStatus8 | undefined;
    uploaded_on?: CloudflareApi.TlsCertificatesAndHostnamesUploadedOn2 | undefined;
}
