// This file was auto-generated by Fern from our API Definition.

export interface TlsCertificatesAndHostnamesMessagesItem {
    code: number;
    documentation_url?: string | undefined;
    message: string;
    source?: TlsCertificatesAndHostnamesMessagesItem.Source | undefined;
}

export namespace TlsCertificatesAndHostnamesMessagesItem {
    export interface Source {
        pointer?: string | undefined;
    }
}
