// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TlsCertificatesAndHostnamesCustomHostnameQuotaResponse {
    errors: CloudflareApi.TlsCertificatesAndHostnamesMessages;
    messages: CloudflareApi.TlsCertificatesAndHostnamesCustomHostnameResponseMessages;
    /** Whether the API call was successful. */
    success: true;
    result?: CloudflareApi.TlsCertificatesAndHostnamesCustomHostnameQuota | undefined;
}
