// This file was auto-generated by Fern from our API Definition.

/** The type 'legacy_custom' enables support for legacy clients which do not include SNI in the TLS handshake. */
export const TlsCertificatesAndHostnamesType = {
    LegacyCustom: "legacy_custom",
    SniCustom: "sni_custom",
} as const;
export type TlsCertificatesAndHostnamesType =
    (typeof TlsCertificatesAndHostnamesType)[keyof typeof TlsCertificatesAndHostnamesType];
