// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TlsCertificatesAndHostnamesFallbackorigin {
    created_at?: CloudflareApi.TlsCertificatesAndHostnamesCreatedAt2 | undefined;
    errors?: CloudflareApi.TlsCertificatesAndHostnamesErrors | undefined;
    origin?: CloudflareApi.TlsCertificatesAndHostnamesOrigin | undefined;
    status?: CloudflareApi.TlsCertificatesAndHostnamesStatus4 | undefined;
    updated_at?: CloudflareApi.TlsCertificatesAndHostnamesUpdatedAt | undefined;
}
