// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TunnelVirtualNetwork {
    comment: CloudflareApi.TunnelVirtualNetworkComment;
    created_at?: CloudflareApi.TunnelCreatedAt | undefined;
    deleted_at?: CloudflareApi.TunnelDeletedAt | undefined;
    id: CloudflareApi.TunnelVirtualNetworkId;
    is_default_network: CloudflareApi.TunnelIsDefaultNetwork;
    name: CloudflareApi.TunnelVirtualNetworkName;
}
