// This file was auto-generated by Fern from our API Definition.

/**
 * The Tunnel Token is used as a mechanism to authenticate the operation of a tunnel.
 */
export type TunnelTunnelToken = string;
