// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TunnelZeroTrustConnectivitySettingsResponseResult {
    icmp_proxy_enabled?: CloudflareApi.TunnelIcmpProxyEnabled | undefined;
    offramp_warp_enabled?: CloudflareApi.TunnelOfframpWarpEnabled | undefined;
}
