// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A Cloudflare Tunnel that connects your origin to Cloudflare's edge.
 */
export interface TunnelCfdTunnel {
    account_tag?: CloudflareApi.TunnelAccountId | undefined;
    config_src?: CloudflareApi.TunnelConfigSrc | undefined;
    connections?: CloudflareApi.TunnelConnectionsDeprecated | undefined;
    conns_active_at?: CloudflareApi.TunnelConnsActiveAt | undefined;
    conns_inactive_at?: CloudflareApi.TunnelConnsInactiveAt | undefined;
    created_at?: CloudflareApi.TunnelCreatedAt | undefined;
    deleted_at?: CloudflareApi.TunnelDeletedAt | undefined;
    id?: CloudflareApi.TunnelTunnelId | undefined;
    metadata?: CloudflareApi.TunnelMetadata | undefined;
    name?: CloudflareApi.TunnelTunnelName | undefined;
    remote_config?: CloudflareApi.TunnelRemoteConfig | undefined;
    status?: CloudflareApi.TunnelStatus | undefined;
    tun_type?: CloudflareApi.TunnelTunnelType | undefined;
}
