// This file was auto-generated by Fern from our API Definition.

/** The type of subnet. */
export const TunnelSubnetType = {
    CloudflareSource: "cloudflare_source",
    InitialResolvedIp: "initial_resolved_ip",
    Warp: "warp",
} as const;
export type TunnelSubnetType = (typeof TunnelSubnetType)[keyof typeof TunnelSubnetType];
