// This file was auto-generated by Fern from our API Definition.

/**
 * If provided, include only resources that were created (and not deleted) before this time. URL encoded.
 */
export type TunnelExistedAt = string;
