// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TunnelTeamnetResponseSingle {
    errors: CloudflareApi.TunnelMessages;
    messages: CloudflareApi.TunnelMessages;
    result: CloudflareApi.TunnelTeamnet;
    /** Whether the API call was successful */
    success: true;
}
