// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface TurnstileApiResponseCommonFailure {
    errors: CloudflareApi.TurnstileMessages;
    messages: CloudflareApi.TurnstileMessages;
    result: Record<string, unknown> | null;
    /** Whether the API call was successful */
    success: boolean;
}
