// This file was auto-generated by Fern from our API Definition.

/** Specifies the type of metric to use calculating distance. */
export const VectorizeIndexMetric = {
    Cosine: "cosine",
    Euclidean: "euclidean",
    DotProduct: "dot-product",
} as const;
export type VectorizeIndexMetric = (typeof VectorizeIndexMetric)[keyof typeof VectorizeIndexMetric];
