// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface VectorizeIndexUpsertResponse {
    /** Specifies the count of the vectors successfully inserted. */
    count?: number | undefined;
    /** Array of vector identifiers of the vectors successfully inserted. */
    ids?: CloudflareApi.VectorizeVectorIdentifier[] | undefined;
}
