// This file was auto-generated by Fern from our API Definition.

/**
 * The unique identifier for the async mutation operation containing the changeset.
 */
export type VectorizeMutationUuid = unknown;
