// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface VectorizeIndexGetVectorsByIdRequest {
    /** A list of vector identifiers to retrieve from the index indicated by the path. */
    ids?: CloudflareApi.VectorizeVectorIdentifier[] | undefined;
}
