// This file was auto-generated by Fern from our API Definition.

/**
 * Successful scan deletion result.
 */
export interface VulnScannerDeleteScanResponse {
    /** ID of the deleted scan. */
    id: string;
}
