// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WafManagedRulesApiResponseCommon {
    errors: CloudflareApi.WafManagedRulesMessages;
    messages: CloudflareApi.WafManagedRulesMessages;
    /** Defines whether the API call was successful. */
    success: true;
}
