// This file was auto-generated by Fern from our API Definition.

/** Defines the default action/mode of a rule. */
export const WafManagedRulesDefaultMode = {
    Disable: "disable",
    Simulate: "simulate",
    Block: "block",
    Challenge: "challenge",
} as const;
export type WafManagedRulesDefaultMode = (typeof WafManagedRulesDefaultMode)[keyof typeof WafManagedRulesDefaultMode];
