// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WafManagedRulesApiResponseCommonFailure {
    errors: CloudflareApi.WafManagedRulesMessages;
    messages: CloudflareApi.WafManagedRulesMessages;
    result: Record<string, unknown> | null;
    /** Defines whether the API call was successful. */
    success: false;
}
