// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WafProductApiBundleResponseStatus {
    errors: CloudflareApi.WafProductApiBundleMessages;
    messages: CloudflareApi.WafProductApiBundleMessages;
    result: CloudflareApi.WafProductApiBundleStatus;
    /** Defines whether the API call was successful. */
    success: true;
}
