// This file was auto-generated by Fern from our API Definition.

export type WafProductApiBundleApiResponseCommon2Result =
    | Record<string, unknown>
    | Record<string, unknown>[]
    | string
    | null;
