// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WafProductApiBundleResponseCustomScanCollection {
    errors: CloudflareApi.WafProductApiBundleMessages;
    messages: CloudflareApi.WafProductApiBundleMessages;
    result: CloudflareApi.WafProductApiBundleCustomScan[];
    /** Whether the API call was successful. */
    success: true;
}
