// This file was auto-generated by Fern from our API Definition.

/**
 * Suspends or allows traffic going to the waiting room. If set to `true`, the traffic will not go to the waiting room.
 */
export type WaitingroomSuspended = boolean;
