// This file was auto-generated by Fern from our API Definition.

/** Specify the target gateway of the hostname. */
export const Web3Target = {
    Ethereum: "ethereum",
    Ipfs: "ipfs",
    IpfsUniversalPath: "ipfs_universal_path",
} as const;
export type Web3Target = (typeof Web3Target)[keyof typeof Web3Target];
