// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Provides content list entries.
 */
export type Web3ContentListEntries = CloudflareApi.Web3ContentListEntry[];
