// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface Web3SingleResponse {
    errors: CloudflareApi.Web3Messages;
    messages: CloudflareApi.Web3Messages;
    result: CloudflareApi.Web3Web3Hostname;
    /** Specifies whether the API call was successful. */
    success: true;
    /** Provides the API response. */
    result_info?: Web3SingleResponse.ResultInfo | undefined;
}

export namespace Web3SingleResponse {
    /**
     * Provides the API response.
     */
    export type ResultInfo = Record<string, unknown> | null | string | null;
}
