// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * A single entry in the `exports` map, keyed by export name (a
 * `WorkerEntrypoint` class name, a Durable Object class name, or
 * `default` for the Worker's default export). The `type`
 * discriminator selects the top-level shape: `worker` entrypoint
 * entries may carry `cache` configuration, while `durable-object`
 * entries are further refined by the optional `state` field
 * (default `created`). Tombstone states (`deleted`, `renamed`,
 * `transferred`) express destructive lifecycle operations
 * declaratively; `expecting-transfer` is the live target side of a
 * transfer. The server validates the exact per-(type, state) field
 * combinations; fields not listed for a variant are rejected.
 */
export type WorkersExportConfig = CloudflareApi.WorkersWorkerExport | CloudflareApi.WorkersDurableObjectExportVariants;
