// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Migrations for Durable Objects associated with the deployment. Migrations are applied when the deployment is created.
 */
export type WorkersPreviewDeploymentConfigMigrations =
    | CloudflareApi.WorkersSingleStepMigrations
    | CloudflareApi.WorkersMultipleStepMigrations;
