// This file was auto-generated by Fern from our API Definition.

export interface WorkersErrorInternalServer {
    /** Code indicating that an unknown internal server error has occurred. */
    code: number;
    /** Message explaining that an unknown error occurred and providing guidance for reporting the issue. */
    message: string;
}
