// This file was auto-generated by Fern from our API Definition.

export interface WorkersBindingKindInherit {
    /** The name of the inherited binding. */
    name: string;
    /** The old name of the inherited binding. If set, the binding will be renamed from `old_name` to `name` in the new version. If not set, the binding will keep the same name between versions. */
    old_name?: string | undefined;
    /** Identifier for the version to inherit the binding from, which can be the version ID or the literal "latest" to inherit from the latest version. Defaults to inheriting the binding from the latest version. */
    version_id?: string | undefined;
}
