// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WorkersKvBulkGetResultWithMetadata {
    /** Requested keys are paired with their values and metadata in an object. */
    values?: Record<string, WorkersKvBulkGetResultWithMetadata.Values.Value | null> | undefined;
}

export namespace WorkersKvBulkGetResultWithMetadata {
    export namespace Values {
        export interface Value {
            expiration?: CloudflareApi.WorkersKvExpiration | undefined;
            /** The metadata associated with the key. */
            metadata: Value.Metadata;
            /** The value associated with the key. */
            value: Value.Value;
        }

        export namespace Value {
            /**
             * The metadata associated with the key.
             */
            export type Metadata =
                | string
                | number
                | number
                | boolean
                | Record<string, unknown>
                | null
                | Record<string, unknown>[];
            /**
             * The value associated with the key.
             */
            export type Value =
                | string
                | number
                | number
                | boolean
                | Record<string, unknown>
                | null
                | Record<string, unknown>[];
        }
    }
}
