// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Migrations for Durable Objects associated with the version. Migrations are applied when the version is deployed.
 */
export type WorkersVersionMigrations =
    | CloudflareApi.WorkersSingleStepMigrations
    | CloudflareApi.WorkersMultipleStepMigrations;
