// This file was auto-generated by Fern from our API Definition.

/**
 * Trace settings for the Preview.
 */
export interface WorkersPreviewObservabilityTraces {
    /** A list of destinations where traces will be exported to. */
    destinations?: string[] | undefined;
    /** Whether traces are enabled for the Preview. */
    enabled?: boolean | undefined;
    /** The sampling rate for traces. From 0 to 1 (1 = 100%, 0.1 = 10%). */
    head_sampling_rate?: number | undefined;
    /** Whether trace persistence is enabled for the Preview. */
    persist?: boolean | undefined;
}
