// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Observability settings for the Preview.
 */
export interface WorkersPreviewObservability {
    /** Whether observability is enabled for the Preview. */
    enabled?: boolean | undefined;
    /** The sampling rate for observability. From 0 to 1 (1 = 100%, 0.1 = 10%). */
    head_sampling_rate?: number | undefined;
    issues?: (CloudflareApi.WorkersPreviewObservabilityIssues | null) | undefined;
    logs?: CloudflareApi.WorkersPreviewObservabilityLogs | undefined;
    /** Whether query strings are removed from request URLs in logs and traces. */
    redact_query_string?: boolean | undefined;
    traces?: CloudflareApi.WorkersPreviewObservabilityTraces | undefined;
}
