// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Migrations to apply for Durable Objects associated with this Worker.
 */
export type WorkersNamespaceScriptAndVersionSettingsItemMigrations =
    | CloudflareApi.WorkersSingleStepMigrations
    | CloudflareApi.WorkersMultipleStepMigrations;
