// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WorkersKvApiResponseCommon {
    errors: CloudflareApi.WorkersKvMessages;
    messages: CloudflareApi.WorkersKvMessages;
    /** Whether the API call was successful. */
    success: true;
}
