// This file was auto-generated by Fern from our API Definition.

export interface WorkersObject {
    /** Whether the Durable Object has stored data. */
    hasStoredData?: boolean | undefined;
    /** ID of the Durable Object. */
    id?: string | undefined;
}
