// This file was auto-generated by Fern from our API Definition.

export interface WorkersWorkerReferencesDispatchNamespaceOutboundsItem {
    /** ID of the dispatch namespace. */
    namespace_id: string;
    /** Name of the dispatch namespace. */
    namespace_name: string;
    /** ID of the Worker using the dispatch namespace. */
    worker_id: string;
    /** Name of the Worker using the dispatch namespace. */
    worker_name: string;
}
