// This file was auto-generated by Fern from our API Definition.

export interface WorkersWorkerReferencesDurableObjectsItem {
    /** ID of the Durable Object namespace being used. */
    namespace_id: string;
    /** Name of the Durable Object namespace being used. */
    namespace_name: string;
    /** ID of the Worker using the Durable Object implementation. */
    worker_id: string;
    /** Name of the Worker using the Durable Object implementation. */
    worker_name: string;
}
