// This file was auto-generated by Fern from our API Definition.

/**
 * Configure the order of the results returned by the query.
 */
export interface WorkersObservabilityQueryParametersOrderBy {
    /** Set the order of the results */
    order?: WorkersObservabilityQueryParametersOrderBy.Order | undefined;
    /** Configure which Calculation to order the results by. */
    value: string;
}

export namespace WorkersObservabilityQueryParametersOrderBy {
    /** Set the order of the results */
    export const Order = {
        Asc: "asc",
        Desc: "desc",
    } as const;
    export type Order = (typeof Order)[keyof typeof Order];
}
