// This file was auto-generated by Fern from our API Definition.

export interface WorkersObservabilityQueryParametersGroupBysItem {
    type: WorkersObservabilityQueryParametersGroupBysItem.Type;
    value: string;
}

export namespace WorkersObservabilityQueryParametersGroupBysItem {
    export const Type = {
        String: "string",
        Number: "number",
        Boolean: "boolean",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
