// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface WorkersBindingKindWorkflow {
    /** Class name of the Workflow. Should only be provided if the Workflow belongs to this script. */
    class_name?: string | undefined;
    name: CloudflareApi.WorkersBindingName;
    /** Script name that contains the Workflow. If not provided, defaults to this script name. */
    script_name?: string | undefined;
    /** Name of the Workflow to bind to. */
    workflow_name: string;
}
