// This file was auto-generated by Fern from our API Definition.

/**
 * Global CacheW configuration for the Worker. When caching is on,
 * the platform provisions a `cloudflare.app` zone for the Worker.
 * A `type: worker` entry in the `exports` map can override this
 * value for a single entrypoint.
 */
export interface WorkersCacheOptions {
    /**
     * Whether cached responses are shared across Worker version
     * uploads. This is independent of `enabled`. It can stay true
     * while caching is off, so the preference survives turning
     * caching off and back on.
     */
    cross_version_cache?: boolean | undefined;
    /** Whether caching is enabled for this Worker. */
    enabled: boolean;
}
