// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Zaraz configuration.
 */
export interface ZarazZarazConfigBase {
    analytics?: CloudflareApi.ZarazZarazConfigBaseAnalytics | undefined;
    consent?: CloudflareApi.ZarazZarazConfigBaseConsent | undefined;
    /** Data layer compatibility mode enabled. */
    dataLayer: boolean;
    /** The key for Zaraz debug mode. */
    debugKey: string;
    /** Single Page Application support enabled. */
    historyChange?: boolean | undefined;
    settings: CloudflareApi.ZarazZarazConfigBaseSettings;
    /** Triggers set up under Zaraz configuration, where key is the trigger alpha-numeric ID and value is the trigger configuration. */
    triggers: Record<string, ZarazZarazConfigBase.Triggers.Value>;
    /** Variables set up under Zaraz configuration, where key is the variable alpha-numeric ID and value is the variable configuration. Values of variables of type secret are not included. */
    variables: Record<string, CloudflareApi.ZarazZarazConfigBaseVariablesValue>;
    /** Zaraz internal version of the config. */
    zarazVersion: number;
}

export namespace ZarazZarazConfigBase {
    export namespace Triggers {
        export interface Value {
            /** Trigger description. */
            description?: string | undefined;
            /** Rules defining when the trigger is not fired. */
            excludeRules: Value.ExcludeRules.Item[];
            /** Rules defining when the trigger is fired. */
            loadRules: Value.LoadRules.Item[];
            /** Trigger name. */
            name: string;
            system?: "pageload" | undefined;
        }

        export namespace Value {
            export type ExcludeRules = ExcludeRules.Item[];

            export namespace ExcludeRules {
                export type Item =
                    | CloudflareApi.ZarazLoadRule
                    | CloudflareApi.ZarazClickListenerRule
                    | CloudflareApi.ZarazTimerRule
                    | CloudflareApi.ZarazFormSubmissionRule
                    | CloudflareApi.ZarazVariableMatchRule
                    | CloudflareApi.ZarazScrollDepthRule
                    | CloudflareApi.ZarazElementVisibilityRule;
            }

            export type LoadRules = LoadRules.Item[];

            export namespace LoadRules {
                export type Item =
                    | CloudflareApi.ZarazLoadRule
                    | CloudflareApi.ZarazClickListenerRule
                    | CloudflareApi.ZarazTimerRule
                    | CloudflareApi.ZarazFormSubmissionRule
                    | CloudflareApi.ZarazVariableMatchRule
                    | CloudflareApi.ZarazScrollDepthRule
                    | CloudflareApi.ZarazElementVisibilityRule;
            }
        }
    }
}
