// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * General Zaraz settings.
 */
export interface ZarazZarazConfigBaseSettings {
    /** Automatic injection of Zaraz scripts enabled. */
    autoInjectScript: boolean;
    contextEnricher?: CloudflareApi.ZarazZarazConfigBaseSettingsContextEnricher | undefined;
    /** The domain Zaraz will use for writing and reading its cookies. */
    cookieDomain?: string | undefined;
    /** Ecommerce API enabled. */
    ecommerce?: boolean | undefined;
    /** Custom endpoint for server-side track events. */
    eventsApiPath?: string | undefined;
    /** Hiding external referrer URL enabled. */
    hideExternalReferer?: boolean | undefined;
    /** Trimming IP address enabled. */
    hideIPAddress?: boolean | undefined;
    /** Removing URL query params enabled. */
    hideQueryParams?: boolean | undefined;
    /** Removing sensitive data from User Agent string enabled. */
    hideUserAgent?: boolean | undefined;
    /** Custom endpoint for Zaraz init script. */
    initPath?: string | undefined;
    /** Injection of Zaraz scripts into iframes enabled. */
    injectIframes?: boolean | undefined;
    /** Custom path for Managed Components server functionalities. */
    mcRootPath?: string | undefined;
    /** Custom endpoint for Zaraz main script. */
    scriptPath?: string | undefined;
    /** Custom endpoint for Zaraz tracking requests. */
    trackPath?: string | undefined;
}
