// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ZarazZarazConfigHistoryResponse {
    errors: CloudflareApi.ZarazMessages;
    messages: CloudflareApi.ZarazMessages;
    /** Whether the API call was successful. */
    success: boolean;
    /** Object where keys are numeric configuration IDs. */
    result: Record<string, ZarazZarazConfigHistoryResponse.Result.Value>;
}

export namespace ZarazZarazConfigHistoryResponse {
    export namespace Result {
        export interface Value extends CloudflareApi.ZarazZarazConfigRowBase {}
    }
}
