// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ZeroTrustGatewayLists {
    count?: CloudflareApi.ZeroTrustGatewayCount | undefined;
    created_at?: CloudflareApi.ZeroTrustGatewayReadOnlyTimestamp | undefined;
    description?: CloudflareApi.ZeroTrustGatewayDescription | undefined;
    id?: CloudflareApi.ZeroTrustGatewayUuid2 | undefined;
    items?: CloudflareApi.ZeroTrustGatewayItems | undefined;
    name?: CloudflareApi.ZeroTrustGatewayName | undefined;
    type?: CloudflareApi.ZeroTrustGatewayType2 | undefined;
    updated_at?: CloudflareApi.ZeroTrustGatewayReadOnlyTimestamp | undefined;
}
