// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Provide the list items.
 */
export type ZeroTrustGatewayItems = CloudflareApi.ZeroTrustGatewayItemsItem[];
