// This file was auto-generated by Fern from our API Definition.

/**
 * Account-level cap on DNS response TTLs, in seconds. Gateway rewrites DNS responses so returned record TTLs do not exceed this value. Null means no cap. Each DNS location can inherit, override, or disable it through the location `max_ttl` setting.
 */
export type ZeroTrustGatewayMaxTtlSecs = number | null;
