// This file was auto-generated by Fern from our API Definition.

/**
 * Configure settings that apply to quarantine rules. Settable only for `http` rules.
 */
export interface ZeroTrustGatewayRuleSettingsQuarantine {
    /** Specify the types of files to sandbox. */
    file_types?: ZeroTrustGatewayRuleSettingsQuarantine.FileTypes.Item[] | undefined;
}

export namespace ZeroTrustGatewayRuleSettingsQuarantine {
    export type FileTypes = FileTypes.Item[];

    export namespace FileTypes {
        export const Item = {
            Exe: "exe",
            Pdf: "pdf",
            Doc: "doc",
            Docm: "docm",
            Docx: "docx",
            Rtf: "rtf",
            Ppt: "ppt",
            Pptx: "pptx",
            Xls: "xls",
            Xlsm: "xlsm",
            Xlsx: "xlsx",
            Zip: "zip",
            Rar: "rar",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
