// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Specify account settings.
 */
export interface ZeroTrustGatewayGatewayAccountSettingsSettings {
    activity_log?: (CloudflareApi.ZeroTrustGatewayActivityLogSettings | null) | undefined;
    antivirus?: (CloudflareApi.ZeroTrustGatewayAntiVirusSettings | null) | undefined;
    block_page?: (CloudflareApi.ZeroTrustGatewayBlockPageSettings | null) | undefined;
    body_scanning?: (CloudflareApi.ZeroTrustGatewayBodyScanningSettings | null) | undefined;
    browser_isolation?: (CloudflareApi.ZeroTrustGatewayBrowserIsolationSettings | null) | undefined;
    certificate?: (CloudflareApi.ZeroTrustGatewayCertificateSettings | null) | undefined;
    custom_certificate?: (CloudflareApi.ZeroTrustGatewayCustomCertificateSettings | null) | undefined;
    extended_email_matching?: (CloudflareApi.ZeroTrustGatewayExtendedEmailMatching | null) | undefined;
    fips?: (CloudflareApi.ZeroTrustGatewayFipsSettings | null) | undefined;
    host_selector?: (CloudflareApi.ZeroTrustGatewayHostSelectorSettings | null) | undefined;
    inspection?: (CloudflareApi.ZeroTrustGatewayInspectionSettings | null) | undefined;
    max_ttl_secs?: (CloudflareApi.ZeroTrustGatewayMaxTtlSecs | null) | undefined;
    protocol_detection?: (CloudflareApi.ZeroTrustGatewayProtocolDetection | null) | undefined;
    sandbox?: (CloudflareApi.ZeroTrustGatewaySandbox | null) | undefined;
    tls_decrypt?: (CloudflareApi.ZeroTrustGatewayTlsSettings | null) | undefined;
}
