// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ZeroTrustGatewayApiResponseCollection {
    errors: CloudflareApi.ZeroTrustGatewayMessages;
    messages: CloudflareApi.ZeroTrustGatewayMessages;
    /** Indicate whether the API call was successful. */
    success: true;
    result_info?: CloudflareApi.ZeroTrustGatewayResultInfo | undefined;
}
