// This file was auto-generated by Fern from our API Definition.

export interface ZeroTrustGatewayResultInfo {
    /** Indicate the total number of results for the requested service. */
    count?: number | undefined;
    /** Indicate the current page within a paginated list of results. */
    page?: number | undefined;
    /** Indicate the number of results per page. */
    per_page?: number | undefined;
    /** Indicate the total results available without any search parameters. */
    total_count?: number | undefined;
}
