// This file was auto-generated by Fern from our API Definition.

/**
 * Identify the type of this application. Multiple applications can share the same type. Refers to the `id` of a returned application type.
 */
export type ZeroTrustGatewayAppTypeId = number;
