// This file was auto-generated by Fern from our API Definition.

/**
 * Indicate the read-only region the certificate authority's key material is pinned to. Omitted for certificates that were created without a region.
 */
export type ZeroTrustGatewayRegion = string;
