// This file was auto-generated by Fern from our API Definition.

/**
 * Value of the zone setting.
 * Notes: Defaults to on for Business+ plans
 */
export const ZonesAdvancedDdosValue = {
    On: "on",
    Off: "off",
} as const;
export type ZonesAdvancedDdosValue = (typeof ZonesAdvancedDdosValue)[keyof typeof ZonesAdvancedDdosValue];
