// This file was auto-generated by Fern from our API Definition.

/**
 * Comma-separated list of allowed origins.
 * Refer to the [Image Transformations](https://developers.cloudflare.com/images/transform-images/sources/) and [Video Transformations](https://developers.cloudflare.com/stream/transform-videos/#getting-started) documentation for more information.
 */
export type ZonesTransformationsAllowedOriginsValue = string;
