// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Origin H2 Max Streams configures the max number of concurrent requests that Cloudflare will send within the same connection when communicating with the origin server, if the origin supports it. Note that if your origin does not support H2 multiplexing, 5xx errors may be observed, particularly 520s. Also note that the default value is `100` for all plan types except Enterprise where it is `1`. `1` means that H2 multiplexing is disabled.
 */
export interface ZonesCacheRulesOriginH2MaxStreams {
    /** Value of the zone setting. */
    id: "origin_h2_max_streams";
    /** Last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value?: CloudflareApi.ZonesCacheRulesOriginH2MaxStreamsValue | undefined;
}
