// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ZonesZone {
    account: CloudflareApi.ZonesZoneAccount;
    /**
     * The last time proof of ownership was detected and the zone was made
     * active.
     */
    activated_on?: (string | null) | undefined;
    /**
     * Allows the customer to use a custom apex.
     * *Tenants Only Configuration*.
     */
    cname_suffix?: string | undefined;
    /** When the zone was created. */
    created_on?: string | undefined;
    /**
     * The interval (in seconds) from when development mode expires
     * (positive integer) or last expired (negative integer) for the
     * domain. If development mode has never been enabled, this value is 0.
     */
    development_mode?: number | undefined;
    /** Identifier */
    id: string;
    meta: CloudflareApi.ZonesZoneMeta;
    /** When the zone was last modified. */
    modified_on?: string | undefined;
    /** The domain name. Per [RFC 1035](https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.4) the overall zone name can be up to 253 characters, with each segment ("label") not exceeding 63 characters. */
    name: string;
    /** The name servers Cloudflare assigns to a zone. */
    name_servers?: string[] | undefined;
    /** DNS host at the time of switching to Cloudflare. */
    original_dnshost?: (string | null) | undefined;
    /** Original name servers before moving to Cloudflare. */
    original_name_servers?: (string[] | null) | undefined;
    /** Registrar for the domain at the time of switching to Cloudflare. */
    original_registrar?: (string | null) | undefined;
    owner: CloudflareApi.ZonesZoneOwner;
    paused?: CloudflareApi.ZonesPaused | undefined;
    /** Legacy permissions based on legacy user membership information. */
    permissions?: string[] | undefined;
    /** A Zones subscription information. */
    plan: ZonesZone.Plan;
    /** The zone status on Cloudflare. */
    status?: ZonesZone.Status | undefined;
    /** The root organizational unit that this zone belongs to (such as a tenant or organization). */
    tenant?: ZonesZone.Tenant | undefined;
    /** The immediate parent organizational unit that this zone belongs to (such as under a tenant or sub-organization). */
    tenant_unit?: ZonesZone.TenantUnit | undefined;
    type?: CloudflareApi.ZonesType | undefined;
    /** An array of domains used for custom name servers. This is only available for Business and Enterprise plans. */
    vanity_name_servers?: string[] | undefined;
    /** Verification key for partial zone setup. */
    verification_key?: string | undefined;
}

export namespace ZonesZone {
    /**
     * A Zones subscription information.
     */
    export interface Plan {
        /** States if the subscription can be activated. */
        can_subscribe?: boolean | undefined;
        /** The denomination of the customer. */
        currency?: string | undefined;
        /** If this Zone is managed by another company. */
        externally_managed?: boolean | undefined;
        /** How often the customer is billed. */
        frequency?: string | undefined;
        id?: CloudflareApi.ZonesIdentifier | undefined;
        /** States if the subscription active. */
        is_subscribed?: boolean | undefined;
        /** If the legacy discount applies to this Zone. */
        legacy_discount?: boolean | undefined;
        /** The legacy name of the plan. */
        legacy_id?: string | undefined;
        /** Name of the owner. */
        name?: string | undefined;
        /** How much the customer is paying. */
        price?: number | undefined;
    }

    /** The zone status on Cloudflare. */
    export const Status = {
        Initializing: "initializing",
        Pending: "pending",
        Active: "active",
        Moved: "moved",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * The root organizational unit that this zone belongs to (such as a tenant or organization).
     */
    export interface Tenant {
        id?: CloudflareApi.ZonesIdentifier | undefined;
        /** The name of the Tenant account. */
        name?: string | undefined;
    }

    /**
     * The immediate parent organizational unit that this zone belongs to (such as under a tenant or sub-organization).
     */
    export interface TenantUnit {
        id?: CloudflareApi.ZonesIdentifier | undefined;
    }
}
