// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Analytics data for a single zone owned by the user.
 */
export interface ZoneAnalyticsApiUserZone {
    /**
     * Time deltas containing analytics data for each bucket. The number of
     * buckets (resolution) is determined by the time range between since and until.
     */
    timeseries?: CloudflareApi.ZoneAnalyticsApiUserPeriod[] | undefined;
    totals?: CloudflareApi.ZoneAnalyticsApiUserPeriod | undefined;
    /** The zone identifier. */
    zone_id?: string | undefined;
}
