// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Allow SHA1 support.
 */
export interface ZonesSha1Support {
    /** Whether or not this setting can be modified for this zone (based on your Cloudflare plan level). */
    editable?: boolean | undefined;
    /** Zone setting identifier. */
    id: "sha1_support";
    /** last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value: CloudflareApi.ZonesSha1SupportValue;
}
