// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * An allowlist of ciphers for TLS termination. These ciphers must be in the BoringSSL format.
 */
export interface ZonesCiphers {
    /** Whether or not this setting can be modified for this zone (based on your Cloudflare plan level). */
    editable?: boolean | undefined;
    /** ID of the zone setting. */
    id: "ciphers";
    /** last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value: CloudflareApi.ZonesCiphersValue;
}
