// This file was auto-generated by Fern from our API Definition.

/** Value of the HTTP3 setting. */
export const ZonesHttp3Value = {
    On: "on",
    Off: "off",
} as const;
export type ZonesHttp3Value = (typeof ZonesHttp3Value)[keyof typeof ZonesHttp3Value];
