// This file was auto-generated by Fern from our API Definition.

/** Value of the zone setting. */
export const ZonesSecurityLevelValue = {
    Off: "off",
    EssentiallyOff: "essentially_off",
    Low: "low",
    Medium: "medium",
    High: "high",
    UnderAttack: "under_attack",
} as const;
export type ZonesSecurityLevelValue = (typeof ZonesSecurityLevelValue)[keyof typeof ZonesSecurityLevelValue];
