// This file was auto-generated by Fern from our API Definition.

/** Value of the zone setting. */
export const ZonesMirageValue = {
    On: "on",
    Off: "off",
} as const;
export type ZonesMirageValue = (typeof ZonesMirageValue)[keyof typeof ZonesMirageValue];
