// This file was auto-generated by Fern from our API Definition.

/** Value of the zone setting. */
export const ZonesServerSideExcludeValue = {
    On: "on",
    Off: "off",
} as const;
export type ZonesServerSideExcludeValue =
    (typeof ZonesServerSideExcludeValue)[keyof typeof ZonesServerSideExcludeValue];
