// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * TLS Client Auth requires Cloudflare to connect to your origin server using a client certificate (Enterprise Only).
 */
export interface ZonesTlsClientAuth {
    /** Whether or not this setting can be modified for this zone (based on your Cloudflare plan level). */
    editable?: boolean | undefined;
    /** ID of the zone setting. */
    id: "tls_client_auth";
    /** last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value: CloudflareApi.ZonesTlsClientAuthValue;
}
