// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Browser Cache TTL (in seconds) specifies how long Cloudflare-cached resources will remain on your visitors' computers. Cloudflare will honor any larger times specified by your server. (https://support.cloudflare.com/hc/en-us/articles/200168276).
 */
export interface ZonesBrowserCacheTtl2 {
    /** Whether or not this setting can be modified for this zone (based on your Cloudflare plan level). */
    editable?: boolean | undefined;
    /** ID of the zone setting. */
    id: "browser_cache_ttl";
    /** last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value: CloudflareApi.ZonesBrowserCacheTtlValue;
}
