// This file was auto-generated by Fern from our API Definition.

/**
 * Breakdown of totals for threats.
 */
export interface ZoneAnalyticsApiThreats {
    /** The total number of identifiable threats received over the time frame. */
    all?: number | undefined;
    /** A list of key/value pairs where the key is a two-digit country code and the value is the number of malicious requests received from that country. */
    country?: Record<string, unknown> | undefined;
    /** The list of key/value pairs where the key is a threat category and the value is the number of requests. */
    type?: Record<string, unknown> | undefined;
}
