// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Breakdown of totals for requests.
 */
export interface ZoneAnalyticsApiRequests {
    /** Total number of requests served. */
    all?: number | undefined;
    /** Total number of cached requests served. */
    cached?: number | undefined;
    /** A variable list of key/value pairs where the key represents the type of content served, and the value is the number of requests. */
    content_type?: Record<string, unknown> | undefined;
    /** A variable list of key/value pairs where the key is a two-digit country code and the value is the number of requests served to that country. */
    country?: Record<string, unknown> | undefined;
    /** Key/value pairs where the key is a HTTP status code and the value is the number of requests served with that code. */
    http_status?: Record<string, unknown> | undefined;
    ssl?: CloudflareApi.ZoneAnalyticsApiRequestsSsl | undefined;
    ssl_protocols?: CloudflareApi.ZoneAnalyticsApiRequestsSslProtocols | undefined;
    /** Total number of requests served from the origin. */
    uncached?: number | undefined;
}
