// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ZonesTrueClientIpHeader {
    /** The status of True Client IP Header. */
    value?: CloudflareApi.ZonesTrueClientIpHeaderValue | undefined;
}
