// This file was auto-generated by Fern from our API Definition.

/**
 * Feature fields to add features about the end-user (client) into
 * the Cache Key.
 */
export interface ZonesCacheKeyFieldsValueUser {
    /**
     * Classifies a request as `mobile`, `desktop`, or `tablet`
     * based on the User Agent.
     */
    device_type?: boolean | undefined;
    /** Includes the client's country, derived from the IP address. */
    geo?: boolean | undefined;
    /**
     * Includes the first language code contained in the
     * `Accept-Language` header sent by the client.
     */
    lang?: boolean | undefined;
}
