// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

export interface ZonesSecurityHeaderValue {
    strict_transport_security?: CloudflareApi.ZonesSecurityHeaderValueStrictTransportSecurity | undefined;
}
