// This file was auto-generated by Fern from our API Definition.

export interface ZonesBase {
    /** Whether or not this setting can be modified for this zone (based on your Cloudflare plan level). */
    editable?: boolean | undefined;
    /** Identifier of the zone setting. */
    id: string;
    /** last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value?: unknown | undefined;
}
