// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../index.js";

/**
 * Media Transformations Allowed Origins restricts transformations for images and video served through Cloudflare's network. Refer to the [Image Transformations](https://developers.cloudflare.com/images/) and [Video Transformations](https://developers.cloudflare.com/stream/transform-videos/#getting-started) documentation for more information.
 */
export interface ZonesTransformationsAllowedOrigins {
    /** Whether or not this setting can be modified for this zone (based on your Cloudflare plan level). */
    editable?: boolean | undefined;
    /** ID of the zone setting. Shared between Image Transformations and Video Transformations. */
    id: "transformations_allowed_origins";
    /** last time this setting was modified. */
    modified_on?: (string | null) | undefined;
    value: CloudflareApi.ZonesTransformationsAllowedOriginsValue;
}
