// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface BillSubsApiAddressValidationRequest {
    /** Address line 1. */
    address?: string;
    /** Address line 2. */
    address2?: string;
    /** City. */
    city?: string;
    /** Country code. */
    country?: string;
    /** State or province. */
    state?: string;
    /** Postal or zip code. */
    zipcode?: string;
}
