// This file was auto-generated by Fern from our API Definition.

export interface ListTargetIndustriesResponse {
    items: ListTargetIndustriesResponse.Items;
    type: string;
}

export namespace ListTargetIndustriesResponse {
    export interface Items {
        type: string;
    }
}
