// This file was auto-generated by Fern from our API Definition.

export const DmarcTimeseriesGroupsRequestArcItem = {
    Pass: "PASS",
    None: "NONE",
    Fail: "FAIL",
} as const;
export type DmarcTimeseriesGroupsRequestArcItem =
    (typeof DmarcTimeseriesGroupsRequestArcItem)[keyof typeof DmarcTimeseriesGroupsRequestArcItem];
