// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const EncryptedTimeseriesGroupsRequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type EncryptedTimeseriesGroupsRequestFormat =
    (typeof EncryptedTimeseriesGroupsRequestFormat)[keyof typeof EncryptedTimeseriesGroupsRequestFormat];
