// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         queue_id: "queue_id"
 *     }
 */
export interface GetMetricsRequest {
    /** A Resource identifier. */
    account_id: string;
    /** A Resource identifier. */
    queue_id: string;
}
