// This file was auto-generated by Fern from our API Definition.

export const DmarcSummaryRequestDkimItem = {
    Pass: "PASS",
    None: "NONE",
    Fail: "FAIL",
} as const;
export type DmarcSummaryRequestDkimItem =
    (typeof DmarcSummaryRequestDkimItem)[keyof typeof DmarcSummaryRequestDkimItem];
