// This file was auto-generated by Fern from our API Definition.

export const TlsVersionSummaryRequestDkimItem = {
    Pass: "PASS",
    None: "NONE",
    Fail: "FAIL",
} as const;
export type TlsVersionSummaryRequestDkimItem =
    (typeof TlsVersionSummaryRequestDkimItem)[keyof typeof TlsVersionSummaryRequestDkimItem];
