// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         target_ids: ["0191dce4-9ab4-7fce-b660-8e5dec5172da"]
 *     }
 */
export interface DeleteBulkRequest {
    /** Account identifier */
    account_id: string;
    /** List of target IDs to bulk delete */
    target_ids: CloudflareApi.InfraTargetId[];
}
