// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         items: [{
 *                 tags: {
 *                     "key": "value"
 *                 },
 *                 target_id: "0191dce4-9ab4-7fce-b660-8e5dec5172da"
 *             }]
 *     }
 */
export interface ReplaceTagsBulkRequest {
    /** Account identifier */
    account_id: string;
    items: CloudflareApi.InfraBatchReplaceTargetTagsItem[];
}
