// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         dimension: "SPAM",
 *         name: ["main_series"],
 *         dateRange: ["7d"],
 *         limitPerGroup: 10
 *     }
 */
export interface SummaryV2SecurityRequest {
    /** Specifies the attribute by which to group the results. */
    dimension: CloudflareApi.radar.email.SummaryV2SecurityRequestDimension;
    /** Array of names used to label the series in the response. */
    name?: string | string[];
    /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
    dateRange?: string | string[];
    /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateStart?: string | string[];
    /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateEnd?: string | string[];
    /** Filters results by ARC (Authenticated Received Chain) validation. */
    arc?:
        | CloudflareApi.radar.email.SummaryV2SecurityRequestArcItem
        | CloudflareApi.radar.email.SummaryV2SecurityRequestArcItem[];
    /** Filters results by DKIM (DomainKeys Identified Mail) validation status. */
    dkim?:
        | CloudflareApi.radar.email.SummaryV2SecurityRequestDkimItem
        | CloudflareApi.radar.email.SummaryV2SecurityRequestDkimItem[];
    /** Filters results by DMARC (Domain-based Message Authentication, Reporting and Conformance) validation status. */
    dmarc?:
        | CloudflareApi.radar.email.SummaryV2SecurityRequestDmarcItem
        | CloudflareApi.radar.email.SummaryV2SecurityRequestDmarcItem[];
    /** Filters results by SPF (Sender Policy Framework) validation status. */
    spf?:
        | CloudflareApi.radar.email.SummaryV2SecurityRequestSpfItem
        | CloudflareApi.radar.email.SummaryV2SecurityRequestSpfItem[];
    /** Filters results by TLS version. */
    tlsVersion?:
        | CloudflareApi.radar.email.SummaryV2SecurityRequestTlsVersionItem
        | CloudflareApi.radar.email.SummaryV2SecurityRequestTlsVersionItem[];
    /** Limits the number of objects per group to the top items within the specified time range. When item count exceeds the limit, extra items appear grouped under an "other" category. Only supported on high-cardinality dimensions; otherwise the request is rejected. Minimum value is 2. */
    limitPerGroup?: number;
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.email.SummaryV2SecurityRequestFormat;
}
