// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         id: "ruleset_id"
 *     }
 */
export interface DeleteRulesetsRequest {
    account_or_zone: string;
    /** The unique ID of the account. */
    account_or_zone_id: string;
    /** The unique ID of the ruleset. */
    id: string;
    /** Validates the request without persisting changes when set to `true`. Responses that normally return 200 return `result: null`; endpoints that normally return 204 continue to return 204. */
    dry_run?: boolean;
}
