// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export interface DeleteViewsResponse {
    result?: DeleteViewsResponse.Result | undefined;
}

export namespace DeleteViewsResponse {
    export interface Result {
        id?: CloudflareApi.DnsSettingsIdentifier | undefined;
    }
}
