// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "a86a8f5c339544d7bdc89926de14fb8c",
 *         portal_id: "portal_id"
 *     }
 */
export interface ToolCallAnalyticsPortalsRequest {
    account_id: string;
    portal_id: string;
    granularity?: CloudflareApi.mcp.ToolCallAnalyticsPortalsRequestGranularity;
    aggregate?: CloudflareApi.mcp.ToolCallAnalyticsPortalsRequestAggregate;
    tz?: string;
    /** Daily trailing-window size; defaults to 7 and is ignored for monthly */
    days?: number;
}
