// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface ListMetricsRequest {
    /** Cloudflare account ID that owns the R2 resource. */
    account_id: string;
}
