// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export interface MuteActiveResponse {
    data?: MuteActiveResponse.Data | undefined;
    success?: boolean | undefined;
}

export namespace MuteActiveResponse {
    export interface Data {
        action?: string | undefined;
        participants?: CloudflareApi.RealtimekitSessionParticipant[] | undefined;
    }
}
