// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         burst_sensitivity: "burst_sensitivity",
 *         mode: "mode",
 *         name: "name",
 *         rate_sensitivity: "rate_sensitivity",
 *         scope: "scope"
 *     }
 */
export interface DosNewSynProtectionRule {
    /** The ID of the account. */
    account_id: string;
    /** The burst sensitivity. Must be one of 'low', 'medium', 'high'. */
    burst_sensitivity: string;
    /** The type of mitigation. Must be one of 'challenge' or 'retransmit'. Optional. Defaults to 'challenge'. */
    mitigation_type?: string;
    /** The mode for SYN Protection. Must be one of 'enabled', 'disabled', 'monitoring'. */
    mode: string;
    /** The name of the SYN Protection rule. Value is relative to the 'scope' setting. For 'global' scope, name should be 'global'. For either the 'region' or 'datacenter' scope, name should be the actual name of the region or datacenter, e.g., 'wnam' or 'lax'. */
    name: string;
    /** The rate sensitivity. Must be one of 'low', 'medium', 'high'. */
    rate_sensitivity: string;
    /** The scope for the SYN Protection rule. Must be one of 'global', 'region', or 'datacenter'. */
    scope: string;
}
