// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         dimension: "CLIENT_TYPE",
 *         name: ["main_series"],
 *         dateRange: ["7d"],
 *         limitPerGroup: 10
 *     }
 */
export interface TimeseriesGroupsWebCrawlersRequest {
    /** Specifies the attribute by which to group the results. */
    dimension: CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestDimension;
    /** Aggregation interval of the results (e.g., in 15 minutes or 1 hour intervals). Refer to [Aggregation intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/). When omitted, the interval is auto-selected from the requested date range; finer intervals are only available for shorter ranges. If the requested interval is too granular for the date range, the request is rejected. */
    aggInterval?: CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestAggInterval;
    /** Array of names used to label the series in the response. */
    name?: string | string[];
    /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
    dateRange?: string | string[];
    /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateStart?: string | string[];
    /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateEnd?: string | string[];
    /** Limits the number of objects per group to the top items within the specified time range. When item count exceeds the limit, extra items appear grouped under an "other" category. Only supported on high-cardinality dimensions; otherwise the request is rejected. Minimum value is 2. */
    limitPerGroup?: number;
    /** Normalization method applied to the results. Refer to [Normalization methods](https://developers.cloudflare.com/radar/concepts/normalization/). `PERCENTAGE_CHANGE` requires exactly one comparison series (e.g. a `control` date range). */
    normalization?: CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestNormalization;
    /** Filters results by bot operator. */
    botOperator?: string | string[];
    /** Filters results by vertical. */
    vertical?: string | string[];
    /** Filters results by industry. */
    industry?: string | string[];
    /** Filters results by agent type. */
    clientType?:
        | CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestClientTypeItem
        | CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestClientTypeItem[];
    /** Filters results by HTTP response status code (e.g. 200, 403, 404). Only [IANA-registered codes](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml) are accepted. */
    responseStatus?: string | string[];
    /** Filters results by HTTP response status code category. */
    responseStatusCategory?:
        | CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestResponseStatusCategoryItem
        | CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestResponseStatusCategoryItem[];
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.bots.TimeseriesGroupsWebCrawlersRequestFormat;
}
