// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface GetConfigurationsResponse extends CloudflareApi.ZeroTrustGatewayGatewayAccountSettings {
    created_at?: CloudflareApi.ZeroTrustGatewayReadOnlyTimestamp | undefined;
    updated_at?: CloudflareApi.ZeroTrustGatewayReadOnlyTimestamp | undefined;
}
