// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenant_tag: "tenant_tag",
 *         custom_ns_id: "custom_ns_id"
 *     }
 */
export interface DeleteTenantCustomNameserversRequest {
    /** Tenant identifier tag. */
    tenant_tag: string;
    /** The FQDN of the name server. */
    custom_ns_id: string;
}
