// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         cloud_type: "AWS",
 *         dynamic_routing: true,
 *         install_routes_in_cloud: true,
 *         install_routes_in_magic_wan: true,
 *         name: "name",
 *         type: "OnrampTypeSingle"
 *     }
 */
export interface McnCreateOnrampRequest {
    account_id: string;
    forwarded?: string;
    adopted_hub_id?: CloudflareApi.McnResourceId;
    attached_hubs?: CloudflareApi.McnResourceId[];
    attached_vpcs?: CloudflareApi.McnResourceId[];
    /** Sets the cloud-side ASN. If unset or zero, the cloud's default ASN takes effect. */
    cloud_asn?: number;
    cloud_type: CloudflareApi.McnOnrampCloudType;
    description?: string;
    /** Enables BGP routing. When enabling this feature, set both install_routes_in_cloud and install_routes_in_magic_wan to false. */
    dynamic_routing: boolean;
    hub_provider_id?: CloudflareApi.McnProviderId;
    install_routes_in_cloud: boolean;
    install_routes_in_magic_wan: boolean;
    manage_hub_to_hub_attachments?: boolean;
    manage_vpc_to_hub_attachments?: boolean;
    name: string;
    region?: string;
    type: CloudflareApi.McnOnrampType;
    vpc?: CloudflareApi.McnResourceId;
}
