// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { ReportsClient } from "../resources/reports/client/Client.js";

export declare namespace PhishguardClient {
    export type Options = BaseClientOptions;
}

export class PhishguardClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PhishguardClient.Options>;
    protected _reports: ReportsClient | undefined;

    constructor(options: PhishguardClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get reports(): ReportsClient {
        return (this._reports ??= new ReportsClient(this._options));
    }
}
