// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { CertificatesClient } from "../resources/certificates/client/Client.js";

export declare namespace CertificatePackClient {
    export type Options = BaseClientOptions;
}

export class CertificatePackClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CertificatePackClient.Options>;
    protected _certificates: CertificatesClient | undefined;

    constructor(options: CertificatePackClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get certificates(): CertificatesClient {
        return (this._certificates ??= new CertificatesClient(this._options));
    }
}
