// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../../index.js";

export interface ListUsersResponse {
    /** Page of processed users. */
    result: CloudflareApi.AccessPolicyUsers[];
    result_info?: Record<string, unknown> | undefined;
}
