// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         app_id: "app_id",
 *         peer_id: "peer_id"
 *     }
 */
export interface GetPeersRequest {
    /** The account identifier tag. */
    account_id: string;
    /** The app identifier tag. */
    app_id: string;
    /** ID of the peer */
    peer_id: string;
    /** Filter to apply to the peer report. */
    filters?: CloudflareApi.realtime.kit.sessions.GetPeersRequestFilters;
    /** if true, response includes all the peer events of participant. */
    include_peer_events?: boolean;
}
