// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface ListUsersRequest {
    /** Identifier. */
    account_id: string;
    /** The name of the user. */
    name?: string;
    /** The email of the user. */
    email?: string;
    /** Search for users by other listed query parameters. */
    search?: string;
    /** Page number of results. */
    page?: number;
    /** Number of results per page. */
    per_page?: number;
}
