// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id",
 *         email: "test@example.com"
 *     }
 */
export interface RevokeUsersRequest {
    account_or_zone: string;
    /** Identifier. */
    account_or_zone_id: string;
    /** When set to `true`, all devices associated with the user will be revoked. */
    devices?: boolean;
    /** The email of the user to revoke. */
    email: string;
    /** The uuid of the user to revoke. */
    user_uid?: string;
    /** When set to `true`, the user will be required to re-authenticate to WARP for all Gateway policies that enforce a WARP client session duration. When `false`, the user’s WARP session will remain active */
    warp_session_reauth?: boolean;
}
