// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface GetReputationResponse {
    /** The reputation policy thresholds currently applied to the account. */
    active_policy: CloudflareApi.EmailReputationPolicy;
    /** When the account's reputation was last evaluated. Null when the account has never been evaluated. */
    evaluated_at: string | null;
    /** When the current At Risk suspension grace period started. This can be later than status_since if the grace period was restarted. Null outside At Risk. Automatic suspension remains subject to enforcement and suspension exemptions. */
    grace_started_at: string | null;
    /** The account's current reputation status. */
    status: GetReputationResponse.Status;
    /** When the account most recently transitioned into its current status. Null if the account has been Healthy since it was first tracked and has never changed status. */
    status_since: string | null;
}

export namespace GetReputationResponse {
    /** The account's current reputation status. */
    export const Status = {
        Healthy: "healthy",
        Warning: "warning",
        AtRisk: "at_risk",
        Suspended: "suspended",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
