// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface GetOwnershipResponse {
    result: CloudflareApi.MagicVisibilityPcapsPcapsOwnershipResponse[] | null;
    result_info?: CloudflareApi.MagicVisibilityPcapsResultInfo | undefined;
}
