// This file was auto-generated by Fern from our API Definition.

export interface SupportTlsResponse {
    bugs: SupportTlsResponse.Bugs;
    /** The host that was tested */
    host: string;
    /** TLS CurveID of the negotiated key exchange */
    kex: number;
    /** Human-readable name of the key exchange algorithm */
    kexName: string;
    /** Whether the negotiated key exchange uses Post-Quantum cryptography (specifically X25519MLKEM768) */
    pq: boolean;
}

export namespace SupportTlsResponse {
    export interface Bugs {
        /** Server sends a HelloRetryRequest but fails to complete the handshake after the client sends the second ClientHello. Often caused by non-compliant TLS 1.3 implementations on shared hosting providers. */
        hrrFailure: boolean;
        /** Server rejects fragmented ClientHello caused by large PQ keyshare, but accepts classical (non-PQ) handshakes. Typically caused by middleboxes or firewalls that cannot reassemble split TLS ClientHello messages. */
        splitClientHello: boolean;
        /** Server cannot handle an unknown key exchange algorithm in the ClientHello keyshare extension. Compliant servers should respond with HelloRetryRequest for a supported algorithm. */
        unknownKeyshare: boolean;
    }
}
