// This file was auto-generated by Fern from our API Definition.

export const BotClassTimeseriesGroupsRequestDeviceTypeItem = {
    Desktop: "DESKTOP",
    Mobile: "MOBILE",
    Other: "OTHER",
} as const;
export type BotClassTimeseriesGroupsRequestDeviceTypeItem =
    (typeof BotClassTimeseriesGroupsRequestDeviceTypeItem)[keyof typeof BotClassTimeseriesGroupsRequestDeviceTypeItem];
