// This file was auto-generated by Fern from our API Definition.

export const BotClassTimeseriesGroupsRequestHttpProtocolItem = {
    Http: "HTTP",
    Https: "HTTPS",
} as const;
export type BotClassTimeseriesGroupsRequestHttpProtocolItem =
    (typeof BotClassTimeseriesGroupsRequestHttpProtocolItem)[keyof typeof BotClassTimeseriesGroupsRequestHttpProtocolItem];
