// This file was auto-generated by Fern from our API Definition.

export const BrowserFamilyTimeseriesGroupsRequestDeviceTypeItem = {
    Desktop: "DESKTOP",
    Mobile: "MOBILE",
    Other: "OTHER",
} as const;
export type BrowserFamilyTimeseriesGroupsRequestDeviceTypeItem =
    (typeof BrowserFamilyTimeseriesGroupsRequestDeviceTypeItem)[keyof typeof BrowserFamilyTimeseriesGroupsRequestDeviceTypeItem];
