// This file was auto-generated by Fern from our API Definition.

export const DeviceTypeTimeseriesGroupsRequestBrowserFamilyItem = {
    Chrome: "CHROME",
    Edge: "EDGE",
    Firefox: "FIREFOX",
    Safari: "SAFARI",
} as const;
export type DeviceTypeTimeseriesGroupsRequestBrowserFamilyItem =
    (typeof DeviceTypeTimeseriesGroupsRequestBrowserFamilyItem)[keyof typeof DeviceTypeTimeseriesGroupsRequestBrowserFamilyItem];
