// This file was auto-generated by Fern from our API Definition.

export const OsTimeseriesGroupsRequestBrowserFamilyItem = {
    Chrome: "CHROME",
    Edge: "EDGE",
    Firefox: "FIREFOX",
    Safari: "SAFARI",
} as const;
export type OsTimeseriesGroupsRequestBrowserFamilyItem =
    (typeof OsTimeseriesGroupsRequestBrowserFamilyItem)[keyof typeof OsTimeseriesGroupsRequestBrowserFamilyItem];
