// This file was auto-generated by Fern from our API Definition.

export const OsTimeseriesGroupsRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type OsTimeseriesGroupsRequestIpVersionItem =
    (typeof OsTimeseriesGroupsRequestIpVersionItem)[keyof typeof OsTimeseriesGroupsRequestIpVersionItem];
