// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         tunnel_id: "tunnel_id",
 *         resources: ["logs"]
 *     }
 */
export interface CreateManagementTokenRequest {
    /** Cloudflare account ID */
    account_id: string;
    /** UUID of the tunnel. */
    tunnel_id: string;
    resources: CloudflareApi.TunnelManagementResources[];
}
