// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         address_map_id: "address_map_id",
 *         member_account_id: "member_account_id"
 *     }
 */
export interface DeleteAccountsRequest {
    /** Identifier of a Cloudflare account. */
    account_id: string;
    /** Identifier of an Address Map. */
    address_map_id: string;
    /** Identifier of a Cloudflare account. */
    member_account_id: string;
}
