// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface ListCertificatesRequest {
    /** Specify the Cloudflare account identifier. */
    account_id: string;
}
