// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         location: "US"
 *     }
 */
export interface GetLocationsRequest {
    /** Location alpha-2 code. */
    location: string;
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.entities.GetLocationsRequestFormat;
}
