// This file was auto-generated by Fern from our API Definition.

/** Target device type. */
export const ScreenshotScansRequestResolution = {
    Desktop: "desktop",
    Mobile: "mobile",
    Tablet: "tablet",
} as const;
export type ScreenshotScansRequestResolution =
    (typeof ScreenshotScansRequestResolution)[keyof typeof ScreenshotScansRequestResolution];
