// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         service_token_id: "service_token_id"
 *     }
 */
export interface RefreshServiceTokensRequest {
    /** Identifier. */
    account_id: string;
    /** UUID. */
    service_token_id: string;
}
