// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface GetPresetsResponse {
    /** Data returned by the operation */
    data: GetPresetsResponse.Data;
    /** Success status of the operation */
    success: boolean;
}

export namespace GetPresetsResponse {
    /**
     * Data returned by the operation
     */
    export interface Data extends CloudflareApi.RealtimekitPreset {
        /** Timestamp this preset was created at */
        created_at: string;
        /** ID of the preset */
        id: string;
        /** Timestamp this preset was last updated */
        updated_at: string;
    }
}
