// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         app_id: "app_id"
 *     }
 */
export interface CreateMeetingsRequest {
    /** The account identifier tag. */
    account_id: string;
    /** The app identifier tag. */
    app_id: string;
    ai_config?: CloudflareApi.RealtimekitAiConfig;
    /** Specifies if the meeting should start getting livestreamed on start. */
    live_stream_on_start?: boolean | null;
    /** If a meeting is set to persist_chat, meeting chat would remain for a week within the meeting space. */
    persist_chat?: boolean;
    /** Specifies if the meeting should start getting recorded as soon as someone joins the meeting. */
    record_on_start?: boolean | null;
    recording_config?: CloudflareApi.RealtimekitRecordingConfig;
    /** Time in seconds, for which a session remains active, after the last participant has left the meeting. */
    session_keep_alive_time_in_secs?: number;
    /** Automatically generate summary of meetings using transcripts. Requires Transcriptions to be enabled, and can be retrieved via Webhooks or summary API. */
    summarize_on_end?: boolean;
    /** Title of the meeting */
    title?: string | null;
    /** Automatically generate transcripts when the meeting ends. */
    transcribe_on_end?: boolean;
}
