// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353",
 *         report_id: "report_id",
 *         effective_before: "2009-11-10T23:00:00Z",
 *         effective_after: "2009-11-10T23:00:00Z"
 *     }
 */
export interface ListMitigationsRequest {
    /** Cloudflare Account ID */
    account_id: string;
    /** Abuse Report ID */
    report_id: string;
    /** Where in pagination to start listing abuse reports */
    page?: number;
    /** How many abuse reports per page to list */
    per_page?: number;
    /** A property to sort by, followed by the order */
    sort?: CloudflareApi.abuseReports.ListMitigationsRequestSort;
    /** Filter by the type of mitigation. This filter parameter can be specified multiple times to include multiple types of mitigations in the result set. */
    type?: CloudflareApi.AbuseReportsMitigationType;
    /** Returns mitigations that were dispatched before the given date */
    effective_before?: string;
    /** Returns mitigation that were dispatched after the given date */
    effective_after?: string;
    /** Filter by the status of the mitigation. */
    status?: CloudflareApi.AbuseReportsMitigationStatus;
    /** Filter by the type of entity the mitigation impacts. */
    entity_type?: CloudflareApi.AbuseReportsMitigatedEntityType;
}
