// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "46148281d8a93d002ef242d8b0d5f9f6",
 *         finding_id: "finding_id"
 *     }
 */
export interface GetFindingsRequest {
    /** Cloudflare account ID for the user making the request. */
    account_id: string;
    /**
     * The `id` of a finding, as returned in each item of the List posture findings response.
     * It is a base64-encoded identifier.
     */
    finding_id: string;
}
