// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface DeleteQueriesRequest {
    account_id: string;
    id?: string;
    tag?: string;
    scan?: boolean;
}
