// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         domains: [{
 *                 domain_name: "example.co.uk"
 *             }]
 *     }
 *
 * @example
 *     {
 *         account_id: "account_id",
 *         domains: [{
 *                 auth_code: "YXV0aF9jb2RlCg==",
 *                 domain_name: "example.com"
 *             }, {
 *                 domain_name: "example.uk"
 *             }, {
 *                 auth_code: "U2xlZXB5IEhvcnNlcwo=",
 *                 domain_name: "example.horse"
 *             }]
 *     }
 *
 * @example
 *     {
 *         account_id: "account_id",
 *         domains: [{
 *                 auth_code: "SSdtIGEgc2VjcmV0IDozCg==",
 *                 domain_name: "example.com"
 *             }]
 *     }
 */
export interface RegistrarApiDomainTransferCheckRequest {
    /** Cloudflare account ID. Required for all Registrar API operations. */
    account_id: string;
    /** List of domain objects to evaluate for transfer eligibility. */
    domains: CloudflareApi.RegistrarApiDomainTransferCheckRequestDomainsItem[];
}
