// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const BotsTopRequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type BotsTopRequestFormat = (typeof BotsTopRequestFormat)[keyof typeof BotsTopRequestFormat];
