// This file was auto-generated by Fern from our API Definition.

export interface CreateUploadResponse {
    /** A "completion" JWT which can be redeemed when creating a Worker version. */
    jwt?: string | undefined;
}
