// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         key_id: "key_id"
 *     }
 */
export interface GetKeysRequest {
    /** The account identifier tag. */
    account_id: string;
    /** A Cloudflare-generated unique identifier for a item. */
    key_id: string;
}
