// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         data_class_id: "data_class_id"
 *     }
 */
export interface DeleteDataClassesRequest {
    account_id: string;
    data_class_id: string;
}
