// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         hold_after: "2023-01-31T15:56:36Z"
 *     }
 */
export interface DeleteHoldsRequest {
    /** Zone ID */
    zone_id: string;
    /**
     * If `hold_after` is provided, the hold will be temporarily disabled,
     * then automatically re-enabled by the system at the time specified
     * in this RFC3339-formatted timestamp. Otherwise, the hold will be
     * disabled indefinitely. `hold_after` cannot be provided for CDN-only zones.
     */
    hold_after?: string;
}
