// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id"
 *     }
 */
export interface EditHoldsRequest {
    /** Zone ID */
    zone_id: string;
    /**
     * If `hold_after` is provided and future-dated, the hold will be temporarily disabled,
     * then automatically re-enabled by the system at the time specified
     * in this RFC3339-formatted timestamp. A past-dated `hold_after` value will have
     * no effect on an existing, enabled hold. Providing an empty string will set its value
     * to the current time. Providing `null` will disable the hold indefinitely.
     */
    hold_after?: string | null;
    /**
     * If `true`, the zone hold will extend to block any subdomain of the given zone, as well
     * as SSL4SaaS Custom Hostnames. For example, a zone hold on a zone with the hostname
     * 'example.com' and include_subdomains=true will block 'example.com',
     * 'staging.example.com', 'api.staging.example.com', etc.
     */
    include_subdomains?: boolean;
}
