// This file was auto-generated by Fern from our API Definition.

export const ListIssuesRequestOrderBy = {
    Id: "id",
    Service: "service",
    Title: "title",
    Type: "type",
    Status: "status",
    StatusUpdated: "statusUpdated",
    Count: "count",
    FirstObserved: "firstObserved",
    LastObserved: "lastObserved",
    Created: "created",
    Updated: "updated",
} as const;
export type ListIssuesRequestOrderBy = (typeof ListIssuesRequestOrderBy)[keyof typeof ListIssuesRequestOrderBy];
