// This file was auto-generated by Fern from our API Definition.

export const ListIssuesRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListIssuesRequestOrder = (typeof ListIssuesRequestOrder)[keyof typeof ListIssuesRequestOrder];
