// This file was auto-generated by Fern from our API Definition.

export const ListJobsRequestDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListJobsRequestDirection = (typeof ListJobsRequestDirection)[keyof typeof ListJobsRequestDirection];
