// This file was auto-generated by Fern from our API Definition.

export const PollFeedsRequestFeedId = {
    All: "all",
} as const;
export type PollFeedsRequestFeedId = (typeof PollFeedsRequestFeedId)[keyof typeof PollFeedsRequestFeedId];
