// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { AvailableAlertsClient } from "../resources/availableAlerts/client/Client.js";
import { DestinationsClient } from "../resources/destinations/client/Client.js";
import { HistoryClient } from "../resources/history/client/Client.js";
import { PoliciesClient } from "../resources/policies/client/Client.js";
import { SilencesClient } from "../resources/silences/client/Client.js";

export declare namespace AlertingClient {
    export type Options = BaseClientOptions;
}

export class AlertingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AlertingClient.Options>;
    protected _availableAlerts: AvailableAlertsClient | undefined;
    protected _history: HistoryClient | undefined;
    protected _policies: PoliciesClient | undefined;
    protected _silences: SilencesClient | undefined;
    protected _destinations: DestinationsClient | undefined;

    constructor(options: AlertingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get availableAlerts(): AvailableAlertsClient {
        return (this._availableAlerts ??= new AvailableAlertsClient(this._options));
    }

    public get history(): HistoryClient {
        return (this._history ??= new HistoryClient(this._options));
    }

    public get policies(): PoliciesClient {
        return (this._policies ??= new PoliciesClient(this._options));
    }

    public get silences(): SilencesClient {
        return (this._silences ??= new SilencesClient(this._options));
    }

    public get destinations(): DestinationsClient {
        return (this._destinations ??= new DestinationsClient(this._options));
    }
}
