// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { SqlClient } from "../resources/sql/client/Client.js";

export declare namespace AnalyticsEngineClient {
    export type Options = BaseClientOptions;
}

export class AnalyticsEngineClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AnalyticsEngineClient.Options>;
    protected _sql: SqlClient | undefined;

    constructor(options: AnalyticsEngineClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get sql(): SqlClient {
        return (this._sql ??= new SqlClient(this._options));
    }
}
