// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         project_name: "project_name",
 *         deployment_id: "deployment_id",
 *         tail_id: "tail_id"
 *     }
 */
export interface DeleteTailsRequest {
    /** Identifier. */
    account_id: string;
    /** Name of the project. */
    project_name: string;
    /** Identifier. */
    deployment_id: string;
    /** Identifier. */
    tail_id: string;
}
