// Generated from cloudflare/workers-sdk@93d72a577. Do not rename cases.
import { describe, it } from "vitest";

const groups = [
	{
		file: "agent-memory.test.ts",
		ancestors: ["agent-memory help"],
		status: "todo",
		names: [
			"should show help text when no arguments are passed",
			"should show help text for the namespace subcommand",
		],
	},
	{
		file: "agent-memory.test.ts",
		ancestors: ["agent-memory namespace commands"],
		status: "todo",
		names: [
			"should create a namespace",
			"should create a namespace and output JSON with --json",
			"should list namespaces as JSON with --json",
			"should get a namespace as JSON with --json",
			"should delete a namespace after confirmation",
			"should cancel deletion when confirmation is declined",
			"should delete a namespace without confirmation when --force is passed",
			"should throw a UserError when `get` hits a 404",
			"should throw a UserError when `delete` hits a 404",
			"should throw a UserError when `create` receives a 400 (invalid name)",
			"should throw a UserError when `create` receives a 409 (duplicate)",
		],
	},
	{
		file: "agent-memory.test.ts",
		ancestors: ["agent-memory namespace commands"],
		status: "skip",
		names: [
			"should list namespaces in a table",
			"should print a message when no namespaces exist",
			"should get a namespace in a table",
		],
	},
	{
		file: "api/startDevWorker/RemoteRuntimeController.test.ts",
		ancestors: ["RemoteRuntimeController", "stale bundle bail-out"],
		status: "skip",
		names: ["should skip stale bundles and only reload once for rapid updates"],
	},
	{
		file: "api/startDevWorker/RemoteRuntimeController.test.ts",
		ancestors: ["RemoteRuntimeController", "proactive token refresh"],
		status: "skip",
		names: [
			"should proactively refresh the token before expiry",
			"should cancel the proactive refresh timer on bundle start",
			"should cancel the proactive refresh timer on teardown",
		],
	},
	{
		file: "api/startDevWorker/RemoteRuntimeController.test.ts",
		ancestors: ["RemoteRuntimeController", "preview token refresh"],
		status: "skip",
		names: [
			"should handle missing state gracefully",
			"should call API with stored config/bundle when refreshing",
			"should emit reloadComplete event with fresh token when refreshing",
		],
	},
	{
		file: "api/startDevWorker/RemoteRuntimeController.test.ts",
		ancestors: ["RemoteRuntimeController", "authentication error handling"],
		status: "skip",
		names: [
			"should call handlePreviewSessionCreationError when createPreviewSession throws a code 10000 auth error",
			"should call handlePreviewSessionCreationError when createPreviewSession throws a code 9106 auth error",
			"should call handlePreviewSessionUploadError when createWorkerPreview throws a code 10000 auth error",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "happy paths"],
		status: "skip",
		names: [
			"parses all flags in --flag value form",
			"parses all flags in --flag=value form",
			"returns an empty object for no flags",
			"omits unset flags from the output",
			"accepts port 0 (OS-assigned)",
			"accepts port 65535 (max)",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "port validation"],
		status: "skip",
		names: [
			"rejects negative ports (--port=-1 form)",
			"rejects ports above 65535",
			"rejects fractional ports",
			"rejects non-numeric ports",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: [
			"cf-wrangler parseArgs",
			"rejected flags (allowNegative disabled)",
		],
		status: "skip",
		names: [
			"rejects --no-local with an unknown-flag error",
			"rejects --remote (whole-worker remote dev is out of scope)",
			"rejects other wrangler dev flags we don't support",
			"rejects --env (must use --mode)",
			"rejects --config (config comes from wrangler's discovery)",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "structural rejections"],
		status: "skip",
		names: ["rejects positional arguments", "rejects unknown flags"],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseArgs", "ArgParseError"],
		status: "skip",
		names: ["wraps node:util.parseArgs errors"],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseBuildArgs", "happy paths"],
		status: "skip",
		names: [
			"returns an empty object for no flags",
			"parses --mode",
			"parses --mode=value",
		],
	},
	{
		file: "cf-wrangler/args.test.ts",
		ancestors: ["cf-wrangler parseBuildArgs", "rejections"],
		status: "skip",
		names: [
			"rejects --env (must use --mode)",
			"rejects --config (config comes from wrangler's discovery)",
			"rejects unknown flags",
			"rejects positional arguments",
		],
	},
	{
		file: "cloudchamber/images.test.ts",
		ancestors: ["cloudchamber image"],
		status: "todo",
		names: [
			"should help",
			"should create an image registry (no interactivity)",
			"should create an image registry (no interactivity)",
			"should remove an image registry (no interactivity)",
			"should list registries (no interactivity)",
		],
	},
	{
		file: "cloudchamber/images.test.ts",
		ancestors: ["cloudchamber image list"],
		status: "todo",
		names: [
			"should help",
			"should list images",
			"should list images with a filter",
			"should filter out repos with no non-sha tags",
			"should list repos as valid json with json flag set",
			"should filter out repos with no non-sha tags in valid json output",
		],
	},
	{
		file: "cloudchamber/images.test.ts",
		ancestors: ["cloudchamber image delete"],
		status: "todo",
		names: [
			"should help",
			"should delete images",
			"should error when provided a repo without a tag",
		],
	},
	{
		file: "containers/images.test.ts",
		ancestors: ["containers images list"],
		status: "todo",
		names: ["should help"],
	},
	{
		file: "containers/images.test.ts",
		ancestors: ["containers images delete"],
		status: "todo",
		names: ["should help"],
	},
	{
		file: "d1/d1.test.ts",
		ancestors: ["d1"],
		status: "todo",
		names: [
			"should show help when no argument is passed",
			"should show help when an invalid argument is passed",
			"should show help when the time travel command is passed",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings"],
		status: "todo",
		names: [
			"should allow bindings with different names",
			"should error when bindings of different types have the same name",
			"should error when bindings of the same type have the same name",
			"should error correctly when bindings of the same and different types use the same name",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[wasm_modules]"],
		status: "skip",
		names: [
			"should be able to define wasm modules for service-worker format workers",
			"should error when defining wasm modules for modules format workers",
			"should resolve wasm modules relative to the wrangler.toml file",
			"should be able to import .wasm modules from service-worker format workers",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[text_blobs]"],
		status: "skip",
		names: [
			"should be able to define text blobs for service-worker format workers",
			"should error when defining text blobs for modules format workers",
			"should resolve text blobs relative to the wrangler.toml file",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[data_blobs]"],
		status: "skip",
		names: [
			"should be able to define data blobs for service-worker format workers",
			"should error when defining data blobs for modules format workers",
			"should resolve data blobs relative to the wrangler.toml file",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[vars]"],
		status: "todo",
		names: ["should support json bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[vars]"],
		status: "skip",
		names: [
			"should render config vars literally and --var as hidden",
			"should read vars passed as cli arguments",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[r2_buckets]"],
		status: "todo",
		names: ["should support r2 bucket bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[logfwdr]"],
		status: "todo",
		names: [
			"should support logfwdr bindings",
			"should error when logfwdr schemas are specified",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[durable_objects]"],
		status: "todo",
		names: [
			"should support durable object bindings",
			"should support durable object bindings to SQLite classes",
			"should support service-workers binding to external durable objects",
			"should support module workers implementing durable objects",
			"should support durable objects and D1",
			"should support durable objects and D1",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[durable_objects]"],
		status: "skip",
		names: [
			"should error when detecting a service-worker worker implementing durable objects",
			"should error when deploying service-worker worker with migrations",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[services]"],
		status: "todo",
		names: [
			"should support service bindings",
			"should support service bindings with entrypoints",
			"should support service bindings with props",
			"should support the internal and non-public facing cross_account_grant service binding field",
			"should strip the local-dev `dev` field from a typed service binding at deploy time",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[analytics_engine_datasets]"],
		status: "todo",
		names: ["should support analytics engine bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[dispatch_namespaces]"],
		status: "todo",
		names: [
			"should support bindings to a dispatch namespace",
			"should support dispatch namespace bindings with an outbound worker",
			"should support dispatch namespace bindings with parameterized outbounds",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[agent_memory]"],
		status: "todo",
		names: ["should support agent_memory bindings"],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[unsafe]", "[unsafe.bindings]"],
		status: "todo",
		names: [
			"should stringify object in unsafe metadata",
			"should warn if using unsafe bindings",
			"should warn if using unsafe bindings already handled by wrangler",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[unsafe]", "[unsafe.capnp]"],
		status: "skip",
		names: [
			"should accept a pre-compiled capnp schema",
			"should error when both pre-compiled and uncompiled-capnp schemas are used",
			"should error when the capnp compiler is not present, but is required",
			"should accept an uncompiled capnp schema",
		],
	},
	{
		file: "deploy/bindings.test.ts",
		ancestors: ["deploy", "bindings", "[unsafe]", "[unsafe.capnp]"],
		status: "todo",
		names: ["should error when no schemas are specified"],
	},
	{
		file: "deploy/exports-reconciliation.test.ts",
		ancestors: ["renderExportsReconciliationSuccess"],
		status: "todo",
		names: [
			"emits no output when nothing changed",
			"renders created / updated / deleted lists wrapped in blank lines",
			"renders renamed pairs with an arrow",
			"renders transferred and transfer_pending entries",
			"renders info entries dimly under an indented `Info:` heading and surfaces referencing_scripts",
			"renders warnings to stderr under an indented `Warnings:` heading",
			"renders the removable_entries one-liner indented under the block",
			"brackets the block with leading and trailing blank lines",
		],
	},
	{
		file: "deploy/exports-reconciliation.test.ts",
		ancestors: ["renderExportsReconciliationError"],
		status: "todo",
		names: [
			"formats per-class details with scenario, message, and optional fields",
		],
	},
	{
		file: "deploy/exports-reconciliation.test.ts",
		ancestors: ["isExportsReconciliationErrorDetails"],
		status: "todo",
		names: [
			"accepts a well-formed details array",
			"rejects non-array values",
			"rejects entries missing required fields",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: ["deploy", "workflows"],
		status: "todo",
		names: [
			"should deploy a workflow",
			"should deploy Artifacts event triggers after their target Workflows",
			"should clear event triggers with an empty array",
			"should reject event targets that are not defined by the Worker",
			"should prompt to create a workers.dev subdomain before deploying owned Workflows",
			"should deploy a workflow with limits",
			"should deploy a workflow with default_retention",
			"should deploy a workflow with concurrency",
			"should deploy a workflow with schedules",
			"should explain that cron-triggered workflows require a paid plan",
			"should update event triggers when an unrelated Workflow fails",
			"should deploy a workflow with schedules as an array of cron expressions",
			"should deploy a workflow with both limits and schedules",
			"should not call Workflow's API if the workflow binds to another script",
			"should error when deploying a workflow with limits that references an external script",
			"should error when deploying a workflow with concurrency that references an external script",
			"should error when deploying a workflow with schedules that references an external script",
			"should error when deploying a workflow with default_retention that references an external script",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: [
			"deploy",
			"workflows",
			"workflow script_name validation with environments",
		],
		status: "todo",
		names: [
			"should error when script_name matches top-level name but not env-suffixed name and limits are set",
			"should allow limits when script_name matches the env-suffixed name",
			"should deploy external script_name under env without limits",
			"should error when script_name matches top-level name but not env-suffixed name and schedules is set",
			"should allow schedules when script_name matches the env-suffixed name",
			"should deploy external script_name under env without schedules",
		],
	},
	{
		file: "deploy/workflows.test.ts",
		ancestors: ["deploy", "workflows", "workflow conflict detection"],
		status: "todo",
		names: [
			"should warn when deploying a workflow that belongs to a different worker",
			"should abort deploy when user declines the workflow conflict confirmation",
			"should not warn when workflow belongs to the same worker",
			"should not warn when workflow does not exist yet",
			"should warn about multiple conflicting workflows",
			"should skip workflow conflict check in non-interactive mode without --strict",
			"should abort deploy in non-interactive strict mode when workflow belongs to different worker",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "file presence"],
		status: "skip",
		names: [
			"throws a UserError when cloudflare.config.ts is missing",
			"loads cloudflare.config.ts alone (no wrangler.config.ts)",
			"loads both cloudflare.config.ts and wrangler.config.ts and merges them",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "ctx.mode propagation"],
		status: "skip",
		names: [
			"passes args.env into the function-form cloudflare.config.ts",
			"falls back to CLOUDFLARE_ENV when args.env is not provided",
			"uses undefined when neither args.env nor CLOUDFLARE_ENV is set",
			"passes ctx.mode into the function-form wrangler.config.ts",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "settings export"],
		status: "todo",
		names: [
			"threads accountId and complianceRegion from the settings export",
			"leaves settings undefined when there is no settings export",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "default worker selection"],
		status: "skip",
		names: [
			"consumes the default export and validates-then-ignores other workers",
			"still validates non-default worker exports",
			"throws when there is no default worker export",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "worker schema validation"],
		status: "skip",
		names: [
			"throws when cloudflare.config.ts has invalid types",
			"formats Zod errors as a bulleted list with dotted paths",
			"explains how to handle non-config exports",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "wrangler.config.ts schema validation"],
		status: "skip",
		names: [
			"throws when a Worker config field is used at the top level",
			"throws and lists supported keys for an unknown top-level field",
			"rejects wrong types for tooling fields",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "assets merging"],
		status: "skip",
		names: [
			"merges worker-side asset binding/handling with tooling-side directory",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "Email Routing"],
		status: "skip",
		names: ["loads email triggers as Wrangler addresses"],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "types.generate"],
		status: "skip",
		names: [
			"defaults to true when wrangler.config.ts is absent",
			"defaults to true when wrangler.config.ts is present but does not set it",
			"honors `dev.types.generate: false`",
			"honors `dev.types.includeRuntime: false`",
			"is not threaded into the merged rawConfig.dev",
		],
	},
	{
		file: "experimental-config/load.test.ts",
		ancestors: ["loadNewConfig", "dependencies"],
		status: "skip",
		names: ["is the union of dependencies from both files"],
	},
	{
		file: "logout.test.ts",
		ancestors: ["logout"],
		status: "skip",
		names: [
			"should clear a cached temporary preview account when not logged in via OAuth",
		],
	},
	{
		file: "logout.test.ts",
		ancestors: ["logout"],
		status: "todo",
		names: [
			"should clear the keyring entry, the encrypted file, and any plaintext TOML when keyring storage is active",
		],
	},
	{
		file: "pages/deployment-delete.test.ts",
		ancestors: ["pages deployment delete"],
		status: "todo",
		names: [
			"should delete a deployment with the given ID",
			"should error if no deployment ID is specified",
			"should not delete if confirmation refused",
			"should delete without asking if --force is provided",
			"should support -f alias for --force",
		],
	},
	{
		file: "pages/deployment-delete.test.ts",
		ancestors: ["pages deployment delete"],
		status: "skip",
		names: ["should prefer CLOUDFLARE_ACCOUNT_ID over cached account id"],
	},
	{
		file: "pages/project-validate.test.ts",
		ancestors: ["pages project validate"],
		status: "todo",
		names: [
			"should exit cleanly for a good directory",
			"should error for a large file",
			"should error for a large directory",
			"should succeed with custom fileCountLimit even when exceeding default limit",
			"should error with custom fileCountLimit when exceeding custom limit",
			"should use fileCountLimit from CF_PAGES_UPLOAD_JWT when set",
			"should error when file count exceeds limit from CF_PAGES_UPLOAD_JWT",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings — variable display"],
		status: "skip",
		names: [
			"shows config vars literally",
			"shows --var/--vars as (hidden)",
			"shows .dev.vars / secret file vars as (hidden)",
			"shows json vars literally",
			"handles all three sources together in one table",
			"truncates long config var values",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings — AI Search bindings"],
		status: "skip",
		names: [
			"shows AI Search namespace bindings",
			"shows AI Search instance bindings",
			"renders inherited AI Search namespace bindings as `(inherited)`",
			"shows Agent Memory bindings",
			"renders inherited Agent Memory bindings as `(inherited)`",
		],
	},
	{
		file: "print-bindings.test.ts",
		ancestors: ["printBindings -- Artifacts bindings"],
		status: "skip",
		names: ["shows Artifacts bindings"],
	},
	{
		file: "templates/__tests__/pages-dev-util.test.ts",
		ancestors: ["isRoutingRuleMatch"],
		status: "skip",
		names: [
			"should match rules referencing root level correctly",
			"should match include-all rules correctly",
			"should match `/*` suffix-ed rules correctly",
			"should match `/` suffix-ed rules correctly",
			"should match `*` suffix-ed rules correctly",
			"should match rules without wildcards correctly",
			"should throw an error if pathname or routing rule params are missing",
		],
	},
	{
		file: "utils/did-you-mean.test.ts",
		ancestors: ["getSuggestion"],
		status: "skip",
		names: [
			"should suggest the closest match for a typo",
			"should suggest 'deploy' for 'delpoy'",
			"should suggest 'dev' for 'dve'",
			"should return undefined for a completely unrelated input",
			"should be case-insensitive",
			"should return undefined when candidates list is empty",
			"should return exact match when input matches a candidate",
			"should respect custom maxDistance",
			"should work with Set input",
			"should not suggest short commands for unrelated short inputs",
			"should still suggest longer commands for short inputs when close enough",
		],
	},
	{
		file: "utils/did-you-mean.test.ts",
		ancestors: ["logDidYouMean"],
		status: "skip",
		names: [
			"should log a suggestion in a box when a close match exists",
			"should not log anything when no close match exists",
			"should include the full command prefix for subcommands",
			"should preserve trailing args after the typo",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances list", "date filtering"],
		status: "todo",
		names: [
			"sends date_start and date_end as UTC ISO 8601",
			"normalises a date-only value to a UTC timestamp",
			"expands a date-only end bound to cover the whole UTC day",
			"treats the same date for both bounds as that whole day",
			"treats an offset-less time as UTC regardless of host timezone",
			"honours an explicit UTC offset regardless of host timezone",
			"leaves an end bound with an explicit time exact",
			"omits date params when the flags are not provided",
			"combines a date filter with a status filter",
			"errors on an unparseable date",
			"errors on a non-ISO date that Date.parse would accept",
			"errors rather than silently shifting the window for 2026-02-30 (a day beyond the end of the month)",
			"errors rather than silently shifting the window for 2026-02-29 (Feb 29 in a non-leap year)",
			"errors rather than silently shifting the window for 2026-04-31 (April 31)",
			"accepts a real leap day",
			"converts a timestamp with a UTC offset",
			"errors when date-start is after date-end",
			"warns that no instances matched the filters",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances pause"],
		status: "todo",
		names: ["should get and pause the bar instance given a name"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances resume"],
		status: "todo",
		names: ["should get and resume the bar instance given a name"],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances terminate"],
		status: "todo",
		names: [
			"should get and terminate the bar instance given a name",
			"should pass rollback when requested",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances delete"],
		status: "todo",
		names: [
			"should delete multiple instances, including cron-generated IDs",
			"should report per-instance errors after logging deletions",
			"should read instance IDs from a JSON file",
			"should require at least one instance ID",
			"should reject an invalid IDs file",
			"should reject more than 100 combined instances",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "instances restart"],
		status: "todo",
		names: [
			"should get and restart the bar instance given a name",
			"should restart an instance from a specific step",
			"should require a step name when restart step options are provided",
			"should reject invalid restart step counts",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: ["wrangler workflows", "workflow binding validation"],
		status: "skip",
		names: [
			"should reject workflow binding with name with invalid characters",
			"should reject workflow binding with name with invalid characters",
			"should reject workflow binding with name with invalid characters",
			"should reject workflow binding with name with invalid characters",
			"should accept workflow binding with valid concurrency",
			"should accept workflow binding with empty concurrency object",
			"should accept workflow binding with concurrency.limit at boundary value 1",
			"should reject workflow binding with concurrency.limit of 0",
			"should reject workflow binding with non-integer concurrency.limit",
			"should reject workflow binding with negative concurrency.limit",
			"should reject workflow binding with non-object concurrency",
			"should reject workflow binding with array concurrency",
			"should warn on unexpected fields in workflow binding concurrency",
		],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances list --local",
		],
		status: "todo",
		names: ["sends the same normalised date bounds as the remote path"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances terminate --local",
		],
		status: "todo",
		names: ["should pass rollback in local dev session"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances delete --local",
		],
		status: "todo",
		names: ["should resolve latest once before local deletion"],
	},
	{
		file: "workflows.test.ts",
		ancestors: [
			"wrangler workflows",
			"local",
			"workflows instances restart --local",
		],
		status: "todo",
		names: [
			"should restart an instance from a specific step in local dev session",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
