// Generated from cloudflare/workers-sdk@93d72a577. Do not rename cases.
import { describe, it } from "vitest";

const groups = [
	{
		file: "api/startDevWorker/MultiworkerRuntimeController.test.ts",
		ancestors: ["MultiworkerRuntimeController", "stale bundle bail-out"],
		status: "skip",
		names: [
			"should not bail out when different workers submit bundles",
			"supports ratelimit bindings on secondary workers",
			"should skip stale bundles for the same worker during rapid updates",
		],
	},
	{
		file: "case-insensitive-env.test.ts",
		ancestors: ["caseInsensitiveEnv"],
		status: "skip",
		names: [
			"resolves get/has/delete case-insensitively",
			"does not leak a stale differently-cased key when a value is overridden",
			"removes the tracked property when deleted under a different casing",
		],
	},
	{
		file: "cloudchamber/curl.test.ts",
		ancestors: ["cloudchamber curl"],
		status: "skip",
		names: [
			"should help",
			"can send data with -d/--data",
			"supports deprecated -D flag",
			"should set headers",
			"should preserve colons in header values",
			"should error for a header without a colon",
			"should error for a header without a name",
			"works",
			"should give a response with headers and request-id when verbose flag is set",
			"includes headers and request-id in JSON when used with --silent and --verbose",
			"should catch and report errors",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["readConfig() upgrade hint"],
		status: "skip",
		names: [
			"should not show an upgrade hint when unexpected fields are found but no update is available",
			"should show an upgrade hint when unexpected fields are found and an update is available",
			"should not show an upgrade hint when warnings are unrelated to unexpected fields",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["readConfig()"],
		status: "skip",
		names: [
			"should not error if a python entrypoint is used with the right compatibility_flag",
			"should error if a python entrypoint is used without the right compatibility_flag",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["experimental_readRawConfig()", "with json config files"],
		status: "skip",
		names: [
			"should find a json config file given a specific path",
			"should find a config file given a specific script",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["experimental_readRawConfig()", "with jsonc config files"],
		status: "skip",
		names: [
			"should find a jsonc config file given a specific path",
			"should find a config file given a specific script",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["experimental_readRawConfig()", "with toml config files"],
		status: "skip",
		names: [
			"should find a toml config file given a specific path",
			"should find a config file given a specific script",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["BOM (Byte Order Marker) handling"],
		status: "skip",
		names: [
			"should remove UTF-8 BOM from TOML config files",
			"should remove UTF-8 BOM from JSON config files",
			"should error on UTF-16 BE BOM",
			"should error on UTF-16 LE BOM",
			"should error on UTF-32 BE BOM",
			"should error on UTF-32 LE BOM",
			"should handle files without BOM normally",
		],
	},
	{
		file: "config/configuration.test.ts",
		ancestors: ["readConfig() custom_domain inheritance warning"],
		status: "skip",
		names: [
			"should warn when a named env inherits custom_domain routes from the top-level config",
			"should not warn when the env explicitly overrides routes",
			"should not warn for the top-level env itself",
		],
	},
	{
		file: "d1/convert-timestamp-to-iso.test.ts",
		ancestors: ["convertTimestampToISO"],
		status: "skip",
		names: [
			"should reject invalid date strings",
			"should convert a JS timestamp to an ISO string",
			"should automagically convert a unix timestamp to an ISO string",
			"should reject unix timestamps older than 30 days",
			"should reject JS timestamps from the future",
			"should return an ISO string when provided an ISO string",
			"should reject ISO strings older than 30 days",
			"should reject ISO strings from the future",
		],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["deploy", "assets"],
		status: "skip",
		names: [
			"should use the directory specified in the CLI over wrangler.toml",
			"should use the directory specified in the CLI and allow the directory to be missing in the configuration",
			"should error if config.site and config.assets are used together",
			"should error if --assets and config.site are used together",
			"should error if directory specified by flag --assets does not exist in non-interactive mode",
			"should error if the directory path specified by the assets config is undefined",
			"should error if the directory path specified by the assets config is an empty string",
			"should error if directory specified by config assets does not exist",
			"should error if path specified by flag --assets is a file, not a directory",
			"should error if path specified by config assets.directory is a file, not a directory",
			"should resolve assets directory relative to wrangler.toml if using config",
			"should resolve assets directory relative to cwd if using cli",
			"should send bulk asset upload stats with deploy metrics",
		],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["deploy", "assets"],
		status: "todo",
		names: [
			"should error if an ASSET binding is provided without a user Worker",
			"should warn when using smart placement with Worker first",
			"should warn if run_worker_first=true but no binding is provided",
			"should error if run_worker_first is true and no user Worker is provided",
			"should attach an 'application/null' content-type header when uploading files with an unknown extension",
			"should be able to upload files with special characters in filepaths",
			"should ignore assets that match patterns in an .assetsignore file in the root of the assets directory",
			"should error if it is going to upload a _worker.js file as an asset",
			"should error if it is going to upload a _worker.js directory as an asset",
			"should not error if it is going to upload a _worker.js file as an asset and there is an .assetsignore file",
			"should not error if it is going to upload a _worker.js file that is not at the root of the asset directory",
			"should error on --dry-run if it is going to upload a _worker.js file as an asset",
			"should upload _redirects and _headers",
			"should upload an asset manifest of the files in the directory specified by --assets",
			"should upload an asset manifest of the files in the directory specified by [assets] config",
			"should upload assets in the requested buckets",
			"should upload each asset individually with raw bytes when wrangler_single_asset_uploads is true",
			"should be able to upload a user worker with ASSETS binding and config",
			"run_worker_first correctly overrides default if set to true",
			"uploads run_worker_first=true when provided in config",
			"uploads run_worker_first=[rules] when provided in config",
			"run_worker_first omitted when not provided in config",
			"should be able to upload an asset-only project",
			"should not provision bindings for an asset-only project",
			"should be able to upload to a WfP script",
			"should error when assets upload session response is null",
			"should retry asset uploads on failure for legacy upload",
			"should retry asset uploads on failure for edge KV upload",
		],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: [
			"deploy",
			"assets",
			"when 'wrangler_single_asset_uploads is miss…'",
		],
		status: "todo",
		names: ["should use legacy base64 bucket upload"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: [
			"deploy",
			"assets",
			"when 'wrangler_single_asset_uploads is false'",
		],
		status: "todo",
		names: ["should use legacy base64 bucket upload"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: [
			"deploy",
			"assets",
			"when 'the upload token cannot be decoded'",
		],
		status: "todo",
		names: ["should use legacy base64 bucket upload"],
	},
	{
		file: "deploy/assets.test.ts",
		ancestors: ["getEdgeKvUploadConcurrency"],
		status: "skip",
		names: [
			"returns value from JWT claim",
			"returns default when claim is missing",
			"returns default when JWT is undecodable",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: ["deploy", "entry-points"],
		status: "skip",
		names: [
			"should be able to use `index` with no extension as the entry-point (esm)",
			"should be able to use `index` with no extension as the entry-point (sw)",
			"should be able to use the `main` config as the entry-point for ESM sources",
			"should use `main` relative to the wrangler.toml not cwd",
			"should be able to transpile TypeScript (esm)",
			"should be able to transpile TypeScript (sw)",
			"should add referenced text modules into the form upload",
			"should allow cloudflare module import",
			"should be able to transpile entry-points in sub-directories (esm)",
			"should not trigger autoconfig on `wrangler deploy <script>`",
			"should preserve exports on a module format worker",
			"should not preserve exports on a service-worker format worker",
			"should be able to transpile entry-points in sub-directories (sw)",
			'should error if a site definition doesn\'t have a "bucket" field',
			"should warn if there is a `site.entry-point` configuration",
			"should resolve site.entry-point relative to wrangler.toml",
			"should error if both main and site.entry-point are specified",
			"should error if there is no entry-point specified",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: [
			"deploy",
			"entry-points",
			"should source map validation errors",
		],
		status: "skip",
		names: [
			"with TypeScript source file",
			"with additional modules",
			"with inline source map",
		],
	},
	{
		file: "deploy/entry-points.test.ts",
		ancestors: [
			"deploy",
			"entry-points",
			"should interactively handle misconfigured asset-only deployments",
		],
		status: "skip",
		names: [
			"should handle interactive `wrangler deploy <directory>` flows without triggering autoconfig",
			"should handle `wrangler deploy --assets` without name or compat date without triggering autoconfig",
			"should suggest 'my-project' if the default name from the cwd is invalid",
			"should error when --script points to a directory",
			"should error when --script points to a directory even when positional path is also provided",
			"should error when --script points to a directory even when positional path is a file",
			"does not write out a wrangler config file if the user says no",
			"includes script path in suggestion when deprecated --script option is used",
			"includes --assets in suggestion when positional path is a file and --assets is separate",
		],
	},
	{
		file: "deploy/secrets.test.ts",
		ancestors: ["deploy secrets", "--secrets-file"],
		status: "todo",
		names: [
			"should upload secrets from a JSON file alongside the worker",
			"should upload secrets from a .env file alongside the worker",
			"should set keepSecrets to inherit non-provided secrets when providing secrets file",
			"should fail when secrets file does not exist",
			"should fail when secrets file contains invalid JSON",
		],
	},
	{
		file: "deploy/secrets.test.ts",
		ancestors: ["deploy secrets", "secrets.required"],
		status: "todo",
		names: [
			"should add inherit bindings for required secrets",
			"should error when required secrets are missing from the deployed Worker",
			"should error before uploading when the Worker does not exist",
		],
	},
	{
		file: "deploy/secrets.test.ts",
		ancestors: ["deploy secrets", "--secrets-file with secrets.required"],
		status: "todo",
		names: [
			"should deploy when --secrets-file satisfies all required secrets even if the Worker does not exist",
			"should error listing only the secrets not provided by --secrets-file when the Worker does not exist",
			"should use inherit bindings only for required secrets not provided by --secrets-file",
		],
	},
	{
		file: "experimental-commands-api.test.ts",
		ancestors: ["experimental_getWranglerCommands"],
		status: "skip",
		names: [
			"returns global flags",
			"returns command tree structure",
			"includes expected commands with metadata",
			"includes nested commands",
			"includes command arguments and metadata",
			"includes namespace commands",
			"preserves command metadata properties",
			"commands opting in to `--temporary` match the expected set",
		],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "put"],
		status: "todo",
		names: [
			"should error if no key is provided",
			"should error if no binding nor namespace is provided",
			"should error if both binding and namespace is provided",
			"should error if a given binding name is not in the configured kv namespaces",
		],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "list", "cursor - undefined"],
		status: "todo",
		names: ["should make multiple requests for paginated results"],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "list", "cursor - null"],
		status: "todo",
		names: ["should make multiple requests for paginated results"],
	},
	{
		file: "kv/key.test.ts",
		ancestors: ["kv", "key", "list", "cursor - "],
		status: "todo",
		names: ["should make multiple requests for paginated results"],
	},
	{
		file: "pages/delegate-to-workers.test.ts",
		ancestors: ["maybeDelegatePagesToWorkers"],
		status: "skip",
		names: [
			"does not delegate (or emit telemetry) when not run by an agent",
			"does not delegate (or emit telemetry) when the account already has Pages projects (deploy)",
			"does not delegate (or emit telemetry) when the account already has Pages projects (create)",
			"delegates when the account has no Pages projects",
			"skips delegation (without emitting telemetry) when the account Pages projects lookup fails",
			"does not query account Pages projects when a cheaper, local check already skips",
			"does not delegate when project has a functions directory",
			"does not delegate when project has a _worker.js",
			"does not delegate when project has a _routes.json",
			"does not delegate when the assets directory has unsupported markers",
			"delegates when project has a supported _redirects file",
			"delegates when the assets directory has a supported _redirects file",
			"delegates when project has a supported _headers file",
			"delegates when the assets directory has a supported _headers file",
			"does not delegate when Pages-only args are present",
			"delegates a brand-new static deploy to Workers",
			"carries the project name across to the Workers deploy",
			"does not forward --assets, so autoconfig stays enabled to configure the deploy",
			"carries name and compatibility settings across on create",
			"does not delegate when --force is set, records the opt-out, and flags forcedOptOut",
			"emits a one-time, deploy-specific --force notice to stdout",
			"emits a one-time, create-specific --force notice to stdout",
			"records failure and gives explicit, loop-safe --force guidance",
			"gives create-specific --force guidance when a create delegation fails",
		],
	},
	{
		file: "pages/project-list.test.ts",
		ancestors: ["pages project list"],
		status: "todo",
		names: [
			"should make request to list projects",
			"should make multiple requests for paginated results",
			"should error before making a request when CLOUDFLARE_ACCOUNT_ID contains characters that are invalid in a URL",
		],
	},
	{
		file: "pages/project-list.test.ts",
		ancestors: ["pages project list"],
		status: "skip",
		names: [
			"should override cached accountId with CLOUDFLARE_ACCOUNT_ID environmental variable if provided",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getBranchName"],
		status: "skip",
		names: [
			"should prefer the Workers CI branch env var",
			"should use the GitHub Actions branch env vars",
			"should use the GitLab branch env var",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "previewContainerAppName"],
		status: "skip",
		names: [
			"should join worker name, preview slug, and class name with underscores",
			"should normalise 'a worker name that starts with a digit' and mark it with a digest",
			"should normalise 'consecutive dashes in a worker name' and mark it with a digest",
			"should normalise 'a character that no application name …' and mark it with a digest",
			"should keep apart worker names that normalise onto one another",
			"should cap the name at the length the API allows",
			"should keep apart worker names that differ only past that length",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getRepositoryUrl"],
		status: "skip",
		names: [
			"should use GitHub Actions repository env vars",
			"should use GitHub Enterprise server URL",
			"should use GitLab project URL",
			"should use and normalize git remote origin URL when in CI",
			"should not shell out to the local git remote outside CI",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getPullRequestMetadata"],
		status: "skip",
		names: [
			"should use direct pull request URL env vars",
			"should use GitHub event pull request metadata",
			"should not fail when the GitHub event pull request has no title",
			"should not recover a title from the GITHUB_REF fallback",
			"should use GitLab merge request metadata",
			"should treat a blank title the same as a missing one",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "getCommitSha"],
		status: "skip",
		names: [
			"should use the GitHub Actions commit SHA",
			"should use the GitLab CI commit SHA",
			"should use the CircleCI commit SHA",
			"should use the generic COMMIT_SHA fallback",
			"should prefer GitHub Actions over other providers",
			"should return undefined when no commit SHA env var is set",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "extractConfigBindings"],
		status: "skip",
		names: [
			"should extract vars as plain_text bindings",
			"should extract non-string vars as json bindings so the runtime preserves the native shape",
			"should extract kv_namespaces",
			"should extract d1_databases",
			"should extract r2_buckets",
			"should extract services",
			"should extract durable_objects bindings",
			"should return empty object when no previews block",
			"should extract multiple binding types",
			"should extract additional supported preview binding types",
			"should pass cross_account_grant on service bindings",
			"should fold unsafe.bindings into the previews env",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview command"],
		status: "todo",
		names: [
			"should create a new preview with defaults applied",
			"should output preview and deployment JSON with --json",
			"should show existing preview status for existing preview",
			"should note when URL arrays are empty",
			"should use the URL-encoded preview name as the Preview identifier in path params",
			"should work without preview_defaults",
			"should show compact success output when observability is configured",
			"should include previews tail_consumers in the preview resource request",
			"should include compatibility_date in the deployment request",
			"should pass ignore_base_config query param when creating a Preview with --ignore-base-config",
			"should include assets payload for deployment when assets are configured",
			"should include the assets binding in env using the configured binding name",
			"should include source maps in deployment modules when upload_source_maps is enabled",
			"should use previews durable_objects for export validation",
			"should use previews workflows for export validation",
			"should include migrations in the deployment request",
			"should handle first preview deployment when latest deployment is missing",
			"should include deployment annotations from metadata and args",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
		],
		status: "todo",
		names: [
			"creates the parent Worker with Preview URLs enabled, then creates the Preview",
			"aborts without creating the parent Worker when the user declines",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'defaults Preview URLs to workers.dev'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'defaults Preview URLs to explicit wor…'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'respects enabled Preview URLs'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
			"'respects disabled Preview URLs'",
		],
		status: "skip",
		names: ["resolves subdomain settings without applying production triggers"],
	},
	{
		file: "preview.test.ts",
		ancestors: [
			"wrangler preview",
			"preview command",
			"when the parent Worker does not exist",
		],
		status: "skip",
		names: ["keeps JSON output parseable when creating the parent Worker"],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview command"],
		status: "skip",
		names: [
			"should warn about top-level bindings missing from preview settings",
			"should not warn about top-level bindings when they are present in local previews config",
			"should use flagship bindings from local previews config",
			"should not warn about inheritable top-level bindings missing from previews",
			"should build correctly when using a redirected config",
			"should include dist/server chunks when using a vite no-bundle redirected config",
			"should include containers in deployment metadata and create a preview-scoped container application",
			"should name applications from the resolved worker name",
			"should take container observability from 'the top-level config when the preview…'",
			"should take container observability from 'the preview config, which wins over t…'",
			"should deploy containers for a Durable Object declared by 'migrations' with no preview binding",
			"should deploy containers for a Durable Object declared by 'exports' with no preview binding",
			"should keep --json output parseable while deploying containers",
			"should resolve a container whose class is also bound cross-script earlier in the config",
			"should not propagate top-level containers into the preview deployment",
			"should omit containers from deployment when none are configured",
			"should exclude containers whose DO binding has script_name set",
			"should fail before creating the preview deployment when a container's class_name matches no Durable Object class",
			"should fail before creating the preview deployment when a container omits class_name",
			"should throw a UserError when no Durable Object namespace can be found for a container's class",
			"should fail before creating the preview deployment when a container's image belongs to a different account",
			"should fail before creating the preview deployment when Docker cannot be launched for a container built from a Dockerfile",
			"should fail before creating the preview deployment when the API token lacks the containers scope",
			"should warn that the preview is live when its containers fail to deploy, and still surface the error",
			"should use previews.define for worker bundling",
			"should fall back to HEAD commit metadata for annotations in CI",
			"should inherit top-level previews config into an environment when env.previews is absent",
			"should use env-specific previews config instead of top-level previews config",
			"should include previews.cache in deployment request, falling back to top-level cache",
			"should prefer previews.cache over top-level cache in deployment request",
			"should respect env-specific worker name for preview and deployment requests",
			"should fail before making API calls when env-specific previews config is invalid",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview delete"],
		status: "todo",
		names: [
			"should delete a preview with --skip-confirmation",
			"should proceed with deletion in non-interactive mode (CI fallback)",
			"should use --worker-name to target the correct worker",
			"should URL-encode the preview name when deleting",
		],
	},
	{
		file: "preview.test.ts",
		ancestors: ["wrangler preview", "preview delete"],
		status: "skip",
		names: ["should respect env-specific worker name when deleting"],
	},
	{
		file: "startup-profiling.test.ts",
		ancestors: ["summarizeStartupProfile"],
		status: "skip",
		names: ["separates active, garbage collection, and idle samples"],
	},
	{
		file: "utils/debounce.test.ts",
		ancestors: ["debounce"],
		status: "skip",
		names: [
			"invokes the function once after the delay has elapsed",
			"collapses a burst of calls into a single invocation",
			"starts a new delay for calls made after an invocation",
			"cancel() discards a pending invocation",
			"cancel() does not prevent later invocations",
			"cancel() is a no-op when nothing is pending",
		],
	},
	{
		file: "vpc.test.ts",
		ancestors: ["vpc service commands"],
		status: "todo",
		names: [
			"should handle creating a service with hostname and resolver network",
			"should handle updating a service",
			"should handle creating a service and display without resolver_ips",
			"should handle creating a TCP service with IPv4",
			"should handle creating a TCP service with hostname",
			"should handle updating a TCP service",
			"should handle listing TCP services with port in table",
			"should handle creating a TCP service with --app-protocol postgresql",
			"should handle creating a TCP service with --app-protocol mysql",
			"should handle updating a TCP service with --app-protocol",
			"should handle creating a TCP service with --cert-verification-mode verify_ca",
			"should handle creating an HTTP service with --cert-verification-mode disabled",
			"should handle updating a service with --cert-verification-mode",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
