// Generated from cloudflare/workers-sdk@93d72a577. Do not rename cases.
import { describe, it } from "vitest";

const groups = [
	{
		file: "ai.test.ts",
		ancestors: ["ai help"],
		status: "todo",
		names: [
			"should show models help",
			"should show schema help without model list flags",
		],
	},
	{
		file: "ai.test.ts",
		ancestors: ["ai commands"],
		status: "todo",
		names: [
			"should handle legacy model list",
			"should query model list with filters",
			"should handle model schema",
		],
	},
	{
		file: "assets.test.ts",
		ancestors: [
			"getAssetsOptions",
			"validateDirectoryExistence: true (default — deploy path)",
		],
		status: "skip",
		names: [
			"throws NonExistentAssetsDirError when the --assets directory does not exist",
			"throws with a message referencing the CLI flag when --assets is used",
			"throws with a message referencing the config file when assets.directory is used",
			"throws NonDirectoryAssetsDirError when the path points to a file, not a directory",
		],
	},
	{
		file: "assets.test.ts",
		ancestors: [
			"getAssetsOptions",
			"validateDirectoryExistence: false (getPlatformProxy / unstable_getMiniflareWorkerOptions path)",
		],
		status: "skip",
		names: [
			"does NOT throw when the assets directory does not exist",
			"returns a valid AssetsOptions object even when the directory is absent",
			"still throws NonDirectoryAssetsDirError when the path points to a file",
			"returns correct options when the directory exists and has files",
			"works with assets from config rather than the CLI flag",
			"returns undefined when no assets are configured",
		],
	},
	{
		file: "cfetch-utils.test.ts",
		ancestors: ["throwFetchError"],
		status: "todo",
		names: [
			"should include api errors, messages and documentation_url in error",
			"nested",
			"should include api errors without messages",
		],
	},
	{
		file: "cloudchamber/list.test.ts",
		ancestors: ["cloudchamber list"],
		status: "todo",
		names: ["should help", "should list deployments (json)"],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "DNS errors"],
		status: "todo",
		names: [
			"should return 'DNSError' for ENOTFOUND to api.cloudflare.com",
			"should return 'DNSError' for ENOTFOUND to dash.cloudflare.com",
			"should return 'DNSError' for DNS errors in error cause",
			"should NOT return 'DNSError' for non-Cloudflare hostnames",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Connection timeout errors"],
		status: "todo",
		names: [
			"should return 'ConnectionTimeout' for api.cloudflare.com timeouts",
			"should return 'ConnectionTimeout' for dash.cloudflare.com timeouts",
			"should return 'ConnectionTimeout' for timeout errors in error cause",
			"should return 'ConnectionTimeout' when Cloudflare URL is in parent message",
			"should NOT return 'ConnectionTimeout' for non-Cloudflare URLs",
			"should NOT return 'ConnectionTimeout' for user's dev server timeouts",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Permission errors"],
		status: "todo",
		names: [
			"should return 'PermissionError' for EPERM errors",
			"should return 'PermissionError' for EACCES errors",
			"should return 'PermissionError' for EPERM errors without path",
			"should return 'PermissionError' for EPERM errors in error cause",
			"should NOT return 'PermissionError' for non-EPERM/EACCES errors",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "File not found errors"],
		status: "todo",
		names: [
			"should return 'FileNotFoundError' for ENOENT errors with path",
			"should return 'FileNotFoundError' for ENOENT errors without path",
			"should return 'FileNotFoundError' for ENOENT errors in error cause",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Authentication errors"],
		status: "todo",
		names: [
			"should return 'AuthenticationError' for code 10000 (expired/revoked token)",
			"should return 'AuthenticationError' for code 9106 (invalid token)",
			"should NOT return 'AuthenticationError' for other API errors",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["getErrorType", "Fallback behavior"],
		status: "todo",
		names: [
			"should return constructor name for unknown Error types",
			"should return undefined for non-Error values",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["isAuthenticationError"],
		status: "todo",
		names: [
			"should return true for APIError with code 10000",
			"should return true for APIError with code 9106",
			"should return true for ParseError with code 10000",
			"should return false for APIError with a non-auth code",
			"should return false for APIError with no code",
			"should return false for a plain Error",
			"should return false for non-Error values",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "SSL/TLS certificate errors"],
		status: "todo",
		names: [
			"should log a warning for self-signed certificate errors",
			"should log a warning for unable to verify first certificate errors",
			"should log a warning for unable to get local issuer certificate errors",
			"should log a warning when certificate error is in error cause",
			"should log a warning when certificate error is part of a longer message",
			"should not log a warning for unrelated errors",
			"should still log the original error after the warning",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "Cloudflare API connection timeout errors"],
		status: "todo",
		names: [
			"should show user-friendly message for api.cloudflare.com timeouts",
			"should show user-friendly message for dash.cloudflare.com timeouts",
			"should handle timeout errors in error cause",
			"should handle timeout when Cloudflare URL is in parent message",
			"should NOT show timeout message for non-Cloudflare URLs",
			"should NOT show timeout message for user's dev server timeouts",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "Permission errors (EPERM, EACCES)"],
		status: "todo",
		names: [
			"should show user-friendly message for EPERM errors with path",
			"should show user-friendly message for EACCES errors with path",
			"should show error message when path is not available",
			"should handle EPERM errors in error cause",
			"should NOT treat non-EPERM errors as permission errors",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "DNS resolution errors (ENOTFOUND)"],
		status: "todo",
		names: [
			"should show user-friendly message for ENOTFOUND to api.cloudflare.com",
			"should show user-friendly message for ENOTFOUND to dash.cloudflare.com",
			"should handle DNS errors in error cause",
			"should NOT show DNS error for non-Cloudflare hostnames",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "File not found errors (ENOENT)"],
		status: "todo",
		names: [
			"should show user-friendly message for ENOENT errors with path",
			"should show error message when path is not available",
			"should handle ENOENT errors in error cause",
		],
	},
	{
		file: "core/handle-errors.test.ts",
		ancestors: ["handleError", "Cloudflare SDK errors"],
		status: "todo",
		names: [
			"should surface the Retry-After header from a 429 SDK error",
			"should not add a Retry-After note when the header is absent",
		],
	},
	{
		file: "d1/info.test.ts",
		ancestors: ["info"],
		status: "skip",
		names: ["should not display version as valid json when not alpha"],
	},
	{
		file: "deploy/check-workflow-conflicts.test.ts",
		ancestors: ["checkWorkflowConflicts"],
		status: "todo",
		names: [
			"should return { hasConflicts: false } when there are no workflows in config",
			"should return { hasConflicts: false } when workflows is undefined",
			"should return { hasConflicts: false } when workflow does not exist yet",
			"should return { hasConflicts: false } when workflow belongs to same worker",
			"should detect conflict when workflow belongs to different worker",
			"should detect multiple conflicts",
			"should skip workflows that bind to another script",
			"should only flag workflows being deployed by this script",
			"should generate correct message for single conflict",
		],
	},
	{
		file: "deploy/get-remote-config-diff.test.ts",
		ancestors: ["getRemoteConfigsDiff"],
		status: "skip",
		names: [
			"should handle a very simple diffing scenario (no diffs, random order)",
			"should handle a very simple diffing scenario where there is only an addition to an array (specifically in `kv_namespaces`)",
			"should handle a very simple diffing scenario (some diffs, random order)",
			"should handle a diffing scenario with only additions",
			"should handle a diffing scenario with only deletions",
			"should handle a diffing scenario with modifications and removals",
			"should ignore local-only configs such as `dev` and `build`",
			"should ignore the `remote` field of bindings during the diffing process (since remote bindings are a local-only concept)",
			"should ignore all fields from an assets binding besides the binding name (since remotely only that information is stored)",
			"should not show spurious diffs when binding arrays have same elements in different order",
		],
	},
	{
		file: "deploy/get-remote-config-diff.test.ts",
		ancestors: ["getRemoteConfigsDiff", "observability"],
		status: "skip",
		names: [
			"shouldn't present any diff when the local config is just { enabled: true } and the remote observability is enabled with its default values",
			"should treat a remote undefined equal to a remote { enabled: false }",
			"should treat a remote undefined equal to a remote { enabled: false, logs: { enabled: false } }",
			"should correctly show the diff of boolean when the remote is undefined and the local is { enabled: true }",
			"should correctly show the diff of boolean when the remote is undefined and the local is { logs: { enabled: false } }",
			"should correctly not show head_sampling_rate being added remotely",
			"should correctly not show logs.invocation_logs being added remotely",
		],
	},
	{
		file: "dev/dev-vars.test.ts",
		ancestors: ["getVarsForDev"],
		status: "skip",
		names: [
			"merges config vars with .dev.vars without secrets defined",
			"merges config vars with .dev.vars with secrets defined",
			"warns about missing required secrets",
			"falls back to .env files when CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV is not false",
			"overrides json-typed config vars",
			"handles undefined loadedSecrets gracefully (no dev var files)",
		],
	},
	{
		file: "friendly-validator-errors.test.ts",
		ancestors: ["helpIfErrorIsSizeOrScriptStartup"],
		status: "skip",
		names: [
			"cleanly reports a startup error even if bundle analysis fails",
			"reports size errors even if bundle analysis would fail",
			"includes profile information when bundle analysis succeeds",
		],
	},
	{
		file: "metrics/sanitization.test.ts",
		ancestors: ["sanitizeArgKeys"],
		status: "skip",
		names: ["should sanitize arg keys based on argv"],
	},
	{
		file: "metrics/sanitization.test.ts",
		ancestors: ["sanitizeArgValues"],
		status: "skip",
		names: ["should redact and allow arg values based on allowedArgs"],
	},
	{
		file: "metrics/sanitization.test.ts",
		ancestors: ["getAllowedArgs"],
		status: "skip",
		names: [
			"should return allowed args for a given command",
			"should allow more specific command rules to override less specific ones",
		],
	},
	{
		file: "metrics/sanitization.test.ts",
		ancestors: ["COMMAND_ARG_ALLOW_LIST"],
		status: "skip",
		names: [
			"should pass boolean flag values through the full sanitisation pipeline for any command",
		],
	},
	{
		file: "pages/functions-build.test.ts",
		ancestors: ["pages functions build"],
		status: "todo",
		names: [
			"should throw an error if no worker script and no Functions directory was found",
			"converts an invalid route in [hyphen-not-allowed].ts to FatalError",
			"converts an invalid route in [[hyphen-not-allowed]].ts to FatalError",
			"should build functions",
			"should include any external modules imported by functions in the output bundle",
			"should output a directory with --outdir",
			"should output a metafile when --metafile is set",
			"should build _worker.js",
			"should include all external modules imported by _worker.js in the output bundle, when bundling _worker.js",
			"should build _worker.js over /functions, if both are present",
			"should leave Node.js imports when the `nodejs_compat` compatibility flag is set",
			"should warn at Node.js imports when the `nodejs_compat` compatibility flag is not set",
			"should compile a _worker.js/ directory",
		],
	},
	{
		file: "pages/functions-build.test.ts",
		ancestors: ["functions build w/ config"],
		status: "todo",
		names: [
			"should include all config in the _worker.bundle metadata",
			"should ignore config with a non-pages config file",
			"should ignore config with a non-pages config file w/ invalid environment",
			"should ignore unparseable config file",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "put", "interactive"],
		status: "todo",
		names: [
			"should trim stdin secret value",
			"should create a secret",
			"should create a secret: preview",
			"should error with invalid env",
			"should error without a project name",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "put", "non-interactive"],
		status: "todo",
		names: [
			"should trim stdin secret value, from piped input",
			"should create a secret, from piped input",
			"should error if the piped input fails",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: [
			"wrangler pages secret",
			"put",
			"non-interactive",
			"with accountId",
		],
		status: "todo",
		names: [
			"should error if request for available accounts fails",
			"should error if a user has no account",
			"should error if a user has multiple accounts, and has not specified an account",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: [
			"wrangler pages secret",
			"put",
			"non-interactive",
			"with accountId",
		],
		status: "skip",
		names: ["should error if request for available memberships fails"],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "delete"],
		status: "todo",
		names: [
			"should delete a secret",
			"should delete a secret: preview",
			"should fail to delete with invalid env",
			"should error without a project name",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "list"],
		status: "todo",
		names: [
			"should list secrets",
			"should list secrets: preview",
			"should fail with invalid env",
			"should error without a project name",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "secret bulk"],
		status: "todo",
		names: [
			"should fail secret bulk w/ no pipe or JSON input",
			"should use secret bulk w/ pipe input",
			"should create secret bulk",
			"should create secret bulk w/ env file",
			"should create secret bulk: preview",
			"should count success and network failure on secret bulk",
			"throws a meaningful error",
		],
	},
	{
		file: "pages/secret.test.ts",
		ancestors: ["wrangler pages secret", "account id resolution"],
		status: "skip",
		names: ["should prefer CLOUDFLARE_ACCOUNT_ID over cached account id"],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "create"],
		status: "todo",
		names: [
			"should create a subscription for images source",
			"should create a subscription for an Artifacts account source",
			"should create a subscription for an Artifacts repository source",
			"should create a subscription for email.sending source",
			"should show error when zone-id is missing for email.sending source",
			"should show error when domain is missing for email.sending source",
		],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "list"],
		status: "skip",
		names: ["should show message when no subscriptions exist"],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "list"],
		status: "todo",
		names: ["should list subscriptions for a queue"],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "get"],
		status: "skip",
		names: [
			"should render the sending domain as the resource for email.sending source",
		],
	},
	{
		file: "queues/queues-subscription.test.ts",
		ancestors: ["queues subscription", "update"],
		status: "skip",
		names: ["should error when no fields provided"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["isValidIdentifier"],
		status: "skip",
		names: [
			"should return true for valid identifiers",
			"should return false for invalid identifiers",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["escapeTypeScriptString"],
		status: "skip",
		names: ["should escape special characters"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["constructTypeKey"],
		status: "skip",
		names: [
			"should return a valid type key",
			"should escape special characters in quoted keys",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["constructTSModuleGlob() should return a valid TS glob "],
		status: "skip",
		names: [
			"'*.wasm' -> undefined",
			"'*.txt' -> undefined",
			"'*/foo' -> undefined",
			"'*foo' -> undefined",
			"'file.foo' -> undefined",
			"'folder/file.foo' -> undefined",
			"'folder/*' -> undefined",
			"'folder/*' -> undefined",
			"'folder/*' -> undefined",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generateImportSpecifier"],
		status: "skip",
		names: ["should generate a relative import specifier"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["getEnvHeader"],
		status: "skip",
		names: [
			"should generate a header with the provided hash and command",
			"should include complex commands with flags",
			"should handle empty hash",
			"should use process.argv when command is not provided",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["toPascalCase"],
		status: "skip",
		names: [
			"should convert simple strings to PascalCase",
			"should convert kebab-case to PascalCase",
			"should convert snake_case to PascalCase",
			"should handle mixed separators",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["toEnvInterfaceName"],
		status: "skip",
		names: [
			"should add Env suffix to environment names",
			"should deduplicate Env suffix",
			"should handle kebab-case environment names",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["validateEnvInterfaceNames"],
		status: "skip",
		names: [
			"should not throw for valid, unique environment names",
			"should throw for reserved name Env",
			"should throw when two environment names convert to the same interface name",
			"should throw when names with different separators collide",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["throwMissingBindingError"],
		status: "skip",
		names: [
			"should throw a `UserError` for top-level bindings with array index",
			"should throw a `UserError` for environment bindings with array index",
			"should handle non-array bindings (index omitted)",
			"should handle undefined config path",
			"should handle different field names",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI"],
		status: "skip",
		names: [
			"should error when no config file is detected",
			"should error when a specified custom config file is missing",
			"should respect the top level -c|--config flag",
			"should log the interface type generated and declare modules",
			"should include stringified process.env types for vars, secrets, and json",
			"should handle multiple worker configs",
			"should resolve secondary worker types when env overrides the worker name",
			"should create a DTS file at the location that the command is executed from",
			"should create a DTS file at the location that the command is executed from",
			"should log the declare global type generated and declare modules",
			"should accept a toml file without an entrypoint and fallback to the standard modules declarations",
			"should not error if expected entrypoint is not found and assume module worker",
			"should include secret keys from .dev.vars",
			"should use explicit --env-file instead of .dev.vars when both exist",
			"should not report stale types when --env-file is used and .dev.vars exists (--check)",
			"should report types as up to date for multi-worker setup without re-passing -c flags (--check)",
			"should include secret keys from .env, if there is no .dev.vars",
			"should allow opting out of strict-vars",
			"should override vars with secrets",
			"should generate types from config `secrets.required`",
			"should ignore .dev.vars when config `secrets` is defined",
			"should ignore .env when config `secrets` is defined",
			"should generate types for per-env config `secrets`",
			"should not fall back to .dev.vars for envs without `secrets` when another env declares `secrets`",
			"should exclude .dev.vars keys when `secrets` is declared without `required`",
			"various different types of vars",
			"should generate types for VPC services bindings",
			"should generate types for VPC networks bindings",
			"should generate types for VPC networks bindings with network_id",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "when nothing was found"],
		status: "skip",
		names: [
			"should not create DTS file for service syntax workers if env only",
			"should create DTS file for service syntax workers with runtime types only",
			"should create a DTS file with an empty env interface for module syntax workers",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: [
			"generate types - CLI",
			"vars present in multiple environments",
		],
		status: "skip",
		names: [
			"should produce string and union types for variables (default)",
			"should produce non-strict types for variables (with --strict-vars=false)",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: [
			"generate types - CLI",
			"bindings present in multiple environments",
		],
		status: "skip",
		names: [
			"should collect bindings from all environments when no --env is specified",
			"should only collect bindings from the specified environment when --env is used",
			"should deduplicate bindings with the same name across environments",
			"should produce union types when binding name has different types across environments",
			"should error when a binding is missing its binding name in an environment",
			"should error when a binding is missing its binding name at top-level",
			"should collect vars only from specified environment with --env",
			"should mark bindings as optional if not present in all environments",
			"should not include top-level bindings in per-environment interfaces",
			"should include secrets in per-environment interfaces since they are inherited",
			"should mark inheritable bindings as required when defined at top-level",
			"should allow inheritable bindings to be overridden in named environments",
			"should mark inheritable bindings as optional when only defined in some environments",
			"should not inherit top-level inheritable bindings when env defines the property without a binding",
			"should produce union types for vars with different values across environments",
			"should generate simple Env when no environments are defined",
			"should error when environment names would collide after conversion",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "customization", "env"],
		status: "skip",
		names: [
			"should allow the user to customize the interface name",
			"should error if --env-interface is specified with no argument",
			"should error if an invalid interface identifier is provided to --env-interface",
			"should error if --env-interface is used with a service-syntax worker",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "customization", "output file"],
		status: "skip",
		names: [
			"should allow the user to specify where to write the result",
			"should error if the user points to a non-d.ts file",
			"should error if both --include-env and --include-runtime are false",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "customization"],
		status: "skip",
		names: ["should allow multiple customizations to be applied together"],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "runtime types output"],
		status: "skip",
		names: [
			"errors helpfully if you use --experimental-include-runtime",
			"prints something helpful if you have @cloudflare/workers-types",
			"prints something helpful if you have a runtime file at the old default location",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - CLI", "declarative Durable Object `exports`"],
		status: "skip",
		names: [
			"populates `durableNamespaces` from live `exports` entries (including unbound + `expecting-transfer`) and excludes tombstones",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["generate types - API"],
		status: "skip",
		names: [
			"returns combined and split `env` output",
			"returns `runtime` output when `env` types are excluded",
			"supports `strictVars=false` and custom env interface/path",
			"builds `env` header command from API options, not process args",
			"supports multi-config service resolution",
			"validates API options",
			"matches CLI output for `env` only generation",
			"matches CLI output for `runtime` + `env` generation",
		],
	},
	{
		file: "type-generation.test.ts",
		ancestors: ["pipeline schema type generation"],
		status: "skip",
		names: [
			"should generate typed pipeline bindings when API returns schema",
			"should fall back to generic type when API returns unstructured stream",
			"should fall back to generic type when API call fails",
			"should handle multiple pipelines with different schemas",
			"should handle nested struct types in schema",
			"should generate pipeline types without Cloudflare namespace prefix for service-worker format",
		],
	},
	{
		file: "utils/levenshtein.test.ts",
		ancestors: ["levenshteinDistance"],
		status: "skip",
		names: [
			"should return 0 for identical strings",
			"should return the length of the other string when one is empty",
			"should return 0 for two empty strings",
			"should handle single character insertions",
			"should handle single character deletions",
			"should handle single character substitutions",
			"should handle transpositions as two edits",
			"should handle completely different strings",
			"should be symmetric",
			"should handle single character strings",
			"should compute correct distance for longer strings",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
