// Generated from cloudflare/workers-sdk@93d72a577. Do not rename cases.
import { describe, it } from "vitest";

const groups = [
	{
		file: "api/startDevWorker/ConfigController.test.ts",
		ancestors: ["ConfigController"],
		status: "skip",
		names: [
			"should prompt user to update types if they're out of date",
			"should use account_id from config file before env var",
			"should emit configUpdate events with defaults applied",
			"should accept wrangler-specific dev fields through the public input",
			"should derive nodejsCompatMode from the config like the CLI",
			"should apply module root to parent if main is nested from base_dir",
			"should shallow merge patched config",
			"should only log warnings once even with multiple config updates",
		],
	},
	{
		file: "banner.test.ts",
		ancestors: ["wrangler banner"],
		status: "skip",
		names: [
			"should display the version banner by default",
			"should hide the version banner when WRANGLER_HIDE_BANNER is present",
			"should not hide the version banner when WRANGLER_HIDE_BANNER=false",
		],
	},
	{
		file: "cloudchamber/build.test.ts",
		ancestors: ["buildAndMaybePush"],
		status: "skip",
		names: [
			"should be able to build image and push with test-app:tag",
			"should be able to build image and push with registry.cloudflare.com/test-app:tag",
			"should be able to build image and push with registry.cloudflare.com/some-account-id/test-app:tag",
			"should use a custom docker path if provided",
			"should be able to build image and push",
			"should be able to build image and not push if it already exists in remote if config sha and digest both match",
			"should inspect the pushed image digest if the local digest is not remote",
			"should match digests for images with registry ports",
			"should be able to build image and not push",
			"should fall back to manifest inspect if pushed image digests are unavailable",
			"should add --network=host flag if WRANGLER_CI_OVERRIDE_NETWORK_MODE_HOST is set",
			"should be able to build image with platform specified",
			"should fail with an invalid platform",
			"should throw UserError when docker build fails",
			"should throw UserError when docker login fails",
		],
	},
	{
		file: "config-cache.test.ts",
		ancestors: ["config cache", "basic operations"],
		status: "skip",
		names: [
			"should return an empty config if no file exists",
			"should read and write values without overriding old ones",
		],
	},
	{
		file: "config-cache.test.ts",
		ancestors: ["config cache", "cache directory resolution"],
		status: "skip",
		names: [
			"should use .wrangler/cache when no node_modules exists",
			"should respect WRANGLER_CACHE_DIR environment variable",
			"should prioritize WRANGLER_CACHE_DIR over any other detection",
			"should always return a string (never null)",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — basic structure"],
		status: "skip",
		names: [
			"should set main_module for ESM workers",
			"should set body_part for commonjs workers",
			"should include the main module as a form part",
			"should include compatibility_date and compatibility_flags",
			"should include source maps as form parts",
			"should include additional ESM modules as form parts",
			"should throw when commonjs worker has additional modules",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — keep_bindings"],
		status: "skip",
		names: [
			"should include plain_text and json in keep_bindings when keepVars is true",
			"should include secret_text and secret_key in keep_bindings when keepSecrets is true",
			"should combine keepVars, keepSecrets, and keepBindings",
			"should not include keep_bindings when none of keepVars/keepSecrets/keepBindings are set",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — optional metadata fields"],
		status: "skip",
		names: [
			"should include 'logpush' when specified",
			"should include 'placement' when specified",
			"should include 'tail_consumers' when specified",
			"should include 'limits' when specified",
			"should include 'observability' when specified",
			"should include 'cache' when specified",
			"should include 'cache with cross version cache' when specified",
			"should include 'exports' when specified",
			"should include 'mixed exports' when specified",
			"should include 'durable object exports with an attach…' when specified",
			"should include 'containers linked by class_name' when specified",
			"should include 'containers linked from the exports si…' when specified",
			"should include 'annotations' when specified",
			"should include containers when specified",
		],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — unsafe metadata"],
		status: "skip",
		names: ["should merge unsafe metadata into the metadata object"],
	},
	{
		file: "create-worker-upload-form/metadata.test.ts",
		ancestors: ["createWorkerUploadForm — static assets only"],
		status: "skip",
		names: [
			"should short-circuit for assets-only uploads",
			"should include compatibility_date in assets-only metadata when provided",
		],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["normalizeSqlLineEndings()"],
		status: "skip",
		names: ["should preserve CRLF inside quoted SQL values and identifiers"],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["mayContainMultipleStatements()"],
		status: "skip",
		names: [
			"should return false if there is only a semi-colon at the end",
			"should return true if there is a semi-colon before the end of the string",
			"should return true if there is more than one statement",
		],
	},
	{
		file: "d1/splitter.test.ts",
		ancestors: ["splitSqlQuery()"],
		status: "skip",
		names: [
			"should trim a regular old sqlite dump",
			"should return original SQL if there are no real statements",
			"should not split single statements",
			"should handle strings",
			"should handle inline comments",
			"should handle block comments",
			"should split multiple statements",
			"should ignore comment at the end",
			"should handle whitespace between statements",
			"should handle $...$ style string markers",
			"should handle compound statements for BEGINs",
			"should handle a lowercase end closing a compound statement",
			"should handle compound statements for CASEs",
		],
	},
	{
		file: "deploy/deploy-interactive-prompts.test.ts",
		ancestors: ["deploy: interactive deploy config prompts"],
		status: "skip",
		names: [
			"should prompt and use the default compatibility date when user confirms",
			"should error when user declines the compatibility date prompt",
			"should error in non-interactive mode when no compatibility_date is provided",
			"should not show config-write prompt when config file already exists",
			"should skip the compat date prompt when --latest is passed",
			"should prompt for name, compat date, and offer to write config when no config file exists",
			"should show suggested CLI flags when user declines config file write",
			"should write config with the default compat date when --latest is used and no config file exists",
			"should include compat date in suggested CLI command when --latest is used and config write declined",
			"should prompt for name when config file exists but has no name",
			"should use the project name without prompting when run by an agent",
			"should not prompt for name when config file provides one",
			"should include compatibility_flags in generated wrangler.jsonc when --compatibility-flags is passed",
			"should include --compatibility-flags in suggested CLI command when user declines config file write",
			"should include multiple --compatibility-flags in suggested CLI command and config file",
			"should include routes in generated wrangler.jsonc when --routes is passed",
			"should include --routes in suggested CLI command when user declines config file write",
			"should include domains as custom_domain routes in generated wrangler.jsonc when --domains is passed",
			"should include --domains in suggested CLI command when user declines config file write",
			"should merge --routes and --domains into routes array in generated wrangler.jsonc",
			"should include triggers in generated wrangler.jsonc when --triggers is passed",
			"should include --triggers in suggested CLI command when user declines config file write",
			"should include vars in generated wrangler.jsonc when --var is passed",
			"should include --var in suggested CLI command when user declines config file write",
			"should include define in generated wrangler.jsonc when --define is passed",
			"should include --define in suggested CLI command when user declines config file write",
			"should include alias in generated wrangler.jsonc when --alias is passed",
			"should include jsx_factory in generated wrangler.jsonc when --jsx-factory is passed",
			"should include jsx_fragment in generated wrangler.jsonc when --jsx-fragment is passed",
			"should include tsconfig in generated wrangler.jsonc when --tsconfig is passed",
			"should include minify in generated wrangler.jsonc when --minify is passed",
			"should include --minify in suggested CLI command when user declines config file write",
			"should include upload_source_maps in generated wrangler.jsonc when --upload-source-maps is passed",
			"should include no_bundle in generated wrangler.jsonc when --no-bundle is passed",
			"should include logpush in generated wrangler.jsonc when --logpush is passed",
			"should include keep_vars in generated wrangler.jsonc when --keep-vars is passed",
			"should include --keep-vars in suggested CLI command when user declines config file write",
			"should include --dispatch-namespace in suggested CLI command when user declines config file write",
			"should include multiple flags in generated wrangler.jsonc and suggested CLI command",
			"should include multiple flags in suggested CLI command when user declines config file write",
		],
	},
	{
		file: "deploy/open-next.test.ts",
		ancestors: ["deploy", "open-next delegation"],
		status: "skip",
		names: [
			"should delegate to open-next when run in an open-next project and set OPEN_NEXT_DEPLOY",
			"should delegate to open-next when run in an open-next project and set OPEN_NEXT_DEPLOY and pass the various CLI arguments",
			"should not delegate to open-next deploy when run in an open-next project and OPEN_NEXT_DEPLOY is set",
			"should not delegate to open-next deploy when --no-autoconfig is provided",
			"should not delegate to open-next deploy when the Next.js config file is missing (to avoid false positives)",
			"should not delegate to open-next deploy when the open-next config file is missing (to avoid false positives)",
			"should not delegate to open-next deploy when --config is explicitly provided",
			"should not delegate to open-next deploy when Pages-to-Workers delegation is running",
		],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: ["RemoteSessionAuthenticationError"],
		status: "skip",
		names: [
			"preserves the original error as its cause",
			"sets a static telemetryMessage",
		],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: [
			"RemoteSessionAuthenticationError",
			"when authenticating via CLOUDFLARE_API_TOKEN",
		],
		status: "skip",
		names: ["mentions the API token environment variable in the message"],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: [
			"RemoteSessionAuthenticationError",
			"when authenticating via CLOUDFLARE_API_KEY + CLOUDFLARE_EMAIL",
		],
		status: "skip",
		names: ["mentions the Global API Key environment variable in the message"],
	},
	{
		file: "dev/remote.test.ts",
		ancestors: [
			"RemoteSessionAuthenticationError",
			"when authenticating via OAuth (no env credentials)",
		],
		status: "skip",
		names: ["suggests re-authenticating with wrangler login"],
	},
	{
		file: "index.test.ts",
		ancestors: ["wrangler", "no command"],
		status: "skip",
		names: ["should not require temporary terms acceptance before root help"],
	},
	{
		file: "index.test.ts",
		ancestors: ["wrangler", "--temporary"],
		status: "skip",
		names: ["is rejected on commands that don't opt in"],
	},
	{
		file: "index.test.ts",
		ancestors: ["wrangler", "command typo suggestions"],
		status: "todo",
		names: [
			"should suggest 'whoami' when user types 'whoamio'",
			"should suggest 'deploy' when user types 'delpoy'",
			"should not suggest anything for a completely unrelated command",
			"should suggest a command even with --help flag",
			"should suggest a subcommand for 'kv namespase'",
			"should suggest a nested subcommand for 'kv namespace craete'",
			"should preserve trailing args in suggestion for 'kv namespase create'",
			"should not suggest a subcommand for a completely unrelated subcommand",
			"should suggest 'whoami' when user types 'who-am-i'",
			"should suggest 'login' when user types 'log-in'",
			"should suggest 'logout' when user types 'log-out'",
		],
	},
	{
		file: "output.test.ts",
		ancestors: ["writeOutput()"],
		status: "skip",
		names: [
			"should do nothing with no env vars set",
			"should write to the file given by WRANGLER_OUTPUT_FILE_PATH",
			"should write to the file given by WRANGLER_OUTPUT_FILE_PATH, ignoring WRANGLER_OUTPUT_FILE_DIRECTORY",
			"should write multiple entries to the file given by WRANGLER_OUTPUT_FILE_PATH",
			"should write to a random file in WRANGLER_OUTPUT_FILE_DIRECTORY",
			"should write multiple entries to the same random file in WRANGLER_OUTPUT_FILE_DIRECTORY",
			"should write an alias and environment for pages-deploy-detailed outputs",
			"should write preview outputs with separate preview and deployment URLs",
			"should write an error log when a handler throws an error",
			"should include retry_after_ms in the error log when the failure carries a Retry-After duration",
		],
	},
	{
		file: "pages/pages.test.ts",
		ancestors: ["pages"],
		status: "skip",
		names: [
			"should display a list of available subcommands, for pages with no subcommand",
			"should display a list of available subcommands, for 'pages dev help'",
			"should display a list of available subcommands for 'pages project help`",
			"should display a list of available subcommands for 'pages deployment'",
			"should display a list of available subcommands for 'pages deploy'",
			"should display a list of available subcommands for 'pages secret'",
			"should display a list of available subcommands for 'pages download'",
		],
	},
	{
		file: "pages/pages.test.ts",
		ancestors: ["pages", "deprecation message for deprecated options"],
		status: "skip",
		names: [
			"should display for 'pages dev -- <command>'",
			"should display for 'pages dev --script-path'",
		],
	},
	{
		file: "pages/pages.test.ts",
		ancestors: ["pages", "beta message for subcommands"],
		status: "skip",
		names: [
			"should display for pages:dev",
			"should display for pages:functions:build",
			"should display for pages:functions:optimize-routes",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret"],
		status: "todo",
		names: [
			"rejects Preview deployment flag '--name my-preview' for 'put API_KEY'",
			"rejects Preview deployment flag '--message \"add secret\"' for 'put API_KEY'",
			"rejects Preview deployment flag '--tag v1' for 'put API_KEY'",
			"rejects Preview deployment flag '--ignore-base-config' for 'put API_KEY'",
			"rejects Preview deployment flag '--name my-preview' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--message \"delete secret\"' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--tag v1' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--ignore-base-config' for 'delete REMOVE_ME'",
			"rejects Preview deployment flag '--name my-preview' for 'list'",
			"rejects Preview deployment flag '--message \"list secrets\"' for 'list'",
			"rejects Preview deployment flag '--tag v1' for 'list'",
			"rejects Preview deployment flag '--ignore-base-config' for 'list'",
			"rejects Preview deployment flag '--name my-preview' for 'bulk'",
			"rejects Preview deployment flag '--message \"bulk secrets\"' for 'bulk'",
			"rejects Preview deployment flag '--tag v1' for 'bulk'",
			"rejects Preview deployment flag '--ignore-base-config' for 'bulk'",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret"],
		status: "skip",
		names: ["does not inherit the preview script positional"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "put"],
		status: "todo",
		names: [
			"patches the base config with the secret",
			"supports --worker-name",
			"fails before making API calls when Worker name is missing",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: [
			"wrangler preview",
			"preview base-config secret",
			"put",
			"(interactive)",
		],
		status: "todo",
		names: ["reads the secret from a masked prompt"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "put"],
		status: "skip",
		names: ["respects env-specific worker name when using --env"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "delete"],
		status: "todo",
		names: [
			"patches the base config removing the secret",
			"confirms before deleting a secret interactively",
			"makes no API call when the user declines confirmation",
			"supports --worker-name when deleting a secret",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "delete"],
		status: "skip",
		names: ["respects env-specific worker name when deleting a secret"],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "list"],
		status: "todo",
		names: [
			"reads the base config",
			"does not fall back to preview defaults when base config is missing",
			"supports --worker-name when listing secrets",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "list"],
		status: "skip",
		names: [
			"lists only secrets and never leaks their values ('json, value provided')",
			"lists only secrets and never leaks their values ('pretty, value provided')",
			"shows (none) when the base config has no secrets",
			"respects env-specific worker name when listing secrets",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "bulk"],
		status: "todo",
		names: [
			"patches the base config with all secrets",
			"creates secrets for empty dotenv values",
			"uploads JSON secrets from stdin",
			"uploads dotenv secrets from stdin",
			"supports --worker-name when bulk uploading secrets",
			"deletes secrets for null values, like `wrangler secret bulk`",
			"patches an empty env for empty input",
			"makes no API call when there is no input",
		],
	},
	{
		file: "preview.base-config.secret.test.ts",
		ancestors: ["wrangler preview", "preview base-config secret", "bulk"],
		status: "skip",
		names: ["respects env-specific worker name when bulk uploading secrets"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "put"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "put", "interactive"],
		status: "todo",
		names: [
			"should trim stdin secret value",
			"should create a secret",
			"should error without a script name",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "put", "non-interactive", "with accountId"],
		status: "todo",
		names: [
			"should error if request for available accounts fails",
			"should error if request for available memberships fails",
			"should error if a user has no account",
			"should error if a user has multiple accounts, and has not specified an account in wrangler.toml",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: [
			"wrangler secret",
			"put",
			"non-interactive",
			"multi-env warning",
		],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "delete"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "delete"],
		status: "todo",
		names: [
			"should delete a secret",
			"should delete a secret",
			"should error without a script name",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "delete", "multi-env warning"],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "list"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "list"],
		status: "todo",
		names: [
			"should error without a script name",
			"should error if worker is not found (error code 10007)",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "bulk"],
		status: "skip",
		names: ["should error helpfully if pages_build_output_dir is set"],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "bulk"],
		status: "todo",
		names: [
			"should create secrets from env stdin",
			"should fail if JSON stdin contains a record with non-string values",
			"should only send provided secrets via secrets-bulk endpoint",
			"should send null values to delete secrets via secrets-bulk endpoint",
			"should show no-op message when bulk input has no secrets",
			"should not create a new worker for delete-only bulk input when the worker is not found",
		],
	},
	{
		file: "secret.test.ts",
		ancestors: ["wrangler secret", "bulk", "multi-env warning"],
		status: "skip",
		names: [
			"should warn if the wrangler config contains environments but none was specified in the command",
			"should not warn if the wrangler config contains environments and one was specified in the command",
			"should not warn if the wrangler config doesn't contain environments and none was specified in the command",
			"should not warn if the wrangler config contains environments and CLOUDFLARE_ENV is set",
			'should not warn if --env="" is passed to explicitly target the top-level environment',
		],
	},
	{
		file: "utils-collectKeyValues.test.ts",
		ancestors: ["collectKeyValues()"],
		status: "skip",
		names: [
			"should return an empty object when passed undefined",
			"should return an empty object when passed an empty array",
			"should parse a key:value string with no value by returning an empty string for the value",
			"should return an object with a single key/value pair when passed an array with a single string",
			"should return an object with multiple key/value pairs when passed an array with multiple strings",
			"should return an object with multiple key/value pairs when passed an array with multiple strings with multiple colons",
		],
	},
	{
		file: "vectorize/vectorize.test.ts",
		ancestors: ["vectorize commands"],
		status: "todo",
		names: [
			"should warn when there are no vectorize indexes",
			"should warn when there are no vectors matching the getByIds identifiers",
			"should warn when query returns no vectors",
			"should warn when list metadata indexes returns empty",
			"should warn when list-vectors returns no vectors",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
