// Generated from cloudflare/workers-sdk@93d72a577. Do not rename cases.
import { describe, it } from "vitest";

const groups = [
	{
		file: "api/startDevWorker/BundlerController.assets-watcher.test.ts",
		ancestors: ["BundlerController — assets watcher"],
		status: "skip",
		names: [
			"a pending assets refresh is discarded on teardown",
			"a pending assets refresh is discarded when the config is replaced",
			"logs a warning and disables the watcher when chokidar emits EMFILE",
			"logs a warning and closes the watcher for non-EMFILE watcher errors",
			"no watchers are created by a config reload that outlives teardown",
		],
	},
	{
		file: "autoconfig/run.test.ts",
		ancestors: ["autoconfig (deploy)"],
		status: "todo",
		names: [
			"should not run autoconfig when `deploy` is run with `--no-autoconfig`",
			"should not run autoconfig when `deploy` is run with `--autoconfig=false`",
			"should check for autoconfig with flag",
			"should run autoconfig if project is not configured",
			"should not run autoconfig if project is already configured",
			"should warn and prompt when Pages project is detected",
		],
	},
	{
		file: "autoconfig/run.test.ts",
		ancestors: ["autoconfig (deploy)", "runAutoConfig()"],
		status: "todo",
		names: [
			"happy path",
			"new gitignore should not have leading empty lines",
			"pre-existing gitignore with trailing newline gets one empty separator line",
			"allows users to edit the auto-detected settings",
			".assetsignore should contain Wrangler files if outputDir === projectPath",
			"pre-existing assetsignore with trailing newline gets one empty separator line",
			"errors if no output directory is specified in the autoconfig details",
			"errors with Pages-specific message when framework is cf-pages",
			"errors with generic message when unsupported framework is not cf-pages",
			"validateFrameworkVersion is called before configure for a supported framework",
		],
	},
	{
		file: "autoconfig/run.test.ts",
		ancestors: [
			"autoconfig (deploy)",
			"runAutoConfig()",
			"nodejs_compat compatibility flag",
		],
		status: "todo",
		names: [
			"should not add nodejs_compat when framework specifies no compatibility flags",
			"should preserve other compatibility flags",
			"should remove a redundant nodejs_compat provided by the framework",
			"should remove nodejs_als while preserving other flags",
		],
	},
	{
		file: "cloudchamber/apply.test.ts",
		ancestors: ["cloudchamber apply"],
		status: "skip",
		names: [
			"should show deprecation warning when running cloudchamber apply",
			"can apply a simple application",
			"can apply a simple existing application",
			"can apply a simple existing application and create other (max_instances)",
			"can skip a simple existing application and create other",
			"can apply a simple existing application and create other",
			"can apply a simple existing application (labels)",
			"can apply an application, and there is no changes (retrocompatibility with regional scheduling policy)",
			"can apply an application, and there is no changes (two applications)",
			"can apply an application, and there is no changes",
			"can enable observability logs (top-level field)",
			"can enable observability logs (logs field)",
			"can disable observability logs (top-level field)",
			"can disable observability logs (logs field)",
			"can disable observability logs (absent field)",
			"keeps observability logs enabled",
			"keeps observability logs disabled (undefined in the app)",
			"keeps observability logs disabled (false in the app)",
			"can apply a simple application (instance type)",
			"can apply a simple application (custom instance type)",
			"can apply a simple existing application (instance type)",
			"can apply a simple existing application (custom instance type)",
			"falls back on dev instance type when instance type is absent",
			"expands image names from managed registry when creating an application",
			"expands image names from managed registry when modifying an application",
			"updates affinities",
		],
	},
	{
		file: "config-cache-wrangler-fallback.test.ts",
		ancestors: ["config cache with .wrangler/cache fallback"],
		status: "skip",
		names: [
			"should use .wrangler/cache when no node_modules exists",
			"should return an empty config if no file exists",
			"should save and retrieve config values using .wrangler/cache fallback",
		],
	},
	{
		file: "create-worker-upload-form/commonjs.test.ts",
		ancestors: ["createWorkerUploadForm — commonjs service-worker format"],
		status: "skip",
		names: [
			"should convert 'wasm → wasm_module' bindings in commonjs format",
			"should convert 'text → text_blob' bindings in commonjs format",
			"should convert 'buffer → data_blob' bindings in commonjs format",
			"should handle __STATIC_CONTENT_MANIFEST in commonjs format",
		],
	},
	{
		file: "create-worker-upload-form/commonjs.test.ts",
		ancestors: [
			"createWorkerUploadForm — __STATIC_CONTENT_MANIFEST ESM subdirectories",
		],
		status: "skip",
		names: [
			"should add re-export stubs in subdirectories for the manifest module",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy"],
		status: "skip",
		names: [
			"should output log file with deployment details",
			"should successfully deploy with CI tag match",
			"should successfully override name with WRANGLER_CI_OVERRIDE_NAME",
			"should successfully override name with WRANGLER_CI_OVERRIDE_NAME and outputs the correct output file",
			"should resolve wrangler.toml relative to the entrypoint",
			"should support wrangler.json",
			"should include serialised FormData in debug logs",
			"should support wrangler.jsonc",
			"should error helpfully if pages_build_output_dir is set in wrangler.toml when --no-autoconfig",
			"should error helpfully if pages_build_output_dir is set in wrangler.toml",
			"should attempt to run the autoconfig flow when pages_build_output_dir",
			"in non-interactive mode, attempts to deploy a Pages project using autoconfig",
			"should not run autoconfig when --config is explicitly provided",
			"should resolve wrangler.toml relative to the entrypoint",
			"should output a deploy and an autoconfig output entry to WRANGLER_OUTPUT_FILE_PATH if autoconfig run",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy"],
		status: "todo",
		names: [
			"should not deploy if there's any other kind of error when checking deployment source",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "output additional script information"],
		status: "skip",
		names: [
			"for first party workers, it should print worker information at log level",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication"],
		status: "todo",
		names: ["drops a user into the login flow if they're unauthenticated"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication"],
		status: "skip",
		names: [
			"creates a temporary preview account in interactive mode when --temporary is passed",
			"aborts in interactive mode when the terms are not accepted",
			"warns a user when they're authenticated with an API token in wrangler config file",
			"throws when the user is already authenticated and requests a temporary account",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication", "with an alternative auth domain"],
		status: "todo",
		names: ["drops a user into the login flow if they're unauthenticated"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication", "with temporary preview accounts"],
		status: "skip",
		names: [
			"creates a temporary preview account in non-interactive mode after printing terms notice",
			"throws when an OAuth token is on disk, even if it is expired and cannot refresh",
			"provisions the preview account against the staging API and caches it per-environment",
			"reuses a cached temporary preview account for later temporary deploys",
			"treats a malformed temporary preview account cache as a miss and refetches",
			"should fail clearly if the temporary preview account request fails",
			"fails the deploy when the proof-of-work challenge can't be obtained",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "authentication", "with temporary preview accounts"],
		status: "todo",
		names: [
			"should not throw an error in non-TTY if 'CLOUDFLARE_API_TOKEN' & 'account_id' are in scope",
			"should not throw an error if 'CLOUDFLARE_ACCOUNT_ID' & 'CLOUDFLARE_API_TOKEN' are in scope",
			"should throw an error in non-TTY & there is more than one account associated with API token",
			"should redact account names in CI even when non-interactive",
			"should throw error in non-TTY if 'CLOUDFLARE_API_TOKEN' is missing",
			"should throw error with no account ID provided and no members retrieved",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "warnings"],
		status: "todo",
		names: ["should warn user when worker was last deployed from api"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "warnings"],
		status: "skip",
		names: [
			"should warn user when additional properties are passed to a services config",
			"should log esbuild warnings",
		],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "environments"],
		status: "skip",
		names: ["should use legacy environments by default"],
	},
	{
		file: "deploy/core.test.ts",
		ancestors: ["deploy", "environments", "legacy"],
		status: "skip",
		names: [
			"uses the script name when no environment is specified",
			"appends the environment name when provided, and there is associated config",
			"appends the environment name when provided (with a warning), if there are no configured environments",
			"should throw an error when an environment name when provided, which doesn't match those in the config",
			"should allow --env and --name to be used together",
		],
	},
	{
		file: "deploy/name-collision-guard.test.ts",
		ancestors: ["deploy name-collision guard (non-interactive)"],
		status: "skip",
		names: [
			"aborts when an agent-generated name matches an existing Worker",
			"aborts when the delegated name was auto-generated (no --name)",
			"aborts even when the delegated name was carried across as --name",
			"does not guard a plain non-interactive deploy (no delegation)",
		],
	},
	{
		file: "dev/remote-bindings.test.ts",
		ancestors: ["dev with remote bindings"],
		status: "skip",
		names: [
			"should attempt to setup remote 'service' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'ai' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'browser render' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'images' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'vectorize' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'dispatch namespace' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'kv namespace' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'r2 bucket' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'd1' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'mtls' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'pipeline' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'artifacts' bindings when starting `wrangler dev`",
			"should attempt to setup remote 'email' bindings when starting `wrangler dev`",
			"should attempt to setup remote $name bindings when updating config during a running `wrangler dev` session",
			"should not recreate the remote proxy session on reload when auth has not changed",
			"should allow both local and remote KV bindings to the same namespace in a single dev session",
			"does not create remote bindings when `--local` is passed",
			"uses the provided api token and account id when starting the remote proxy session",
			"uses the account_id in the config when starting the remote proxy session",
		],
	},
	{
		file: "hyperdrive.test.ts",
		ancestors: ["hyperdrive planetscale"],
		status: "todo",
		names: [
			"should show the planetscale namespace help",
			"should show the signature command help",
			"should POST to the planetScale integration endpoint",
			"should print only the signature JSON, so it can be piped",
			"should send only the fields the PlanetScale CLI accepts",
		],
	},
	{
		file: "hyperdrive.test.ts",
		ancestors: ["hyperdrive commands"],
		status: "todo",
		names: [
			"should create a hyperdrive config given individual params instead of a connection string",
			"should reject a create hyperdrive config with --service-id and --origin-host",
			"should reject a create hyperdrive config with --service-id and --access-client-id",
			"should throw an exception when creating a hyperdrive config without network origin options",
		],
	},
	{
		file: "navigator-user-agent.test.ts",
		ancestors: ["isNavigatorDefined"],
		status: "skip",
		names: [
			"default",
			"modern date",
			"old date",
			"switch date",
			"before date",
			"old date, but with flag",
			"old date, with disable flag",
			"new date, but with disable flag",
			"new date, with enable flag",
			"errors with disable and enable flags specified",
		],
	},
	{
		file: "navigator-user-agent.test.ts",
		ancestors: ["defineNavigatorUserAgent is respected"],
		status: "skip",
		names: [
			"preserves `navigator` when `defineNavigatorUserAgent` is `false`",
			"tree shakes `navigator` when `defineNavigatorUserAgent` is `true`",
			"tree shakes `navigator` when `defineNavigatorUserAgent` is `true` and `process.env.NODE_ENV` is `undefined`",
		],
	},
	{
		file: "pages/pages-download-config.test.ts",
		ancestors: ["pages download config"],
		status: "skip",
		names: [
			"should download full config correctly",
			"should generate preview override if preview has limits and production does not",
			"should not duplicate inheritable properties if they're equal",
			"should prefer CLOUDFLARE_ACCOUNT_ID over cached account id",
			"should fail if not given a project name",
			"should fail if project does not exist",
		],
	},
	{
		file: "pages/pages-download-config.test.ts",
		ancestors: ["pages download config", "overwrite existing file"],
		status: "skip",
		names: [
			"should overwrite existing file w/ --force",
			"should not overwrite existing file w/o --force (non-interactive)",
			"should overwrite existing file w/ prompt",
			"should not overwrite existing file w/ prompt",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines list"],
		status: "todo",
		names: ["should surface failed pipelines in the list"],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines get"],
		status: "todo",
		names: [
			"highlights failure reason for a failed pipeline",
			"resolves pipeline by name",
			"resolves pipeline by name across multiple pages",
			"resolves pipeline by name when identifier looks like a 32-char hex string",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines delete"],
		status: "todo",
		names: ["deletes pipeline by name"],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines streams get"],
		status: "todo",
		names: [
			"resolves stream by name",
			"resolves stream by name when API returns error code 1016",
			"resolves stream by name across multiple pages",
			"resolves stream by name when identifier looks like a 32-char hex string",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines streams delete"],
		status: "todo",
		names: ["deletes stream by name"],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines sinks create"],
		status: "todo",
		names: [
			"should create R2 JSON sink with gzip compression",
			"should create uncompressed JSON sink when compression is omitted",
			"should create JSON sink with explicit uncompressed output",
			"should reject unsupported JSON compression",
			"should reject row group size for JSON sinks",
			"should create R2 Data Catalog sink",
			"should error when r2-data-catalog has interval below minimum",
			"should allow r2 sinks with interval below 60 seconds",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines sinks get"],
		status: "todo",
		names: [
			"resolves sink by name",
			"resolves sink by name when API returns error code 1015",
			"resolves sink by name across multiple pages",
			"resolves sink by name when identifier looks like a 32-char hex string",
		],
	},
	{
		file: "pipelines.test.ts",
		ancestors: ["wrangler pipelines", "pipelines sinks delete"],
		status: "todo",
		names: ["deletes sink by name"],
	},
	{
		file: "register-yargs-command-skills.test.ts",
		ancestors: ["register-yargs-command skills integration"],
		status: "skip",
		names: [
			"does not check skills for commands without suggestSkillsAfterHandler",
			"calls runSkillsInstallFlow with force: true and command when --install-skills is passed",
			"calls runSkillsUpdateFlow after commands with suggestSkillsAfterHandler: true",
			"calls runSkillsUpdateFlow after `wrangler whoami` (non-JSON)",
			"command in skills install event contains only the command name, not positional args or flags",
			"does not check skills after `wrangler whoami --json`",
			"does not fail the command when runSkillsUpdateFlow throws",
			"does not call runSkillsUpdateFlow when WRANGLER_NO_SKILLS_UPDATE_PROMPTS env var is set",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login"],
		status: "skip",
		names: [
			"should clear the cached temporary preview account when logging in",
			"should send the `login user` metric when `--scopes` is provided",
			"--use-keyring stores credentials in an encrypted file with a key in the OS keyring",
			"--no-use-keyring scrubs encrypted credentials without writing them to plaintext, then the fresh login uses the file store",
			"--no-use-keyring still scrubs the encrypted credentials and keyring entry when CLOUDFLARE_AUTH_USE_KEYRING=false is set (the env var must not defeat the opt-out scrub)",
			"--use-keyring rolls the keyring_enabled preference back when eager credential-store validation throws",
			"--use-keyring rolls the keyring_enabled preference back when the resolver soft-falls-back to the file store",
			"--use-keyring persists the preference and skips the misleading rollback when CLOUDFLARE_AUTH_USE_KEYRING=false overrides for this command",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login", "OAuth callback error handling"],
		status: "todo",
		names: [
			"rejects with the bare OAuth error code when no description is provided",
			"rejects with both the OAuth error code and error_description",
			"rejects with the existing consent-denied message for access_denied",
			"rejects with the provider error when /oauth2/token fails after a valid auth code",
			"rejects with the provider error when /oauth2/token returns 2xx with an error body",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login"],
		status: "todo",
		names: [
			"should error if --scopes contains an invalid scope",
			"should error if --scopes contains multiple invalid scopes",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "auth keyring"],
		status: "skip",
		names: [
			"`auth keyring enable` persists the preference without requiring a login",
			"`auth keyring enable` rolls the preference back when the keyring backend is unavailable",
			"`auth keyring disable` scrubs the default profile's encrypted credentials",
			"`auth keyring disable` scrubs encrypted credentials created via the env var even when the preference was never persisted",
			"`auth keyring` with no action reports the current setting without changing it",
			"`auth keyring` rejects the --profile flag",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User"],
		status: "todo",
		names: ["refreshes the profile passed to loginOrRefreshIfRequired"],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "login (device flow)"],
		status: "skip",
		names: [
			"should complete login on the first successful poll",
			"should display the effective timeout when the server's `expires_in` is shorter than the 5-minute cap",
			"should fall back to constructing a verification URL when the server omits `verification_uri_complete`",
			"should not open the browser when `--browser=false`",
			"should keep polling while the server returns `authorization_pending`, then succeed",
			"should keep polling when a poll fails transiently (non-JSON body), then succeed",
			"should time out with a message reflecting the server's `expires_in` when shorter than the cap",
			"should error with a clear message when the user denies consent",
			"should error with a clear message when the device code expires",
			"should error when `--callback-host` is passed alongside `--device`",
			"should error when `--callback-port` is passed alongside `--device`",
			"should reject the incompatible flag combination before `--no-use-keyring` mutates any credential-storage state",
		],
	},
	{
		file: "user.test.ts",
		ancestors: [
			"User",
			"CLOUDFLARE_API_TOKEN priority over stored OAuth state",
		],
		status: "todo",
		names: [
			"getAPIToken returns the env token even when a stored OAuth token also exists",
			"loginOrRefreshIfRequired does not attempt to refresh an expired OAuth token when env auth is set",
			"wrangler whoami succeeds via env token when a stale OAuth token also exists on disk",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "auth token"],
		status: "todo",
		names: [
			"should re-read refresh_token from disk before refreshing in case a sibling process rotated it",
			"should preserve the stored refresh_token when the OAuth server omits one on refresh",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "account caching"],
		status: "todo",
		names: [
			"should only prompt for account selection once when getOrSelectAccountId is called multiple times",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "getActiveAccountId"],
		status: "todo",
		names: [
			"should return config.account_id when set",
			"should return CLOUDFLARE_ACCOUNT_ID env var when config has no account_id",
			"should prefer env var over cache",
			"should return cached account when config and env var are not set",
			"should return undefined when no source is available",
			"should reject a config.account_id that cannot be used in an API URL",
			"should reject a CLOUDFLARE_ACCOUNT_ID that cannot be used in an API URL",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "getActiveAccountId"],
		status: "skip",
		names: ["should prefer config.account_id over env var and cache"],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "fetchAllAccounts"],
		status: "todo",
		names: [
			"should return the intersection of /accounts and /memberships",
			"should drop accounts present in /accounts but not /memberships",
			"should drop accounts present in /memberships but not /accounts",
			"should throw when no accounts are found",
			"should throw when /accounts and /memberships have no overlap",
			"should fall back to /accounts when /memberships returns 9106 (Account API Token path)",
			"should throw a helpful error on 9106 when /accounts is also unusable",
			"should fall back to /accounts when /memberships returns 10000 (Authentication error)",
			"should throw a helpful error on 10000 when /accounts is also unusable",
			"should include env-var hint when /memberships returns 9106 and /accounts is empty",
			"should propagate /memberships errors that are not 9106 or 10000",
			"should return an empty array instead of throwing when throwOnEmpty is false",
		],
	},
	{
		file: "user.test.ts",
		ancestors: ["User", "getOrSelectAccountId with env var"],
		status: "todo",
		names: [
			"should return env var without making API calls",
			"should prefer env var over cached account",
			"should not write to cache when using env var",
			"should not write to cache when using config account_id",
			"should write to cache when account is resolved via API",
			"should reject an invalid env var without making API calls",
		],
	},
	{
		file: "utils/shell-quote.test.ts",
		ancestors: ["quote"],
		status: "skip",
		names: [
			"returns unquoted string for safe arguments",
			"wraps strings with spaces in quotes",
			"escapes special characters",
			"handles single quotes by wrapping in double quotes",
			"handles empty array",
			"handles multiple arguments",
		],
	},
	{
		file: "utils/shell-quote.test.ts",
		ancestors: ["parse"],
		status: "skip",
		names: [
			"parses simple arguments",
			"parses single-quoted strings",
			"parses double-quoted strings",
			"handles escaped characters",
			"handles environment variables when env is provided",
			"returns empty string for unresolved env variable",
			"handles glob patterns",
			"handles comments",
			"throws for control operators",
			"handles empty input",
			"handles Windows-style backslash paths",
			"handles nested quotes",
		],
	},
] as const;

function register(group: (typeof groups)[number], depth = 0): void {
	const ancestor = group.ancestors[depth];
	if (ancestor !== undefined) {
		describe(ancestor, () => register(group, depth + 1));
		return;
	}
	for (const name of group.names) {
		if (group.status === "todo") {
			it.todo(name);
		} else {
			it.skip(name);
		}
	}
}

for (const group of groups) {
	register(group);
}
