// This file was auto-generated by Fern from our API Definition.

export type MarkdownQuickActionRequestBody =
    | {
          actionTimeout?: number | undefined;
          addScriptTag?:
              | {
                    content?: string | undefined;
                    id?: string | undefined;
                    type?: string | undefined;
                    url?: string | undefined;
                }[]
              | undefined;
          addStyleTag?:
              | {
                    content?: string | undefined;
                    url?: string | undefined;
                }[]
              | undefined;
          allowRequestPattern?: string[] | undefined;
          allowResourceTypes?:
              | (
                    | "document"
                    | "stylesheet"
                    | "image"
                    | "media"
                    | "font"
                    | "script"
                    | "texttrack"
                    | "xhr"
                    | "fetch"
                    | "prefetch"
                    | "eventsource"
                    | "websocket"
                    | "manifest"
                    | "signedexchange"
                    | "ping"
                    | "cspviolationreport"
                    | "preflight"
                    | "other"
                )[]
              | undefined;
          authenticate?:
              | {
                    password: string;
                    username: string;
                }
              | undefined;
          bestAttempt?: boolean | undefined;
          cookies?:
              | {
                    domain?: string | undefined;
                    expires?: number | undefined;
                    httpOnly?: boolean | undefined;
                    name: string;
                    partitionKey?: string | undefined;
                    path?: string | undefined;
                    priority?: ("Low" | "Medium" | "High") | undefined;
                    sameParty?: boolean | undefined;
                    sameSite?: ("Strict" | "Lax" | "None") | undefined;
                    secure?: boolean | undefined;
                    sourcePort?: number | undefined;
                    sourceScheme?: ("Unset" | "NonSecure" | "Secure") | undefined;
                    url?: string | undefined;
                    value: string;
                }[]
              | undefined;
          emulateMediaType?: string | undefined;
          gotoOptions?:
              | {
                    referer?: string | undefined;
                    referrerPolicy?: string | undefined;
                    timeout?: number | undefined;
                    waitUntil?:
                        | (
                              | "load"
                              | "domcontentloaded"
                              | "networkidle0"
                              | "networkidle2"
                              | ("load" | "domcontentloaded" | "networkidle0" | "networkidle2")[]
                          )
                        | undefined;
                }
              | undefined;
          html?: string | undefined;
          rejectRequestPattern?: string[] | undefined;
          rejectResourceTypes?:
              | (
                    | "document"
                    | "stylesheet"
                    | "image"
                    | "media"
                    | "font"
                    | "script"
                    | "texttrack"
                    | "xhr"
                    | "fetch"
                    | "prefetch"
                    | "eventsource"
                    | "websocket"
                    | "manifest"
                    | "signedexchange"
                    | "ping"
                    | "cspviolationreport"
                    | "preflight"
                    | "other"
                )[]
              | undefined;
          setExtraHTTPHeaders?: Record<string, string> | undefined;
          setJavaScriptEnabled?: boolean | undefined;
          url: string;
          userAgent?: string | undefined;
          viewport?:
              | {
                    deviceScaleFactor?: number | undefined;
                    hasTouch?: boolean | undefined;
                    height: number;
                    isLandscape?: boolean | undefined;
                    isMobile?: boolean | undefined;
                    width: number;
                }
              | undefined;
          waitForSelector?:
              | {
                    hidden?: true | undefined;
                    selector: string;
                    timeout?: number | undefined;
                    visible?: true | undefined;
                }
              | undefined;
          waitForTimeout?: number | undefined;
      }
    | {
          actionTimeout?: number | undefined;
          addScriptTag?:
              | {
                    content?: string | undefined;
                    id?: string | undefined;
                    type?: string | undefined;
                    url?: string | undefined;
                }[]
              | undefined;
          addStyleTag?:
              | {
                    content?: string | undefined;
                    url?: string | undefined;
                }[]
              | undefined;
          allowRequestPattern?: string[] | undefined;
          allowResourceTypes?:
              | (
                    | "document"
                    | "stylesheet"
                    | "image"
                    | "media"
                    | "font"
                    | "script"
                    | "texttrack"
                    | "xhr"
                    | "fetch"
                    | "prefetch"
                    | "eventsource"
                    | "websocket"
                    | "manifest"
                    | "signedexchange"
                    | "ping"
                    | "cspviolationreport"
                    | "preflight"
                    | "other"
                )[]
              | undefined;
          authenticate?:
              | {
                    password: string;
                    username: string;
                }
              | undefined;
          bestAttempt?: boolean | undefined;
          cookies?:
              | {
                    domain?: string | undefined;
                    expires?: number | undefined;
                    httpOnly?: boolean | undefined;
                    name: string;
                    partitionKey?: string | undefined;
                    path?: string | undefined;
                    priority?: ("Low" | "Medium" | "High") | undefined;
                    sameParty?: boolean | undefined;
                    sameSite?: ("Strict" | "Lax" | "None") | undefined;
                    secure?: boolean | undefined;
                    sourcePort?: number | undefined;
                    sourceScheme?: ("Unset" | "NonSecure" | "Secure") | undefined;
                    url?: string | undefined;
                    value: string;
                }[]
              | undefined;
          emulateMediaType?: string | undefined;
          gotoOptions?:
              | {
                    referer?: string | undefined;
                    referrerPolicy?: string | undefined;
                    timeout?: number | undefined;
                    waitUntil?:
                        | (
                              | "load"
                              | "domcontentloaded"
                              | "networkidle0"
                              | "networkidle2"
                              | ("load" | "domcontentloaded" | "networkidle0" | "networkidle2")[]
                          )
                        | undefined;
                }
              | undefined;
          html: string;
          rejectRequestPattern?: string[] | undefined;
          rejectResourceTypes?:
              | (
                    | "document"
                    | "stylesheet"
                    | "image"
                    | "media"
                    | "font"
                    | "script"
                    | "texttrack"
                    | "xhr"
                    | "fetch"
                    | "prefetch"
                    | "eventsource"
                    | "websocket"
                    | "manifest"
                    | "signedexchange"
                    | "ping"
                    | "cspviolationreport"
                    | "preflight"
                    | "other"
                )[]
              | undefined;
          setExtraHTTPHeaders?: Record<string, string> | undefined;
          setJavaScriptEnabled?: boolean | undefined;
          url?: string | undefined;
          userAgent?: string | undefined;
          viewport?:
              | {
                    deviceScaleFactor?: number | undefined;
                    hasTouch?: boolean | undefined;
                    height: number;
                    isLandscape?: boolean | undefined;
                    isMobile?: boolean | undefined;
                    width: number;
                }
              | undefined;
          waitForSelector?:
              | {
                    hidden?: true | undefined;
                    selector: string;
                    timeout?: number | undefined;
                    visible?: true | undefined;
                }
              | undefined;
          waitForTimeout?: number | undefined;
      };
