// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface UpdatePoliciesResponse {
    id?: CloudflareApi.AaaUuid | undefined;
}
