// This file was auto-generated by Fern from our API Definition.

/** Specifies the attribute by which to group the results. */
export const TimeseriesGroupsBotsRequestDimension = {
    UserAgent: "USER_AGENT",
    CrawlPurpose: "CRAWL_PURPOSE",
    Industry: "INDUSTRY",
    Vertical: "VERTICAL",
    ContentType: "CONTENT_TYPE",
    ResponseStatus: "RESPONSE_STATUS",
    ResponseStatusCategory: "RESPONSE_STATUS_CATEGORY",
} as const;
export type TimeseriesGroupsBotsRequestDimension =
    (typeof TimeseriesGroupsBotsRequestDimension)[keyof typeof TimeseriesGroupsBotsRequestDimension];
