// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "cf-brapi-guardrails": "eyJtb2RlIjoicmVhZG9ubHkifQ",
 *         account_id: "account_id",
 *         session_id: "session_id",
 *         target_id: "target_id"
 *     }
 */
export interface GetPageRequest {
    /** Account ID. */
    account_id: string;
    /** Browser session ID. */
    session_id: string;
    /** Target ID, e.g. page ID. */
    target_id: string;
    /** Optional base64url-encoded JSON connection guardrails (mode) */
    "cf-brapi-guardrails"?: string | null;
}
