// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface BulkUpdateGreTunnelsResponse {
    modified?: boolean | undefined;
    modified_gre_tunnels?: CloudflareApi.MagicGreTunnel[] | undefined;
}
