// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface UpdateItemsResponse {
    result: CloudflareApi.ListsApiResponseCommonResult;
    result_info?: Record<string, unknown> | undefined;
}
