// This file was auto-generated by Fern from our API Definition.

/** Aggregation interval of the results (e.g., in 15 minutes or 1 hour intervals). Refer to [Aggregation intervals](https://developers.cloudflare.com/radar/concepts/aggregation-intervals/). When omitted, the interval is auto-selected from the requested date range; finer intervals are only available for shorter ranges. If the requested interval is too granular for the date range, the request is rejected. */
export const TimeseriesOriginsRequestAggInterval = {
    V15M: "15m",
    V1H: "1h",
    V1D: "1d",
    V1W: "1w",
} as const;
export type TimeseriesOriginsRequestAggInterval =
    (typeof TimeseriesOriginsRequestAggInterval)[keyof typeof TimeseriesOriginsRequestAggInterval];
