// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const TimeseriesOriginsRequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type TimeseriesOriginsRequestFormat =
    (typeof TimeseriesOriginsRequestFormat)[keyof typeof TimeseriesOriginsRequestFormat];
