// This file was auto-generated by Fern from our API Definition.

export const TimeseriesGroupsV2SecurityRequestArcItem = {
    Pass: "PASS",
    None: "NONE",
    Fail: "FAIL",
} as const;
export type TimeseriesGroupsV2SecurityRequestArcItem =
    (typeof TimeseriesGroupsV2SecurityRequestArcItem)[keyof typeof TimeseriesGroupsV2SecurityRequestArcItem];
