// This file was auto-generated by Fern from our API Definition.

export const ListLocationsRequestOrderBy = {
    Name: "name",
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
} as const;
export type ListLocationsRequestOrderBy =
    (typeof ListLocationsRequestOrderBy)[keyof typeof ListLocationsRequestOrderBy];
