// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListTriggersResponse {
    result: CloudflareApi.BuildsTriggerResponse[];
    result_info?: CloudflareApi.BuildsPaginationInfo | undefined;
}
