// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         rule_identifier: "rule_identifier"
 *     }
 */
export interface GetRulesRequest {
    /** Identifier. */
    zone_id: string;
    /** Routing rule identifier. */
    rule_identifier: string;
}
