// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface ListFeedsRequest {
    account_id: string;
    page?: number;
    per_page?: number;
    limit?: number;
    sort?: string;
    category?: string;
    source_type?: CloudflareApi.cloudforceOne.threatSignals.ListFeedsRequestSourceType;
    enabled?: boolean;
    status?: string;
}
