// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface GetMonthlyReportResponse {
    /** A map of month (YYYY-MM) to the disposition counts recorded for that month. */
    by_month?:
        | Record<
              string,
              CloudflareApi.FernCompatibilityEmailSecurityGetMonthlyReportResponse200ApplicationJsonByMonthMapValue
          >
        | undefined;
}
