// This file was auto-generated by Fern from our API Definition.

export interface GetTypeResponse {
    result: GetTypeResponse.Result.Item[];
    result_info?: Record<string, unknown> | undefined;
}

export namespace GetTypeResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export interface Item {
            count?: number | undefined;
            value?: string | undefined;
        }
    }
}
