// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         test_id: "test_id",
 *         from: "from",
 *         to: "to",
 *         interval: "minute"
 *     }
 */
export interface GetTracerouteRequest {
    /** Unique Cloudflare account ID. */
    account_id: string;
    /** Unique identifier for a specific test. */
    test_id: string;
    /** Optionally filter result stats to a specific device(s). Cannot be used in combination with colo param. */
    deviceId?: string | string[];
    /** Start time for aggregate metrics in ISO ms. */
    from: string;
    /** End time for aggregate metrics in ISO ms. */
    to: string;
    /** Time interval for aggregate time slots. */
    interval: CloudflareApi.zeroTrust.dex.testResults.GetTracerouteRequestInterval;
    /** Optionally filter result stats to a Cloudflare colo. Cannot be used in combination with deviceId param. */
    colo?: string;
}
