// This file was auto-generated by Fern from our API Definition.

export interface SyncServersResponse {
    error?: string | undefined;
    error_details?: SyncServersResponse.ErrorDetails | undefined;
    status?: SyncServersResponse.Status | undefined;
}

export namespace SyncServersResponse {
    export interface ErrorDetails {
        /** Underlying error message */
        cause?: string | undefined;
        /** True = MCP server returned an error. False = couldn't reach the server */
        is_upstream?: boolean | undefined;
        /** MCP protocol error code */
        mcp_code?: number | undefined;
        /** Whether the error is transient and worth retrying */
        retryable?: boolean | undefined;
        /** HTTP status code from the server */
        status_code?: number | undefined;
    }

    export const Status = {
        Waiting: "waiting",
        Ready: "ready",
        Stale: "stale",
        Error: "error",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
