// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         automationId: "automationId"
 *     }
 */
export interface DeleteAutomationsRequest {
    /** Your Cloudflare account ID. */
    account_id: string;
    automationId: string;
}
