// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface EditVariantsResponse extends CloudflareApi.CacheSettingsVariants {
    value: CloudflareApi.CacheSettingsVariantsValue;
}
