// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { ExtensionsClient } from "../resources/extensions/client/Client.js";
import { RegistrationsClient } from "../resources/registrations/client/Client.js";

export declare namespace RegistrarClient {
    export type Options = BaseClientOptions;
}

export class RegistrarClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<RegistrarClient.Options>;
    protected _registrations: RegistrationsClient | undefined;
    protected _extensions: ExtensionsClient | undefined;

    constructor(options: RegistrarClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get registrations(): RegistrationsClient {
        return (this._registrations ??= new RegistrationsClient(this._options));
    }

    public get extensions(): ExtensionsClient {
        return (this._extensions ??= new ExtensionsClient(this._options));
    }
}
