// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import * as core from "../../../../../../core/index.js";
import * as environments from "../../../../../../environments.js";
import { PackagesClient } from "../resources/packages/client/Client.js";

export declare namespace WafClient {
    export type Options = BaseClientOptions;
}

export class WafClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WafClient.Options>;
    protected _packages: PackagesClient | undefined;

    constructor(options: WafClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get packages(): PackagesClient {
        return (this._packages ??= new PackagesClient(this._options));
    }
}
