// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         namespace_id: "namespace_id",
 *         title: "My Own Namespace"
 *     }
 */
export interface WorkersKvCreateRenameNamespaceBody {
    /** ID of the Cloudflare account that owns the Workers KV namespaces. */
    account_id: string;
    /** ID of the Workers KV namespace. */
    namespace_id: string;
    title: CloudflareApi.WorkersKvNamespaceTitle;
}
