// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface BatchUrlIgnorePatternsResponse {
    deletes: CloudflareApi.EmailSecurityDeletedUrlIgnorePattern[];
    patches: CloudflareApi.EmailSecurityUrlIgnorePattern[];
    posts: CloudflareApi.EmailSecurityUrlIgnorePattern[];
    puts: CloudflareApi.EmailSecurityUrlIgnorePattern[];
}
