// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListHostnameAssociationsResponse {
    result: CloudflareApi.TlsCertificatesAndHostnamesHostnameAssocObject[];
    result_info?: ListHostnameAssociationsResponse.ResultInfo | undefined;
}

export namespace ListHostnameAssociationsResponse {
    export interface ResultInfo {
        /** Total results returned based on your search parameters. */
        count?: number | undefined;
        /** Current page within paginated list of results. */
        page?: number | undefined;
        /** Number of results per page of results. */
        per_page?: number | undefined;
        /** Total results available without any search parameters. */
        total_count?: number | undefined;
        /** Total pages available of results. */
        total_pages?: number | undefined;
    }
}
