// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         issueId: "issueId"
 *     }
 */
export interface OccurrencesIssuesRequest {
    /** Your Cloudflare account ID. */
    account_id: string;
    /** Issue ID returned by the issues API. */
    issueId: string;
    /** Opaque cursor returned in result_info.cursors.after. */
    cursor?: string;
    per_page?: number;
}
