// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface SummaryIssuesRequest {
    /** Your Cloudflare account ID. */
    account_id: string;
    service?: string;
}
