// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         script_name: "script_name",
 *         body: {
 *             strategy: "percentage",
 *             versions: [{
 *                     percentage: 100,
 *                     version_id: "023e105f-2a42-4f8b-a1c1-73f6a2a30c0f"
 *                 }]
 *         }
 *     }
 */
export interface CreateDeploymentsRequest {
    /** Identifier. */
    account_id: string;
    /** Name of the script, used in URLs and route configuration. */
    script_name: string;
    /** If set to true, the deployment will be created even if normally blocked by something such rolling back to an older version when a secret has changed. */
    force?: boolean;
    body: CloudflareApi.WorkersDeployment;
}
