// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         script_name: "script_name"
 *     }
 */
export interface ListDeploymentsRequest {
    /** Identifier. */
    account_id: string;
    /** Name of the script. */
    script_name: string;
    /** Start of the deployment creation time range, inclusive. */
    since?: string;
    /** End of the deployment creation time range, inclusive. */
    until?: string;
    /** Current page. */
    page?: number;
    /** Items per page. */
    per_page?: number;
}
