// This file was auto-generated by Fern from our API Definition.

export const DeleteCustomRequestCfR2Jurisdiction = {
    VDefault: "default",
    Eu: "eu",
    Us: "us",
    Fedramp: "fedramp",
    FedrampHigh: "fedramp-high",
} as const;
export type DeleteCustomRequestCfR2Jurisdiction =
    (typeof DeleteCustomRequestCfR2Jurisdiction)[keyof typeof DeleteCustomRequestCfR2Jurisdiction];
