// This file was auto-generated by Fern from our API Definition.

export interface ListActiveSessionsResponse {
    result: ListActiveSessionsResponse.Result.Item[];
    result_info?: ListActiveSessionsResponse.ResultInfo | undefined;
}

export namespace ListActiveSessionsResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export interface Item {
            expiration?: number | undefined;
            metadata?: Item.Metadata | undefined;
            name?: string | undefined;
        }

        export namespace Item {
            export interface Metadata {
                apps?: Record<string, Metadata.Apps.Value> | undefined;
                expires?: number | undefined;
                iat?: number | undefined;
                nonce?: string | undefined;
                ttl?: number | undefined;
            }

            export namespace Metadata {
                export namespace Apps {
                    export interface Value {
                        hostname?: string | undefined;
                        name?: string | undefined;
                        type?: string | undefined;
                        uid?: string | undefined;
                    }
                }
            }
        }
    }

    export interface ResultInfo {
        /** Total number of results for the requested service. */
        count?: number | undefined;
        /** Current page within paginated list of results. */
        page?: number | undefined;
        /** Number of results per page of results. */
        per_page?: number | undefined;
        /** Total results available without any search parameters. */
        total_count?: number | undefined;
        /** The number of total pages in the entire result set. */
        total_pages?: number | undefined;
    }
}
