// This file was auto-generated by Fern from our API Definition.

export interface ListArticlesResponse {
    articles: ListArticlesResponse.Articles.Item[];
    has_more: boolean;
    next_cursor: string | null;
    total_count: number | null;
    total_count_is_exact: boolean;
}

export namespace ListArticlesResponse {
    export type Articles = Articles.Item[];

    export namespace Articles {
        export interface Item {
            /** Threat Events dataset identifier for the article redirect. Null when the account feeds dataset mapping is unavailable. */
            dataset_id: string | null;
            /** Threat Events event identifier associated with this article for a UI redirect. Null when no event has been linked. */
            event_id: string | null;
            feed_display_name: string | null;
            feed_id: string;
            fetched_at: string;
            id: string;
            link: string | null;
            published_at: string | null;
            read: boolean;
            read_at: string | null;
            /** Persisted enrichment summary. Null until enrichment produces a summary. */
            summary: string | null;
            tags: Item.Tags.Item[];
            title: string | null;
        }

        export namespace Item {
            export type Tags = Tags.Item[];

            export namespace Tags {
                export interface Item {
                    applied_by: Item.AppliedBy;
                    categoryId: string | null;
                    uuid: string;
                    value: string;
                }

                export namespace Item {
                    export const AppliedBy = {
                        Ai: "ai",
                        Analyst: "analyst",
                        System: "system",
                    } as const;
                    export type AppliedBy = (typeof AppliedBy)[keyof typeof AppliedBy];
                }
            }
        }
    }
}
