// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         certificate_pack_id: "certificate_pack_id"
 *     }
 */
export interface EditCertificatePacksRequest {
    /** Identifier. */
    zone_id: string;
    /** The unique identifier for a certificate_pack. */
    certificate_pack_id: string;
    cloudflare_branding?: CloudflareApi.TlsCertificatesAndHostnamesCloudflareBranding;
}
