// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "c3dc5f0b34a14ff8e1b3ec04895e1b22",
 *         name: "my-namespace",
 *         id: "my-ai-search",
 *         key: "key"
 *     }
 */
export interface UpsertItemsRequest {
    account_id: string;
    /** Namespace name */
    name: string;
    /** AI Search instance ID. Lowercase alphanumeric, hyphens, and underscores. */
    id: string;
    /** Item key / filename. Must not exceed 128 characters. */
    key: string;
    /** Wait for indexing to fully complete before responding. On RAGs with vector indexing enabled, this additionally waits for Vectorize ingestion confirmation (up to 40s) so the returned item reflects a queryable state. On timeout the item is returned in `running` state and the background alarm continues polling. Defaults to false. */
    wait_for_completion?: boolean;
}
