// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         query_id: "query_id"
 *     }
 */
export interface GetLogoMatchesRequest {
    account_id: string;
    offset?: string;
    limit?: string;
    query_id: string;
    download?: string;
    /** Column to sort by. Options: 'matchedAt', 'domain', 'similarityScore', or 'registrar' */
    orderBy?: CloudflareApi.brandProtection.GetLogoMatchesRequestOrderBy;
    /** Sort order. Options: 'asc' (ascending) or 'desc' (descending) */
    order?: CloudflareApi.brandProtection.GetLogoMatchesRequestOrder;
}
