// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../index.js";

export interface ListHyperdriveResponse {
    result: CloudflareApi.HyperdriveHyperdriveConfigResponse[];
    result_info?: CloudflareApi.HyperdriveResultInfo | undefined;
}
