// This file was auto-generated by Fern from our API Definition.

/** Filters the returned cookies that match the specified type attribute */
export const ListCookiesRequestType = {
    FirstParty: "first_party",
    Unknown: "unknown",
} as const;
export type ListCookiesRequestType = (typeof ListCookiesRequestType)[keyof typeof ListCookiesRequestType];
