// This file was auto-generated by Fern from our API Definition.

/** Specifies the attribute by which to group the results. */
export const SummaryV2LeakedCredentialsRequestDimension = {
    Compromised: "COMPROMISED",
    BotClass: "BOT_CLASS",
} as const;
export type SummaryV2LeakedCredentialsRequestDimension =
    (typeof SummaryV2LeakedCredentialsRequestDimension)[keyof typeof SummaryV2LeakedCredentialsRequestDimension];
