// This file was auto-generated by Fern from our API Definition.

/** Specifies the attribute by which to group the results. */
export const TimeseriesGroupsV2LeakedCredentialsRequestDimension = {
    Compromised: "COMPROMISED",
    BotClass: "BOT_CLASS",
} as const;
export type TimeseriesGroupsV2LeakedCredentialsRequestDimension =
    (typeof TimeseriesGroupsV2LeakedCredentialsRequestDimension)[keyof typeof TimeseriesGroupsV2LeakedCredentialsRequestDimension];
