// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tenant_id: "tenant_id"
 *     }
 */
export interface ListAccountTypeRequest {
    tenant_id: string;
}
