// This file was auto-generated by Fern from our API Definition.

export interface SubmitBrandProtectionResponse {
    matches: SubmitBrandProtectionResponse.Matches.Item[];
}

export namespace SubmitBrandProtectionResponse {
    export type Matches = Matches.Item[];

    export namespace Matches {
        export interface Item {
            account_id?: string | undefined;
            /** MIME type of the image (only present when download=true) */
            content_type?: string | undefined;
            domain?: string | undefined;
            /** Base64-encoded image data (only present when download=true) */
            image_data?: string | undefined;
            query_id?: number | undefined;
            r2_path?: string | undefined;
            similarity_score: number;
            similarity_threshold?: number | undefined;
            tag?: string | undefined;
            timestamp?: number | undefined;
            url_scan_id?: string | undefined;
            vector_id?: string | undefined;
        }
    }
}
