// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id"
 *     }
 */
export interface ListPacfilesRequest {
    /** Specify the Cloudflare account identifier. */
    account_id: string;
    /** Page number of paginated results. */
    page?: number;
    /** Number of items per page. */
    per_page?: number;
}
