// This file was auto-generated by Fern from our API Definition.

export const MaliciousTimeseriesGroupsRequestSpfItem = {
    Pass: "PASS",
    None: "NONE",
    Fail: "FAIL",
} as const;
export type MaliciousTimeseriesGroupsRequestSpfItem =
    (typeof MaliciousTimeseriesGroupsRequestSpfItem)[keyof typeof MaliciousTimeseriesGroupsRequestSpfItem];
