// This file was auto-generated by Fern from our API Definition.

export const TlsVersionTimeseriesGroupsRequestDmarcItem = {
    Pass: "PASS",
    None: "NONE",
    Fail: "FAIL",
} as const;
export type TlsVersionTimeseriesGroupsRequestDmarcItem =
    (typeof TlsVersionTimeseriesGroupsRequestDmarcItem)[keyof typeof TlsVersionTimeseriesGroupsRequestDmarcItem];
