// This file was auto-generated by Fern from our API Definition.

/** Format in which results will be returned. */
export const TimeseriesGroupsV2DnsRequestFormat = {
    Json: "JSON",
    Csv: "CSV",
} as const;
export type TimeseriesGroupsV2DnsRequestFormat =
    (typeof TimeseriesGroupsV2DnsRequestFormat)[keyof typeof TimeseriesGroupsV2DnsRequestFormat];
