// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         cookie_id: "cookie_id"
 *     }
 */
export interface GetCookiesRequest {
    /** Identifier */
    zone_id: string;
    /** Identifier */
    cookie_id: string;
}
