// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface ListAclsResponse {
    result: CloudflareApi.MagicAcl[];
    result_info?: Record<string, unknown> | undefined;
}
