// This file was auto-generated by Fern from our API Definition.

/** Dimension to summarize TLD nameserver latency by. */
export const SummaryPerformanceRequestDimension = {
    Latency: "LATENCY",
    NameserverLatency: "NAMESERVER_LATENCY",
    LocationLatency: "LOCATION_LATENCY",
} as const;
export type SummaryPerformanceRequestDimension =
    (typeof SummaryPerformanceRequestDimension)[keyof typeof SummaryPerformanceRequestDimension];
