// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export interface ListOperationsResponse extends CloudflareApi.ApiShieldApiResponseCollection {
    result: ListOperationsResponse.Result.Item[];
}

export namespace ListOperationsResponse {
    export type Result = Result.Item[];

    export namespace Result {
        export type Item = CloudflareApi.ApiShieldOperation | CloudflareApi.ApiShieldBasicOperation;
    }
}
