// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { normalizeClientOptionsWithAuth, type NormalizedClientOptionsWithAuth } from "../../../../BaseClient.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { AddressesClient } from "../resources/addresses/client/Client.js";
import { ProfilesClient } from "../resources/profiles/client/Client.js";
import { RatePlansClient } from "../resources/ratePlans/client/Client.js";
import { UsageClient } from "../resources/usage/client/Client.js";

export declare namespace BillingClient {
    export type Options = BaseClientOptions;
}

export class BillingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BillingClient.Options>;
    protected _usage: UsageClient | undefined;
    protected _profiles: ProfilesClient | undefined;
    protected _addresses: AddressesClient | undefined;
    protected _ratePlans: RatePlansClient | undefined;

    constructor(options: BillingClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }

    public get profiles(): ProfilesClient {
        return (this._profiles ??= new ProfilesClient(this._options));
    }

    public get addresses(): AddressesClient {
        return (this._addresses ??= new AddressesClient(this._options));
    }

    public get ratePlans(): RatePlansClient {
        return (this._ratePlans ??= new RatePlansClient(this._options));
    }
}
