// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         displayName: "My IdP Group"
 *     }
 */
export interface IamScimGroupCreateRequest {
    /** Account identifier tag. */
    account_id: string;
    /** A human-readable name for the Group. REQUIRED. Must not start with `CF` (reserved prefix for Cloudflare-managed virtual groups). */
    displayName: string;
    /** Identifier for the Group as defined by the provisioning client (IdP). */
    externalId?: string;
}
