// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_or_zone: "account_or_zone",
 *         account_or_zone_id: "account_or_zone_id"
 *     }
 */
export interface ListAccountWaitingRoomsRequest {
    account_or_zone: string;
    /** Identifier. */
    account_or_zone_id: string;
    /** Page number of paginated results. */
    page?: number;
    /** Maximum number of results per page. Must be a multiple of 5. */
    per_page?: number;
}
