// This file was auto-generated by Fern from our API Definition.

export const TimeseriesCtRequestPublicKeyAlgorithmItem = {
    Dsa: "DSA",
    Ecdsa: "ECDSA",
    Rsa: "RSA",
} as const;
export type TimeseriesCtRequestPublicKeyAlgorithmItem =
    (typeof TimeseriesCtRequestPublicKeyAlgorithmItem)[keyof typeof TimeseriesCtRequestPublicKeyAlgorithmItem];
