// This file was auto-generated by Fern from our API Definition.

export const TimeseriesCtRequestLogApiItem = {
    Rfc6962: "RFC6962",
    Static: "STATIC",
} as const;
export type TimeseriesCtRequestLogApiItem =
    (typeof TimeseriesCtRequestLogApiItem)[keyof typeof TimeseriesCtRequestLogApiItem];
