// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         index_name: "index_name",
 *         description: "This is my example index."
 *     }
 */
export interface VectorizeUpdateIndexRequest {
    /** Identifier */
    account_id: string;
    index_name: string;
    description: CloudflareApi.VectorizeIndexDescription;
}
