// This file was auto-generated by Fern from our API Definition.

export const ListBulkRequestActionType = {
    Move: "MOVE",
    Release: "RELEASE",
} as const;
export type ListBulkRequestActionType = (typeof ListBulkRequestActionType)[keyof typeof ListBulkRequestActionType];
