// This file was auto-generated by Fern from our API Definition.

export const DurationSummaryRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type DurationSummaryRequestIpVersionItem =
    (typeof DurationSummaryRequestIpVersionItem)[keyof typeof DurationSummaryRequestIpVersionItem];
