// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface ListDataTagsResponse {
    result: CloudflareApi.DlpDataTagArray;
    result_info?: Record<string, unknown> | undefined;
}
