// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         input: {
 *             "ClientIP": "198.51.100.1",
 *             "ClientRequestHost": "example.com",
 *             "EdgeStartTimestamp": 1722513600000000000,
 *             "RayID": "abcdef1234567890"
 *         },
 *         sql: "SELECT ClientIP, RayID FROM http_requests"
 *     }
 */
export interface LogpushTransformerPreviewRequest {
    /** Identifier. */
    account_id: string;
    /** A single log record to transform (JSON object). */
    input: Record<string, unknown>;
    sql: CloudflareApi.LogpushTransformerCode;
}
