// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         signing_key_name: "signing_key_name"
 *     }
 */
export interface DeleteKeysRequest {
    /** Account identifier tag. */
    account_id: string;
    signing_key_name: string;
}
