// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         site_id: "site_id",
 *         lan_1: {
 *             lan_id: "lan_id"
 *         },
 *         lan_2: {
 *             lan_id: "lan_id"
 *         },
 *         name: "PIN Pad - Cash Register"
 *     }
 */
export interface MagicAclsAddSingleRequest {
    /** Identifier */
    account_id: string;
    /** Identifier */
    site_id: string;
    /** Description for the ACL. */
    description?: string;
    forward_locally?: CloudflareApi.MagicForwardLocally;
    lan_1: CloudflareApi.MagicLanAclConfiguration;
    lan_2: CloudflareApi.MagicLanAclConfiguration;
    /** The name of the ACL. */
    name: string;
    protocols?: MagicAclsAddSingleRequest.Protocols.Item[];
    unidirectional?: CloudflareApi.MagicUnidirectional;
}

export namespace MagicAclsAddSingleRequest {
    export type Protocols = Protocols.Item[];

    export namespace Protocols {
        /** Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed. */
        export const Item = {
            Tcp: "tcp",
            Udp: "udp",
            Icmp: "icmp",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
