// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface DeleteIdpFederationGrantsResponse {
    /** UID of the deleted IdP federation grant. */
    id?: CloudflareApi.AccessIdentifier | undefined;
}
