// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         device_type: "DESKTOP",
 *         limit: 5,
 *         name: ["main_series"],
 *         dateRange: ["7d"]
 *     }
 */
export interface GetDeviceTypeRequest {
    /** Device type. */
    device_type: CloudflareApi.radar.http.locations.GetDeviceTypeRequestDeviceType;
    /** Limits the number of objects returned in the response. */
    limit?: number;
    /** Array of names used to label the series in the response. */
    name?: string | string[];
    /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
    dateRange?: string | string[];
    /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateStart?: string | string[];
    /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateEnd?: string | string[];
    /** Filters results by Autonomous System. Specify one or more Autonomous System Numbers (ASNs) as a comma-separated list. Prefix with `-` to exclude ASNs from results. For example, `-174, 3356` excludes results from AS174, but includes results from AS3356. */
    asn?: string | string[];
    /** Filters results by location. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude locations from results. For example, `-US,PT` excludes results from the US, but includes results from PT. */
    location?: string | string[];
    /** Filters results by continent. Specify a comma-separated list of alpha-2 codes. Prefix with `-` to exclude continents from results. For example, `-EU,NA` excludes results from EU, but includes results from NA. */
    continent?: string | string[];
    /** Filters results by Geolocation. Specify a comma-separated list of GeoNames IDs. Prefix with `-` to exclude geoIds from results. For example, `-2267056,360689` excludes results from the 2267056 (Lisbon), but includes results from 5128638 (New York). */
    geoId?: string | string[];
    /** Filters results by bot class. Refer to [Bot classes](https://developers.cloudflare.com/radar/concepts/bot-classes/). */
    botClass?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestBotClassItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestBotClassItem[];
    /** Filters results by HTTP protocol (HTTP vs. HTTPS). */
    httpProtocol?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestHttpProtocolItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestHttpProtocolItem[];
    /** Filters results by HTTP version. */
    httpVersion?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestHttpVersionItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestHttpVersionItem[];
    /** Filters results by IP version (Ipv4 vs. IPv6). */
    ipVersion?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestIpVersionItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestIpVersionItem[];
    /** Filters results by operating system. */
    os?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestOsItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestOsItem[];
    /** Filters results by TLS version. */
    tlsVersion?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestTlsVersionItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestTlsVersionItem[];
    /** Filters results by browser family. */
    browserFamily?:
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestBrowserFamilyItem
        | CloudflareApi.radar.http.locations.GetDeviceTypeRequestBrowserFamilyItem[];
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.http.locations.GetDeviceTypeRequestFormat;
}
