// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         pool_id: "pool_id",
 *         body: {}
 *     }
 */
export interface CreateHealthRequest {
    /** Identifier. */
    account_id: string;
    pool_id: string;
    body: CloudflareApi.LoadBalancingMonitorEditable;
}
