// This file was auto-generated by Fern from our API Definition.

export const DeleteLocksRequestCfR2Jurisdiction = {
    VDefault: "default",
    Eu: "eu",
    Us: "us",
    Fedramp: "fedramp",
    FedrampHigh: "fedramp-high",
} as const;
export type DeleteLocksRequestCfR2Jurisdiction =
    (typeof DeleteLocksRequestCfR2Jurisdiction)[keyof typeof DeleteLocksRequestCfR2Jurisdiction];
