// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         queue_id: "queue_id",
 *         refs: [{
 *                 ref: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIn0..Q8p21d7dceR6vUfwftONdQ.JVqZgAS-Zk7MqmqccYtTHeeMElNHaOMigeWdb8LyMOg.T2_HV99CYzGaQuhTyW8RsgbnpTRZHRM6N7UoSaAKeK0"
 *             }]
 *     }
 */
export interface PurgeMessagesRequest {
    /** A Resource identifier. */
    account_id: string;
    /** A Resource identifier. */
    queue_id: string;
    refs: PurgeMessagesRequest.Refs.Item[];
}

export namespace PurgeMessagesRequest {
    export type Refs = Refs.Item[];

    export namespace Refs {
        export interface Item {
            ref: CloudflareApi.MqRef;
        }
    }
}
