// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         member_id: "member_id"
 *     }
 */
export interface DeleteMembersRequest {
    /** Account identifier tag. */
    account_id: string;
    /** Membership identifier tag. */
    member_id: string;
}
