// This file was auto-generated by Fern from our API Definition.

/** Filter by SSL certificate status. */
export const ListCustomHostnamesRequestSslStatus = {
    Initializing: "initializing",
    PendingValidation: "pending_validation",
    Deleted: "deleted",
    PendingIssuance: "pending_issuance",
    PendingDeployment: "pending_deployment",
    PendingDeletion: "pending_deletion",
    PendingExpiration: "pending_expiration",
    Expired: "expired",
    Active: "active",
    InitializingTimedOut: "initializing_timed_out",
    ValidationTimedOut: "validation_timed_out",
    IssuanceTimedOut: "issuance_timed_out",
    DeploymentTimedOut: "deployment_timed_out",
    DeletionTimedOut: "deletion_timed_out",
    PendingCleanup: "pending_cleanup",
    StagingDeployment: "staging_deployment",
    StagingActive: "staging_active",
    Deactivating: "deactivating",
    Inactive: "inactive",
    BackupIssued: "backup_issued",
    HoldingDeployment: "holding_deployment",
} as const;
export type ListCustomHostnamesRequestSslStatus =
    (typeof ListCustomHostnamesRequestSslStatus)[keyof typeof ListCustomHostnamesRequestSslStatus];
