// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353",
 *         options: {
 *             gateway: {
 *                 id: "id"
 *             }
 *         },
 *         query: "query"
 *     }
 */
export interface WebSearchAiGatewayRequest {
    account_id: string;
    byokAlias?: string;
    limit?: number;
    options: WebSearchAiGatewayRequest.Options;
    provider?: string;
    query: string;
}

export namespace WebSearchAiGatewayRequest {
    export interface Options {
        gateway: Options.Gateway;
    }

    export namespace Options {
        export interface Gateway {
            id: string;
        }
    }
}
