// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353"
 *     }
 */
export interface ListCategoriesRequest {
    /** Account ID. */
    account_id: string;
    /** Number of results to return. Defaults to 25; values are clamped to 1–250. */
    limit?: number;
    /** Number of results to skip. Defaults to 0; negative values are clamped to 0. */
    offset?: number;
}
