// This file was auto-generated by Fern from our API Definition.

export const ListRegistrationsRequestDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListRegistrationsRequestDirection =
    (typeof ListRegistrationsRequestDirection)[keyof typeof ListRegistrationsRequestDirection];
