// This file was auto-generated by Fern from our API Definition.

export const TlsVersionSummaryRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type TlsVersionSummaryRequestIpVersionItem =
    (typeof TlsVersionSummaryRequestIpVersionItem)[keyof typeof TlsVersionSummaryRequestIpVersionItem];
