// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account-123",
 *         domain: "domain"
 *     }
 */
export interface DeleteRegistriesRequest {
    /** Account identifier. */
    account_id: string;
    /** The domain to delete. */
    domain: string;
}
