// This file was auto-generated by Fern from our API Definition.

export interface SnapshotAspaResponse {
    asnInfo: SnapshotAspaResponse.AsnInfo;
    aspaObjects: SnapshotAspaResponse.AspaObjects.Item[];
    meta: SnapshotAspaResponse.Meta;
}

export namespace SnapshotAspaResponse {
    export interface AsnInfo {
        "13335": AsnInfo._13335;
    }

    export namespace AsnInfo {
        export interface _13335 {
            /** ASN number. */
            asn: number;
            /** Alpha-2 country code. */
            country: string;
            /** AS name. */
            name: string;
        }
    }

    export type AspaObjects = AspaObjects.Item[];

    export namespace AspaObjects {
        export interface Item {
            /** The customer ASN publishing the ASPA object. */
            customerAsn: number;
            providers: number[];
        }
    }

    export interface Meta {
        /** Timestamp of the underlying data. */
        dataTime: string;
        /** Timestamp when the query was executed. */
        queryTime: string;
        /** Total number of ASPA objects. */
        totalCount: number;
    }
}
