// This file was auto-generated by Fern from our API Definition.

export const TimeseriesGroupsV2RoutingRequestEncryptedItem = {
    Encrypted: "ENCRYPTED",
    NotEncrypted: "NOT_ENCRYPTED",
} as const;
export type TimeseriesGroupsV2RoutingRequestEncryptedItem =
    (typeof TimeseriesGroupsV2RoutingRequestEncryptedItem)[keyof typeof TimeseriesGroupsV2RoutingRequestEncryptedItem];
