// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../index.js";

export interface ListInstancesResponse {
    /** Array of finding instance objects. */
    result: CloudflareApi.PostureApiFindingInstance[];
    result_info?: CloudflareApi.PostureApiResultInfo | undefined;
}
