// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         image_id: "image_id"
 *     }
 */
export interface GetImagesRequest {
    /** Account identifier tag. */
    account_id: string;
    /** Image unique identifier. */
    image_id: string;
}
