// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         subdivision_code: "CA",
 *         country_code: "US"
 *     }
 */
export interface ListRegionsRequest {
    subdivision_code?: CloudflareApi.LoadBalancingSubdivisionCodeA2;
    /** Two-letter alpha-2 country code as defined in ISO 3166-1. */
    country_code?: string;
}
