// This file was auto-generated by Fern from our API Definition.

export const GetBrowserFamilyRequestHttpVersionItem = {
    HttPv1: "HTTPv1",
    HttPv2: "HTTPv2",
    HttPv3: "HTTPv3",
} as const;
export type GetBrowserFamilyRequestHttpVersionItem =
    (typeof GetBrowserFamilyRequestHttpVersionItem)[keyof typeof GetBrowserFamilyRequestHttpVersionItem];
