// This file was auto-generated by Fern from our API Definition.

export const ListRegistrationsRequestStatus = {
    Active: "active",
    All: "all",
    Revoked: "revoked",
} as const;
export type ListRegistrationsRequestStatus =
    (typeof ListRegistrationsRequestStatus)[keyof typeof ListRegistrationsRequestStatus];
