// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../index.js";

export interface ListRegistrationsResponse {
    result: CloudflareApi.TeamsDevicesRegistration[];
    result_info?: CloudflareApi.TeamsDevicesCursorResultInfo | undefined;
}
