// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         project_type: "project_type",
 *         request_id: "request_id",
 *         message_id: "message_id"
 *     }
 */
export interface GetMessagesRequest {
    account_id: string;
    project_type: string;
    request_id: string;
    message_id: string;
}
