// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface CreateSuppressionsResponse {
    /** The suppression's identifier. */
    id: string;
    /** Where the suppression applies: `account` for every sending domain of the account, or `sending_domain` for one envelope MAIL FROM domain. */
    scope?: CloudflareApi.emailSending.CreateSuppressionsResponseScope | undefined;
}
