// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         identifier: "identifier",
 *         entries: [{}]
 *     }
 */
export interface Web3ContentListUpdateRequest {
    /** Specify the identifier of the hostname. */
    zone_id: string;
    /** Specify the identifier of the hostname. */
    identifier: string;
    entries: CloudflareApi.Web3ContentListEntries;
}
