// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         prefix_id: "prefix_id",
 *         cidr: "192.0.2.0/24"
 *     }
 */
export interface AddressingBgpPrefixCreate {
    /** Identifier of a Cloudflare account. */
    account_id: string;
    /** Identifier of an IP Prefix. */
    prefix_id: string;
    cidr: CloudflareApi.AddressingCidr;
}
