// This file was auto-generated by Fern from our API Definition.

/** Specifies whether the `location` filter applies to the source or target location. */
export const BitrateTimeseriesGroupsRequestDirection = {
    Origin: "ORIGIN",
    Target: "TARGET",
} as const;
export type BitrateTimeseriesGroupsRequestDirection =
    (typeof BitrateTimeseriesGroupsRequestDirection)[keyof typeof BitrateTimeseriesGroupsRequestDirection];
