// This file was auto-generated by Fern from our API Definition.

export const DurationTimeseriesGroupsRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type DurationTimeseriesGroupsRequestIpVersionItem =
    (typeof DurationTimeseriesGroupsRequestIpVersionItem)[keyof typeof DurationTimeseriesGroupsRequestIpVersionItem];
