// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         body: {
 *             enabled: true,
 *             endpoint: "/metrics",
 *             hideOriginalIp: true,
 *             measurementId: "GTM-P2F3N47Q"
 *         }
 *     }
 */
export interface UpdateConfigRequest {
    /** Identifier. */
    zone_id: string;
    body: CloudflareApi.GoogleTagGatewayGoogleTagGatewayConfig;
}
