// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         app_id: "app_id",
 *         flag_key: "flag_key"
 *     }
 */
export interface ListChangelogRequest {
    /** Cloudflare account ID. */
    account_id: string;
    /** App identifier. */
    app_id: string;
    /** Flag key (slug). */
    flag_key: string;
    /** Max items to return (1–200). */
    limit?: string;
    /** Pagination cursor from a previous response. */
    cursor?: string;
}
