// This file was auto-generated by Fern from our API Definition.

export interface ListPathsResponse {
    asnInfo: Record<string, ListPathsResponse.AsnInfo.Value | null> | null;
    collectors: string[];
    meta: ListPathsResponse.Meta;
    paths: ListPathsResponse.Paths.Item[];
}

export namespace ListPathsResponse {
    export namespace AsnInfo {
        export interface Value {
            /** ASN number. */
            asn: number;
            /** Alpha-2 country code. */
            country: string | null;
            /** AS name. */
            name: string | null;
        }
    }

    export interface Meta {
        /** Timestamp of the underlying RIB data. */
        dataTime: string | null;
        effectiveCollector: string | null;
        /** Timestamp when the query was executed. */
        queryTime: string | null;
        stale: boolean;
    }

    export type Paths = Paths.Item[];

    export namespace Paths {
        export interface Item {
            collectors: string[];
            pathsCount: number;
            peersCount: number;
            segment: number[];
        }
    }
}
