// This file was auto-generated by Fern from our API Definition.

export interface MoasRoutesResponse {
    meta: MoasRoutesResponse.Meta;
    moas: MoasRoutesResponse.Moas.Item[];
}

export namespace MoasRoutesResponse {
    export interface Meta {
        data_time: string;
        query_time: string;
        total_peers: number;
    }

    export type Moas = Moas.Item[];

    export namespace Moas {
        export interface Item {
            origins: Item.Origins.Item[];
            prefix: string;
        }

        export namespace Item {
            export type Origins = Origins.Item[];

            export namespace Origins {
                export interface Item {
                    origin: number;
                    peer_count: number;
                    rpki_validation: string;
                }
            }
        }
    }
}
