// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         destination_type: "NONE",
 *         name: "name",
 *         update_mode: "AUTO"
 *     }
 */
export interface McnCreateCatalogSyncRequest {
    account_id: string;
    forwarded?: string;
    description?: string;
    destination_type: CloudflareApi.McnCatalogSyncDestinationType;
    name: string;
    policy?: string;
    update_mode: CloudflareApi.McnCatalogSyncUpdateMode;
}
