// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         provider_id: "provider_id"
 *     }
 */
export interface DeleteCloudIntegrationsRequest {
    account_id: string;
    provider_id: string;
}
