// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account-123",
 *         build_uuid: "build_uuid",
 *         cursor: "eyJsaW5lIjoxMDAsInRpbWVzdGFtcCI6MTYzNjQ3MjQwMH0"
 *     }
 */
export interface GetLogsRequest {
    account_id: CloudflareApi.BuildsAccountId;
    build_uuid: CloudflareApi.BuildsBuildUuid;
    cursor?: CloudflareApi.BuildsCursor;
}
