// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export type ZarazZarazConfigBodyVariablesValue =
    | CloudflareApi.zaraz.ZarazZarazConfigBodyVariablesValue.String
    | CloudflareApi.zaraz.ZarazZarazConfigBodyVariablesValue.Secret
    | CloudflareApi.zaraz.ZarazZarazConfigBodyVariablesValue.Worker;

export namespace ZarazZarazConfigBodyVariablesValue {
    export interface String extends CloudflareApi.ZarazStringVariable {
        type: "string";
    }

    export interface Secret extends CloudflareApi.ZarazSecretVariable {
        type: "secret";
    }

    export interface Worker extends CloudflareApi.ZarazWorkerVariable {
        type: "worker";
    }
}
