// This file was auto-generated by Fern from our API Definition.

export interface GenerateSummariesResponse {
    data?: GenerateSummariesResponse.Data | undefined;
    success?: boolean | undefined;
}

export namespace GenerateSummariesResponse {
    export interface Data {
        session_id?: string | undefined;
        status?: string | undefined;
    }
}
