// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         colo: "SJC",
 *         deviceId: ["cb49c27f-7f97-49c5-b6f3-f7c01ead0fd7"],
 *         registration_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *         page: 1,
 *         per_page: 10
 *     }
 */
export interface ListTestsRequest {
    /** Unique Cloudflare account ID. */
    account_id: string;
    /** Optionally filter result stats to a Cloudflare colo. Cannot be used in combination with deviceId param. */
    colo?: string;
    /** Optionally filter results by test name. */
    testName?: string;
    /** Optionally filter result stats to a specific device(s). Cannot be used in combination with colo param. */
    deviceId?: string | string[];
    /** Optionally filter results to a specific device registration. Must be used in combination with a single deviceId. */
    registration_id?: string;
    /** Page number of paginated results */
    page?: number;
    /** Number of items per page */
    per_page?: number;
    /** Filter by test type. */
    kind?: CloudflareApi.zeroTrust.dex.overview.ListTestsRequestKind;
}
