// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../index.js";

export interface ListApplicationsResponse {
    result: CloudflareApi.AlexandriaApplications;
    result_info?: ListApplicationsResponse.ResultInfo | undefined;
}

export namespace ListApplicationsResponse {
    export interface ResultInfo {
        /** Returns the number of results in this response. */
        count?: number | undefined;
        /** Returns the zero-based result offset, not a page number. */
        page?: number | undefined;
        /** Returns the effective `limit` for this response. */
        per_page?: number | undefined;
        /** Returns the number of results matching the request before pagination. */
        total_count?: number | undefined;
        /** Returns the number of pages at the effective `limit`, including 0 when there are no matches. */
        total_pages?: number | undefined;
    }
}
