// This file was auto-generated by Fern from our API Definition.

export const ListLogsRequestOrderBy = {
    CreatedAt: "created_at",
    Provider: "provider",
    Model: "model",
    ModelType: "model_type",
    Success: "success",
    Cached: "cached",
} as const;
export type ListLogsRequestOrderBy = (typeof ListLogsRequestOrderBy)[keyof typeof ListLogsRequestOrderBy];
