// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../../../../../BaseClient.js";
import {
    normalizeClientOptionsWithAuth,
    type NormalizedClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import * as core from "../../../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../../../environments.js";
import { TldsClient } from "../resources/tlds/client/Client.js";

export declare namespace TopClient {
    export type Options = BaseClientOptions;
}

export class TopClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TopClient.Options>;
    protected _tlds: TldsClient | undefined;

    constructor(options: TopClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get tlds(): TldsClient {
        return (this._tlds ??= new TldsClient(this._options));
    }
}
