// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         spoof: "SPOOF",
 *         limit: 5,
 *         name: ["main_series"],
 *         dateRange: ["7d"]
 *     }
 */
export interface GetSpoofRequest {
    /** Spoof classification. */
    spoof: CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestSpoof;
    /** Limits the number of objects returned in the response. */
    limit?: number;
    /** Array of names used to label the series in the response. */
    name?: string | string[];
    /** Filters results by relative date range ending at the current time, with each value producing a separate series. Use `<n>d` for days (up to `364d`) or `<n>w` for weeks (up to `52w`). Append `control` to request the equivalent previous period for comparison: the comparison window is shifted back by the current window's length rounded up to a whole number of weeks, so it keeps the same weekday alignment and does not overlap the current window (e.g. `7dcontrol` covers days -14 to -7, `10dcontrol` covers days -24 to -14). For example, pass `7d` and `7dcontrol` to compare this week with the previous week. All series must resolve to the same duration as the main series; relative ranges (including `control`) satisfy this automatically. Use this parameter or set specific start and end dates (`dateStart` and `dateEnd` parameters). */
    dateRange?: string | string[];
    /** Start of the date range. Alternative to `dateRange`; provide together with `dateEnd`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateStart?: string | string[];
    /** End of the date range (inclusive). Alternative to `dateRange`; provide together with `dateStart`. When requesting comparison series, every series must resolve to the same duration as the main series. Each `dateStart`/`dateEnd` is floored to the nearest 15 minutes before evaluation, so windows whose durations match only before alignment may be rejected. */
    dateEnd?: string | string[];
    /** Filters results by ARC (Authenticated Received Chain) validation. */
    arc?:
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestArcItem
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestArcItem[];
    /** Filters results by DKIM (DomainKeys Identified Mail) validation status. */
    dkim?:
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestDkimItem
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestDkimItem[];
    /** Filters results by DMARC (Domain-based Message Authentication, Reporting and Conformance) validation status. */
    dmarc?:
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestDmarcItem
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestDmarcItem[];
    /** Filters results by SPF (Sender Policy Framework) validation status. */
    spf?:
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestSpfItem
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestSpfItem[];
    /** Filters results by TLS version. */
    tlsVersion?:
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestTlsVersionItem
        | CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestTlsVersionItem[];
    /** Filters results by TLD category. */
    tldCategory?: CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestTldCategory;
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.email.security.top.tlds.GetSpoofRequestFormat;
}
