// This file was auto-generated by Fern from our API Definition.

export const TimeseriesBotsRequestBotKindItem = {
    Agent: "AGENT",
    Bot: "BOT",
} as const;
export type TimeseriesBotsRequestBotKindItem =
    (typeof TimeseriesBotsRequestBotKindItem)[keyof typeof TimeseriesBotsRequestBotKindItem];
