// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         target_environment: "target_environment",
 *         release_track: "ga"
 *     }
 */
export interface ListClientVersionsRequest {
    account_id: string;
    /** The target environment for the client version (e.g., windows, macos). */
    target_environment: string;
    /** The release track (ga for General Availability, beta for Beta releases). */
    release_track: CloudflareApi.zeroTrust.devices.ListClientVersionsRequestReleaseTrack;
    /** The page number to return. */
    page?: number;
    /** The maximum number of versions to return per page. */
    per_page?: number;
}
