// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id",
 *         identifier: "identifier"
 *     }
 */
export interface GetHostnamesRequest {
    /** Specify the identifier of the hostname. */
    zone_id: string;
    /** Specify the identifier of the hostname. */
    identifier: string;
}
