// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         zone_id: "zone_id"
 *     }
 */
export interface ListHostnamesRequest {
    /** Specify the identifier of the hostname. */
    zone_id: string;
}
