// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         zone_id: "023e105f4ecef8ad9ca31a8372d0c353",
 *         name: "login"
 *     }
 */
export interface ApiShieldPatchLabelRequest {
    zone_id: CloudflareApi.ApiShieldIdentifier2;
    /** The label name */
    name: CloudflareApi.ApiShieldLabelName;
    description?: CloudflareApi.ApiShieldLabelDescription;
    metadata?: CloudflareApi.ApiShieldLabelMetadata;
}
