// This file was auto-generated by Fern from our API Definition.

export interface ListLocationsResponse {
    locations: ListLocationsResponse.Locations.Item[];
}

export namespace ListLocationsResponse {
    export type Locations = Locations.Item[];

    export namespace Locations {
        export interface Item {
            alpha2: string;
            continent: string;
            /** A numeric string. */
            latitude: string;
            /** A numeric string. */
            longitude: string;
            name: string;
            region: string;
            subregion: string;
        }
    }
}
