// This file was auto-generated by Fern from our API Definition.

/** Filters results by continent code. */
export const ListLocationsRequestContinent = {
    Af: "AF",
    As: "AS",
    Eu: "EU",
    Na: "NA",
    Oc: "OC",
    Sa: "SA",
} as const;
export type ListLocationsRequestContinent =
    (typeof ListLocationsRequestContinent)[keyof typeof ListLocationsRequestContinent];
