// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         body: {
 *             decision: "allow",
 *             include: [{
 *                     certificate: {
 *                         "key": "value"
 *                     }
 *                 }],
 *             name: "Allow devs"
 *         }
 *     }
 */
export interface CreatePoliciesRequest {
    /** Identifier. */
    account_id: string;
    body: CloudflareApi.AccessPolicyReq;
}
