// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         destination: {
 *             batch: {},
 *             compression: {},
 *             credentials: {
 *                 access_key_id: "<access key id>",
 *                 endpoint: "https://123f8a8258064ed892a347f173372359.r2.cloudflarestorage.com",
 *                 secret_access_key: "<secret key>"
 *             },
 *             format: "json",
 *             path: {
 *                 bucket: "bucket",
 *                 prefix: "base"
 *             },
 *             type: "r2"
 *         },
 *         name: "sample_pipeline",
 *         source: [{
 *                 type: "binding",
 *                 format: "json"
 *             }]
 *     }
 */
export interface LegacyCreatePipelinesRequest {
    /** Specifies the public ID of the account. */
    account_id: string;
    destination: LegacyCreatePipelinesRequest.Destination;
    /** Defines the name of the pipeline. */
    name: string;
    source: CloudflareApi.LegacyCreatePipelinesRequestSourceItem[];
}

export namespace LegacyCreatePipelinesRequest {
    export interface Destination {
        batch: Destination.Batch;
        compression: Destination.Compression;
        credentials: Destination.Credentials;
        /** Specifies the format of data to deliver. */
        format: "json";
        path: Destination.Path;
        /** Specifies the type of destination. */
        type: "r2";
    }

    export namespace Destination {
        export interface Batch {
            /** Specifies rough maximum size of files. */
            max_bytes?: number | undefined;
            /** Specifies duration to wait to aggregate batches files. */
            max_duration_s?: number | undefined;
            /** Specifies rough maximum number of rows per file. */
            max_rows?: number | undefined;
        }

        export interface Compression {
            /** Specifies the desired compression algorithm and format. */
            type?: Compression.Type | undefined;
        }

        export namespace Compression {
            /** Specifies the desired compression algorithm and format. */
            export const Type = {
                None: "none",
                Gzip: "gzip",
                Deflate: "deflate",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }

        export interface Credentials {
            /** Specifies the R2 Bucket Access Key Id. */
            access_key_id: string;
            /** Specifies the R2 Endpoint. */
            endpoint: string;
            /** Specifies the R2 Bucket Secret Access Key. */
            secret_access_key: string;
        }

        export interface Path {
            /** Specifies the R2 Bucket to store files. */
            bucket: string;
            /** Specifies the name pattern to for individual data files. */
            filename?: Path.Filename | undefined;
            /** Specifies the name pattern for directory. */
            filepath?: string | undefined;
            /** Specifies the base directory within the bucket. */
            prefix?: string | undefined;
        }

        export namespace Path {
            /**
             * Specifies the name pattern to for individual data files.
             */
            export interface Filename {}
        }
    }
}
