// This file was auto-generated by Fern from our API Definition.

export const GetAsesRequestUpdateTypeItem = {
    Announcement: "ANNOUNCEMENT",
    Withdrawal: "WITHDRAWAL",
} as const;
export type GetAsesRequestUpdateTypeItem =
    (typeof GetAsesRequestUpdateTypeItem)[keyof typeof GetAsesRequestUpdateTypeItem];
