// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         ip: "ip"
 *     }
 */
export interface GetEntitiesRequest {
    /** IP address. */
    ip: string;
    /** Format in which results will be returned. */
    format?: CloudflareApi.radar.GetEntitiesRequestFormat;
}
