// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         database_id: "database_id"
 *     }
 */
export interface ExportD1Request {
    /** Account identifier tag. */
    account_id: string;
    /** D1 database identifier (UUID). */
    database_id: string;
    /** To poll an in-progress export, provide the current bookmark (returned by your first polling response) */
    current_bookmark?: string;
    dump_options?: ExportD1Request.DumpOptions;
}

export namespace ExportD1Request {
    export interface DumpOptions {
        /** Export only the table definitions, not their contents */
        no_data?: boolean | undefined;
        /** Export only each table's contents, not its definition */
        no_schema?: boolean | undefined;
        /** Filter the export to just one or more tables. Passing an empty array is the same as not passing anything and means: export all tables. */
        tables?: string[] | undefined;
    }
}
