// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "023e105f4ecef8ad9ca31a8372d0c353",
 *         investigate_id: "4Njp3P0STMz2c02Q-2024-01-05T10:00:00-12345678"
 *     }
 */
export interface GetInvestigateRequest {
    /** Account identifier tag. */
    account_id: CloudflareApi.EmailSecurityIdentifier;
    investigate_id: CloudflareApi.EmailSecurityInvestigateId;
    /**
     * When true, search the submissions datastore only. When false or omitted, search the
     * regular datastore only.
     */
    submission?: boolean;
}
