// This file was auto-generated by Fern from our API Definition.

export interface SendEventsResponse {
    instanceId: string;
    /** Accepts ISO 8601 with no timezone offsets and in UTC. */
    timestamp: string;
}
