// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         custom_page_id: "custom_page_id"
 *     }
 */
export interface GetCustomPagesRequest {
    /** Identifier. */
    account_id: string;
    /** UUID. */
    custom_page_id: string;
}
