// This file was auto-generated by Fern from our API Definition.

import * as CloudflareApi from "../../../../../../index.js";

/**
 * @example
 *     {
 *         account_id: "account_id",
 *         bucket_name: "bucket_name",
 *         object_key: "path/to/my-object.txt"
 *     }
 */
export interface DeleteObjectsRequest {
    /** Cloudflare account ID that owns the R2 resource. */
    account_id: string;
    /** Name of the bucket. */
    bucket_name: string;
    /**
     * The key (name) of the object to delete. May contain slashes for path-like keys.
     * Slashes (`/`) within the key MUST be sent literally and MUST NOT be percent-encoded
     * (i.e. `%2F`); other reserved characters should be percent-encoded as usual.
     */
    object_key: string;
    /** Jurisdiction where objects in this bucket are guaranteed to be stored. */
    "cf-r2-jurisdiction"?: CloudflareApi.r2.DeleteObjectsRequestCfR2Jurisdiction;
}
