// This file was auto-generated by Fern from our API Definition.

export const ManagedRulesTimeseriesGroupsRequestIpVersionItem = {
    IPv4: "IPv4",
    IPv6: "IPv6",
} as const;
export type ManagedRulesTimeseriesGroupsRequestIpVersionItem =
    (typeof ManagedRulesTimeseriesGroupsRequestIpVersionItem)[keyof typeof ManagedRulesTimeseriesGroupsRequestIpVersionItem];
